from pathlib import Path
import json,re,hashlib,sys
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='heads-fourteenth';IDS=[1126, 1127, 1128, 6691, 3322, 3323, 3324, 5259, 6772, 6773, 1897, 2183]
sys.path.insert(0,str(B.parent));from prepare_sources import ReleaseResources,decode_mmp
from audit_texture_groups import read_database
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
regs=(ROOT/'DBFormat/DataFormat.cpp').read_text(encoding='utf-8');names={int(i,0):n for i,n in re.findall(r'REGISTER_DATABASE_CLASS\(\s*(0x[0-9a-fA-F]+|[0-9]+),\s*"([^"]+)"',regs)}
DB=Path('G:/SS/Silent-Storm/Complete/game.db');db=read_database(DB);by={names[k]:{r['ID']:r for r in t['records']}for k,t in db.items()if k in names};release=ReleaseResources('G:/SS/lab/baseline/res')
records=json.loads((B/f'remaining-{ST}.json').read_text(encoding='utf-8'));rmap={r['id']:r for r in records};checks=[]
old={}
for stem in ['tenth','eleventh','twelfth','thirteenth']:
 d=json.loads((B/f'source-check-heads-{stem}.json').read_text(encoding='utf-8'))
 for r in d['source_checks']:old.setdefault(r['id'],[]).append(f'source-check-heads-{stem}.json')
for i in IDS:
 r=rmap[i];assert by['Textures'][i]==r['texture'];op=B/f'original/{i}.png';o=Image.open(op).convert('RGBA');hb=Path(f'G:/SS/Silent-Storm/Complete/Textures/{i}').read_bytes();rb=release.read(i);h=decode_mmp(hb).convert('RGBA');rr=decode_mmp(rb).convert('RGBA')
 assert h.size==rr.size==o.size==tuple(r['logical_size']);assert h.tobytes()==rr.tobytes()==o.tobytes();assert sha(Path(f'G:/SS/Silent-Storm/Complete/Textures/{i}'))==r['source_sha256'];assert hashlib.sha256(o.tobytes()).hexdigest()==r['source_rgba_sha256']==r['release_rgba_sha256'];assert all(z['role']=='color'for z in r['usage']['direct_texture_uses'])
 chains=[];dynamic=[]
 for tab in ['Materials','TransformableFaceTextures','TransformableEyeTextures','TransformableEyelashTeethTextures']:
  actual=[x for x in by[tab].values()if x['TextureID']==i];queued={z['id']for z in r['usage']['direct_texture_uses']if z['table']==tab};assert queued=={x['ID']for x in actual},(i,tab)
  for x in actual:
   if tab=='Materials':
    t=by['MaterialTemplates'][x['TemplateID']];cons=[{'slot':f,'model':mo,'model_template':by['ModelTemplates'][mo['TemplateID']],'geometry':by['Geometries'][mo['GeometryID']]}for mo in by['Models'].values()for f,v in mo.items()if re.fullmatch(r'Material\d+',f)and v==t['ID']]
    tm={c['model']['TemplateID']for c in cons};hc=[{'actual_complex_head':ch,'hair_fields':[f for f in ['Hair','HairInCap']if ch.get(f)in tm],'actual_head':by['Heads'].get(ch.get('HeadID')),'actual_body_race':by['Races'].get(ch.get('BodyColor'))}for ch in by['ComplexHeads'].values()if any(ch.get(f)in tm for f in ['Hair','HairInCap'])]
    hairs=[v for v in by.get('TransformableHeadHairs',{}).values()if v.get('Hair')in tm]
    chains.append({'actual_material':x,'actual_material_template':t,'all_actual_model_consumers':cons,'actual_complexhead_hair_consumers':hc,'actual_transformablehair_consumers':hairs,'direct_heads_material_consumers':[v for v in by['Heads'].values()if v.get('MaterialID')==t['ID']],'direct_races_material_consumers':[v for v in by['Races'].values()if v.get('MaterialID')==t['ID']],'qualification':'Actual Materials.TextureID diffuse/template consumers. Unknown runtime dispatch or model mesh UV not invented.'})
   else:
    owner=by['TransformableHeadMaterials'][x['THMID']];heads=[v for v in by['Heads'].values()if v.get('TransformableTextures')==owner['ID']];headids={v['ID']for v in heads};complexheads=[{'actual_complex_head':ch,'actual_head':by['Heads'].get(ch.get('HeadID')),'actual_body_race':by['Races'].get(ch.get('BodyColor'))}for ch in by['ComplexHeads'].values()if ch.get('HeadID')in headids]
    assert heads
    dynamic.append({'actual_layer_table':tab,'actual_layer':x,'actual_THMID_owner':owner,'all_actual_Heads_consumers':heads,'actual_ComplexHeads_consumers':complexheads,'qualification':'Dynamic FaceGen source color layer; THMID owner/Heads exact. No static material alpha mode invented. Native sourceA and all original layer counts/weights/wholecanvas UV remain unchanged.','eye_canvas_runtime':{'file':'Main/LSHead.cpp','source_SHA256':sha(ROOT/'Main/LSHead.cpp'),'BuildTexLayers_eye_lines':[1119,1252],'MixTexture_eye_destination':[64,64,128,128],'fill':0,'orientation':'V-flipped per BlendLayer implementation; source canvas preserved, no pre-rotation','unknowns':'Actual FaceGen channel weights/runtime dispatch are not measured by this readonly source audit; root owns runtime tests.'}if tab=='TransformableEyeTextures'else None})
 hp=B/f'generated/{i}-{ST}-source-rgb-support.png';scale=768//max(o.size);o.convert('RGB').resize((o.width*scale,o.height*scale),Image.Resampling.NEAREST).save(hp)
 prior=[p for p in B.rglob(f'{i}-*source*.png')if ST not in p.name]
 checks.append({'id':i,'source_record':r,'fresh_DB_SHA256':sha(DB),'exact_Texture_row':by['Textures'][i],'fresh_actual_typed_material_head_race_hair_chains':chains,'actual_dynamic_texture_layer_head_consumer_chains':dynamic,'history_release_original_fullRGBA_dimensions_exact':True,'historical_release_native_bytes_equal':hb==rb,'historical_MMP_SHA256':hashlib.sha256(hb).hexdigest(),'release_MMP_SHA256':hashlib.sha256(rb).hexdigest(),'original_PNG_SHA256':sha(op),'source_RGBA_SHA256':hashlib.sha256(o.tobytes()).hexdigest(),'native_size':list(o.size),'actual_native_type':r['texture']['Type'],'actual_sourceA_extrema':list(o.getchannel('A').getextrema()),'actual_material_Alpha_AddressMode':[{'id':c['actual_material']['ID'],'Alpha':c['actual_material']['Alpha'],'AddressMode':c['actual_material']['AddressMode']}for c in chains],'prior_heads10_11_12_sourceonly_audits':old.get(i,[]),'prior_sourceonly_helper_examples':[p.relative_to(ROOT).as_posix()for p in sorted(prior)[:6]],'view_novelty':'Readonly re-audit if prior source-only evidence; no first-ever view claim. Previous raw/calls/held/accepted/identicalRGBA guarded separately.','full_original_and_helper_privately_inspected':False,'call_count':0,'reference_recipe':{'input':op.relative_to(ROOT).as_posix(),'operations':f'Whole native storedRGBA to opaqueRGB NEAREST{scale}x only, no crop/BBox/registration/padding/rotate/unpremultiply/sourceartRGB repair. Original fullA separately restored; ENTIRE raw inverse original4x/pure scalar/defaultpad.','source_size':list(o.size),'guide_size':[o.width*scale,o.height*scale],'source_bbox':[0,0,o.width,o.height],'helper':hp.relative_to(ROOT).as_posix(),'references':[op.relative_to(ROOT).as_posix(),hp.relative_to(ROOT).as_posix()],'references_SHA256':[sha(op),sha(hp)]}})
save(f'selected-{ST}.json',[rmap[i]for i in IDS]);save(f'source-check-{ST}.json',{'batch':ST,'source_entry_count_at_audit':len(json.loads((B.parent/'sources.json').read_text(encoding='utf-8'))['textures']),'queue_entry_count_at_audit':len(json.loads((B/'queue.json').read_text(encoding='utf-8'))),'source_count_semantics':'Root2400source entries/q2862 pending32 validation at task dispatch; committed/pushed2390 per coordinator. Fresh source entry counts are not automatically accepted production counts.','source_checks':checks,'all_source_RGBA_history_release_parity_exact':True,'shared_modified':False})
print('Exact fresh source12:',[(x['id'],x['actual_sourceA_extrema'],len(x['actual_dynamic_texture_layer_head_consumer_chains']),len(x['fresh_actual_typed_material_head_race_hair_chains']))for x in checks])
