from pathlib import Path
B=Path(__file__).resolve().parent
s=(B/'prepare_clothing_fiftieth.py').read_text(encoding='utf-8').replace('clothing-fiftieth','clothing-fifty-first').replace('CALL=[2353];ORIG=[1885,1893]','CALL=[6834];ORIG=[4564]')
start=s.index(' boxes=');end=s.index('\n domains=[]',start)
s=s[:start]+" boxes=[('ONE upperhorizontal darkgrayfield',[0,0,128,24]),('ONE curved graylinepaint upperleft',[2,3,62,25]),('ONE olduppercentral greenangularpaint',[30,11,59,34]),('ONE centralsoft unequalpatchpatternfield',[33,42,57,101]),('ONE leftdottedgraypaintcolumn',[26,28,32,86]),('ONE rightdottedgraypaintcolumn',[57,28,62,86]),('ONE oldtinygraymark abovecentralpatchfield',[40,33,47,42]),('ONE darklowerleftpaintfield',[0,24,33,128]),('ONE darkrightpaintfield',[62,24,128,128]),('ONE originalwarmtan lowercentralpaintpatch',[38,101,51,121]),('ONE originalangulargraygreen lower rightUVfield',[71,81,128,128])]"+s[end:]
s=s.replace("[('column',12,64,125),('column',110,1,125),('row',59,1,29),('row',73,1,101),('row',82,45,83),('row',102,46,79),('column',63,92,116)]", "[('column',29,29,85),('column',58,29,85),('column',37,43,86),('column',51,43,86),('row',37,26,63),('row',84,26,63),('row',112,30,64)]")
start=s.index(' desc=');end=s.index('\n c={',start)
desc='ENTIRE original128square subdued charcoalgray/graygreen/tan MATTE softlyfiltered painted UVmap. Keep ONE original topdarkhorizontalfield/oldcurvedgrayline, ONE oldangulargraygreen topcentralfield, ONE centralsoftUNEQUAL rectangular mottledpatchfield x33..56,y42..100, TWO original dottedGRAYPAINT columns (leftx26..31,y28..85 andrightx57..61,y28..85), ONE oldtinygraypaintmark x40..46,y33..41, ONE warmtanlowercentralpaintpatch x38..50,y101..120, ONE angulargraygreen lowerRIGHT UVfield x71..127,y81..127 andALL surroundingoriginalnearblackfields. These are originalflatCOLORpaintmarks, NOT recreatedphysicalbuttons/lacing/rivets/bucklemechanisms/skin/anatomy. LEFT nativecol29 has18 actualshade peaks y30,33,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84; RIGHT nativecol58 has19 actualshade peaks y30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84. Preserve LEFTmissing36 vsRIGHTexisting36 EXACTLY, doNOT regularize intoidenticalcolumns orfilloldgap; these are sourcepaintshadephases notlicense fornewholes/rivets/stitches. Centralweakpaint unequalLEFT nativecol37 peaks y45,48,51,57,64,70,80,82,84 andRIGHT col51 peaks y45,48,50,57,63,68,70,77,80,84: preserve SAMEasymmetry/nativepatchscale/sourceblur, NO new regulargrid/cells. Keep tinyoldgraymark exactlyassource indistinctpaint, no newlettering/symbol. Keeporiginalweakblack/dark fields includingblackRGB/A255—not emptyUVareasto repaint. Fineoriginalmattecolorwash ONLY, NO sourcewash changedtop hysicalgrain/photo clothfibers/weave/new seams/castmetal/chrome/raisedgrayrims/goldglints/lacedhardware/stipple/mosaic/coarsecells/texturepattern/contrastyclouds. Keepexact dimrelativepalette/weakmark strengths/paintblur. Do NOT reconstructhumanparts beneath tanpatch or darkfields.'
s=s[:start]+' desc='+repr(desc)+s[end:]
start=s.index("'source_feature_counts':{");end=s.index(",'native_repeat_count_phase_evidence'",start)
s=s[:start]+"'source_feature_counts':{'centralunequalpatchpaintfield':1,'pairedsidegraypaintcolumns':2,'left_column29_literal_graymaxima_y29to85':18,'right_column58_literal_graymaxima_y29to85':19,'left37central_literalpatchmaxima_y43to86':9,'right51central_literalpatchmaxima_y43to86':10,'uppercurvedgraylinepaint':1,'oldtinygraymark':1,'warmtanlowerpaintfield':1,'lowerRightangulargraygreenfield':1}"+s[end:]
s=s.replace('EligibleFIRST originalwhole mattekhaki cloth-leather128 UVpaint withliteralparts/weakmarks/nativephase/count/oldplus Fourarms beforeproof; nativeRGBA/historyrelease/POT/OrdinaryA255/actualstaticMaterials→TemplateID→Models. No symbolreinterpretation orphysicalhardware/newweave/gloss/grain; sourceblur/nativepaintscale preserved.','EligibleFIRST honestfreshre-audit ofsource-only6834 (no priorraw/call/jobs) graygreen/body matteCOLOR whole128. LEFT18 vsRIGHT19 sidepaint maxima/sourceleftmissing36 andunequalcentral9/10literalshade phases provenbeforeprompt; fullnativeRGBA/historyrelease/POT/OrdinaryA255/actualMaterials→TemplateID→Models, originalblur/nativepaintscale. Literalshade peaks notguessed physicalbuttons/stitches. No newregulargrid/material/fibers/hardware/glyphs.')
s=s.replace("'maximum_call_count':3", "'previous_scope_sourceonly_reaudit_ids':[2005,3892,4442,4451,4549,6806,6834,6835],'fresh_ID_scope_ids':[4564,4947,5456,5670],'maximum_call_count':3").replace("'all_selected_outside_previousClothing1to49':True", "'all_selected_outside_previousClothing1to50':False,'qualification':'FOUR newIDs plusEIGHT honest prior0callbody sourceaudits, no accepted/generated/held/rawdonor repeat.'")
s=s.replace('1885 exactRGBA toprevioussource-only4518 zero recommendation0calls, noaccepted/generated donor claim. 1893 hasdifferent64x128 dimensions. Individualfreshactualconsumers/sourcepayload re-audit, not neverviewedpayload fiction.','4564 exactRGBA/dims/Type toprior1893 source-only0callzeroRGBA recommendation. Honestnativepayloadreaudit, noaccepted/generateddonor claim. IndividualnewactualMaterial2845 Template1829 Models1903.Material3/ModelTemplate1467/Geometry2194, fullRGBA sourcebytes authoritative.').replace("'id':4518", "'id':1893")
s=s.replace('12newIDs, commonpendingpayload groups disclosed. 1885 exactRGBA toprevioussource-only4518 zero recommendation0calls, noaccepted/generated donor. No artisticcalls onanyaccepted/generated/heldsameRGBA.','FournewIDs/Eightold0callsourceaudits disclosed, exactpendingpayload groups explicit. 4564 previous1893zero0call nativepayload reaudit, noaccepted/generated donor.')
start=s.index(" i=c['id'];parts=");end=s.index("\n arg=",start)
parts=" i=c['id'];parts=['Use case: precise-object-edit. Asset type: full softlyfiltered MATTEgraygreen/charcoal/tan diffuse COLOR UV painting. SubtleHD SAMEsourcepaint/sourceblur/nativepatternscale/count/weakphase/material/palette, not physicalrenderedgarment.', 'Image1 edit target ENTIRE exactnative128square storedRGBopaque atoriginalresolution, NO NNtool. ActualstaticMaterials TemplateID Models diffuse source (source-onlypreviousviews honestlyreaudited/no previousimagegen). Ordinary straightRGB/noPremul/fulloriginalA255 separatelyrestored. All originalblack/darkUVpaint authoredsource, noemptyfill.', c['source_description'],f'ActualnativeRGBA extrema {c[\"actual_RGBA_extrema\"]}; strongestnativeRGBA {c[\"native_source_max_mean_RGBA\"]} at{c[\"native_source_max_mean_RGB_xy\"]}. KeepoldSMALLdim peak/relativeweakfields exactly, not white255/glare. Originalsoft filteredpaint intentional; NO raisedcontrast/photograin/cloudmottle/coarseblocks/cells/fibers beneath sourceblur.', 'Output SAME ENTIRE SQUARE opaqueRGB UVcanvas. All exactsource graypaint asymmetriccounts/nativephase anddarkfields remain; no border/padding/whitespace/portrait/zoom/crop/rotate/recenter/BBox/fitting/registration/islandmoves. No new symbols/letters/hardware/buttons/skin/anatomy/grid/lacing/weave/seams/hair/fibers/relief. No repaintingexistingmottle into newpattern; keep originalsubtlepaint.']"
s=s[:start]+parts+s[end:]
s=s.replace('Cl50 BEFORE12; sole2353/originalrec1885+1893','Cl51 BEFORE12 honestreaudit; sole6834/originalrec4564')
n=B/'prepare_clothing_fifty_first.py';assert not n.exists();n.write_text(s,encoding='utf-8');print('CreatedCl51 preciseasymmetricliteralphase beforepreparer')
