from pathlib import Path
B=Path(__file__).resolve().parent
s=(B/'prepare_clothing_forty_seventh.py').read_text(encoding='utf-8').replace('forty-seventh','forty-eighth').replace('CALL=[2440]','CALL=[4425]').replace('if i==3085:','if i==4449:').replace('if i==3400:','if i==4425:')
s=s.replace('Individual actualMaterials1897 TextureID3085 / Template1271 opaqueClamp diffuseCOLOR with no staticModels consumers resolved. StoredRGB has79 distinctvalues and sparse whitegray linearpaint across black field, variableA0/255. Exact sourcepurpose unresolved; no fake structuralclassification/faceanatomy or original-onlyrecommendation. Genuinepending0call, every storedRGB/A byte preserved.','Genuine actual staticMaterials→TemplateID→Models coloredleaf/camouflage/maskedface diffuseUV with TWO actualeye alpha holes andcomplexoriginalleafpaint, fullRGB/variableA0/255. Exactsmall leafpaintcount/roles notfullyresolved here, genuinepending0call; not technical by Scout/name/mask/A or falseoriginalpurpose recommendation.')
start=s.index(' boxes=');end=s.index('\n domains=[]',start)
s=s[:start]+" boxes=[('ONE original large nearflat warmbrown diffusefield',[0,28,128,128]),('ONE original darker top bandedpaintpatch',[58,0,83,24]),('ONE original lighter top bandedpaintpatch',[96,0,123,27]),('ONE original weakleftvertical pale pigmentdab',[0,6,13,28])]"+s[end:]
s=s.replace("[('column',65,1,25),('column',108,1,25),('row',72,40,93),('row',43,52,77),('row',61,49,79),('row',105,1,127),('row',120,1,127),('column',24,1,28)]","[('column',65,1,25),('column',108,1,25),('column',5,1,28),('row',8,48,123),('row',14,48,123),('row',64,1,127),('row',120,1,127)]")
start=s.index(' description=');end=s.index('\n cons.append',start)
description='Image1 is ENTIRE original128square warmbrown FLATPAINT diffuseUV artwork, NOT a facephoto or portrait. The sourcehasNOvisibleface/ears/eyes/mouth/hair/body andNONE maybe invented despite resourceheadname. Keep ONE dominant nearflat matte warmbrown field RGB162/106/71 overmostcanvas (14236 exactnativepixels); no grain/no surface/lighting/backgroundgradient/newmottle. Keep ONLY the existing THREE localpaint features: TWO faintsmall horizontalbandedpatches near TOP (darker x58..82,y0..23; lighterx96..122,y0..26) andONE weakpaleverticaldab atLEFT x0..12,y6..27. Keep EXACT existing softedges, sourcefilteredblur, horizontalbandstroke count/pitch/phase andweakpigmentstrength; no new horizontalstrokes/rectangles/buttons/metal/grids/numbers/glyphs. Native darkbandcolumn65 literalshade maxima y7,10,14,18 andlightbandcolumn108 y4,7,10,14,24; these exactsourcepaintprofiles are NOT physicalfingers/teeth/anatomy. Preserveoriginalweakleftdab insteadof addingnewstripe or turningitwhite. No new forms, no roughpaper/fibers/weave/photo pores/anatomy/skin lighting/relief/bevel/glare/rust/etchedlines/hair locks or decorativepattern; entireclearflatfield staysflatpaint, NO artisticdetail beneath sourceblur.'
s=s[:start]+' description='+repr(description)+s[end:]
start=s.index("'source_feature_counts':{");end=s.index(",'native_repeat_count_phase_evidence'",start)
s=s[:start]+"'source_feature_counts':{'dominant_nearflatpaintfield':1,'existing_top_bandedpaintpatches':2,'weakleftverticalpigmentdab':1,'visibleface_or_hair_parts':0}"+s[end:]
s=s.replace('EligibleFIRST on genuinelynew originalinvertedFace wholeUV layout after sourcehistorical/release/nativeRGBA/POT/TypeA255/actualstaticMaterials→TemplateID→Models/fullRGB+A+NN/identity/softpaint/nativeweakphase/count proof. Complete native128opaque RGBtoolref, no NN/toolrotate/register; one sourcemouth/ear andpaired shadowpaint unchanged, no photoanatomy or sharpenedfibers.','EligibleFIRST originalnearflatcolorpaint with TWO topbandedpatches/ONEweakleftdab, fullnative exactRGBA/historyrelease/POT/TypeOrdinaryA255/actualMaterial2721→Template1760→Models4585.Material1, nativeopaqueRGB reference +privateNN counts. SourceRGB186distinct/weakexistingpigment notconstantRGBA/technicalbyname. No invisibleface reconstruction/grain/materialreinterpretation; sourceblur/nativephase/fullUV preserved.')
s=s.replace('all_selected_outside_previousClothing1to46','all_selected_outside_previousClothing1to47').replace('sole2440 FIRSTcall','sole4425 FIRSTcall').replace('Cl47 immutable12ID/uniquegroups/ONEprospectiveFIRST','Cl48 immutable12ID/uniquegroups/ONEprospectiveFIRST')
start=s.index(" i=c['id'];parts=");end=s.index("\n arg=",start)
parts=" i=c['id'];parts=['Use case: precise-object-edit. Asset type: softlyfiltered painted diffuse COLOR UV map. Refine SAME existing tiny paintedmarks while strictly retaining nativeblur/count/phase/scale andnearflatpaint.', 'Image1 edit target: ENTIRE nativeoriginal128square storedRGBmadeopaque atnative resolution, not NN reference. ActualMaterial2721 Template1760 Models4585.Material1 colorasset. Ordinary straightRGB/sourceA255 separately restored; no premise of invisibleface/anatomy fromfilename.', c['source_description'], f'ExactnativeRGBA extrema {c[\"actual_RGBA_extrema\"]}; oldstrongestRGBA {c[\"native_source_max_mean_RGBA\"]} at{c[\"native_source_max_mean_RGB_xy\"]}. Keep those SAME olddim patches, sameoriginalwarmbrown/palegraybrown palette and SMALLpeak. Do NOT brighten towhite255 or increaseoldmarkstrength. DominantbackgroundRGB162/106/71 remains flatuniformpaint with onlytheoriginalweakcompressedvariations, NO addedgrain/dither/coarsecells/tonalclouds.', 'Output SAME ENTIRE SQUARE opaqueRGB UVcanvas at higherresolution. Preserve exact normalizedUVpositions/relativeareas/sourceblur/nativepatternscale; no crop/zoom/rotate/recenter/padding/whitespace/border/BBox/islandmoves/fitting. Do NOT create a face or limbs/hair/eyes/teeth/anatomy/physicalmaterial/lights/text/glyphs/brushcurl/texturegrain. Onlytheexisting TWObandedpaintpatches plusONEweakleftdab ontheoriginalnearflatwarmfield.']"
s=s[:start]+parts+s[end:]
n=B/'prepare_clothing_forty_eighth.py';assert not n.exists();n.write_text(s,encoding='utf-8')
print('Created Cl48 exact nearflatpaint fullcanvas BEFOREproof preparer')
