from pathlib import Path
B=Path(__file__).resolve().parent
s=(B/'prepare_clothing_forty_sixth.py').read_text(encoding='utf-8').replace('forty-sixth','forty-ninth').replace('CALL=[799]','CALL=[6238]').replace('if i==2010:', 'if i==4518:').replace('if i==2237:', 'if i==5729:')
s=s.replace('Genuine actual staticdiffuse coloredleaf/camouflage/maskedface UV canvas with TWO actual alphaeyeholes, complex existing leafpaint/variableA. FulloriginalstoredRGB and EVERY A byte remain authoritative; not analytic/technical by alpha/mask/Scoutname. Exactsmall leafcount/paintroles unresolved for a firstcall here, genuinepending0call.','Individual ORIGINAL-ONLY recommendation pendingROOT: fullnative256x128 Ordinary RGBA ALL32768pixels exactly[0,0,0,0], not merelyRGBblack/A0/nearflat guess. ActualMaterials2812 Texture4518 Alphaalpha_test AddressClamp Template1814→Models4587.Material3/ModelTemplate3067/Geometry2703. Fullhistorical/release exactRGBA/binary parity andrealconsumer proveconstantzero/discard-color source; no coloredpaint/weakpigment/hiddenusefulRGB togenerate. No runtime/modelmesh role invented, rootfullnative/functional test required; fullsource retained unchanged/no imagegen. Notgroupban andNOTOrdinarymeansA255.')
s=s.replace('Individual actualstatic color diffuse source has186 distinctRGB values, nearflatwarmtanpaint plus TWO upperbandedbrown/lightpatches and a weaklefttonalmark, A255. FullRGBA notconstant and no provenanalyticpurpose. Genuinepending0call preservingweakpaint/nativephase ratherthan technical/name/family/nearflatness ban or inventedmissing face.','Genuine actualstatic color diffuse128whole with471distinctRGB, broadnearflatpinkbrownfield plusONEearpaint/TWOtopbandedfields/ONEdarkdiagonalcornerstrip. No fullconstantRGBA/analyticpurpose classification. Exactweakfield/nativephase/material andunknownnarrowstrip purpose unresolved; genuinepending0call without inventedface/hardware beneathflatpaint.')
start=s.index(' boxes=');end=s.index('\n domains=[]',start)
s=s[:start]+" boxes=[('ONE original deliberately inverted centralfacepaint',[24,22,116,101]),('ONE original visibleearpaint upperleft',[3,0,37,29]),('ONE originalleft topnearflatpaintstrip',[0,0,14,31]),('ONE originalbrown topbandedpaintpatch',[48,0,83,28]),('ONE originallighter topbandedpaintpatch',[98,0,123,27]),('FIRST originaldim brown eyeshadowpaint',[43,64,65,84]),('SECOND originaldim brown eyeshadowpaint',[67,64,89,84]),('ONE originalnosepigment',[55,48,75,65]),('ONE originalclosedpinkredmouthpaint',[52,34,77,51]),('ONE originalforeheadsoftpaint',[39,78,91,102]),('ONE originalconnectedlowerhairpaint andirregularUVtips',[0,78,128,128])]"+s[end:]
s=s.replace('centralinverted facepaint x28..110,y22..98','centralinverted facepaint x24..115,y22..100').replace('topLEFT x8..37,y0..29','topLEFT x3..36,y0..28').replace('brownx48..81,y0..26','brownx48..82,y0..27').replace('x44..64 and69..88,y65..82','x43..64 and67..88,y64..83').replace('nosepigment x56..73,y48..64','nosepigment x55..74,y48..64').replace('closedpinkmouthpaint x54..72,y36..49','closedpinkredmouthpaint x52..76,y34..50').replace('x0..127,y80..127','x0..127,y78..127')
s=s.replace('all_selected_outside_previousClothing1to45','all_selected_outside_previousClothing1to48').replace('Selected12ID contain8uniqueoriginalpayloads; pendingaliases1883/2006/2156 and1887/1891/2152 are NOTaccepted donors or calledreuse. Onlyunique799 toolcandidate; allaccepted/generatedexactRGBA excluded.','Selected12 exactnativeRGBA groups enumerated; pending-onlyduplicates NOTaccepted/generated donors orreuse. Onlyunique6238 soleFIRST; prioraccepted/generated aliases excluded.').replace('Cl46 immutable12ID/8unique/ONEprospectiveFIRST','Cl49 immutable12ID/uniquegroups/ONEprospectiveFIRST')
s=s.replace("save(f'original-only-proof-{ST}.json',[]);", "orig=[{'id':r['id'],'status':'individual-original-only-fullconstant-zeroRGBA-recommendation-rootreview','call_count':0,'reason':r['source_only_reason'],'native_matrix_ref':r['native_matrix_ref'],'actual_consumers':r['fresh_actual_static_consumers'],'common_actual_records':r['common_actual_records'],'source_RGBA_extrema':M[str(r['id'])]['actual_source_RGBA_extrema'],'fullsourceRGBA_constant_proof':{'size':[256,128],'pixel_count':32768,'one_distinct_RGBA':[0,0,0,0],'historical_release_native_exact':True},'not_runtimeaccepted':True}for r in P if r['id']==4518];save(f'original-only-proof-{ST}.json',orig);selected=read(B/f'selected-{ST}.json');save(f'selected-original-only-{ST}.json',[{**r,'worker_original_only_recommendation':orig[0]}for r in selected if r['id']==4518]);")
s=s.replace("'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL]", "'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL and r['id']!=4518]").replace("'recommended_original_only_ids':[]", "'recommended_original_only_ids':[4518]")
s=s.replace(" if i not in CALL:continue", " if i==4556:r['source_only_reason']='Genuineactualstatic leather/cloth paintedatlas128square A255 witholdcrosspaint/narrowstraps/buckledgraylines; exactsymbol/weakfastener/paintcounts requireliteralproof beforeanycall, genuinepending0call withouttechnical/nameban or guessedphysicalmechanism.'\n if i==4518:assert np.all(a==0)and o.size==(256,128)and r['fresh_actual_static_consumers'][0]['actual_Alpha_AddressMode']==['alpha_test','Clamp']\n if i not in CALL:continue")
n=B/'prepare_clothing_forty_ninth.py';assert not n.exists();n.write_text(s,encoding='utf-8');print('CreatedCl49 BEFORE counts/sourceRGBA/individualconstant4518 preparer')
