from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='equipment-thirty-sixth';CALL=[5390];READY=[5390]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
before=B/f'source-check-{ST}-before-call.json';proof=read(B/f'source-check-{ST}.json');assert proof==read(before)
selected=read(B/f'selected-{ST}.json');scope=read(B/f'scope-{ST}.json');assert len(selected)==12 and [r['id']for r in selected]==scope['selected_ids']
constraints=read(B/f'pattern-constraints-{ST}.json')[0];cpath=B/f'generated/5390-{ST}-call.json';c=read(cpath)
assert sha(ROOT/c['generated'])==c['raw_sha256'];assert sha(ROOT/c['prompt_file'])==c['prompt_sha256'];assert (ROOT/c['prompt_file']).read_bytes()==c['exact_prompt'].encode('utf-8')
assert all(sha(ROOT/p)==h for p,h in c['reference_sha256'].items());assert sha(B/f'pattern-constraints-{ST}.json')==c['pattern_constraints_file_sha256']
o=Image.open(B/'original/5390.png').convert('RGBA');n=Image.open(B/f'private-{ST}/native4x/5390-calibrated-native-alpha-private.png').convert('RGBA')
assert n.size==(128,128);assert n.getchannel('A').tobytes()==o.getchannel('A').resize(n.size,Image.Resampling.LANCZOS).tobytes()
s=np.asarray(o.convert('RGB'));g=np.asarray(Image.open(B/f'private-{ST}/native4x/5390-stored-rgb-private.png').resize(o.size,Image.Resampling.LANCZOS).convert('RGB'))
v=g[24:31,11:18].mean((1,2));peaks=[24]+[y+24 for y in range(1,len(v)-1)if v[y]>v[y-1]and v[y]>v[y+1]];assert peaks==constraints['source_band_native_y_phase']==[24,26,29]
local={'id':5390,'whole_inverse':'ENTIRE calibrated storedRGB LANCZOS inverse to32x32 solely numeric diagnostic, never image repair/crop/composite.','source_band_count':3,'source_band_native_y_phase':[24,26,29],'production_band_native_y_phase':peaks,'production_band_mean_luma_profile_y24_through30':v.tolist(),'actual_native_type':'Ordinary','sourceA_extrema':[255,255],'fullA4x_byte_exact':True,'domains':[]}
for z in constraints['source_domains']:
 x0,y0,x1,y1=z['bbox'];p=g[y0:y1,x0:x1];local['domains'].append({'name':z['name'],'bbox':z['bbox'],'source_mean_RGB':z['mean_RGB'],'production_mean_RGB':p.mean((0,1)).tolist(),'source_max_RGB':z['max_RGB'],'production_max_RGB':p.max((0,1)).tolist()})
save(f'local-tone-phase-{ST}.json',[local])
metrics=read(B/f'metrics-{ST}.json')[0];detail=read(B/f'detail-metrics-{ST}.json')[0]
note='Candidate ONLY root final art/native review, not accepted. Full originalRGBA/opaqueRGB NN16x512 reference/raw1254/full4x128/sourceA/pure scalar storedRGB privately inspected. Entire graybrown/olive atlas preserves upper-left gray painted round field, lower-left gray rectangle, lower-middle graycyan field, right dark warm brown/olive and lower warm source wedge. EXACT THREE original flat graycyan tonal bands retain source y24/26/29 maxima and native width/pitch/phase; these are tonal bands, not inferred physical vents/mechanisms. No new fasteners/parts/rays/text or physical material relief observed. Caveats: gray upper-left field becomes warmer and contrast stronger, gray shadow edges/blocklike source transitions become more evident. Its meanRGB38.66/35.44/30.13 ->43.37/38.85/32.26, peak82/73/66 ->95/86/77. Lower-left gray rectangle mean76.84/77.22/75.26 ->68.94/69.14/68.20 (dimmer). Right dark warm field mean32.90/23.20/4.87 ->34.82/23.68/3.88 and peak85/64/44 ->104/76/39. Existing lower border pixel native19,21 source107/93/66 ->133/111/71 maxchannel+26. Graycyan field mean66.37/69.94/67.18 ->61.39/64.58/62.46. Source fine painted texture becomes visibly more brush-textured at fullraw resolution; root should judge native material softness against explicit source. Moderate local lift/1pixel smoothing is not alone a count failure or invented hardware proof. Stored native inverse luma correlation.9771 diagnostic, not acceptance threshold. Ordinary actual Material3515 Alphaopaque/AddressModeClamp/Template2256 actualModel5637/Geometry3465/ModelTemplate3720; exact nativeRGBA/history-release-source parity checked; no Particle bindings and no inferred meshUV. A255 entire source includes black shadows, not empty cutouts. Default sourceA4x byteexact/pure scalar/defaultpad0/POT128whole; no RGB repair/crop/BBox/optout/retry. One first sole builtin call.'
records=[{'id':5390,'status':'ready-for-coordinator-art-native-review','call_count':1,'reason':note,'generated':c['generated'],'raw_sha256':c['raw_sha256'],'prompt_file':c['prompt_file'],'prompt_argument_sha256':c['prompt_sha256'],'call_metadata':rel(cpath),'call_metadata_sha256':sha(cpath),'reference_sha256':c['reference_sha256'],'source_transform_recipe':c['source_transform_recipe'],'actual_tool_arguments':{'prompt':c['exact_prompt'],'referenced_image_paths':[str((ROOT/p).resolve()).replace('\\','/')for p in c['reference_pngs']],'transparent_background':False},'metrics':metrics,'detail_metrics':detail,'local_tone_phase':local}]
for r in proof:
 if r['id']==5390:r.update(imagegen_call_count=1,postcall_status='ready-for-coordinator-art-native-review',review_note=note,full_raw_native4x_source_alpha_storedRGB_privately_reviewed=True)
 else:records.append({'id':r['id'],'status':'genuine-art-pending-source-count-content-material-proof','call_count':0,'reason':r['source_only_reason']})
save(f'jobs-{ST}.json',[{'id':5390,'generated':c['generated'],'prompt':c['exact_prompt'],'source_transform_recipe':c['source_transform_recipe']}]);save(f'source-check-{ST}.json',proof)
sp=B.parent/'sources.json';qp=B/'queue.json';ss=read(sp)['textures'];q=read(qp);ex=read(B/f'exclusions-{ST}.json')
assert not set(scope['selected_ids']).intersection(ex['ids']);assert all(r['source_rgba_sha256']not in ex['blocked_hashes']for r in proof)
save(f'final-guards-{ST}.json',{'utc':datetime.now(timezone.utc).isoformat(),'precall_source_entry_count':ex['source_entry_count'],'precall_queue_count':ex['queue_count'],'postcall_source_entry_count':len(ss),'postcall_queue_count':len(q),'current_queue_status_counts':{z:sum(r.get('status')==z for r in q)for z in sorted({str(r.get('status'))for r in q})},'source_count_semantics':'Source entries may include root generated-pending-validation; entry count is NOT productionaccepted count. Legacy exclusion accepted_count key means source entries.','own_postcall_overlap':[{'id':r['id'],'status':r.get('status')}for r in ss+q if r['id']in scope['selected_ids']],'sources_sha256':sha(sp),'queue_sha256':sha(qp),'calls':1,'retries':0,'shared_writes':False,'guard_semantics':'Fresh beforecall accepted/queue/allaliases/raw/calls/jobs/held/refusal/exactRGBA guard passed. Honest prior source-only views are allowed re-audits; no prior generated source repeated.'})
save(f'review-{ST}.json',{'status':'stable-complete-ready-subset-coordinator-review','batch':ST,'selected_ids':scope['selected_ids'],'generated_ids':CALL,'ready_ids':READY,'held_ids':[],'pending_uncalled_ids':scope['pending_uncalled_ids'],'call_count':1,'maximum_authorized_call_count':3,'not_forced_calls':True,'records':records,'source_before_call':rel(before),'source_before_call_sha256':sha(before),'pattern_before_call':rel(B/f'pattern-constraints-{ST}.json'),'pattern_before_call_sha256':sha(B/f'pattern-constraints-{ST}.json'),'source_parity':'All12 native historicalMMP/release resource/existing original fullRGBA/dimensions exact; fresh actualTexture/Materials/MaterialTemplate/allActualModels/Geometries/ModelTemplates and other direct typed consumers checked. No missingParticle classification forMaterial-only sources, no fake modelUV proof. All sourceonly genuine source art individually pending, not blankettechnical.','QA':'One first builtin only after whole sourceRGBA/RGB/reference inspection and native count/phase/palette BEFOREprompt. ExactCRLF argument/raw/refSHA/call saved immediately. Fullraw/native4x/material/fullsourceA/defaultpad/pure scalar privately reviewed. Native sourcealpha byteexact and three tonal peaksphase asserted. All local-tone/material-softness caveats explicit; root sole final acceptance. No oldstable/shared/Git/Game/C++/build/import writes, RGB artistic repair/crop/BBox/retry/optout.'})
mp=B/f'sha256-{ST}.json';files=list(B.glob(f'*{ST}*.json'))+list(B.glob('*thirty_sixth.py'))+list((B/'generated').glob(f'*{ST}*.png'))+list((B/'generated').glob(f'*{ST}*-call.json'))+[ROOT/c['generated'],ROOT/c['prompt_file']]+list((B/f'private-{ST}').rglob('*.png'))
save(mp.name,{rel(p):sha(p)for p in sorted(set(files))if p!=mp});assert all(sha(ROOT/p)==h for p,h in read(mp).items())
print(json.dumps({'ready':READY,'pending_uncalled':11,'calls':1,'sha256':{n:sha(B/f'{n}-{ST}.json')for n in ['jobs','review','source-check','selected','sha256']}},indent=2))
