from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='effects-twenty-eighth';CALL=[4089,4092];READY=[4089];HELD=[4092]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def ref(p):return {'path':rel(p),'file_SHA256':sha(p)}
before=B/f'source-check-{ST}-before-call.json';source=B/f'source-check-{ST}.json'
assert source.read_bytes()==before.read_bytes()
proof=read(before);scope=read(B/f'scope-{ST}.json');selected=read(B/f'selected-{ST}.json')
assert len(selected)==12 and [r['id']for r in selected]==scope['selected_ids']
matrices=read(B/f'native-matrices-{ST}.json');actual=read(B/f'actual-records-{ST}.json')
canonical=lambda row:hashlib.sha256(json.dumps(row,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode('utf-8')).hexdigest()
for table,rows in actual['tables'].items():
 for key,row in rows.items():assert canonical(row)==actual['record_SHA256'][table][key]
for r in proof:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');m=matrices['sources'][str(i)]
 assert np.array(m['native_RGBA_matrix'],dtype=np.uint8).tobytes()==o.tobytes()
 assert sha(B/f'original/{i}.png')==r['original_PNG_file_SHA256']
 for key in ['native_matrix_ref','common_actual_records']:
  rr=r[key];assert sha(ROOT/rr['path'])==rr['file_SHA256']
 rref=r['actual_Texture_record_ref'];assert canonical(actual['tables'][rref['table']][str(rref['id'])])==rref['canonical_record_SHA256']
metrics={r['id']:r for r in read(B/f'metrics-{ST}.json')};detail={r['id']:r for r in read(B/f'detail-metrics-{ST}.json')};material={r['id']:r for r in read(B/f'material-phase-{ST}.json')};weak={r['id']:r for r in read(B/f'weakpixel-{ST}.json')};uncalled={r['id']:r for r in read(B/f'source-only-detail-{ST}.json')}
notes={
4089:'READY CANDIDATE for coordinator whole-art/native review, not accepted. Original native32 Transparent A0..255 stored RGB has two literal positive-RGB 8-connected painted domains: main66 pixels bbox[10,7,22,25], separate dim lower-right27 pixels bbox[17,21,24,28]. These are bitmap diagnostics, not physicalparticle/hardware counts. Full originalRGBA/RGB/NN16x512/A inspected before tool; immutable native matrix/count/weak-pigment/zero-map/maxima/phase/palette proof before prompt. One FIRST sole builtin retains two broad painted fields, winding subdued gray-violet/brown main stroke and dim separate right field, original normalized UV/scale/asymmetry, no new bright fragments/shine/outlined physical mechanism observed. Fullraw1254 has finer soft/fuzzy painted transitions, native128 standard scalar0.8287353515625/defaultpad0/Transparent premultiply/full originalA byteexact inspected. Caveats: lower native peak13,20 source129/114/117 ->115/102/103 weakens; same strongestmean location retained. Max localmean lift+21.33 at14,22 source59/51/51 ->84/71/70, maxloss-20.33 at13,23. Upper mean18.66/15.91/17.11 ->19.60/16.09/17.09; middle30.61/26.71/28.68 ->34.71/29.79/31.61; lower31.46/27.14/27.64 ->31.25/26.82/26.64. Separate dim right mean7.22/6.16/6.63 ->7.90/6.45/6.61; max49/42/44 ->48/40/41. Some internal original RGB-zero pixels with nonzero A receive adjacent paint: native14,18 A255 ->12/10/10;14,19 A255 ->16/14/14;15,23 A190 ->12/10/10;20,25 A255 ->6/5/5, all adjacent original pigment. Weak source1..5 bits include quantization losses, detailed individually. Not a claim of exact native maxima/zero pixels preserved, no invented threshold acceptance; these local darkgap/blur/phase relationships need root review. Whole native footprint remains source-aligned; finer wash HPstd .987/.836/.860 ->1.466/1.260/1.280. No255 clip or new detached bright area observed. No RGBpatch/crop/BBox/fitting/retry/padding optout; source A complete. Present resolved actual Wrap0/0/Normal instance blend/IsCrown0 only, missingParticle200 for instance2070 explicit unknown. Root alone final material/weak-pigment acceptance.',
4092:'HELD soft material/paint blur review, not accepted; no repeat. Original native32 Transparent A0..255 one literal178 positive-RGB pixel domain bbox[9,2,22,24], compact asymmetric upright muted red/graybrown painted field, two original upper projections, original darkmiddle pigment gap, warmer lower wash and dimtaper. Not a physical metalplate/rock/U-mechanism count. SourceRGBA/RGB/NN16x512/A and complete native weakpixel/zero-map/count/maxima/phase/palette immutable before prompt. Fullraw1254 retains broad original field/projection positions/darkmiddle gap/count/whole UV; native128 standard scalar0.84454345703125/defaultpad0/Transparent downstream premultiply/fullsourceA byteexact. However full raw/private native4x gives the original blurred wash more definite outlined edges and visibly mottled/coarser colored paint fields instead of source soft smooth shades. Hold is actual material/blur depiction, not automatic highpass/1pixel or any grayscale family ban. HPstd .937/.554/.510 ->2.273/1.451/1.387 supports the visible fine-material difference, not independent threshold. Same source peak19,12 RGB119/80/73 ->131/86/77; max localmean lift+14.67 at15,14 source120/62/42 ->142/76/50, maxloss-12.33 at18,15. Upperleft mean22.01/13/14.54 ->23.71/12.83/14.34; upperright34.32/23.79/24.41 ->36.20/24.12/24.08; warmer lower34.73/23.19/22.48 ->36.41/22.95/21.33; relative redbrown stronger locally and more concrete shaded forms. Original zero RGB locations production max1/1/1, none>5, no255 clip, but faint original bits partially quantize to zero. Whole original alpha restored; no acceptance/Game/runtime claim. Present resolved actual Wrap0/0/Normal/IsCrown0 only, missingParticle200 instance2070 unknown. Raw/exactarg/reference remain untouched; rejected copy+reason retained, genuine pending artreview not permanent refusal.'}
records=[];jobs=[];post=[]
for i in CALL:
 cp=B/f'generated/{i}-{ST}-call.json';c=read(cp)
 assert sha(ROOT/c['generated'])==c['raw_sha256'] and sha(ROOT/c['prompt_file'])==c['prompt_sha256']
 assert (ROOT/c['prompt_file']).read_bytes()==c['exact_prompt'].encode('utf-8')
 assert all(sha(ROOT/p)==h for p,h in c['reference_sha256'].items())
 for key in ['pattern_constraints_ref','native_matrix_ref','common_actual_records','source_before_call_ref']:
  rr=c[key];assert sha(ROOT/rr['path'])==rr['file_SHA256']
 o=Image.open(B/f'original/{i}.png').convert('RGBA');n=Image.open(B/f'private-{ST}/native4x/{i}-calibrated-native-alpha-private.png').convert('RGBA')
 assert n.size==(o.width*4,o.height*4) and n.getchannel('A').tobytes()==o.getchannel('A').resize(n.size,Image.Resampling.LANCZOS).tobytes()
 status='ready-for-coordinator-art-native-review'if i in READY else'held-original-softpaint-material-blur-review'
 r={'id':i,'status':status,'call_count':1,'reason':notes[i],'generated':c['generated'],'raw_sha256':c['raw_sha256'],'prompt_file':c['prompt_file'],'prompt_argument_sha256':c['prompt_sha256'],'call_metadata':ref(cp),'reference_sha256':c['reference_sha256'],'source_transform_recipe':c['source_transform_recipe'],'metrics':metrics[i],'detail_metrics':detail[i],'material_phase':material[i],'weakpixel_checks_ref':{**ref(B/f'weakpixel-{ST}.json'),'id':i},'production_matrix_ref':{**ref(B/f'production-matrices-{ST}.json'),'source_key':str(i)}}
 if i in READY:jobs.append({'id':i,'generated':c['generated'],'prompt':c['exact_prompt'],'source_transform_recipe':c['source_transform_recipe']})
 else:
  rd=B/f'rejected/{ST}';rd.mkdir(parents=True,exist_ok=True)
  for suffix,p in [('raw.png',ROOT/c['generated']),('prompt.txt',ROOT/c['prompt_file']),('call.json',cp)]:
   target=rd/f'{i}-attempt1-{suffix}';assert not target.exists();shutil.copyfile(p,target)
  save(f'rejected/{ST}/{i}-attempt1-reason.json',{'id':i,'status':status,'reason':notes[i],'raw_sha256':c['raw_sha256'],'no_repeat':True,'not_permanent_refusal':True});r['rejected_raw']=rel(rd/f'{i}-attempt1-raw.png')
 records.append(r);post.append({'id':i,'imagegen_call_count':1,'postcall_status':status,'postcall_review_note':notes[i],'full_raw_native4x_sourceA_storedRGB_privately_reviewed':True})
for r in proof:
 if r['id']not in CALL:records.append({'id':r['id'],'status':'genuine-color-art-pending-faithful-weakphase-material-review','call_count':0,'reason':uncalled[r['id']]['reason'],'native_matrix_ref':r['native_matrix_ref'],'common_actual_records':r['common_actual_records'],'unresolved_Particles_definitions':r['material_evidence']['unresolved_particle_definitions'],'missing_sibling_Textures':r['material_evidence']['missing_sibling_Texture_rows']})
save(f'jobs-{ST}.json',jobs);save(f'postcall-source-status-{ST}.json',post)
S=read(B.parent/'sources.json')['textures'];Q=read(B/'queue.json');ex=read(B/f'exclusions-{ST}.json')
assert not set(scope['selected_ids']).intersection(ex['ids']) and all(r['source_rgba_sha256']not in ex['blocked_hashes']for r in proof)
save(f'final-guards-{ST}.json',{'utc':datetime.now(timezone.utc).isoformat(),'before_source_entry_count':ex['source_entry_count'],'before_queue_entry_count':ex['queue_count'],'postcall_source_entry_count':len(S),'postcall_queue_entry_count':len(Q),'source_entry_count_is_not_accepted_count':True,'queue_status_counts':{z:sum(r.get('status')==z for r in Q)for z in sorted({str(r.get('status'))for r in Q})},'own_postcall_overlap':[{'id':r['id'],'status':r.get('status')}for r in S+Q if r['id']in scope['selected_ids']],'sources_SHA256':sha(B.parent/'sources.json'),'queue_SHA256':sha(B/'queue.json'),'calls':2,'retries':0,'shared_writes':False,'guard_semantics':'Fresh sources/q/allaliases/priorraw/calls/jobs/held/refusal/exactRGBA guards passed before each tool. Prior0call source-only honest re-audit allowed, no accepted/called repeat. Sourceproof main/before bytes immutable; postcall status separate. Any concurrent root sharedwrites not worker.'})
save(f'review-{ST}.json',{'batch':ST,'status':'stable-complete-ready-subset-coordinator-review','selected_ids':scope['selected_ids'],'unique_native_RGBA_groups':scope['unique_native_RGBA_groups'],'unique_native_RGBA_count':scope['unique_native_RGBA_count'],'generated_ids':CALL,'ready_ids':READY,'held_ids':HELD,'pending_uncalled_ids':scope['pending_uncalled_ids'],'call_count':2,'max_authorized_calls':3,'not_forced_call_count':True,'records':records,'source_before_call':ref(before),'source_check':ref(source),'pattern_before_call':ref(B/f'pattern-constraints-{ST}.json'),'native_matrix':ref(B/f'native-matrices-{ST}.json'),'actual_records':ref(B/f'actual-records-{ST}.json'),'production_matrix':ref(B/f'production-matrices-{ST}.json'),'postcall_source_status':ref(B/f'postcall-source-status-{ST}.json'),'preparation_diagnostics':ref(B/f'preparation-diagnostics-{ST}.json'),'postcall_corrections':[],'source_parity':'Fresh historical MMP == release native resource == original fullRGBA/dims/Type. Fresh exact all ParticleInstances TextureN slots/static/blend/pivots/positiveframes/siblings and present definitions Wrap; missing explicit unknown. All actual Material/Final/Container/Model/template records if present saved once. Compact canonical-record SHA refs to593 unique actualDB rows and native matrices12 once, no duplicated raster arrays per consumer. Original native extrema, weak/count/zero/maxphase fully proven before prompt. Prior source-only0call audits honest re-audit, not newly neverviewed. A0 Add useful RGB retained; fullcanvas annotation concerns imageprocessing, not guessed renderer mesh/framegrid.', 'QA':'Two FIRST sole builtins/no retries/no forced third; whole original sourceRGB/A/NN then fullraw/private128 standard scalar/defaultpad0/nativeType-premultiply/sourceA byteexact/material/weakzero/palette checks. 4089 readycandidate caveats softened lowerpeak, slightly stronger thinmiddle, some adjacent internalzero/dim bits smoothed and some1..5 quantization losses;4092 held materially more outlined mottled colored paint than smooth source wash. Ten genuine pending0call sources, individual reasons, no broad family/technical ban. No artist RGB repair/crop/BBox/fitting/padding optout/native/Game acceptance. Final art/weakstrength/root approval pending.', 'ownership':'Own Effects28 files only. Effects27/26 and all earlier stable/sourceproof bytes untouched, shared/import/calibration/build/Game/C++/Git untouched. Root sole coordinator/final native material acceptance.'})
assert source.read_bytes()==before.read_bytes()
mp=B/f'sha256-{ST}.json';files=list(B.glob(f'*{ST}*.json'))+list(B.glob('*effects_twenty_eighth*.py'))+list((B/'generated').glob(f'*{ST}*.png'))+list((B/'generated').glob(f'*{ST}*-call.json'))+list((B/f'private-{ST}').rglob('*.png'))+list((B/f'rejected/{ST}').rglob('*'))
for i in CALL:files.extend([B/f'generated/{i}-raw.png',B/f'generated/{i}-prompt.txt'])
save(mp.name,{rel(p):sha(p)for p in sorted(set(files))if p.is_file()and p!=mp});assert all(sha(ROOT/p)==h for p,h in read(mp).items())
print(json.dumps({'ready':READY,'held':HELD,'calls':2,'pending0call':10,'selectedIDs':12,'uniqueRGBA':scope['unique_native_RGBA_count'],'beforeproof_byteunchanged':True,'flat_manifest_entries':len(read(mp)),'SHA256':{n:sha(B/f'{n}-{ST}.json')for n in ['jobs','review','source-check','selected','sha256']}},indent=2))
