from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='clothing-forty-fourth';CALL=[6823,7607,7610];READY=[7607,7610];HELD=[6823]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
def ref(p):return {'path':rel(p),'file_SHA256':sha(p)}
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
before=B/f'source-check-{ST}-before-call.json';source=B/f'source-check-{ST}.json';assert source.read_bytes()==before.read_bytes()
P=read(before);selected=read(B/f'selected-{ST}.json');scope=read(B/f'scope-{ST}.json');assert len(P)==len(selected)==12
actual=read(B/f'actual-records-{ST}.json');matrices=read(B/f'native-matrices-{ST}.json')['sources'];canon=lambda r:hashlib.sha256(json.dumps(r,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode('utf-8')).hexdigest()
for table,rows in actual['tables'].items():
 for k,r in rows.items():assert canon(r)==actual['record_SHA256'][table][k]
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');assert np.array(matrices[str(i)]['native_RGBA_matrix'],dtype=np.uint8).tobytes()==o.tobytes();assert sha(B/f'original/{i}.png')==r['original_PNG_file_SHA256']and r['source_RGBA_RGB_A_NN_privately_inspected'];assert r['imagegen_call_count']==0
 for k in ['native_matrix_ref','common_actual_records']:assert sha(ROOT/r[k]['path'])==r[k]['file_SHA256']
 h=ROOT/r['helper_recipe']['output'];assert Image.open(h).size==o.size and Image.open(h).convert('RGB').tobytes()==o.convert('RGB').tobytes()
notes={
6823:'HELD for original irregular tiny-paint phase/material review, not permanent refusal and no retry. Entire native128square Ordinary straightRGB/A255 original/history/release identical, actual Material→TemplateID→Models diffuse proof. Fullnative RGB toolreference preserves sourceblur, NN only private. Source has NINE bluegray groups and ONE grayupperrightbar, graymiddlecurve, smoothupperbrown/lowerwarmbrown/rightbrown fields, ONE tiny angular paleoutline and ONE flatwarmgray rightmark. Fullraw1254square→512square RGB-FIRST LANCZOS, fullsourceA255 restored, defaultwholepad/clear0/noPremul/scalar; all entire fields retained. HOWEVER small gray/brown irregular partially filtered pigment at native69..77,29..41 became TWO regular columns at x72/75 with FOUR roundedgray dots each at y31/34/37/39. Full source already contains more small gray/brown maxima than the SIX specifically named left-column gray marks in the prompt; do NOT assert six total physical parts became eight new eyelets. Exact before native matrix has sourceleft graypeaks71,32/35/38 and72,33/36/39 plus other right-gray/brown weak shades. Held because these irregular weak shades are regularized into round repeated dotforms with altered phase, not because a diagnostic maxima count measures physicalhardware. Sourceoriginalleft peaks71,32/35/38 RGB33/32/33,33/32/33,33/36/33→15/15/14,14/14/13,15/14/13; source72,33 RGB41/44/41→13/13/12. Actual production localdot peaks72,31 RGB45/45/44,75,31 41/41/40,72,34 42/42/41,75,34 42/41/41,72,37 40/39/38,75,37 36/35/34,72,39 33/33/33,75,39 33/33/32. Originaltriangle ONE retained but nativephase changes: source4,80 RGB16/24/33→100/103/106 versus natural39/43/51; source3,85 RGB132/130/132→64/70/74 versus natural121/120/122. Originalglobalpeak2,80 RGB173/174/173→154/166/169 versus natural161/163/162, not a new255 glint. Originalfarrightmark113,117 RGB123/117/99→121/102/97 vsnatural107/98/82, darkcap113,116 andside114,117 remain same ONE originalpaintmark, not a newphysicalbutton. Lowerbrownpaint became smoother/broader and diagonalbrushwash slightly clearer; no artist RGBfix or attempt to restore old dots. SourceA255 authoredblackUV notempty; fullA cannot repair RGBphase. All original raw/exactargs/ref/call/before remain unchanged; rejected copy retained. One-nativepixel smoothing alone is not hold, this is qualitative original irregular→regular repeated dotshape/phase drift.' ,
7607:'Worker READY CANDIDATE pending root independent source/raw/native artacceptance, NOT productionaccepted. FIRST sole builtin native128square Ordinary straightRGB/A255, fullsource exact historical/releaseRGBA and actual Material→TemplateID→Models. Entire nativeopaqueRGB reference, private NNcountproof only, sourceblur intentionally kept. Entire raw1254square→original4x512square RGB-FIRST LANCZOS independently originalA, defaultpadding/clear0/scalar/noPremul; no crop/islandregistration/source artistic insertion/localgain/retry. Original ONE deepredleft softpaint with broadwash, ONE smooth DARK warmbrown lowerleftplane, ONE connected thin ochre angularoutline+diagonaltrace, ONE darkgrayblue rightfield with originalshadowpaths, opaque authoredblackUV, ONE tiny pale cornerstroke in original horizontaltrace and TWO weak ochrepigment patches remain same whole UV/count/scale. Fullraw/4x show filteredmatte paint, no textilemesh/weave/fibers/castmetal/etchedgrain/newphysicalparts or altered broad field layout. Existing thin ochre line somewhat clearer/thicker, originalpolygoncorner remains connected with originaldiagonalendpoint; do not reinterpret as necklace/chain/glyph/hardware. Explicit weakphase/localtone caveats: firstpatch32..35,58..63 nativeROI mean6.208/4.292/2.458→9.25/6.333/2.792 andmax41/28/16→54/38/18; original34,60 RGB41/28/16→54/38/18 vsnatural39/26/15,34,61→45/30/14 vsnatural37/25/14. Patch remains dim with same location, secondpatch38,78 RGB46/29/18→41/28/12 vsnatural46/30/18, not new brightflecks. Originaltinyrightpeak106,66 RGB189/186/189→138/137/137 vsnatural167/164/167, productionnativepeak shifts to106,65 RGB167/166/166 versus original134/132/134/natural132/130/131; adjacent105,66 original24→76 vsnatural40/39/40. Existingstroke ONE locally broadened/clearer and one-nativepixel lightphase altered, globalpeak actually DIMMER than original, no newlyadded catch or white255. Lowerline native3,72 original181/146/99→121/77/38 versus natural178/142/95: originalweak angulartrace partly dimmer/harder and localpaintstrength not exactly retained, rootmustjudge fullshape/palette not meanmatch. Deepredfieldmean49.010/14.838/10.758→54.504/12.024/7.691, warmplane54.896/24.211/16.975→58.130/22.215/12.961, darkgrayblue10.751/12.381/13.675→10.922/12.804/14.518: warmred slightlystronger, caveat explicit. Whole originalsoftwash/material retained at nativepaintscale with modestpaintrefinement; moderatepaint/onepixelcontext not automatic hold or automaticaccept. Sourceblackcorner0,127 remains0; fulloriginalA restored byteexact; no clips/allwhite255. RootfinalUV/material/localtone acceptance required, scalar doesnotrepair localized strength or phase.' ,
7610:'Worker READY CANDIDATE pending root independent art/nativeacceptance, NOT productionaccepted. FIRST sole builtin native128square Ordinary straightRGB/sourceA255, fulloriginal/history/releaseRGBA exact, actual Material→TemplateID→Models diffuse bindings. ENTIRE originalnative opaqueRGB guide avoids NNblockseed, NNprivate only. Raw1254square→whole512square RGB-FIRST LANCZOS/fullsourceA255/defaultpad0/clear0/pureglobal scalar/noPremul. OriginalONE muteddeepredleft wash,ONE smoothwarmTAN lowerleftplane,ONE connected thin ochreangularoutline/diagonaltrace,ONE darkgraybluefield/shadowstrokes/blackUV,ONE smallpale cornerstroke inexistinghorizontaltrace and TWO dimochrepatches remain same originalwholepaint with softfilteredmaterial, no newweave/mesh/fibers/physicalgrain/hardware/shine/anatomy/glints or addedfields. Originaltan plane stays smoothbroadpaint; angularthintrace softer andsomewhat broader, nativepolygoncorner is less sharply outlined butsame connected sourcepigment location/endpoint, no RGB repair. Exactweaklocaltone/phase caveats: firstpatchROI source mean6.208/4.292/2.458→9.875/5.333/1.083 andsource max41/28/16→57/32/8;34,60 source41/28/16→57/32/8 vsnatural39/26/15,34,61→47/26/6 vsnatural37/25/14. Existingweakpatch more red/warm andclearer, still dimflatpaint, secondpatch38,78 source46/29/18→44/32/20 vsnatural46/30/18. Tinyrightpeak106,66 source189/186/189→160/157/156 vsnatural167/164/167, still same ONE cornerstroke/globalpeak DIMMER, not newwhitecatch. Neighbor107,66 source24/24/24→86/85/86 vsnatural45/45/46 givesmaxmeanlift61.667 andbroadercornerpaint footprint/lightphase; rootmustassess this explicit localchange ratherthan assume exactness from scalar. Lowerdiagonaltrace10,87 source164/108/71→97/62/37 vsnatural144/95/63 givesmaxmeanloss−49; weakline locallydimmer/softer and source-nativeextent altered within originalarea, no artificialrestore. Originalredfieldmean54.895/19.326/13.605→57.516/18.259/12.741; tanmean81.330/44.551/29.886→82.638/43.643/28.786; darkgrayblue10.709/12.349/13.668→10.852/12.403/13.952: broadpalette hierarchy retained with modestlocalwarmerpaint caveat. Fullraw/fullnative/sourceRGB/A privately reviewed: broad filteredwash retained, no physicalweave/photograin or reshaped broadUV. One-nativepixel/moderate finepaint alone not automatic hold; real sourceweakpigment/trace softness/phase remain rootdecision caveat. BlackUVcorner source0 stays0, noRGB255clips/allwhite, complete sourceA restored byteexact. ExactactualCRLF argument/raw/ref/call/before immutable; no RGBartistpatch/BBox/crop/fitting/registration/localgain/padoptout/retry.'}
corrections={'source_beforeproof_byteunchanged':True,'postcall_corrections':[{'id':6823,'correction':'The BEFORE prose/prompts specifically named SIX graypeaks in x71/72, not every tiny pigment component in the entire gray/brown ROI. Fresh postcall literalmatrix review also identifies original x75,33 gray30/30/30 and original x76,32/35 brown38/22/19, x76,38 brown35/21/13, plus x73,31 and other irregular shades, all already exactly present in immutable BEFORE fullnativeRGBA matrix. Do not claim six physicalparts→eight new eyelets. Held actual irregular partialshades→two regular columns/fourrounddots phase/shape redistribution. BEFORE pattern/source/native/fullmatrix unchanged; this correction is separate and no newcall/artrepair.'}],'third_tool_output_truncated':'7610 builtin exec directoutput truncated by context, tool result persisted in store and save within sameexec completed. First next readonly lookup confirmed raw/call already present; no retry or duplicatecall.','exact_actual_tool_args':'Immediatelysaved UTF8 CRLF/noLF actualprompt and literalabsolute refs. Root later canonicalONEserviceLF representation separate, not corruption.','no_tool_retries':True,'no_artistic_corrections':True}
save(f'postcall-corrections-{ST}.json',corrections)
metrics={r['id']:r for r in read(B/f'metrics-{ST}.json')};details={r['id']:r for r in read(B/f'detail-metrics-{ST}.json')};phases={r['id']:r for r in read(B/f'material-phase-{ST}.json')};records=[];post=[];jobs=[]
for i in CALL:
 cp=B/f'generated/{i}-{ST}-call.json';c=read(cp);assert sha(ROOT/c['generated'])==c['raw_sha256'];assert (ROOT/c['prompt_file']).read_bytes()==c['exact_prompt'].encode('utf-8')and sha(ROOT/c['prompt_file'])==c['prompt_sha256'];assert all(sha(ROOT/p)==h for p,h in c['reference_sha256'].items())
 for k in ['pattern_constraints_ref','native_matrix_ref','common_actual_records','source_before_call_ref']:assert sha(ROOT/c[k]['path'])==c[k]['file_SHA256']
 assert c['literal_actual_tool_arguments']=={'prompt':c['exact_prompt'],'referenced_image_paths':[(ROOT/p).as_posix()for p in c['reference_pngs']],'transparent_background':False}
 o=Image.open(B/f'original/{i}.png').convert('RGBA');n=Image.open(B/f'private-{ST}/native4x/{i}-calibrated-native-alpha-private.png').convert('RGBA');assert n.size==(o.width*4,o.height*4)and n.getchannel('A').tobytes()==o.getchannel('A').resize(n.size,Image.Resampling.LANCZOS).tobytes();assert Image.open(ROOT/c['generated']).convert('RGBA').getchannel('A').getextrema()==(255,255)
 status='worker-ready-candidate-pending-root-art-native-acceptance'if i in READY else'held-original-irregular-tiny-paint-phase-material-review'
 r={'id':i,'status':status,'call_count':1,'reason':notes[i],'generated':c['generated'],'raw_sha256':c['raw_sha256'],'prompt_file':c['prompt_file'],'prompt_argument_sha256':c['prompt_sha256'],'call_metadata':ref(cp),'reference_sha256':c['reference_sha256'],'source_transform_recipe':c['source_transform_recipe'],'metrics':metrics[i],'detail_metrics':details[i],'material_phase':phases[i],'repeat_phase_ref':{**ref(B/f'repeat-phase-{ST}.json'),'id':i},'postcall_material_details_ref':{**ref(B/f'postcall-material-details-{ST}.json'),'id':i},'production_matrix_ref':{**ref(B/f'production-matrices-{ST}.json'),'source_key':str(i)},'fullsource_fullraw_defaultnative4x_RGB_A_privately_inspected':True}
 if i in READY:jobs.append({'id':i,'generated':c['generated'],'prompt':c['exact_prompt'],'reference_png':c['reference_pngs'][0],'reference_recipe':c['source_transform_recipe'],'worker_status':status,'worker_review_note':notes[i]})
 else:
  rd=B/f'rejected/{ST}';rd.mkdir(parents=True,exist_ok=True)
  for suffix,p in [('raw.png',ROOT/c['generated']),('prompt.txt',ROOT/c['prompt_file']),('call.json',cp)]:
   target=rd/f'{i}-attempt1-{suffix}';assert not target.exists();shutil.copyfile(p,target)
  save(f'rejected/{ST}/{i}-attempt1-reason.json',{'id':i,'status':status,'reason':notes[i],'raw_sha256':c['raw_sha256'],'no_repeat':True,'not_permanent_refusal':True});r['rejected_raw']=rel(rd/f'{i}-attempt1-raw.png')
 records.append(r);post.append({'id':i,'imagegen_call_count':1,'postcall_status':status,'sourcebefore_zero_call_snapshot_immutable':True,'fullsource_fullraw_native4x_storedRGB_fullA_privately_reviewed':True})
sourceonly=[]
for r in P:
 if r['id']in CALL:continue
 d={'id':r['id'],'status':'genuine-clothing-art-pending-nativephase-material-review','call_count':0,'reason':r['source_only_reason'],'native_matrix_ref':r['native_matrix_ref'],'common_actual_records':r['common_actual_records'],'actual_static_consumers':r['fresh_actual_static_consumers'],'native_RGB_distinct_count':r['native_RGB_distinct_count'],'dominant_RGB_count_values':r['dominant_RGB_count_values'],'recommended_original_only':False};sourceonly.append(d);records.append(d)
save(f'source-only-detail-{ST}.json',sourceonly);save(f'selected-original-only-{ST}.json',[]);save(f'jobs-{ST}.json',jobs);save(f'postcall-source-status-{ST}.json',post)
S=read(B.parent/'sources.json')['textures'];Q=read(B/'queue.json');ex=read(B/f'exclusions-{ST}.json');assert not set(scope['selected_ids']).intersection(ex['ids'])and all(r['source_rgba_sha256']not in ex['blocked_hashes']for r in P)
guards={'utc':datetime.now(timezone.utc).isoformat(),'before_source_entry_count':ex['source_entry_count'],'before_queue_count':ex['queue_count'],'postcall_source_entry_count':len(S),'postcall_queue_count':len(Q),'source_entry_count_not_finalaccepted_claim':True,'source_current_status_counts':{st:sum(r.get('status')==st for r in S)for st in sorted({str(r.get('status'))for r in S})},'own_postcall_overlap':[{'id':r['id'],'status':r.get('status')}for r in S+Q if r['id']in scope['selected_ids']],'sources_SHA256':sha(B.parent/'sources.json'),'queue_SHA256':sha(B/'queue.json'),'calls':3,'retries':0,'shared_writes':False,'policy':'FreshS/Q/globalraw/jobs/calls/prompts/held/refusals/exactRGBA before each solefirstcall. Previous source-only0call views honestly reaudited, no fake never-viewed claim. Concurrentrootwrites not worker.'};save(f'final-guards-{ST}.json',guards)
recordcount=sum(len(v)for v in actual['tables'].values())
save(f'review-{ST}.json',{'batch':ST,'status':'stable-complete-ready-subset-coordinator-review','selected_ids':scope['selected_ids'],'unique_native_RGBA_count':scope['unique_native_RGBA_count'],'generated_ids':CALL,'ready_ids':READY,'held_ids':HELD,'genuine_pending_uncalled_ids':scope['genuine_pending_uncalled_ids'],'recommended_original_only_ids':[],'call_count':3,'max_authorized_calls':3,'no_retries':True,'records':records,'source_before_call':ref(before),'source_check':ref(source),'pattern_before_call':ref(B/f'pattern-constraints-{ST}.json'),'native_matrix':ref(B/f'native-matrices-{ST}.json'),'actual_records':ref(B/f'actual-records-{ST}.json'),'production_matrix':ref(B/f'production-matrices-{ST}.json'),'natural_RGB_roundtrip':ref(B/f'natural-RGB-roundtrip-{ST}.json'),'repeat_phase':ref(B/f'repeat-phase-{ST}.json'),'postcall_corrections_ref':ref(B/f'postcall-corrections-{ST}.json'),'source_parity':f'Fresh12 original/historical/release exactFULLRGBA/Type/POT/dims;{recordcount} uniqueactualDBrows canonicalSHA once and fullnativeRGBA matrices once. ActualMaterial→TemplateID→Models.MaterialN/ModelTemplates/Geometries exactfresh sourcequeue DBsets. Runtime/meshUV/physicalpart meaning unknown, no invented hardware/Model proofs. Calls3 native128square opaqueRGBtoolrefs/noNNenlargedblocks, fullsourceA255 and sourceblack notempty. Literal weakpaint/nativecounts/phase/palette/naturalRGBroundtrip BEFORE immutable.','QA':'ThreeFIRSTsolebuiltins. Workerready7607/7610 pending rootindependent review with explicit dimpatch/trace width/localpalette/nativephase caveats, not productionacceptance nor scalar-means=acceptance. Filteredsoft mattepaint fields/counts/material broadlayout retained, no clothweave/fibers/metalgrain/newhardware. 6823held irregularsourcegray/brown tinyshade distribution became two regularcolumns/fourroundedgray dots each; no false6physical→8neweyelets claim, separatepostcallprosecorrection references alloriginalexact BEFOREpixels. Nineuncalledgenuinepending tinyuncertainemblems/parts/camo/actualcolorcheckerphase, no blanket family/alpha/technical ban or original-only recommendations. Allfullraw1254square/private512square purewhole4x/fullsourceA inspected, pad0/clear0/OrdinarynoPremul/zero255clips. SourceRGBnative inverse separateA plus naturalLANCZOSroundtrip includes onepixel context, not acceptance threshold. No sourceRGBartrepair/crop/BBox/registration/localgain/optout/retry; exactactualargs/raw/ref immediatelysaved, before unchanged.','ownership':'Own independentClothing44 only. FrozenClothing43/42, Eq43/Heads22 and all prior scopes untouched. Rootsole sharedmetadata/import/native/build/Game/C++/Git/finalacceptance.'})
assert before.read_bytes()==source.read_bytes();mp=B/f'sha256-{ST}.json';files=list(B.glob(f'*{ST}*.json'))+list(B.glob('*clothing_forty_fourth*.py'))+list((B/'generated').glob(f'*{ST}*.png'))+list((B/'generated').glob(f'*{ST}*-call.json'))+list((B/f'private-{ST}').rglob('*'))+list((B/f'rejected/{ST}').rglob('*'))
for i in CALL:files.extend([B/f'generated/{i}-raw.png',B/f'generated/{i}-prompt.txt'])
save(mp.name,{rel(p):sha(p)for p in sorted(set(files))if p.is_file()and p!=mp});assert all(sha(ROOT/p)==h for p,h in read(mp).items())
print(json.dumps({'ready':READY,'held':HELD,'FIRST_calls':3,'genuine_pending0call':len(sourceonly),'actualDB_unique_rows':recordcount,'manifest_entries':len(read(mp)),'manifest_differences':0,'source_before_byteunchanged':True,'sourceentries_queue_current':[len(S),len(Q)],'SHA256':{n:sha(B/f'{n}-{ST}.json')for n in ['jobs','review','source-check','selected','sha256']}},indent=2))
