from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='effects-twenty-fifth';CALL=[2577];READY=[2577];HELD=[]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
before=B/f'source-check-{ST}-before-call.json';proof=read(B/f'source-check-{ST}.json');assert proof==read(before)
scope=read(B/f'scope-{ST}.json');selected=read(B/f'selected-{ST}.json');assert len(selected)==12 and [r['id']for r in selected]==scope['selected_ids'];assert scope['unique_native_RGBA_count']==4
metrics={r['id']:r for r in read(B/f'metrics-{ST}.json')};details={r['id']:r for r in read(B/f'detail-metrics-{ST}.json')};material={r['id']:r for r in read(B/f'material-phase-{ST}.json')};sourceonly={r['id']:r for r in read(B/f'source-only-detail-{ST}.json')['records']}
note='READY CANDIDATE ONLY coordinator fullart/native review, not accepted. Native64 TransparentAdd/A0 useful storedRGB full brown/orange painted field, complete originalalpha independently restored at256x256; no packpremultiply. HistoricalMMP==release==original fullRGBA/Type/dims checked freshly; allactualParticleInstances TextureN/positiveframe slots/resolvedParticles/Wrap/pivots/blend/static/siblingTexture rows stored, missingdefinitions and missingTexture rows explicitlyunknown. Whole originalRGBA/RGB/NN8x512 source inspected BEFOREtool, entire nativeRGBA/zeroRGB map/allweakpixel coordinates/row-columnshade maxima/palette/sourcepaint footprintcount BEFOREprompt immutable. One actual entire RGB-connected bitmap footprint, NOT a physicalflame/lobe count. Fullraw1254/native256 storedRGB/defaultpure scalar.6724853515625/sourceA0 byteexact/defaultpad0/POT reviewed. Original entire irregular painted swath/upper band/brighterupperleft patch/centraldarkgap/lower-right curvedshade and dimboundary remain same native phase/width/sourcepatternscale; existing soft uneven orange-brown painted material retained with finer mild paint transitions. No newfiretongues/particles/rays/glints/physicalrocks/outsidefragments observed, no whitened core/cellgrid/coarsecauliflower material. OriginalzeroRGB native locations productionmax1/1/0, none>5; no new separatelystanding bright flecks. Caveats: slightly more defined/finer original shade; HPstd source.574/.174/.0039 ->1.021/.410/.0748, root may hold material blur differences despite original broadpattern retention. Same nativepeak22,14 source139/62/4 ->138/69/8; maxlocalmean+10.33 at17,16 source103/38/1 ->124/49/0. Source upperarcmean21.65/5.45/.179 ->22.56/5.96/.035; upperleftbandmean34.71/10.57/.490 ->35.91/11.55/.106; centralgapmean14.51/3.98/.210 ->14.43/4.01/.015, lower-rightmean9.44/2.11/.061 ->8.71/1.92/.010. Original veryweak blue mostly loses1level while peakblue rises4->8, slightwarm huehierarchy change recorded, no artistRGBrepair. Dimrightboundary mean7.68/1.45/.011 ->6.90/1.27/0; maxmeanloss-4.33 at22,42. Actual sourceA0 kept entirely, scalar only/defaultpadding, no crop/BBox/fitting/artistpatch/optout/retry. Normalinstanceblend/IsCrown0 and resolvedWrap0/0 recorded onlyifpresent, Particles163/164 referenced byinstances1178/1181 missingunknown, numerous siblingTexture missingrows explicit; replacement changes no DB/runtimebindings. One FIRST solebuiltin, no assertion rootproduction acceptance/nativeGame validation.'
records=[];jobs=[]
for i in CALL:
 cp=B/f'generated/{i}-{ST}-call.json';c=read(cp);assert sha(ROOT/c['generated'])==c['raw_sha256'];assert sha(ROOT/c['prompt_file'])==c['prompt_sha256'];assert (ROOT/c['prompt_file']).read_bytes()==c['exact_prompt'].encode('utf-8');assert all(sha(ROOT/p)==h for p,h in c['reference_sha256'].items());assert sha(B/f'pattern-constraints-{ST}.json')==c['pattern_constraints_file_sha256']
 o=Image.open(B/f'original/{i}.png').convert('RGBA');n=Image.open(B/f'private-{ST}/native4x/{i}-calibrated-native-alpha-private.png').convert('RGBA');assert n.size==(o.width*4,o.height*4)and n.getchannel('A').tobytes()==o.getchannel('A').resize(n.size,Image.Resampling.LANCZOS).tobytes()
 status='ready-for-coordinator-art-native-review';records.append({'id':i,'status':status,'call_count':1,'reason':note,'generated':c['generated'],'raw_sha256':c['raw_sha256'],'prompt_file':c['prompt_file'],'prompt_argument_sha256':c['prompt_sha256'],'call_metadata':rel(cp),'call_metadata_sha256':sha(cp),'reference_sha256':c['reference_sha256'],'source_transform_recipe':c['source_transform_recipe'],'actual_tool_arguments':{'prompt':c['exact_prompt'],'referenced_image_paths':[str((ROOT/p).resolve()).replace('\\','/')for p in c['reference_pngs']],'transparent_background':False},'metrics':metrics[i],'detail_metrics':details[i],'material_phase':material[i]});jobs.append({'id':i,'generated':c['generated'],'prompt':c['exact_prompt'],'source_transform_recipe':c['source_transform_recipe']})
 for r in proof:
  if r['id']==i:r.update(imagegen_call_count=1,postcall_status=status,postcall_review_note=note,full_raw_native4x_alpha_storedRGB_privately_reviewed=True)
for r in proof:
 if r['id']not in CALL:records.append({'id':r['id'],'status':'genuine-color-art-pending-faithful-weakpixel-hierarchy-review','call_count':0,'reason':sourceonly[r['id']]['reason'],'unresolved_Particles_definitions':r['material_evidence']['unresolved_particle_definitions'],'missing_sibling_Textures':r['material_evidence']['missing_sibling_Texture_rows']})
save(f'jobs-{ST}.json',jobs);save(f'source-check-{ST}.json',proof)
S=read(B.parent/'sources.json')['textures'];Q=read(B/'queue.json');ex=read(B/f'exclusions-{ST}.json');assert not set(scope['selected_ids']).intersection(ex['ids']);assert all(r['source_rgba_sha256']not in ex['blocked_hashes']for r in proof)
save(f'final-guards-{ST}.json',{'utc':datetime.now(timezone.utc).isoformat(),'before_source_entry_count':ex['source_entry_count'],'before_queue_entry_count':ex['queue_count'],'postcall_source_entry_count':len(S),'postcall_queue_entry_count':len(Q),'source_entry_count_is_not_accepted_count':True,'queue_status_counts':{z:sum(r.get('status')==z for r in Q)for z in sorted({str(r.get('status'))for r in Q})},'own_postcall_overlap':[{'id':r['id'],'status':r.get('status')}for r in S+Q if r['id']in scope['selected_ids']],'sources_SHA256':sha(B.parent/'sources.json'),'queue_SHA256':sha(B/'queue.json'),'calls':1,'retries':0,'shared_writes':False,'guard_semantics':'Fresh sources/q/allaliases/priorraw/calls/jobs/held/refusal/exactRGBA guards beforetool passed; honest prior0call source-only re-audit permitted, no never-viewed fiction. Twelve sourceIDs/four distinctfullRGBA not twelveunique artbitmaps. Pending sameRGBA siblings are not accepted donor reuse. Root shared changes concurrent, worker none.'})
save(f'review-{ST}.json',{'batch':ST,'status':'stable-complete-ready-subset-coordinator-review','selected_ids':scope['selected_ids'],'unique_native_RGBA_groups':scope['unique_native_RGBA_groups'],'unique_native_RGBA_count':4,'generated_ids':CALL,'ready_ids':READY,'held_ids':HELD,'pending_uncalled_ids':scope['pending_uncalled_ids'],'call_count':1,'max_authorized_calls':3,'not_forced_call_count':True,'records':records,'source_before_call':rel(before),'source_before_call_SHA256':sha(before),'pattern_before_call':rel(B/f'pattern-constraints-{ST}.json'),'pattern_before_call_SHA256':sha(B/f'pattern-constraints-{ST}.json'),'postcall_corrections':'No source/raw/prompt/call/argument corrections made. Extra source-only native matrices/connectedpixel domains written separately AFTERcall; source beforeproof/nativecount/palette/weakpixel proof untouched. Pixel-connected labels never inferred physicalparticles.','source_parity':'Fresh12 actualtyped resources, four distinctRGBA historicalMMP==release==original/fullsourceA/Type/dimensions. AllParticleInstances TextureN/static/blend/pivots/allpositiveframes/siblingTexture presentrows and resolvedParticles/Wrap exactly; missingdefinitions/siblings remain explicitunknown. AllactualMaterial/Final/Container directdiffuse consumers checked; source wholecanvas imageprocessing only, no fabricated grid/UV/renderer factors. A0TransparentAdd usefulRGB, no nativepremultiply or falseempty classification.','QA':'One FIRST builtin after whole original/RGB/NN and entire nativeRGBA/allweakpixels/darkzero map/phase/palette proof BEFOREprompt. Immediate raw/exactCRLFprompt/refSHA/call/recipe/constraintSHA. Fullraw/native4x256/sourceA0 byteexact/standardwhole scalar/defaultpadding/noRGBrepair/crop/BBox/optout/retry privately reviewed. 2577 readycandidate with moderate localstrength/hue/fineblur caveats. Eleven genuinepending sources no forced call, not generic technical/family ban. Ten sparse-frame IDs consist of only two exactRGBA original images; rawcall only one independent2577, no duplicate sameRGBA calls. No rootactualnative/CPU/GPU/Game acceptance claim.','ownership':'Own Effects25 only. Alloldstable Effects24/23/Eq37/Heads16 and shared/import/native/build/Game/Git/C++ untouched; rootsole finalartacceptance/runtime coordinator.'})
mp=B/f'sha256-{ST}.json';files=list(B.glob(f'*{ST}*.json'))+list(B.glob('*effects_twenty_fifth*.py'))+list((B/'generated').glob(f'*{ST}*.png'))+list((B/'generated').glob(f'*{ST}*-call.json'))+list((B/f'private-{ST}').rglob('*.png'))
for i in CALL:files.extend([B/f'generated/{i}-raw.png',B/f'generated/{i}-prompt.txt'])
save(mp.name,{rel(p):sha(p)for p in sorted(set(files))if p.is_file()and p!=mp});assert all(sha(ROOT/p)==h for p,h in read(mp).items())
print(json.dumps({'ready':READY,'held':HELD,'calls':1,'pending0call':11,'selectedIDs':12,'uniqueRGBA':4,'sha256':{n:sha(B/f'{n}-{ST}.json')for n in ['jobs','review','source-check','selected','sha256']}},indent=2))
