from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='heads-twenty-third';CALL=[6774];READY=[];HELD=CALL;UNUSED=[6775,6776]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
def ref(p):return {'path':rel(p),'file_SHA256':sha(p)}
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
before=B/f'source-check-{ST}-before-call.json';source=B/f'source-check-{ST}.json';assert source.read_bytes()==before.read_bytes();P=read(before);selected=read(B/f'selected-{ST}.json');scope=read(B/f'scope-{ST}.json');assert len(P)==len(selected)==12
actual=read(B/f'actual-records-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];canon=lambda r:hashlib.sha256(json.dumps(r,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode('utf-8')).hexdigest()
for table,rows in actual['tables'].items():
 for k,r in rows.items():assert canon(r)==actual['record_SHA256'][table][k]
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');assert np.array(M[str(i)]['native_RGBA_matrix'],dtype=np.uint8).tobytes()==o.tobytes()and sha(B/f'original/{i}.png')==r['original_PNG_file_SHA256'];assert r['source_RGBA_RGB_A_NN_privately_inspected']and r['imagegen_call_count']==0
 for k in ['native_matrix_ref','common_actual_records']:assert sha(ROOT/r[k]['path'])==r[k]['file_SHA256']
 h=ROOT/r['helper_recipe']['output'];assert Image.open(h).size==o.size and Image.open(h).convert('RGB').tobytes()==o.convert('RGB').tobytes()
for i in CALL+UNUSED:
 p=B/f'generated/{i}-prompt.txt';e=B/f'generated/{i}-{ST}-exact-call-argument.txt';assert p.read_bytes()==e.read_bytes()+b'\n'
for i in UNUSED:assert not (B/f'generated/{i}-raw.png').exists()and not (B/f'generated/{i}-{ST}-call.json').exists()
reason='HELD source painted-material/lightphase review, not permanent refusal; FIRST sole builtin6774 only. Exact historical/release/native128square Ordinary straightRGB/sourceA255 with actual staticMaterial→TemplateID→Models/Hair refs; NO dynamicFaceGen binding invented. Entire nativeopaque RGBtoolguide/sourceblur, NN private only. Fullraw1254square→whole512square RGB-FIRST LANCZOS/fulloriginalA255 byteexact/defaultpad0/clear0/scalar1.26904296875/noPremul. THREE original broad directionalpaint fields and TWO original flatangularpaintoutline fields retained, no newanatomy/eyebrows/teeth/physicalhardware or fake physicalstrandcount. But softfiltered original brushshades became many individuallydefined fiber/photo-hair-like thinlines; angularpaint outlines acquired fuzzy granular/fringed relief-like edges and substantiallybrighter warmgray strength. Fullraw andsource/standardnative4x show material/paintscale change even though whole native inverse still resembles originalmacrofields. Held for specific fine-material/lightphase drift, not name/family/A255 or quota. Actualsourcepeak3,32 RGB156/142/140→227/195/185 versus natural158/144/141. Productionglobalpeak16,36 RGB238/207/197 versus original140/125/123 andnatural143/129/127. Maxmeanlift118.667 at2,53 source46/43/41→181/157/148 versus natural52/48/46; maxmeanloss−42.667 at4,57 source57/51/49→12/9/8 versus natural58/52/50: originalleftangularline/lightphase redistributed, not mere scalar neutrality. OriginalRIGHTangularROI max132/125/115→214/186/178, LEFTmax156/142/140→238/207/197, lowercrosssweptpaintmax99/89/90→129/114/112; existingflatoutline shapes became bright prominent edges, no manualsourceRGBrepair. SourceblackUV/lowcorners authoredA255 notempty: corner0,127 source8/5/2→9/5/2 vsnatural8/5/2. HPstd/source~1.130/1.044/1.017→4.505/3.971/3.816 and correlation0.9353931462503997 diagnostic ONLY, not numerical acceptance thresholds/physicalhaircounts. Zero255clips/allwhite, wholeA fidelity doesnotfix RGBmaterial. Originaldirectionalmarks already existed, no false newmacrohairlock count; observed refinement specifically creates fine photo/fiber material and localrim strength. No retries/crop/BBox/fitting/paddingoptout/RGBartistpatch/localgain/brightnessregen; exactactualargument/ref/raw/call/BEFORE unchanged. Planned6775/6776 remain genuinepending0call rather than forcing same-layout material outcome; unused exactprompt artifacts retained and explicitlynot toolcalls.'
corrections={'source_beforeproof_byteunchanged':True,'actual_call_count':1,'before_prospective_call_ids':[6774,6775,6776],'unused_prepared_prompt_ids':UNUSED,'before_scope_planned3_not_actual3':'Immutable BEFORE scope sole_call_ids were prospective candidates, all sourceimagegen_call_count0; only6774 actually called. Finalcalled1/genuinepending11 reported separately without rewriting before.','processing_errors':[{'stage':'first private preview view','description':'Normalizer exec_command returned running session15867; attempted image view before process finished gave invalid/unsupported image. Then explicitly waited session completion and viewed complete saved preview; no imagegen retry or datarepair.'},{'stage':'material_phase diagnostic','description':'Cloned loop still listed prospective6775/76 without raw; two attempts printed6774 then failed missing6775 preview before writing JSON. Corrected own diagnostic to skip trulyuncalled raw and reran once successfully. Source/tool/raw/prompts/before unmodified; this is diagnostic automation correction only.'}],'prompt_representation':'Per root explicit Heads23 instruction, canonicalprompt file is exact actual CRLF argument + ONE additional LF. Separate exact-call-argument UTF8 without serviceLF, literalabsolute args and separateSHAs retained; canonicalLF not toolargument or corruption.','no_artist_RGB_correction':True,'no_tool_retry':True};save(f'postcall-corrections-{ST}.json',corrections)
metrics={r['id']:r for r in read(B/f'metrics-{ST}.json')};details={r['id']:r for r in read(B/f'detail-metrics-{ST}.json')};phases={r['id']:r for r in read(B/f'material-phase-{ST}.json')};records=[];post=[]
for i in CALL:
 cp=B/f'generated/{i}-{ST}-call.json';c=read(cp);assert sha(ROOT/c['generated'])==c['raw_sha256'];assert (ROOT/c['prompt_file']).read_bytes()==(c['exact_prompt']+'\n').encode('utf-8')and sha(ROOT/c['prompt_file'])==c['prompt_sha256'];assert hashlib.sha256(c['exact_prompt'].encode('utf-8')).hexdigest()==c['prompt_argument_sha256'];assert all(sha(ROOT/p)==h for p,h in c['reference_sha256'].items())
 for k in ['pattern_constraints_ref','native_matrix_ref','common_actual_records','source_before_call_ref']:assert sha(ROOT/c[k]['path'])==c[k]['file_SHA256']
 assert c['literal_actual_tool_arguments']=={'prompt':c['exact_prompt'],'referenced_image_paths':[(ROOT/p).as_posix()for p in c['reference_pngs']],'transparent_background':False}
 o=Image.open(B/f'original/{i}.png').convert('RGBA');n=Image.open(B/f'private-{ST}/native4x/{i}-calibrated-native-alpha-private.png').convert('RGBA');assert n.size==(o.width*4,o.height*4)and n.getchannel('A').tobytes()==o.getchannel('A').resize(n.size,Image.Resampling.LANCZOS).tobytes();assert Image.open(ROOT/c['generated']).convert('RGBA').getchannel('A').getextrema()==(255,255)
 status='held-original-filteredpaint-material-and-local-lightphase';rd=B/f'rejected/{ST}';rd.mkdir(parents=True,exist_ok=True)
 for suffix,p in [('raw.png',ROOT/c['generated']),('prompt.txt',ROOT/c['prompt_file']),('exact-call-argument.txt',B/f'generated/{i}-{ST}-exact-call-argument.txt'),('call.json',cp)]:
  target=rd/f'{i}-attempt1-{suffix}';assert not target.exists();shutil.copyfile(p,target)
 save(f'rejected/{ST}/{i}-attempt1-reason.json',{'id':i,'status':status,'reason':reason,'raw_sha256':c['raw_sha256'],'no_repeat':True,'not_permanent_refusal':True})
 records.append({'id':i,'status':status,'call_count':1,'reason':reason,'generated':c['generated'],'raw_sha256':c['raw_sha256'],'prompt_file':c['prompt_file'],'prompt_canonical_SHA256':c['prompt_sha256'],'prompt_actual_argument_SHA256':c['prompt_argument_sha256'],'call_metadata':ref(cp),'reference_sha256':c['reference_sha256'],'source_transform_recipe':c['source_transform_recipe'],'metrics':metrics[i],'detail_metrics':details[i],'material_phase':phases[i],'repeat_phase_ref':{**ref(B/f'repeat-phase-{ST}.json'),'id':i},'production_matrix_ref':{**ref(B/f'production-matrices-{ST}.json'),'source_key':str(i)},'fullsource_fullraw_standardnative4x_RGB_A_privately_inspected':True,'rejected_raw':rel(rd/f'{i}-attempt1-raw.png')});post.append({'id':i,'actual_imagegen_call_count':1,'postcall_status':status,'sourcebefore0call_snapshot_immutable':True})
sourceonly=[]
for r in P:
 if r['id']in CALL:continue
 why=r['source_only_reason']
 if r['id']in UNUSED:why='Genuine staticHair diffuse source, no imagegen call or raw. BEFORE prospective exactcount/phase proof and canonical/exact prompts prepared; first6774 same-layout material failure observed, so optional coloredvariants6775/76 were not forced. Source remains genuinepending0call, not held/toolrefusal/technicalfamilyban. Prepared but UNUSED prompt bytes retained truthfully, firstsource-only re-audit was honest; no claim neverprepared.'
 d={'id':r['id'],'status':'genuine-head-hair-FaceGen-color-pending-uncalled','actual_call_count':0,'reason':why,'native_matrix_ref':r['native_matrix_ref'],'common_actual_records':r['common_actual_records'],'actual_static_consumers':r['fresh_actual_static_consumers'],'actual_dynamic_consumers':r['fresh_actual_dynamic_consumers'],'actual_FaceGen_layer_channels':r['actual_FaceGen_layer_channels'],'native_RGB_distinct_count':r['native_RGB_distinct_count'],'sourceA_extrema':r['material_evidence']['source_alpha_extrema'],'prepared_but_unused_prompt':r['id']in UNUSED,'recommended_original_only':False};sourceonly.append(d);records.append(d)
save(f'source-only-detail-{ST}.json',sourceonly);save(f'selected-original-only-{ST}.json',[]);save(f'jobs-{ST}.json',[]);save(f'postcall-source-status-{ST}.json',post)
S=read(B.parent/'sources.json')['textures'];Q=read(B/'queue.json');ex=read(B/f'exclusions-{ST}.json');assert not set(scope['selected_ids']).intersection(ex['ids'])and all(r['source_rgba_sha256']not in ex['blocked_hashes']for r in P)
save(f'final-guards-{ST}.json',{'utc':datetime.now(timezone.utc).isoformat(),'before_source_entry_count':ex['source_entry_count'],'before_queue_count':ex['queue_count'],'postcall_source_entry_count':len(S),'postcall_queue_count':len(Q),'production_sourceentries_not_published_finalaccepted_claim':True,'own_postcall_overlap':[{'id':r['id'],'status':r.get('status')}for r in S+Q if r['id']in scope['selected_ids']],'sources_SHA256':sha(B.parent/'sources.json'),'queue_SHA256':sha(B/'queue.json'),'calls':1,'retries':0,'shared_writes':False,'policy':'Fresh current before6774 guards2467/q2942 honest; root47 subsequent2471/q2946 productionentries readpostcall. Prior source-only0call honest re-audit permitted; all raw/call/held/accepted/unavailable/sameRGBA guarded.'})
recordcount=sum(len(v)for v in actual['tables'].values());save(f'review-{ST}.json',{'batch':ST,'status':'stable-complete-checked-held-bounded-scope','selected_ids':scope['selected_ids'],'unique_native_RGBA_count':scope['unique_native_RGBA_count'],'generated_ids':CALL,'ready_ids':READY,'held_ids':HELD,'genuine_pending_uncalled_ids':[r['id']for r in sourceonly],'before_prospective_call_ids':[6774,6775,6776],'prepared_unused_prompt_ids':UNUSED,'recommended_original_only_ids':[],'call_count':1,'max_authorized_calls':3,'not_forced_quota':True,'no_retries':True,'records':records,'source_before_call':ref(before),'source_check':ref(source),'pattern_before_call':ref(B/f'pattern-constraints-{ST}.json'),'native_matrix':ref(B/f'native-matrices-{ST}.json'),'actual_records':ref(B/f'actual-records-{ST}.json'),'production_matrix':ref(B/f'production-matrices-{ST}.json'),'natural_RGB_roundtrip':ref(B/f'natural-RGB-roundtrip-{ST}.json'),'repeat_phase':ref(B/f'repeat-phase-{ST}.json'),'consumer_code_ref':ref(B/f'consumer-code-proof-{ST}.json'),'postcall_corrections_ref':ref(B/f'postcall-corrections-{ST}.json'),'source_parity':f'Fresh12 historical/release/nativeoriginal exactFULLRGBA/Type/POT/dims,{recordcount} actualDBunique rows canonicalSHA references and allfullTHMIDsiblings once. Callsnative128square opaqueRGBtoolreference/sourceblur, NNONLYprivatecountproof. StaticMaterials→TemplateID→Models/Hair separate from actual dynamicFaceTextures→THMID→Heads/ALLlayers. Before fullnativeRGB/A/weakpigment/nativephase/commonmatrices untouched.','QA':'ONEFIRSTsole6774 heldspecific filteredbrush→definedphoto/fiber-like material and brightfuzzyoutline/localphase; THREEbroadfields/TWOangularpaintfields retained, no false physicalhaircount/newanatomy assertion. No rootready jobs, no quota: planned6775/76 genuinepending0call after observed same-layout materialdrift, preparedunused exactargs/canonicalLF retained. Nineother genuinepending including sourcebrowstinted/nonconstantRGB/varA arcs/whitecorner NOTtechnicalconstantmask or original-only recommendation. Fullraw1254square/native512square standardwhole scalar/fullA255 byteexact/defaultpad0/clear0/noPremul/zero255clips, storedRGBnative inverse/naturalRGBroundtrip independentA privately inspected. Diagnosticmean/corr/HP/literalpaintmaxima not acceptance thresholds or physicalstrands. No retries/crop/BBox/fitting/sourceRGBpatch/localgain/padoptout; exactargs/raw/ref/call immediatelysaved, prompt canonicalONEextraLF proven and beforeunchanged. Diagnosticerrors separatelydocumented, no artistrepair.','ownership':'Own independentHeads23 only; allfrozenClothing44/43/42, Heads22/21,Eq43/42 and older scopes immutable. Rootonly sharedmetadata/import/native/build/Game/C++/Git/finalacceptance.'})
assert before.read_bytes()==source.read_bytes();mp=B/f'sha256-{ST}.json';files=list(B.glob(f'*{ST}*.json'))+list(B.glob('*heads_twenty_third*.py'))+list((B/'generated').glob(f'*{ST}*.png'))+list((B/'generated').glob(f'*{ST}*-call.json'))+list((B/'generated').glob(f'*{ST}*-exact-call-argument.txt'))+list((B/f'private-{ST}').rglob('*'))+list((B/f'rejected/{ST}').rglob('*'))
files.extend(B/f'generated/{i}-prompt.txt'for i in CALL+UNUSED);files.extend(B/f'generated/{i}-raw.png'for i in CALL)
save(mp.name,{rel(p):sha(p)for p in sorted(set(files))if p.is_file()and p!=mp});assert all(sha(ROOT/p)==h for p,h in read(mp).items())
print(json.dumps({'ready':READY,'held':HELD,'FIRST_calls':1,'unusedprepared0call':UNUSED,'genuine_pending0call':len(sourceonly),'actualDB_unique_rows':recordcount,'manifest_entries':len(read(mp)),'manifest_differences':0,'sourcebefore_byteunchanged':True,'sourceentries_queue_current':[len(S),len(Q)],'SHA256':{n:sha(B/f'{n}-{ST}.json')for n in ['jobs','review','source-check','selected','sha256']}},indent=2))
