from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='clothing-fifty-second';CALL=[5683]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
def ref(p):return {'path':rel(p),'file_SHA256':sha(p)}
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
before=B/f'source-check-{ST}-before-call.json';source=B/f'source-check-{ST}.json';assert before.read_bytes()==source.read_bytes()
P=read(before);scope=read(B/f'scope-{ST}.json');selected=read(B/f'selected-{ST}.json');assert len(P)==len(selected)==12
M=read(B/f'native-matrices-{ST}.json')['sources'];actual=read(B/f'actual-records-{ST}.json')
canon=lambda v:hashlib.sha256(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode('utf-8')).hexdigest()
for table,rows in actual['tables'].items():
 for k,row in rows.items():assert canon(row)==actual['record_SHA256'][table][k]
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');assert np.array(M[str(i)]['native_RGBA_matrix'],dtype=np.uint8).tobytes()==o.tobytes()
 assert r['source_RGBA_RGB_A_NN_privately_inspected'] and r['imagegen_call_count']==0 and sha(B/f'original/{i}.png')==r['original_PNG_file_SHA256']
 for k in ['native_matrix_ref','common_actual_records']:assert sha(ROOT/r[k]['path'])==r[k]['file_SHA256']
 h=Image.open(ROOT/r['helper_recipe']['output']);assert h.size==o.size and h.convert('RGB').tobytes()==o.convert('RGB').tobytes()
metrics={r['id']:r for r in read(B/f'metrics-{ST}.json')};details={r['id']:r for r in read(B/f'detail-metrics-{ST}.json')};phases={r['id']:r for r in read(B/f'material-phase-{ST}.json')}
records=[];post=[]
for i in CALL:
 cp=B/f'generated/{i}-{ST}-call.json';c=read(cp);d=details[i];m=metrics[i];f=phases[i]
 assert sha(ROOT/c['generated'])==c['raw_sha256'] and (ROOT/c['prompt_file']).read_bytes()==(c['exact_prompt']+'\n').encode('utf-8')
 assert sha(ROOT/c['prompt_file'])==c['prompt_sha256'] and (B/f'generated/{i}-{ST}-exact-call-argument.txt').read_bytes()==c['exact_prompt'].encode('utf-8')
 for k in ['pattern_constraints_ref','native_matrix_ref','common_actual_records','source_before_call_ref']:assert sha(ROOT/c[k]['path'])==c[k]['file_SHA256']
 assert all(sha(ROOT/p)==s for p,s in c['reference_sha256'].items())
 assert c['literal_actual_tool_arguments']=={'prompt':c['exact_prompt'],'referenced_image_paths':[(ROOT/p).as_posix()for p in c['reference_pngs']],'transparent_background':False}
 o=Image.open(B/f'original/{i}.png').convert('RGBA');n=Image.open(B/f'private-{ST}/native4x/{i}-calibrated-native-alpha-private.png').convert('RGBA')
 assert n.size==(o.width*4,o.height*4) and n.getchannel('A').tobytes()==o.getchannel('A').resize(n.size,Image.Resampling.LANCZOS).tobytes()
 assert Image.open(ROOT/c['generated']).convert('RGBA').getchannel('A').getextrema()==(255,255)
 numeric={'scalar_gain':m['native_preview_luma_gain'],'root_padding_texels':m['root_padding_texels'],'root_hidden_clear_texels':m['root_hidden_clear_texels'],'source_peak_xy':d['source_peak_xy'],'source_peak_RGB':d['source_peak_RGB'],'production_at_source_peak_RGB':d['production_at_source_peak_RGB'],'max_local_mean_lift':d['max_local_mean_lift'],'max_local_mean_lift_xy':d['max_local_mean_lift_xy'],'source_at_max_lift_RGB':d['source_at_max_lift_RGB'],'production_at_max_lift_RGB':d['production_at_max_lift_RGB'],'max_local_mean_loss':d['max_local_mean_loss'],'max_local_mean_loss_xy':d['max_local_mean_loss_xy'],'source_at_max_loss_RGB':d['source_at_max_loss_RGB'],'production_at_max_loss_RGB':d['production_at_max_loss_RGB'],'source_highpass_std_RGB':f['highpass_radius1_source_std_RGB'],'production_highpass_std_RGB':f['highpass_radius1_production_std_RGB'],'prepack_RGB255_pixels':f['prepack_corrected_RGB255_pixels_inside_positive_sourceA'],'inverse_RGB_correlation':d['inverse_RGB_correlation']}
 reason='Worker HELD pending independent root material/blur/weakpaintphase review, not permanent refusal. ONE genuinely FIRST5683, previous source-only views honestly reaudited. Entire native256 Ordinary straightRGB/A255 opaque Clamp Material3741→Template2379→Model6092.Material0, ModelTemplate3929/Geometry2770, fresh original/history/release fullRGBA/POT source-first proved. Full native opaque originalRGB toolref viewed; NN only private. Complete raw1254square→whole1024 RGB-FIRST LANCZOS/defaultpureglobal scalar/fulloriginalA restored, noPremul/defaultpadding/zero255clips. ONE rustyred polygon/TWO original adjacent graypaintpatches/ONE lower innersemicircular paintpatch/THREE thin lowerstrippaint shapes/TWO lower-middle horizontal bands retained, with existing weakgray/brown marks and blackpaint. Counts are literal sourcepaintregions, not guessed physicalmechanisms/hardware/particle counts. Specific HOLD: originally filtered gray/red paint has become more visibly granular/mottled at sourcepaint interiors, old narrowstrip outlines and graymetal-like border fields read more sharply edged/relief-like, reducing original soft mattepaint/sourceblur. Old broad folds and tiny source marks remain; not claiming invented bolts/buckles/components or symboliccontent. Fullraw/privateproduction4x/source4x/nativeinverse viewed; natural sourceRGB4x→native roundtrip checked independentlyA. Localstrength changes documented separately in exact numeric overview/probes, not a gain threshold or acceptance test. Moderate contrast/onepixel smoothing alone not automatic hold. No RGBartisticrepair/crop/registration/fitting/rotation/localgain/paddingoptout/retry. Eleven other genuinely painted sources pending0call with individually unresolved weakmarks/countphase, no blanket name/type/familyban. No original-only recommendation here. Root sole finalart/native acceptance/sharedmetadata/Game/Git.'
 rd=B/f'rejected/{ST}';rd.mkdir(parents=True,exist_ok=True)
 for suffix,p in [('raw.png',ROOT/c['generated']),('prompt.txt',ROOT/c['prompt_file']),('call.json',cp)]:
  target=rd/f'{i}-attempt1-{suffix}';assert not target.exists();shutil.copyfile(p,target)
 status='held-source-soft-matte-paint-material-blur-localshade-rootreview'
 save(f'rejected/{ST}/{i}-attempt1-reason.json',{'id':i,'status':status,'reason':reason,'numeric_overview':numeric,'raw_sha256':c['raw_sha256'],'no_repeat':True,'not_permanent_refusal':True})
 records.append({'id':i,'status':status,'call_count':1,'reason':reason,'numeric_overview':numeric,'generated':c['generated'],'raw_sha256':c['raw_sha256'],'rejected_raw':rel(rd/f'{i}-attempt1-raw.png'),'prompt_file':c['prompt_file'],'prompt_argument_sha256':c['prompt_argument_sha256'],'prompt_canonical_sha256':c['prompt_sha256'],'call_metadata':ref(cp),'reference_sha256':c['reference_sha256'],'source_transform_recipe':c['source_transform_recipe'],'metrics':m,'detail_metrics':d,'material_phase':f,'repeat_phase_ref':ref(B/f'repeat-phase-{ST}.json'),'source_specific_probes_ref':ref(B/f'postcall-source-specific-probes-{ST}.json'),'production_matrix_ref':ref(B/f'production-matrices-{ST}.json'),'fullsource_fullraw_native4x_RGB_A_privately_inspected':True})
 post.append({'id':i,'imagegen_call_count':1,'postcall_status':status,'sourcebefore_ZEROcall_snapshot_unchanged':True})
sourceonly=[{'id':r['id'],'status':'genuine-clothing-accessory-color-pending-literal-weakphase-material-review','call_count':0,'reason':r['source_only_reason'],'native_matrix_ref':r['native_matrix_ref'],'common_actual_records':r['common_actual_records'],'actual_static_consumers':r['fresh_actual_static_consumers'],'recommended_original_only':False}for r in P if r['id']not in CALL];records+=sourceonly
save(f'jobs-{ST}.json',[]);save(f'source-only-detail-{ST}.json',sourceonly);save(f'postcall-source-status-{ST}.json',post)
save(f'postcall-corrections-{ST}.json',{'source_before_byteunchanged':True,'source_before_errors_detected':[],'processing_errors':[],'artistic_corrections':[],'tool_retries':0,'qualification':'Exact native source matrix/count/phase/complete toolref immutable BEFORE; numerical material/phase diagnostics retain literal source points, not invented hardware. Actualarg+ONEadditionalLF canonical, separately actualarg noLF. Raw untouched.'})
S=read(B.parent/'sources.json')['textures'];Q=read(B/'queue.json');ex=read(B/f'exclusions-{ST}.json');assert not set(scope['selected_ids']).intersection(ex['ids']) and all(r['source_rgba_sha256']not in ex['blocked_hashes']for r in P)
save(f'final-guards-{ST}.json',{'utc':datetime.now(timezone.utc).isoformat(),'before_source_entry_count':ex['source_entry_count'],'before_queue_count':ex['queue_count'],'postcall_source_entry_count':len(S),'postcall_queue_count':len(Q),'source_entry_count_not_finalpublished_claim':True,'current_status_counts':{v:sum(r.get('status')==v for r in S)for v in sorted({str(r.get('status'))for r in S})},'own_postcall_overlap':[{'id':r['id'],'status':r.get('status')}for r in S+Q if r['id']in scope['selected_ids']],'sources_SHA256':sha(B.parent/'sources.json'),'queue_SHA256':sha(B/'queue.json'),'shared_writes':False,'calls':1,'retries':0,'qualification':'Fresh actual root imports reflected by source-entrycount2485/q2963; published validated2480 commit3ce4b51f separatelyqualified. Concurrentrootupdates not worker writes. Previoussourceonly ZEROcall views honestly reaudited.'})
save(f'review-{ST}.json',{'batch':ST,'status':'stable-complete-bounded-held-review','selected_ids':scope['selected_ids'],'unique_native_RGBA_count':scope['unique_native_RGBA_count'],'generated_ids':CALL,'ready_ids':[],'held_ids':CALL,'genuine_pending_uncalled_ids':scope['genuine_pending_uncalled_ids'],'recommended_original_only_ids':[],'call_count':1,'max_authorized_calls':3,'no_quota_no_retries':True,'records':records,'source_before_call':ref(before),'source_check':ref(source),'pattern_before_call':ref(B/f'pattern-constraints-{ST}.json'),'native_matrix':ref(B/f'native-matrices-{ST}.json'),'actual_records':ref(B/f'actual-records-{ST}.json'),'consumer_code_proof':ref(B/f'consumer-code-proof-{ST}.json'),'natural_RGB_roundtrip':ref(B/f'natural-RGB-roundtrip-{ST}.json'),'postcall_corrections_ref':ref(B/f'postcall-corrections-{ST}.json'),'source_parity':'12within-scope distinct fullRGBA payloads/history-release exactnative parity/POT/type/dims/A and80 unique actualDBrows. ALL12 honest previous clothing source-only0call re-audits; no newoutsideCl1–51 among80eligible. Actual Materials→TemplateID→Models sourcecolor roles, runtime/meshUV/physicalsemantic interpretation unknown, not unused.','ownership':'Own Clothing52 only, all Heads26/25/24/Cl51/olderfrozen unchanged. Root sole shared/import/build/native/Game/Git/finalacceptance.'})
assert before.read_bytes()==source.read_bytes()
mp=B/f'sha256-{ST}.json';files=list(B.glob(f'*{ST}*.json'))+list(B.glob('*clothing_fifty_second*.py'))+list((B/'generated').glob(f'*{ST}*.png'))+list((B/'generated').glob(f'*{ST}*-call.json'))+list((B/'generated').glob(f'*{ST}*-exact-call-argument.txt'))+list((B/f'private-{ST}').rglob('*'))+list((B/f'rejected/{ST}').rglob('*'))
for i in CALL:files.extend([B/f'generated/{i}-raw.png',B/f'generated/{i}-prompt.txt'])
save(mp.name,{rel(p):sha(p)for p in sorted(set(files))if p.is_file()and p!=mp});assert all(sha(ROOT/p)==h for p,h in read(mp).items())
old={}
for st in ['heads-twenty-sixth','heads-twenty-fifth','heads-twenty-fourth','clothing-fifty-first']:
 d=read(B/f'sha256-{st}.json');bad=[p for p,h in d.items()if sha(ROOT/p)!=h];assert not bad,(st,bad);old[st]=0
print(json.dumps({'ready':[],'held':CALL,'FIRSTcalls':1,'pending0call':len(sourceonly),'actualDBrows':sum(len(v)for v in actual['tables'].values()),'manifestentries':len(read(mp)),'manifestdifferences':0,'older_frozen_differences':old,'current_sourceentries_queue':[len(S),len(Q)],'SHA256':{n:sha(B/f'{n}-{ST}.json')for n in ['jobs','review','source-check','selected','sha256']}},indent=2))
