from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='clothing-fifty-third';CALL=[7615]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
def ref(p):return {'path':rel(p),'file_SHA256':sha(p)}
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
before=B/f'source-check-{ST}-before-call.json';source=B/f'source-check-{ST}.json';assert before.read_bytes()==source.read_bytes()
P=read(before);scope=read(B/f'scope-{ST}.json');selected=read(B/f'selected-{ST}.json');assert len(P)==len(selected)==12
M=read(B/f'native-matrices-{ST}.json')['sources'];actual=read(B/f'actual-records-{ST}.json')
canon=lambda v:hashlib.sha256(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode('utf-8')).hexdigest()
for table,rows in actual['tables'].items():
 for k,row in rows.items():assert canon(row)==actual['record_SHA256'][table][k]
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');assert np.array(M[str(i)]['native_RGBA_matrix'],dtype=np.uint8).tobytes()==o.tobytes()
 assert r['source_RGBA_RGB_A_NN_privately_inspected'] and r['imagegen_call_count']==0 and sha(B/f'original/{i}.png')==r['original_PNG_file_SHA256']
 for k in ['native_matrix_ref','common_actual_records']:assert sha(ROOT/r[k]['path'])==r[k]['file_SHA256']
 h=Image.open(ROOT/r['helper_recipe']['output']);assert h.size==o.size and h.convert('RGB').tobytes()==o.convert('RGB').tobytes()
metrics={r['id']:r for r in read(B/f'metrics-{ST}.json')};details={r['id']:r for r in read(B/f'detail-metrics-{ST}.json')};phases={r['id']:r for r in read(B/f'material-phase-{ST}.json')}
records=[];post=[]
for i in CALL:
 cp=B/f'generated/{i}-{ST}-call.json';c=read(cp);d=details[i];m=metrics[i];f=phases[i]
 assert sha(ROOT/c['generated'])==c['raw_sha256'] and (ROOT/c['prompt_file']).read_bytes()==(c['exact_prompt']+'\n').encode('utf-8')
 assert sha(ROOT/c['prompt_file'])==c['prompt_sha256'] and (B/f'generated/{i}-{ST}-exact-call-argument.txt').read_bytes()==c['exact_prompt'].encode('utf-8')
 for k in ['pattern_constraints_ref','native_matrix_ref','common_actual_records','source_before_call_ref']:assert sha(ROOT/c[k]['path'])==c[k]['file_SHA256']
 assert all(sha(ROOT/p)==s for p,s in c['reference_sha256'].items())
 assert c['literal_actual_tool_arguments']=={'prompt':c['exact_prompt'],'referenced_image_paths':[(ROOT/p).as_posix()for p in c['reference_pngs']],'transparent_background':False}
 o=Image.open(B/f'original/{i}.png').convert('RGBA');n=Image.open(B/f'private-{ST}/native4x/{i}-calibrated-native-alpha-private.png').convert('RGBA')
 assert n.size==(o.width*4,o.height*4) and n.getchannel('A').tobytes()==o.getchannel('A').resize(n.size,Image.Resampling.LANCZOS).tobytes()
 assert Image.open(ROOT/c['generated']).convert('RGBA').getchannel('A').getextrema()==(255,255)
 checker=read(B/f'postcall-checker-phase-{ST}.json')['checks']
 numeric={'scalar_gain':m['native_preview_luma_gain'],'root_padding_texels':m['root_padding_texels'],'root_hidden_clear_texels':m['root_hidden_clear_texels'],'source_peak_xy':d['source_peak_xy'],'source_peak_RGB':d['source_peak_RGB'],'production_at_source_peak_RGB':d['production_at_source_peak_RGB'],'max_local_mean_lift':d['max_local_mean_lift'],'max_local_mean_lift_xy':d['max_local_mean_lift_xy'],'source_at_max_lift_RGB':d['source_at_max_lift_RGB'],'production_at_max_lift_RGB':d['production_at_max_lift_RGB'],'max_local_mean_loss':d['max_local_mean_loss'],'max_local_mean_loss_xy':d['max_local_mean_loss_xy'],'source_at_max_loss_RGB':d['source_at_max_loss_RGB'],'production_at_max_loss_RGB':d['production_at_max_loss_RGB'],'source_highpass_std_RGB':f['highpass_radius1_source_std_RGB'],'production_highpass_std_RGB':f['highpass_radius1_production_std_RGB'],'prepack_RGB255_pixels':f['prepack_corrected_RGB255_pixels_inside_positive_sourceA'],'inverse_RGB_correlation':d['inverse_RGB_correlation'],'checker_phase_negative_rows':{n:[r['y']for r in v['every_row_native_y_signed_original_even_minus_odd_meanRGB']if r['difference']<0]for n,v in checker.items()},'checker_phase_negative_columns':{n:[r['x']for r in v['every_column_native_x_signed_original_even_minus_odd_meanRGB']if r['difference']<0]for n,v in checker.items()}}
 reason='Worker HELD pending independent root sourcepaint/material/checkerphase review, not permanent refusal. ONE genuinely FIRST7615; all12 previous source-only ZEROcall views honestly reaudited. Entire native128 Ordinary straightRGB/sourceA255/opaque Clamp Material5784→Template3091→Model7725.Material2, ModelTemplate4649/Geometry4255; fresh original/history/release fullRGBA/POT/actualconsumer and source nativeblur/literalweakpaint/countphase proved BEFORE. Full original nativeopaqueRGB toolreference privately viewed, NN private only. Raw1254square→whole512 RGB-FIRST LANCZOS/defaultpureglobal scalar/fulloriginalA byteexact/noPremul/defaultpad0/clear0/zero255clips. Broad ONE redstripefield/ONE darkshoe-like paintedfield/ONE existingcheckerrectangle/TWO oldbrownmarks/ONE tinyoldopen triangularoutline/ONElowergrayfield/ONErightgrayfield/ONE oldsmallblack-gray mark retained, blackRGB/A255 authoredpaint retained. HOLD specific sourcepaintmaterial: nativefiltered darkgray/shoe-like paint has become visibly diagonal crosshatched/grainy/leather-weave-like, with more defined shiny-looking old grayline contours and stronger redstripe depiction. Lowergray intentional softwash now reads as fine physical diagonal textilegrain; not new anatomical/hardware parts or blanket cloth/family ban. Existing checker source interior48columns×20rows,480warm+480gray at nativepitch1 with even(x+y)warm/oddgray sourceRGB24/28/33 asserted beforetool. Sourceproof refers to nativeCOLOR pixels, not physical mesh holes/particles. Production retains ONE checkerfield but alters its literal nativepattern phase: signed meanRGB contrast of original even-minus-odd locations is negative in nine native rows and eight columns; source and natural sourceRGB4x→native have none negative. Whole checker source and production matrices/probes documented. R-B>20 classmismatches are NOT independently a hold or newcellcount: even natural roundtrip shifts many classlabels because of filtered color mixing; actual phase contrast and qualitative fullviews checked separately. Local sourceweakstrength numeric overview derived from exact diagnostics, not arbitrary thresholds; moderatecontrast/1nativepixel alone not automatichold. Oldtinyoutline remains ONE region, oldlowergraymark ONE, no invented symbol/hardware count claimed. Fullsource/fullraw/private512/nativeinverse and originalRGBnaturalroundtrip independentlyA reviewed. No RGBartisticrepair/crop/BBox/registration/fitting/rotation/localgain/paddingoptout/retry. Eleven other genuinepainted diffuse sources pending0call with specific unresolved weakmarks/complexatlas/materialphase; no name/type/familyban, no original-only recommendation. PRE-AUDIT guard initial lexical called-versus-uncalled parsing error disclosed and corrected before source selection/proof/prompts/calls; corrected currentglobal allraw/call/jobs/reviews/exactRGBA guards passed before FIRST. Root sole finalart/native acceptance/shared/Game/Git.'
 rd=B/f'rejected/{ST}';rd.mkdir(parents=True,exist_ok=True)
 for suffix,p in [('raw.png',ROOT/c['generated']),('prompt.txt',ROOT/c['prompt_file']),('call.json',cp)]:
  target=rd/f'{i}-attempt1-{suffix}';assert not target.exists();shutil.copyfile(p,target)
 status='held-sourcefiltered-paint-material-checkerphase-rootreview'
 save(f'rejected/{ST}/{i}-attempt1-reason.json',{'id':i,'status':status,'reason':reason,'numeric_overview':numeric,'raw_sha256':c['raw_sha256'],'no_repeat':True,'not_permanent_refusal':True})
 records.append({'id':i,'status':status,'call_count':1,'reason':reason,'numeric_overview':numeric,'generated':c['generated'],'raw_sha256':c['raw_sha256'],'rejected_raw':rel(rd/f'{i}-attempt1-raw.png'),'prompt_file':c['prompt_file'],'prompt_argument_sha256':c['prompt_argument_sha256'],'prompt_canonical_sha256':c['prompt_sha256'],'call_metadata':ref(cp),'reference_sha256':c['reference_sha256'],'source_transform_recipe':c['source_transform_recipe'],'metrics':m,'detail_metrics':d,'material_phase':f,'repeat_phase_ref':ref(B/f'repeat-phase-{ST}.json'),'source_specific_probes_ref':ref(B/f'postcall-source-specific-probes-{ST}.json'),'production_matrix_ref':ref(B/f'production-matrices-{ST}.json'),'checker_phase_ref':ref(B/f'postcall-checker-phase-{ST}.json'),'fullsource_fullraw_native4x_RGB_A_privately_inspected':True})
 post.append({'id':i,'imagegen_call_count':1,'postcall_status':status,'sourcebefore_ZEROcall_snapshot_unchanged':True})
sourceonly=[{'id':r['id'],'status':'genuine-clothing-accessory-color-pending-literal-weakphase-material-review','call_count':0,'reason':r['source_only_reason'],'native_matrix_ref':r['native_matrix_ref'],'common_actual_records':r['common_actual_records'],'actual_static_consumers':r['fresh_actual_static_consumers'],'recommended_original_only':False}for r in P if r['id']not in CALL];records+=sourceonly
save(f'jobs-{ST}.json',[]);save(f'source-only-detail-{ST}.json',sourceonly);save(f'postcall-source-status-{ST}.json',post)
save(f'postcall-corrections-{ST}.json',{'source_before_byteunchanged':True,'source_before_errors_detected':[],'preaudit_guard_correction_ref':ref(B/f'preaudit-guard-correction-{ST}.json'),'processing_errors':[],'artistic_corrections':[],'tool_retries':0,'qualification':'Exact native source matrix/count/phase/complete toolref immutable BEFORE; numerical material/phase diagnostics retain literal source points, not invented hardware. Actualarg+ONEadditionalLF canonical, separately actualarg noLF. Raw untouched.'})
S=read(B.parent/'sources.json')['textures'];Q=read(B/'queue.json');ex=read(B/f'exclusions-{ST}.json');assert not set(scope['selected_ids']).intersection(ex['ids']) and all(r['source_rgba_sha256']not in ex['blocked_hashes']for r in P)
save(f'final-guards-{ST}.json',{'utc':datetime.now(timezone.utc).isoformat(),'before_source_entry_count':ex['source_entry_count'],'before_queue_count':ex['queue_count'],'postcall_source_entry_count':len(S),'postcall_queue_count':len(Q),'source_entry_count_not_finalpublished_claim':True,'parent_reported_publication_before_actual_call':{'sourceentries':2485,'queue':2963,'commit':'64e855d2eace720b5d047b8303cbffee1f82434e'},'audit_prior_publication':{'sourceentries':2480,'commit':'3ce4b51f719719e106e333de4c1a4059c9bf594f'},'current_status_counts':{v:sum(r.get('status')==v for r in S)for v in sorted({str(r.get('status'))for r in S})},'own_postcall_overlap':[{'id':r['id'],'status':r.get('status')}for r in S+Q if r['id']in scope['selected_ids']],'sources_SHA256':sha(B.parent/'sources.json'),'queue_SHA256':sha(B/'queue.json'),'shared_writes':False,'calls':1,'retries':0,'qualification':'Fresh actual root source-entrycount2485/q2963; sourceaudit started while published2480 commit3ce4b51f, parent reported publication50 validated2485 commit64e855d2 before actualcall. Older BEFORE unchanged. Concurrentrootupdates not worker writes. Previoussourceonly ZEROcall views honestly reaudited.'})
save(f'review-{ST}.json',{'batch':ST,'status':'stable-complete-bounded-held-review','selected_ids':scope['selected_ids'],'unique_native_RGBA_count':scope['unique_native_RGBA_count'],'generated_ids':CALL,'ready_ids':[],'held_ids':CALL,'genuine_pending_uncalled_ids':scope['genuine_pending_uncalled_ids'],'recommended_original_only_ids':[],'call_count':1,'max_authorized_calls':3,'no_quota_no_retries':True,'records':records,'source_before_call':ref(before),'source_check':ref(source),'pattern_before_call':ref(B/f'pattern-constraints-{ST}.json'),'native_matrix':ref(B/f'native-matrices-{ST}.json'),'actual_records':ref(B/f'actual-records-{ST}.json'),'consumer_code_proof':ref(B/f'consumer-code-proof-{ST}.json'),'natural_RGB_roundtrip':ref(B/f'natural-RGB-roundtrip-{ST}.json'),'postcall_corrections_ref':ref(B/f'postcall-corrections-{ST}.json'),'source_parity':'12within-scope distinct fullRGBA payloads/history-release exactnative parity/POT/type/dims/A and67 unique actualDBrows. ALL12 honest previous source-only0call re-audits. Corrected currentglobalguard79eligible. PRE-AUDIT guard parsing error explicitly preserved/corrected before source selection/nativeproof/calls. Actual Materials→TemplateID→Models sourcecolor roles, runtime/meshUV/physicalsemantic interpretation unknown, not unused.','ownership':'Own Clothing53 only; Cl52/Heads26/25/24/Cl51/olderfrozen unchanged. Root sole shared/import/build/native/Game/Git/finalacceptance.'})
assert before.read_bytes()==source.read_bytes()
mp=B/f'sha256-{ST}.json';files=list(B.glob(f'*{ST}*.json'))+list(B.glob('*clothing_fifty_third*.py'))+list((B/'generated').glob(f'*{ST}*.png'))+list((B/'generated').glob(f'*{ST}*-call.json'))+list((B/'generated').glob(f'*{ST}*-exact-call-argument.txt'))+list((B/f'private-{ST}').rglob('*'))+list((B/f'rejected/{ST}').rglob('*'))
for i in CALL:files.extend([B/f'generated/{i}-raw.png',B/f'generated/{i}-prompt.txt'])
save(mp.name,{rel(p):sha(p)for p in sorted(set(files))if p.is_file()and p!=mp});assert all(sha(ROOT/p)==h for p,h in read(mp).items())
old={}
for st in ['clothing-fifty-second','heads-twenty-sixth','heads-twenty-fifth','heads-twenty-fourth','clothing-fifty-first']:
 d=read(B/f'sha256-{st}.json');bad=[p for p,h in d.items()if sha(ROOT/p)!=h];assert not bad,(st,bad);old[st]=0
print(json.dumps({'ready':[],'held':CALL,'FIRSTcalls':1,'pending0call':len(sourceonly),'actualDBrows':sum(len(v)for v in actual['tables'].values()),'manifestentries':len(read(mp)),'manifestdifferences':0,'older_frozen_differences':old,'current_sourceentries_queue':[len(S),len(Q)],'SHA256':{n:sha(B/f'{n}-{ST}.json')for n in ['jobs','review','source-check','selected','sha256']}},indent=2))
