from pathlib import Path
import json,hashlib
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='heads-fifteenth';C=json.loads((B/f'pattern-constraints-{ST}.json').read_text(encoding='utf-8'));out=[]
for c in C:
 i=c['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');n=Image.open(B/f'private-{ST}/native4x/{i}-stored-rgb-private.png').convert('RGB');a=np.asarray(o,dtype=float);g=np.asarray(n.resize(o.size,Image.Resampling.LANCZOS),dtype=float);regions={}
 for name,r in c['region_diagnostics'].items():
  b=r['native_bbox'];x0,y0,x1,y1=b;s=a[y0:y1,x0:x1,:3];v=g[y0:y1,x0:x1];sy,sx=np.unravel_index(s.mean(2).argmax(),s.shape[:2]);gy,gx=np.unravel_index(v.mean(2).argmax(),v.shape[:2]);regions[name]={'native_bbox':b,'source_mean_RGB':s.mean((0,1)).tolist(),'inverse_mean_RGB':v.mean((0,1)).tolist(),'source_std_RGB':s.std((0,1)).tolist(),'inverse_std_RGB':v.std((0,1)).tolist(),'source_peak_xy':[int(x0+sx),int(y0+sy)],'source_peak_RGB':s[sy,sx].tolist(),'inverse_peak_xy':[int(x0+gx),int(y0+gy)],'inverse_peak_RGB':v[gy,gx].tolist()}
 weights={}
 for w in [.25,.5,1.]:
  aa=a[:,:,3:4]/255*w;s=np.flipud(np.clip(np.floor(a[:,:,:3]*aa+128*(1-aa)+.5),0,255));v=np.flipud(np.clip(np.floor(g*aa+128*(1-aa)+.5),0,255));d=abs(s-v);weights[str(w)]={'mean_absolute_channel_difference':float(d.mean()),'maximum_channel_difference':float(d.max())}
 size=n.size;src=np.asarray(o.convert('RGB').resize(size,Image.Resampling.LANCZOS),dtype=float).mean(2);gen=np.asarray(n,dtype=float).mean(2)
 def hp(v):return v[1:-1,1:-1]-(v[1:-1,:-2]+v[1:-1,2:]+v[:-2,1:-1]+v[2:,1:-1])/4
 hs=hp(src);hg=hp(gen);out.append({'id':i,'mode':'POSTCALL readonly local tone/phase diagnostics of whole pure scalar/sourceA restored native4x. No manipulations of artistic RGB; boxes numeric domains only, no cropping/registration/compositing to production. No universal correlation or gain cutoff.','native4x_highpass_std_source':float(hs.std()),'native4x_highpass_std_candidate':float(hg.std()),'regions':regions,'sourceA_positive_native_pixels':int((a[:,:,3]>0).sum()),'sourceA_max':int(a[:,:,3].max()),'approximate_face_layer_sourceover_diagnostic':weights,'diagnostic_limits':'Source-over only numerical diagnostic: straightRGB, original nativeA, gray128 fill, Vflip and weights0.25/0.5/1 per actual header. Candidate inverse128 is LANCZOS approximation, NOT actual selected native mip/probe/real FaceGen weights or game validation.'})
(B/f'local-metrics-{ST}.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
runtime={'mode':'Readonly actual CFaceTexture THMID source-chain and current CPU implementation audit; no source/code/CPU/Game/build change','dynamic_import_file':'DBFormat/DataFaceGen.cpp','dynamic_import_SHA256':hashlib.sha256((ROOT/'DBFormat/DataFaceGen.cpp').read_bytes()).hexdigest(),'binding':'CFaceTexture::Import actualTHMID owner PushItem(&pOwner->face,(CHeadTexture*)this), NOT CEyeTexture owner.eye or static material','actual_runtime_file':'Main/LSHead.cpp','actual_runtime_SHA256':hashlib.sha256((ROOT/'Main/LSHead.cpp').read_bytes()).hexdigest(),'BuildTexLayers_face_lines':[1118,1251],'actual_FACE_destination':[0,128,128,256],'source':'ENTIRE logical128square source bitmap, no internal atlas grid inferred','fill':{'ARGB_hex':'FF808080','RGB':[128,128,128],'A':255},'actual_sampler_file':'Main/FaceGenTextureSampling.h','actual_sampler_SHA256':hashlib.sha256((ROOT/'Main/FaceGenTextureSampling.h').read_bytes()).hexdigest(),'operation':'LogicalSourceMip chooses logical dims; BlendLayer clips original whole128 to fixedFACE128 subrect, Vflips and blends straight sourceRGB by originalA*actualweight/255, forces destinationA255. Original DB/layers/sourceA/weights/UV unchanged.','unknowns':'Actual FaceGen weights/runtime dispatch/native selected mip/probe not tested by worker. Root sole native/runtime authority.'}
(B/f'runtime-proof-{ST}.json').write_text(json.dumps(runtime,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print([(r['id'],[(k,v['source_mean_RGB'],v['inverse_mean_RGB'],v['source_peak_RGB'],v['inverse_peak_RGB'])for k,v in r['regions'].items()],r['approximate_face_layer_sourceover_diagnostic']['1.0'])for r in out])
print(out[-1]['regions']['whole_almost_constant_brown_pigment'])
