from pathlib import Path
B=Path(__file__).resolve().parent
s=(B/'prepare_effects_twenty_eighth.py').read_text(encoding='utf-8').replace('effects-twenty-eighth','effects-twenty-ninth').replace('CALL=[4089,4092]','CALL=[4086,2626]')
start=s.index('boxes=');end=s.index('for r in P:')
s=s[:start]+'''boxes={4086:[('original upper graybrown strongest patch',[9,6,16,13]),('original narrow muted middle paint',[11,12,18,20]),('original dim irregular lower taper',[16,20,24,30])],2626:[('original upper bluegray soft peak region',[31,8,45,24]),('original softer left bluegray core region',[12,12,30,32]),('original lower soft bluegray pigment',[35,32,49,48]),('original dim right patch',[52,22,64,38]),('original very dim broad lower tail',[12,42,42,64])]}
descs={4086:'EXACT original ONE thin irregular slanting muted graybrown PAINTED COLOR footprint. Literal native positiveRGB bitmap domain has93 pixels extent[9,6,24,30], not a physical metalpart count. Keep original soft upper graybrown patch, narrow darker and faintly warmer middle paint, original dim irregular lower taper and every interior original blackshade. Original strongest mean shade native[12,11] RGB111/94/92 stays subdued. Do not straighten, thicken, whiten or turn this soft uneven paint into a shiny metalrod/wire/beveled mechanism; do not interpret weak native bits as new parts. Retain source width, exact diagonal phase and weak lower tint, no sharpened edge/raised ridge/physicalgrain.',2626:'EXACT original ONE connected softly painted bluegray diffuse color bitmap field, positiveRGB3182 pixels across entire64x64 source extent[0,0,64,64]. That is bitmap topology, NOT number of physical clouds/spray particles. Keep the exact referenced original broad asymmetric diffuse silhouette/soft outer haze, existing left softly bright patch, existing upper grayblue patch, dim middle shade, lower-right softly shaded field, original separate-looking dim right extension and very dim lower falloff. Native strongest mean shade[39,15] RGB179/185/200, keep the original cold bluegray muted palette without whiteglints. Every original tone knot/blur patch/gap stays at original normalized position, size, width and relative intensity; do not subdivide broad paint into more cloudy cells, stipples, hard rings, rocks, spray droplets or cauliflower turbulence. Source has very faint RGB bits near canvas boundaries; preserve entire original canvas, not auto-bounding, cropping or adding a black margin.'}
''' +s[end:]
s=s.replace("expected={4089:([13,20],[129,114,117,249]),4092:([19,12],[119,80,73,255])}","expected={4086:([12,11],[111,94,92,246]),2626:([39,15],[179,185,200,200])}")
s=s.replace('assert len(domains)==(2 if i==4089 else 1)','assert len(domains)==1')
s=s.replace('wholecanvas NEAREST32x32→512x512 madeopaque','wholecanvas nearest source sampling to512x512 madeopaque')
s=s.replace('Keep ORIGINAL dimgray/brown/grayviolet hierarchy and nativepeak strengths','Keep ORIGINAL muted source color hierarchy and nativepeak strengths')
s=s.replace('OriginalTransparent A0..255 stays separately source-restored','Full original alpha stays separately source-restored exactly, including actual original max219 for2626 and max255 for4086')
s=s.replace("parts=['Use case: precise-object-edit.","parts=['Use case: precise-object-edit.")
s=s.replace('No physicalshine/glints/whiteplates/rims/bevels/raisedhardware/rust/etchedscratches/rods/wires/knurl/bolts/rocks/rings/newholes/fibers/photo texture/cloudgranules/stipples/furryedge/coarsemottle or addedfragments','No physical shine, glints, whiteplates, rims, bevels, raisedhardware, rust, etchedscratches, rods, wires, knurl, bolts, rocks, rings, newholes, fibers, photo texture, cloudgranules, stipples, furryedge, coarse mottle or addedfragments')
(B/'prepare_effects_twenty_ninth.py').write_text(s,encoding='utf-8')
print('Prepared own script without changing frozen28')
