from pathlib import Path
B=Path(__file__).resolve().parent
s=(B/'prepare_effects_twenty_eighth.py').read_text(encoding='utf-8').replace('effects-twenty-eighth','effects-thirtieth').replace('CALL=[4089,4092]','CALL=[4101,2575]')
start=s.index('boxes=');end=s.index('for r in P:')
s=s[:start]+'''boxes={4101:[('original extremely dim tiny upper-right field',[22,9,24,12]),('original dim warmgray uppermain field',[17,11,21,18]),('original dim coolgray lower field',[16,19,18,26])],2575:[('original dim broad upper loop',[12,4,43,23]),('original dark upper-middle pigmentgap',[22,14,37,29]),('original central warmer paint',[20,27,47,42]),('original strongest lower warm paint',[28,40,45,54]),('original right softer lobe',[45,31,62,47]),('original verydim lower falloff',[22,53,49,62])]}
descs={4101:'EXACT original THREE literal positiveRGB painted bitmap domains on complete black native32 canvas, not three physical particles/objects. TWO subdued main paint areas plus a much fainter original tiny upper-right area. Exact native domain1 FOUR pixels bbox[22,9,24,12] maxRGB8/5/5; keep this ORIGINAL tiny faint brown-gray paint at exact normalized coordinates and dim strength, without turning it into a bright new spark or removing it. Domain2 SEVENTEEN pixels bbox[17,11,21,18] maxRGB29/18/18, original warmgray slightly irregular upper-middle soft stripe. Domain3 THIRTEEN pixels bbox[16,19,18,26] maxRGB40/39/45, original cool gray/violet narrow lower soft stripe. Original strongest mean paint[16,23] RGBA40/39/45/251 remains the brightest but still VERY DIM muted pigment. Preserve exact widths, softblur, phase, spaces, all blackRGB even where originalA is positive; no connecting new line, new mechanism, glare, metalrod or raised edge. Very faint upper-right native field is original, not an optional decoration.',2575:'EXACT original softly painted orange/brown COLOR field with original broad upper loop/dark center, original darker inner pigment gaps, warmer middle paint, stronger lower patch and softer right lobe. Preserve the EXACT original knot/foldlike colorwash positions, widths, asymmetric silhouette, blur and relative strengths; do not reinterpret source shades as newly raised folds/firetongues/cloud cells. Literal bitmap count is ONE broad2145-pixel positiveRGB domain extent[5,2,62,62], plus SIX isolated nativeRGB[1,0,0] pixels at[50,17],[5,19],[18,47],[56,52],[52,54],[49,55]. These six are almost black source bits, NOT six physical sparks; keep them almost black, no glints/additional flecks. Native strongest mean[36,45] RGBA218/123/30/0; actual source channel extremaR218/G124/B30. Keep original brown-orange palette, dim upper wash, existing darkgaps and subdued relative weak falloff, no whitening/orange glare or blue cast. SourceA0 TransparentAdd uses visible storedRGB, not an empty mask and not premultiplied by zero. Entire guide is original storedRGB only.'}
''' +s[end:]
s=s.replace("expected={4089:([13,20],[129,114,117,249]),4092:([19,12],[119,80,73,255])}","expected={4101:([16,23],[40,39,45,251]),2575:([36,45],[218,123,30,0])}")
s=s.replace('assert len(domains)==(2 if i==4089 else 1)','assert len(domains)==(3 if i==4101 else 7)')
s=s.replace('wholecanvas NEAREST32x32→512x512 madeopaque','wholecanvas nearest original sampling to512x512 madeopaque')
s=s.replace('Keep ORIGINAL dimgray/brown/grayviolet hierarchy and nativepeak strengths','Keep ORIGINAL muted source color hierarchy and nativepeak strengths')
s=s.replace('OriginalTransparent A0..255 stays separately source-restored','Original fullA stays separately source-restored exactly:4101 Transparent A0..255;2575 TransparentAdd entireA0 but useful storedRGB/no premultiplication')
s=s.replace('Do not make new sparks/rays/tongues/curls','Do not make NEW sparks/rays/tongues/curls')
s=s.replace(" if i==2575:reason=", " if i==2575:reason=")
s=s.replace(" r['source_only_reason']=reason", " if i in [2372,2373]:reason='Actual thin bluegray branching paintedcolor line, individual original tiny branch/tip/relativeglow layout clear in complete matrix, but forced newdetail risks changing existing narrowphase. Genuine pending0calls, not analytically classified from name/appearance; typedconsumer and fullnative proof retained.'\n if i in [717,718]:reason='Actual sparse dim brown painted fragments and tinyweak RGB bits over original completeRGBA canvas. Exact matrix/counts/phase retained; faithful relative weak strength/gaps uncertain for forced scope call. Genuine pending0calls, no physicalparticle count from alpha or technicalfamilyban.'\n r['source_only_reason']=reason")
(B/'prepare_effects_thirtieth.py').write_text(s,encoding='utf-8')
print('Own30 exact preparation script')
