from pathlib import Path
B=Path(__file__).resolve().parent;ST='equipment-forty-first'
notes={
5431:'HELD actual wholecanvas UV/nativepaintscale and palette/material fidelity; genuineequipment artwork pending rootreview, no retry. Actual original128x32 Ordinary sourceA255, Materials.TextureID/TemplateID/Models.MaterialN diffuse/opaqueClamp consumers through fresh compact78uniqueactualDBrows plus historical/release/nativeRGBA exactparity. Wholeopaque nativeRGB128x32 originaltoolreference, NN PRIVATEnativecount/phase view only. BEFORE wholeRGBA/count/weakzero/rowpitch/sourceblur evidence immutable: left dark shadedpaintfield, complete brown finealternating repeatfield, TWO right shadedendcapfields and ONE darkdivider. Fullraw2164x727 adds87consecutive nearlywhite topcanvasrows and97bottomcanvasrows (12.0%/13.3% rawheight), source128x32 hasNOsuchwhiteborders. Diagnosticwhite-row recipe minRGB>=250 fraction>=.995 not BBox/crop/fitting permission. Wholeinverse512x128 therefore compresses sourceart vertically and inserts two pale fullUVbands; rootfullA255 restoration cannot remove either. Defaultscalar0.2919921875 makes borderRGB~74-78 and suppresses originalpaint; sourcepeak115/117/132 becomes34/35/38 at same coordinate. Source repeatfieldmean31.61/15.54/16.32 becomes25.11/21.90/21.79, tint hierarchy changes due newwhitecanvas; originalleftpaintmean43.58/42.96/48.39→28.35/28.29/28.96. Literal row4 original48shade maxima becomes31, row16 48→28, sourceeveryrow/phase exactarrays attached, NOTphysicalcheckers or hard numericalthreshold; actualcanvaspadding and paintscale shift privately visible independently. NativeRGBinverse actualblackpixel120,2 (sourceA255) becomes77/77/77 in paddedregion, +77mean. No sourceblackhole assumption. OriginalnativeRGBA(fullA255) restored byteexact/fullLANCZOS4x/RGB-FIRST separatelyA/defaultpad0/clear0/noPremul; no255clip afterscalar. Fullraw checkerpaint coarser and outlined, but actualUVwhitepadding alone decisively fails entirecanvas fidelity. Nativecorrelation−0.2192 diagnostic not threshold. Raw/exactargs/refSHA/beforeproof preserved; rejected ordinaryPNG copy+reason. No crop/BBox/registration/whitebandremoval/sourceRGBinsert/localgain/defaultpadoptout/retry. Hold realUV/palette/scale, not simplepaintpatternfamily or native4:1 assetban.',
5333:'HELD actual softmattepaint material/nativepaintscale fidelity, genuineequipment colorart pending rootreview/no repeat. Actualoriginal128x128 OrdinaryA255, fresh Materials.TextureID/TemplateID/Models.MaterialN opaqueClamp diffuse roles withcompact78actualDBrows and exacthistorical/release/nativeRGBA. Wholeopaque nativeRGB128x128 originaltooltarget, NNPRIVATE counts/weakphase only. BEFOREsource completepalette/allweakpigment/fullRGBA/softblur/nativepatterncount fixed: broad dimgreenupperfield with irregular coolgrayedgewash, lowerleftgraypaintisland, lowergraystrips, lowerrightgreenpolygon and existingthin grayloop paint. Never inferred physicalhardware from vaguepaint, no meshUV/runtime semantic claim. Fullraw1254square keeps broadwholecanvas positions/blackgaps/stripeends/grayloop/sourcefragmentfootprints and originalrelativegreen-gray hierarchy, no claimed newphysicalparts. However wholefullraw and pure512native4x visibly add widespread regular diagonal crossed/diamond stipple to originalsoftgreen-graypaint: coarse repeated cells across uppergreenwash, lowerleftgrayfield, middlegraystrips and rightpolygon. Sourcefine blurredbrush/shading becomes patternedmosaic, material/paintscale drift; broadUVcorrelation0.9822 and means cannot provefinepaint fidelity. HPstd1.621/1.498/1.809→3.371/3.197/3.902 supports visiblechange only, no numeric acceptance threshold. Purewhole scalar1.0330810546875/defaultpad0/clear0/fulloriginalA255byteexact/RGB-FIRST inverse separatelyA/OrdinarynoPremul, no255clipping. Nativebroadgreenmean34.15/37.45/18.06→32.84/38.33/16.05; grayedgewash45.81/52.03/32.05→44.83/53.50/31.64, graywashmax123/105/132→100/98/126. Lowerleftgraymean76.42/74.06/78.33→78.04/75.45/79.58 withmax189/186/189→206/200/201, maxlocalmeanlift47.67 at38,78 source115/113/120→167/160/164; maxloss−40.33 at124,56 separatelyrecorded. Same BEFOREliteral coolgray pixel-selection recipe uppercanvas B>=R/minRGB>=25/meanRGB>=45 yields413→473 selectedpixels, descriptivepaintstrength/phase diagnostic only, NOTparticle/hardwarecount or newfragment accusation. Source allsubthreshold weakpixels remain authoritative; topwash existingpigment shapes broader/coarser without inventing physicalcomponent counts. Sourcepeak30,78 RGB214/207/214→187/181/185, productionstrongest50,78 native217/211/213; modest localtone differences alone not automatic hold. Actualfailure is newlyregular fullpaint texture/cellscale seen at fullraw and source-scale native512, not mildgain/1pixelsoftening/naturalLANCZOS. Raw/exactargs/sourcebefore/refSHA untouched/rejectedcopy+reason. No RGBrepair/crop/BBox/localgain/defaultpadoptout/retry.'}
s=(B/'finalize_equipment_fortieth.py').read_text(encoding='utf-8').replace('equipment-fortieth',ST).replace('equipment_fortieth','equipment_forty_first').replace('CALL=[5237,5383]','CALL=[5431,5333]')
start=s.index('notes={');end=s.index('metrics={',start);s=s[:start]+'notes='+repr(notes)+'\n'+s[end:]
start=s.index('corrections={');end=s.index("save(f'postcall-corrections",start)
s=s[:start]+"corrections={'source_beforeproof_byteunchanged':True,'postcall_corrections':[],'postcall_serialization_clarification':'Original immediatelysaved callmetadata contains exactpromptCRLFUTF8/noLF and portable repo-relative reference recipe resolving exactly to actualabsolute toolinput. New exactactualargs files explicitly record absolute actualreferenced_image_paths without modifying originalcallmetadata/sourcebefore/ref/raw/prompt. Not a source/count/palette correction.','no_tool_retries':True,'no_artistic_corrections':True}\n"+s[end:]
start=s.index("'source_parity':'");end=s.index("','QA':'",start)
s=s[:start]+"'source_parity':'Fresh12 historicalMMP==release native==original exactRGBA/dimensions/POT/nativeType,78uniqueactualDB rows compactcanonicalrefs. ActualMaterials.TextureID/TemplateID/Models.MaterialN/Geometries/ModelTemplates exactfresh rowsets; runtime/meshUV/printedhardware meanings unknown. Honestprevioussource-only audits notneverviewed. CalledoriginalnativeopaqueRGB128x32 and128square, NNPRIVATEcountphase only; OrdinaryA255 straightRGB/actualopaqueClamp. Entireweakpixel/count/phase/palette/sourceblur beforeproof immutable"+s[end:]
start=s.index("'QA':'");end=s.index("','ownership':'",start)
s=s[:start]+"'QA':'2 genuinely FIRST solebuiltins/max3 withoutquota. ready[],held5431 actualwhitecanvaspadding/UVpaintscale/palette error and5333 newlyregular crossedmosaic coarsepaint material. Fullraw2164x727/1254square and pure512x128/512square storedRGB/fulloriginalA standardscalar0.291992/1.033081 inspectedprivately, rawA255/defaultpad0/clear0/fullAbyteexact. Exactrepeatrowphase/weakpaintdiagnostics contextual nothardacceptthreshold, countsnotinferredhardware.10genuinepending0call/source-onlyaudit, no grouptechnical/original-onlyrecommendation. No crop/BBox/paddingremoval/reposition/artistRGB/sourceartinsert/optout/retry"+s[end:]
s=s.replace('OwnEquipment40 independentfiles only; Eq39/38/37/Heads21/20/19/Effects30/29/etc','OwnEquipment41 independentfiles only; Eq40/39/38/37/Heads21/20/19/Effects30/29/etc')
# Portable savedrefs and literal actualtoolargs are both verified, actualprompt bytes unchanged.
needle="for k in ['pattern_constraints_ref','native_matrix_ref','common_actual_records','source_before_call_ref']:assert sha(ROOT/c[k]['path'])==c[k]['file_SHA256']"
s=s.replace(needle,needle+"\n actualargs={'id':i,'tool':'built-in image_gen.imagegen','prompt':c['exact_prompt'],'referenced_image_paths':[(ROOT/p).as_posix()for p in c['reference_pngs']],'transparent_background':False,'literal_actual_argument_UTF8_CRLF_no_finalLF':True,'reference_sha256':c['reference_sha256'],'original_immediate_call_metadata':ref(cp),'qualification':'Explicit actualabsolute refs serialize original solecall; relative recipe in immediatelysaved call remains unchanged/portable.'};save(f'exact-actualargs-{ST}-{i}.json',actualargs)")
(B/'finalize_equipment_forty_first.py').write_text(s,encoding='utf-8')
print('OwnEq41 finalizer12/2FIRSTheld/0ready/10pending, no frozen40/shared changes')
