from pathlib import Path
import json,numpy as np,hashlib
from PIL import Image
B=Path(__file__).resolve().parent;ST='effects-twenty-seventh';i=4096
o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];y,x=np.where(rgb.max(2)>0);ay,ax=np.where(a[:,:,3]>0)
assert not a[:,31].any()
g=np.array(Image.open(B/f'private-{ST}/native4x/{i}-stored-rgb-private.png').convert('RGB').resize((32,32),Image.Resampling.LANCZOS));n=Image.open(B/f'private-{ST}/native4x/{i}-calibrated-native-alpha-private.png').convert('RGBA')
assert n.getchannel('A').tobytes()==o.getchannel('A').resize(n.size,Image.Resampling.LANCZOS).tobytes()
c={'id':i,'phase':'Postcall separate correction of a visual descriptive mistake; all original BEFOREproof/raw/call/exactarg/helper/nativepixel data immutable.','incorrect_previously_stated_description':'4096 righttail reaches/clips original RIGHT canvas edge; this phrase exists in immutable source description and actualprompt argument.','correct_native_pixel_evidence':'Native32 fullRGBA matrix shows entire lastcolumn x31 exactly RGBA0. Color and alpha positive extents end at x30, so there is ONE completely empty native column at RIGHT; original is NOT clipped by canvas. It is a near-right-edge existing taper with original weakpaint at x30. Original count/phase/wholeRGBA/zeromap/reference PNG proof already contains actual correct pixels; only descriptive visualhypothesis was wrong.','source_RGB_positive_extent_native':[int(x.min()),int(y.min()),int(x.max())+1,int(y.max())+1],'source_A_positive_extent_native':[int(ax.min()),int(ay.min()),int(ax.max())+1,int(ay.max())+1],'last_native_column_RGBA':a[:,31].tolist(),'near_right_edge_nonzero_RGB_pixels':[[yy,30,*a[yy,30].tolist(),*g[yy,30].tolist()]for yy in range(32)if rgb[yy,30].any()],'production_native4x_fullsourceA_byteexact':True,'no_generated_geometry_fitting':True,'corrective_action':'No regenerate or artistRGBrepair/composite/crop/BBox/fitting. Do not erase/repair actualargument. Preserve immutable exactcall/sourcepixel proof and use actual complete sourceA/UV and private output inspection; readydecision must be output-native/material based, not this inaccurate descriptive word. Numeric extents are diagnostics only, never used forregistration.','immutable_before_source_SHA256':hashlib.sha256((B/f'source-check-{ST}-before-call.json').read_bytes()).hexdigest(),'immutable_before_constraints_SHA256':hashlib.sha256((B/f'pattern-constraints-{ST}.json').read_bytes()).hexdigest()}
(B/f'postcall-correction-{ST}.json').write_text(json.dumps(c,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Separate correction4096: emptycolumn31, near-edgecolor30; before/raw/call untouched')
