from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='effects-twenty-fifth';CALL=[2577]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'));cons=[];groups={}
for r in proof:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];l=rgb.mean(2);groups.setdefault(r['source_rgba_sha256'],[]).append(i)
 r['full_source_RGB_private_view']=True;r['actual_source_RGBA_extrema']=[list(z)for z in o.getextrema()];r['previous_source_only_views']=[p.relative_to(B.parents[2]).as_posix()for p in sorted(B.rglob(f'{i}-*source*.png'))if ST not in p.as_posix()][:12];r['view_novelty']='Honest fresh source-only re-audit: earlier0call native views exist. No never-viewed or newunique-bitmap claim; exactRGBA/source/call/held/raw guards passed.'
 r['source_only_reason']='Genuine sparse soft muted cloudpaint remnants with very weak separately standing sourcepixels; complete tinyweak domain/count phase not eligible for call in this bounded scope. No automatic technical/family exclusion.'
 if i==2575:r['source_only_reason']='Genuine complex orange-brown softly painted field with many original interior brightknots/darkgaps plus six single-pixel RGB1 remnants outside mainfield; source-only pending preciseweakpigment topology proof for faithfulcall, not technical byname/Type/A0.'
 if i not in CALL:continue
 y,x=np.unravel_index(l.argmax(),l.shape);assert o.size==(64,64)and not a[:,:,3].any()and rgb.max((0,1)).tolist()==[139,62,4]and [int(x),int(y)]==[22,14]and a[y,x].tolist()==[139,62,4,0]
 zero=rgb.max(2)==0
 c={'id':i,'before_prompt':True,'native_size':list(o.size),'source_RGBA_sha256':hashlib.sha256(o.tobytes()).hexdigest(),'actual_RGBA_extrema':[list(z)for z in o.getextrema()],'whole_native_RGBA_matrix':a.tolist(),'complete_original_zero_RGB_xy':[[int(x),int(y)]for y,x in zip(*np.where(zero))],'complete_weak_RGB_max_le5_positive_xy_RGBA':[[int(x),int(y),*a[y,x].tolist()]for y,x in zip(*np.where((rgb.max(2)>0)&(rgb.max(2)<=5)))],'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l.T],'native_source_max_mean_RGB_xy':[int(x),int(y)],'native_source_max_mean_RGBA':a[y,x].tolist(),'source_feature_counts':{'entire_connected_positive_sourceRGB_bitmap_domain':1,'native_positive_RGB_pixels':int((~zero).sum()),'native_zero_RGB_pixels':int(zero.sum()),'qualification':'ONE complete native painted colorfield RGB-connected domain, not a physical flame/particle/lobe count. All internal source shade extrema/weakpixels/zero gaps included exactly in native matrix; no interpretation as rings/tongues/cloud/anatomy. Counts are literal image topology evidence only.'},'source_domains':[],'semantic_qualification':'Native source-only wholeRGB guide, no crop/thresholdguide/padding/BBox/registration/artistrepair. Domainboxes only numeric diagnostic. All originalA0 restored separately; TransparentAdd usefulRGB no premultiply. Missing actualParticles definitions/siblingTexture rows remain unknown, not invented.'}
 boxes=[('original dim upper arc',[8,2,51,18]),('original brighter upper left painted band',[5,8,28,33]),('original broad dark central gap',[25,21,42,37]),('original dim left/lower irregular paint',[2,25,30,61]),('original lower right subdued curved paint',[30,36,55,57]),('original dim right boundary',[42,14,63,44])]
 for name,b in boxes:
  x0,y0,x1,y1=b;v=rgb[y0:y1,x0:x1];aa=a[y0:y1,x0:x1,3];c['source_domains'].append({'name':name,'bbox':b,'native_RGB':v.tolist(),'mean_RGB':v.mean((0,1)).tolist(),'max_RGB':v.max((0,1)).tolist(),'sourceA_extrema':[int(aa.min()),int(aa.max())],'original_zero_RGB_pixels':int((v.max(2)==0).sum())})
 cons.append(c);r['source_only_reason']='One FIRST wholecanvas faithful edit eligible after complete actual nativeRGBA/weakpixels/zero-gaps/palette/phase/maxima proof and whole sourceRGB/original views. Single entire original colorfield, no invented physicalcomponent count.'
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in proof],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in proof if r['id']not in CALL]});save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
c=cons[0];parts=['Use case: precise-object-edit. Faithfully edit the existing historical Silent Storm soft PAINTED COLOR effect bitmap to higher resolution. Do not draw a new explosion/flame/smoke simulation or realistic physical objects.', 'Image1 is the EXACT ENTIRE native storedRGB source solely wholecanvas NEAREST enlargement from64x64 to512x512, made opaque to expose useful native color. Preserve COMPLETE edge-to-edge normalizedUV, all original fieldpositions/widths/footprint/phase/sourcepatternscale. Final original alpha0 across WHOLE canvas is independently restored for TransparentAdd, which uses usefulRGB with no premultiply. Brightness correction is only one global numerical scalar. No crop/zoom/padding/whitespace/BBox/fitting/recenter/UV repacking. Source nearest pixels are positional evidence, NOT a request for blockcells/mosaic/granules.', 'Original source is ONE entire softly painted asymmetric DIM brown/orange colorfield with a muted upper curved band, brighter upper-left EXISTING patch near native[22,14], dim irregular left/lower painted swath, original dark central gap around[25,21,42,37], existing lower-right subdued curved paint and dimright boundary. Keep EVERY original irregular tonalband, nativeweakpixel and darkzero gap in exactly its original position, shape, blur and relative strength. No new lobes or physical flame tongues, rings, wisps, curls, sparks, cracks, rays, protrusions or cloudknots. Do not regularize the source pattern. Existing brighter tiny knots stay exact originalsize/location/intensity; original extremelydim reddish pixels remain verydim, not newglints. Do not interpret original dark paint gaps as newly outlined holes/bevels.', 'Actual nativeRGBA extrema are [[0,139],[0,62],[0,4],[0,0]]; original brightest native[22,14] is RGB139/62/4, not255 or white-hot fire. Preserve exact muted warm brown/red-orange palette and dim hierarchy with nearly absent blue. Do not add yellowwhite highlights, strengthen dark surroundings, sharpen source edges, introduce brighter metal/rocks or photonoise. Sourcepaint has original softblur and softly uneven broad shading, not granular cauliflower turbulence or lace. Add only subtle finer depiction of original smoothpaint, no new physical texture, stipples, cells, coarsemottle or gritty contrast.', 'Output ONLY the SAME ENTIRE opaque RGB square canvas with all original composition/material/count/scale/softblur/palette and blackoutside retained. No framing, cutout, newmarks, symbols, text or artistcomposites. Preserve all original source tones rather than beautifying color or geometry; fulloriginalalpha and nativeType are restored downstream.']
p=B/'generated/2577-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Immutable BEFORE12 IDs /4 distinct RGBA /one FIRST planned2577')
