from pathlib import Path
import json,shutil,hashlib
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='clothing-fifty-first';CALL=[6834];ORIG=[4564]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];groups={};rounds={};constraints=[];original=[]
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];lum=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['source_RGBA_RGB_A_NN_privately_inspected']=True
 r['source_only_reason']='Genuine actualstaticMaterials→TemplateID→Models paintedCOLOR source. Exactfullnative/history/release/A/type/consumers proven; complex existingweakmarks/sourceblur/material/nativephase requireliteralcounts beforeanyFIRST, genuinepending0call without name/type/familyban or inferredphysicalparts.'
 if i in [801,1760,1761,1762,2446]:r['source_only_reason']='Genuinecolored smallinsignia/diamond/oldglyphpaint onblacksource withvariableA; fullstoredRGB/alpha preserved, not technical fromOrders/name orA0. Specific tiny existingglyph/oldstroke identities andweakphase needexactliteralproof; no symboliccontent reinterpretation/newlettering, pending0call.'
 if i in [5682,5689]:r['source_only_reason']='Genuine full512x256 mattepainted red orgray metalatlas witholdwear/arcs/smallribs/markedglyphs andmanytinyshadefields. Sourceparts/count/pitch/phase notfullydescribed here beyondcompleteRGBA matrix, pending0call without Robot/name/materialban; notguesshardware orinventgrain/relief.'
 if i==2016:r['source_only_reason']='Individualsource27RGB browncoloredpolygon withvariableA0/255 onblack128canvas, actualdiffuseconsumer. NotconstantRGBA andno provenanalyticalpurpose; preserving exactflatpaint/boundary/UV/materialrequiresclarification, genuinepending0call NOToriginal-onlytechnical frompolygon/name/A.'
 if i==6365:r['source_only_reason']='Genuine471RGB originaldeliberatelyinverted face/hair warmdimpaint withintentionalblur, actualstaticdiffuse. Exactweakidentity/paintphase/material retained; genuinepending0call, no face/human/nameban.'
 if i in ORIG:
  assert np.all(a==0)and r['material_evidence']['actual_source_native_type']=='Ordinary'and r['fresh_actual_static_consumers'][0]['actual_Alpha_AddressMode']==['alpha_test','Clamp'];r['source_only_reason']='Individual ORIGINAL-ONLYrecommendation pendingroot: EVERYnativeRGBAbyte0 andALLstoredRGB0, Ordinary sourceA0; fullhistorical/release exactRGBA/binary andactualalpha_test Clamp Materials→TemplateID→Models consumer. ConstantRGBA exactpixels, no hiddenusefulRGB orpaint inferred. Rootfunctional/nativefinalclassification required; no group/type/A blanketban.'
  original.append({'id':i,'status':'individual-original-only-fullconstant-zeroRGBA-recommendation-rootreview','call_count':0,'reason':r['source_only_reason'],'fullconstantRGBA_proof':{'native_size':list(o.size),'pixel_count':o.width*o.height,'one_distinct_RGBA':[0,0,0,0],'sourcehistorical_release_exact':True},'native_matrix_ref':r['native_matrix_ref'],'common_actual_records':r['common_actual_records'],'actual_consumers':r['fresh_actual_static_consumers'],'previoussource_only_exactRGBA':{'id':1893,'call_count':0,'qualification':'1885 sameFULLRGBA/dims/Type asprevioussource-only4518 recommendation, noaccepted/generated donor claim. 1893 hasdifferent64x128 dimensions. Individualfreshactualconsumers/sourcepayload re-audit, not neverviewedpayload fiction.'},'not_runtimeaccepted':True})
 if i not in CALL:continue
 assert o.size==(128,128)and o.getchannel('A').getextrema()==(255,255)and r['fresh_actual_static_consumers'];rnd=np.array(o.convert('RGB').resize((512,512),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS));rounds[str(i)]={'id':i,'source_RGB_LANCZOS4x_then_native_RGB_matrix':rnd.tolist(),'recipe':'EntireRGB FIRST independentlyA 4x LANCZOS thenwhole nativeinverse/noPILpremul/crop/registration/patch.'}
 boxes=[('ONE upperhorizontal darkgrayfield',[0,0,128,24]),('ONE curved graylinepaint upperleft',[2,3,62,25]),('ONE olduppercentral greenangularpaint',[30,11,59,34]),('ONE centralsoft unequalpatchpatternfield',[33,42,57,101]),('ONE leftdottedgraypaintcolumn',[26,28,32,86]),('ONE rightdottedgraypaintcolumn',[57,28,62,86]),('ONE oldtinygraymark abovecentralpatchfield',[40,33,47,42]),('ONE darklowerleftpaintfield',[0,24,33,128]),('ONE darkrightpaintfield',[62,24,128,128]),('ONE originalwarmtan lowercentralpaintpatch',[38,101,51,121]),('ONE originalangulargraygreen lower rightUVfield',[71,81,128,128])]
 domains=[]
 for name,b in boxes:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);domains.append({'name':name,'bbox':b,'native_pixels_ref':{'matrix_ref':r['native_matrix_ref'],'slice_native_xyxy':b},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_std_RGB':v[:,:,:3].std((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'source_peak_xy':[x0+int(x),y0+int(y)],'source_peak_RGBA':v[y,x].tolist(),'sourceA_extrema':[255,255]})
 profiles=[]
 for axis,coord,z0,z1 in [('column',29,29,85),('column',58,29,85),('column',37,43,86),('column',51,43,86),('row',37,26,63),('row',84,26,63),('row',112,30,64)]:
  v=lum[coord]if axis=='row'else lum[:,coord];xs=[z for z in range(z0,z1)if v[z]>v[z-1]and v[z]>=v[z+1]];profiles.append({'axis':axis,'native_fixed_coordinate':coord,'native_axis_interval':[z0,z1],'literal_paintshade_maximum_axis_coordinates':xs,'literal_count':len(xs),'native_successive_pitch':[b-a for a,b in zip(xs,xs[1:])],'qualification':'Literalpaintpigment weakmarks/nativephase, NOTphysicalbelt holes/fasteners/rivets/buckles counts oracceptance thresholds. FullRGBApixels authoritative.'})
 desc='ENTIRE original128square subdued charcoalgray/graygreen/tan MATTE softlyfiltered painted UVmap. Keep ONE original topdarkhorizontalfield/oldcurvedgrayline, ONE oldangulargraygreen topcentralfield, ONE centralsoftUNEQUAL rectangular mottledpatchfield x33..56,y42..100, TWO original dottedGRAYPAINT columns (leftx26..31,y28..85 andrightx57..61,y28..85), ONE oldtinygraypaintmark x40..46,y33..41, ONE warmtanlowercentralpaintpatch x38..50,y101..120, ONE angulargraygreen lowerRIGHT UVfield x71..127,y81..127 andALL surroundingoriginalnearblackfields. These are originalflatCOLORpaintmarks, NOT recreatedphysicalbuttons/lacing/rivets/bucklemechanisms/skin/anatomy. LEFT nativecol29 has18 actualshade peaks y30,33,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84; RIGHT nativecol58 has19 actualshade peaks y30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84. Preserve LEFTmissing36 vsRIGHTexisting36 EXACTLY, doNOT regularize intoidenticalcolumns orfilloldgap; these are sourcepaintshadephases notlicense fornewholes/rivets/stitches. Centralweakpaint unequalLEFT nativecol37 peaks y45,48,51,57,64,70,80,82,84 andRIGHT col51 peaks y45,48,50,57,63,68,70,77,80,84: preserve SAMEasymmetry/nativepatchscale/sourceblur, NO new regulargrid/cells. Keep tinyoldgraymark exactlyassource indistinctpaint, no newlettering/symbol. Keeporiginalweakblack/dark fields includingblackRGB/A255—not emptyUVareasto repaint. Fineoriginalmattecolorwash ONLY, NO sourcewash changedtop hysicalgrain/photo clothfibers/weave/new seams/castmetal/chrome/raisedgrayrims/goldglints/lacedhardware/stipple/mosaic/coarsecells/texturepattern/contrastyclouds. Keepexact dimrelativepalette/weakmark strengths/paintblur. Do NOT reconstructhumanparts beneath tanpatch or darkfields.'
 c={'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':[128,128],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':{'centralunequalpatchpaintfield':1,'pairedsidegraypaintcolumns':2,'left_column29_literal_graymaxima_y29to85':18,'right_column58_literal_graymaxima_y29to85':19,'left37central_literalpatchmaxima_y43to86':9,'right51central_literalpatchmaxima_y43to86':10,'uppercurvedgraylinepaint':1,'oldtinygraymark':1,'warmtanlowerpaintfield':1,'lowerRightangulargraygreenfield':1},'native_repeat_count_phase_evidence':profiles,'native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_sourceA0_pixel_count':0,'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'source_description':desc,'qualification':'LiteraloriginalCOLOR painting regions/weakcounts/phase beforetool, not assumedphysicalmechanism. Descriptiveoverlappingbboxes notcrop/registration. CompleteRGBA/nativepalette/sourceblur authoritative.'};constraints.append(c)
 r['source_only_reason']='EligibleFIRST honestfreshre-audit ofsource-only6834 (no priorraw/call/jobs) graygreen/body matteCOLOR whole128. LEFT18 vsRIGHT19 sidepaint maxima/sourceleftmissing36 andunequalcentral9/10literalshade phases provenbeforeprompt; fullnativeRGBA/historyrelease/POT/OrdinaryA255/actualMaterials→TemplateID→Models, originalblur/nativepaintscale. Literalshade peaks notguessed physicalbuttons/stitches. No newregulargrid/material/fibers/hardware/glyphs.'
save(f'natural-RGB-roundtrip-{ST}.json',{'sources':rounds,'before_call':True});rp=B/f'natural-RGB-roundtrip-{ST}.json'
for c in constraints:c['natural_RGB_roundtrip_ref']={'path':rp.relative_to(ROOT).as_posix(),'file_SHA256':sha(rp),'source_key':str(c['id'])}
save(f'pattern-constraints-{ST}.json',constraints);save(f'original-only-proof-{ST}.json',original);selected=read(B/f'selected-{ST}.json');save(f'selected-original-only-{ST}.json',[{**r,'worker_original_only_recommendation':next(o for o in original if o['id']==r['id'])}for r in selected if r['id']in ORIG]);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'previous_scope_sourceonly_reaudit_ids':[2005,3892,4442,4451,4549,6806,6834,6835],'fresh_ID_scope_ids':[4564,4947,5456,5670],'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL+ORIG],'recommended_original_only_ids':ORIG,'all_selected_outside_previousClothing1to50':False,'qualification':'FOUR newIDs plusEIGHT honest prior0callbody sourceaudits, no accepted/generated/held/rawdonor repeat.','pending_exactRGBA_alias_qualification':'FournewIDs/Eightold0callsourceaudits disclosed, exactpendingpayload groups explicit. 4564 previous1893zero0call nativepayload reaudit, noaccepted/generated donor.'});save(f'source-check-{ST}.json',P);assert not(B/f'source-check-{ST}-before-call.json').exists();shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in constraints:
 i=c['id'];parts=['Use case: precise-object-edit. Asset type: full softlyfiltered MATTEgraygreen/charcoal/tan diffuse COLOR UV painting. SubtleHD SAMEsourcepaint/sourceblur/nativepatternscale/count/weakphase/material/palette, not physicalrenderedgarment.', 'Image1 edit target ENTIRE exactnative128square storedRGBopaque atoriginalresolution, NO NNtool. ActualstaticMaterials TemplateID Models diffuse source (source-onlypreviousviews honestlyreaudited/no previousimagegen). Ordinary straightRGB/noPremul/fulloriginalA255 separatelyrestored. All originalblack/darkUVpaint authoredsource, noemptyfill.', c['source_description'],f'ActualnativeRGBA extrema {c["actual_RGBA_extrema"]}; strongestnativeRGBA {c["native_source_max_mean_RGBA"]} at{c["native_source_max_mean_RGB_xy"]}. KeepoldSMALLdim peak/relativeweakfields exactly, not white255/glare. Originalsoft filteredpaint intentional; NO raisedcontrast/photograin/cloudmottle/coarseblocks/cells/fibers beneath sourceblur.', 'Output SAME ENTIRE SQUARE opaqueRGB UVcanvas. All exactsource graypaint asymmetriccounts/nativephase anddarkfields remain; no border/padding/whitespace/portrait/zoom/crop/rotate/recenter/BBox/fitting/registration/islandmoves. No new symbols/letters/hardware/buttons/skin/anatomy/grid/lacing/weave/seams/hair/fibers/relief. No repaintingexistingmottle into newpattern; keep originalsubtlepaint.']
 arg='\r\n\r\n'.join(parts);p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes((arg+'\n').encode('utf-8'));(B/f'generated/{i}-{ST}-exact-call-argument.txt').write_bytes(arg.encode('utf-8'))
print('Cl51 BEFORE12 honestreaudit; sole6834/originalrec4564',[(c['id'],c['native_source_max_mean_RGBA'],c['native_source_max_mean_RGB_xy'])for c in constraints])
