from pathlib import Path
import json,shutil,hashlib
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='heads-twenty-third';CALL=[6774,6775,6776]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];actual=read(B/f'actual-records-{ST}.json');cons=[];groups={};rounds={}
codeproof={'qualification':'Actual code bindings separately from DB: Materials diffuse resolves via TemplateID/modelroles. DynamicFaceTextures TextureID/THMID owner.face, LSHead.BuildTexLayers/GetTextureWeights and MixTexture weighted source-over use completeRGB/sourceA. Registration is not measured runtime weight. SourcestoredRGB, even A0 color and authoringcorner, remain original; no staticModel inference for dynamic layer.','files':[{'path':n,'file_SHA256':sha(ROOT/n)}for n in ['DBFormat/DataFaceGen.cpp','Main/LSHead.cpp','Main/FaceGenTextureSampling.h']]};save(f'consumer-code-proof-{ST}.json',codeproof)
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];lum=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['source_RGBA_RGB_A_NN_privately_inspected']=True
 r['FaceGen_binding_code_ref']={'path':(B/f'consumer-code-proof-{ST}.json').relative_to(ROOT).as_posix(),'file_SHA256':sha(B/f'consumer-code-proof-{ST}.json')}
 r['actual_FaceGen_layer_channels']=[{'table':v['actual_layer_table'],'id':v['actual_layer_ref']['id'],'THMID':v['actual_THMID_owner_ref']['id'],'TextureName':actual['tables'][v['actual_layer_table']][str(v['actual_layer_ref']['id'])]['TextureName'],'Priority':actual['tables'][v['actual_layer_table']][str(v['actual_layer_ref']['id'])]['Priority'],'full_THMID_sibling_layer_count':len(v['all_actual_THMID_texture_sibling_refs']),'actual_runtimeweight':'unknown/unmeasured'}for v in r['fresh_actual_dynamic_consumers']]
 r['source_only_reason']='Genuine sourcepaint pending full weakphase/nativepaint detail fidelity, not technical by hair/head/family/A0. Previous source-only0call views honestly reaudited; no forced generation.'
 if i in [6772,6773]:r['source_only_reason']='Genuine actualstatic Material/template/model hairpaint COLOR source with many irregular curls/softdirectional brushfields. Exact RGBA/native phase retained in common BEFORE matrix; individual source complexity and tinyfilteredstroke grouping not resolved for faithful FIRSTcall here. Genuinepending0call, NOT all hair family unsuitable or analytic mask.'
 if i in [6781,6782,6784,6785,6787,6788]:r['source_only_reason']='Genuine actual TransformableFaceTextures→THMID→Heads COLOR layer with TWO original sourcealpha arcs and ONE whiteauthoringcorner; RGB is tinted near-flat but contains weak nonconstant pigment (source distinctRGB8/42/5/10/16/7 respectively), not constantRGBA or pureblackmask. Individual sourceweakpaint/tintedwholefield/A needs preservation; source-only0call genuinepending, NOT original-only technical recommendation based on name/nearflatness/A. Exact originalRGB and every variableA byte retained; no sharpenedbrows/backgroundgrain or newanatomy guessed.'
 if i==6921:r['source_only_reason']='Genuine actual dynamicFaceGen colorpaint layer with irregular softred/cream/gray sourcepigment plus complex variableA holes, not analytic by name or damage/head family. Whole originalRGBA/storedRGB and literal fragmentedA retained; unknown anatomical interpretation/detailgrouping not suitable for a firstcall here. Genuinepending0call; no newparts/teeth/anatomy inferred.'
 if i not in CALL:continue
 assert r['material_evidence']['actual_source_native_type']=='Ordinary'and o.size==(128,128)and r['fresh_actual_static_consumers']and not r['fresh_actual_dynamic_consumers'];assert o.getchannel('A').getextrema()==(255,255)
 source=o.convert('RGB');rnd=np.array(source.resize((512,512),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS));rounds[str(i)]={'id':i,'source_size':[128,128],'recipe':'ENTIRE native storedRGB FIRST LANCZOS4x then entire LANCZOSnative independently sourceA; natural numerical phase/blur diagnostic BEFORE call, no PIL implicitRGBApremul or artistpatch.','source_RGB_LANCZOS4x_then_native_RGB_matrix':rnd.tolist(),'source_corner_RGBA':a[127,0].tolist(),'natural_RGB_roundtrip_corner':rnd[127,0].tolist()}
 domains=[]
 boxes=[('ONE upper curved filtered hairbrush field',[0,0,128,36]),('ONE broad middle curved filtered hairbrush field',[0,36,128,92]),('ONE lower crossswept filtered hairbrush patch',[24,92,106,128]),('ONE LEFT angular thin pale originalpaintoutline',[0,20,25,62]),('ONE RIGHT angular thin pale originalpaintoutline',[102,20,128,63]),('original softdark lowerleft field',[0,92,24,128]),('original softdark lowerright field',[106,92,128,128])]
 for name,b in boxes:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);domains.append({'name':name,'bbox':b,'native_pixels_ref':{'matrix_ref':r['native_matrix_ref'],'slice_native_xyxy':b},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_std_RGB':v[:,:,:3].std((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'source_peak_xy':[x0+int(x),y0+int(y)],'source_peak_RGBA':v[y,x].tolist(),'sourceA_extrema':[255,255]})
 patterns=[]
 for y,x0,x1 in [(12,1,127),(24,25,102),(50,1,127),(68,1,127),(82,1,127),(108,24,106),(32,1,25),(32,102,127),(52,1,25),(52,102,127)]:
  v=lum[y];xs=[x for x in range(x0,x1)if v[x]>v[x-1]and v[x]>=v[x+1]];patterns.append({'axis':'row','native_fixed_coordinate':y,'native_axis_interval':[x0,x1],'literal_paintshade_maximum_axis_coordinates':xs,'literal_count':len(xs),'native_successive_pitch':[b-a for a,b in zip(xs,xs[1:])],'qualification':'Literal sourcepigment maxima in fullpaint bitmap, NOT physicalhair/strand/link count or allowance for addingfiber detail.'})
 color={6774:'muted black/darkwarmgray',6775:'muted darkwarmbrown/ochre',6776:'muted darkwarmgray/brown'}[i]
 description=f'Keep THREE original broad filtered hairCOLOR brushfields in complete128canvas: ONE upper curvedpaint x0..127,y0..35; ONE middle curvedpaint x0..127,y36..91; ONE small lower crosssweptpaint x24..105,y92..127. These are observed source COLORpaintdomains, not three newobjects or inferred locks. Keep originalsource{color} palette and ALL existing dimbrushstrokes/weakgray/brown peaks/directionalphase/nativepaintscale; same softblur, no brighterrim/gloss/fibers/newcurls. Keep TWO original irregular thin paleangular paintoutlines atnativeLEFT x0..24,y20..61 andRIGHT x102..127,y20..62, exact originalcorners/shortdiagonal/crossbar positions and linecount from reference; do not interpret them as newclips/pins/buckles/glyphs. Source darkgaps andblackUV are opaque authoredRGB/A255, not holes. NativeRGB sourcepeak{M[str(i)]["native_peak_mean_RGBA"]} at{M[str(i)]["native_peak_mean_RGB_xy"]} stays same flatpaint/localstrength and footprint, no white255 substitute if not original. Preserve entire source dark lowercorners, no grain/mottle or erased paint.'
 cons.append({'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':[128,128],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':{'broad_original_hairCOLOR_brushdomains':3,'original_irregular_thin_angular_pale_paintfields':2},'native_repeat_count_phase_evidence':patterns,'native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_sourceA0_pixel_count':0,'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'qualification':'Exact fullsourceRGB/A once beforetool; domainbboxes descriptive, not crop/islandfit. THREE broadbrushfields/TWO thinangularpaintfields do not count physicalhairlocks, eyelets/hardware. Every weak nativepigment/phase kept by exact common matrix; no fictitious anatomicalModel or numericalacceptance threshold.','source_description':description,'actual_static_consumers':r['fresh_actual_static_consumers']})
 r['source_only_reason']='Eligible FIRST after exactsource/history/releaseRGBA/POT/actualstaticMaterials→TemplateID→Models/Hair consumers/native128opaqueRGB toolreference/fullsourceA255/THMID distinction/weakphase/count/palette/softmaterial audit. THREE original broadpaintfields/TWO originalangularoutlinefields; source anatomy/physicalstrand meanings not inferred.'
rp=B/f'natural-RGB-roundtrip-{ST}.json';save(rp.name,{'sources':rounds,'before_call':True})
for c in cons:c['natural_RGB_roundtrip_ref']={'path':rp.relative_to(ROOT).as_posix(),'file_SHA256':sha(rp),'source_key':str(c['id'])}
save(f'pattern-constraints-{ST}.json',cons);save(f'original-only-proof-{ST}.json',[]);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[]});save(f'source-check-{ST}.json',P);assert not (B/f'source-check-{ST}-before-call.json').exists();shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Asset type: original mattefiltered HAIR COLOR UV bitmap, not a portrait or photographic hair. Faithfully edit SAME ENTIRE bitmap at higherresolution while preserving sourceblur/nativepaintscale/count/phase/palette/weakpigment/wholeUV/material.', 'Image1 is ENTIRE exactnative original128square storedRGB madeopaque at ORIGINAL resolution. No NN enlargedtoolguide. NativeOrdinary straightRGB/noPremul/fullsourceA255 andstandard wholebrightnessscalar/defaultpadding restored downstream. Source darkblackRGB/A255 is authoredsourceUVpaint, not empty. Actualsource Material→TemplateID→Models diffuse/hairbindings, NOT dynamicFaceGen COLORoverlay or anatomy inference.',c['source_description'],f'Exact source fullRGBA extrema {c["actual_RGBA_extrema"]}; original nativeweakpigment allpoints/peak strength/graybrown shade hierarchy authoritative. Existing directionalbrushmarks are softlypainted and filtered; no newphysicalstrands or increasing brushstroke count/contrast. Retain the same original bluntsoft ends and gaps, not sharp reconstructed newhair.', 'Subtle fine rendition of SAME original filtered mattebrush only. NO photo hairfibers/individualhairs/newradiallines/newlocks/curls/syntheticstrandtexture/mosaic/coarsecells/beardgrain/backgroundmottle/granules/grain/shine/glare/glints/brightoutlinedrims/raised seams/metal clips/anatomy/skin/pores/eyebrows/teeth/newparts/letters/logo. Existing paleangularpaintfields remain FLAT SOFT PAINT, not inventedhardware or newglyphs. Do not reveal imaginarydetail under originalblur or whiten weakgraymarks.', 'Output SAME ENTIRE SQUARE opaqueRGB originalUVcanvas. No whitespace/padding/border/frame/cutout/crop/zoom/recenter/BBox/fitting/islandmoves/registration. Same THREE broadsourcepaintfields/TWO originalthinangularpaintfields/darkcorners and allnativepaintphase/count/sourceA/material/blur/palette.']
 arg='\r\n\r\n'.join(parts);p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes((arg+'\n').encode('utf-8'));(B/f'generated/{i}-{ST}-exact-call-argument.txt').write_bytes(arg.encode('utf-8'))
print('Heads23 immutable before12/3 prospectiveFIRST/9genuinepending/nooriginalrecommend',[(c['id'],c['native_source_max_mean_RGB_xy'],c['native_source_max_mean_RGBA'])for c in cons])
