from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='effects-twenty-sixth';CALL=[4091,4094]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'));cons=[];groups={}
boxes={4091:[('upper left dim reddish gray wash',[8,5,16,13]),('upper right graybrown vertical paint',[15,4,21,13]),('middle mutedgray warm diagonal wash',[9,11,23,18]),('original lower middle darkpixel pocket',[17,14,19,16]),('lower soft warm paint',[10,15,23,21])],4094:[('left palegray short painted extension',[6,8,18,15]),('upper middle dim brown-gray field',[16,6,26,15]),('original center lightgray diagonal paint',[10,12,22,19]),('original dark lower left notch',[14,17,18,21]),('lower right subdued gray taper',[18,16,29,28])]}
descs={4091:'ONE compact original asymmetric muted brown/redgray PAINTED color footprint. Keep two existing dim upper projections separated by the exact original black topnotch, original middlegray/brown wash, existing small darkpigment pocket around native[17,14,19,16], and original lower softer warmer wash. These are exact source painted tonal domains, NOT a physical part or metalobject. Keep original uneven shortprojections/tapers and all black gaps without turning the darkpaint pocket into a newly outlined hole/cavity/ring/bevel. Do not draw bolts/rust/cracks, do not reshape to a neat U or any hardware.',4094:'ONE original irregular diagonal muted gray/brown PAINTED color footprint. Keep original short left palegray extension, dim upper-right brown-gray projection, lighter diagonal centerwash with exact original peak native[13,14], original lower-left darknotch, original lower-right subdued gray taper. Preserve all original irregular sourcepositions/widths/count/phase and relativegray vswarm shading. This is flat softly painted bitmap shade, NOT a wing, propeller, shard, rock, plate or realistic metallicobject; no new physicalinterpretation. Do not turn original lightgray paint into a whiteplate/glint/bevelededge. All original darkpixel gaps and softshade remain original, no newholes or sharpening ofgray boundaries.'}
reasons={2626:'Genuine broad softly painted bluegray field with multiple existing tonalcores, interior unevenshade and darkgaps. Complete faintpixel/tonalcomponent phase not fully established for faithful boundedcall, source-only genuinepending0calls, not technical byname/missingParticle/A.',2627:'Genuine bluegray originalpaint with numerous verydim separated tiny bits/thinstreaks. SourceA0 TransparentAdd usefulRGB; strict weakcomponent strength/phase needs more proof. Pending0calls, not empty or technical.',2628:'Genuine sparse bluegray softly painted streaks and several separate dimbits; precise original weakstreak hierarchy/count matters, source-only genuinepending0calls.',2629:'Genuine bluegray manythin diagonal sourcepaint streaks and faintspots; exactcomponent/hierarchy proof not established, source-only genuinepending0calls.',5391:'Individually inspected whole storedRGB: one verythin smooth vertical bluegray tonefield with original A0..98. No independently visible painted surface detail; generating grain would change original softblur. Source-only pending0calls, genuinecolor not declared technical or analytic solely fromname/simplefield.',5392:'Individually inspected whole storedRGB: one broad smooth vertical bluegray softly shaded tonefield with sourceA0..62. No independent original finepaint detail to synthesize confidently withoutchanging softblur. Source-only pending0calls; not falseempty/technical/analytic classification.',2523:'Genuine complex brown/violet painted blast with many narrowrays and original sparseweak flecks. Exactweak fragment/ray strength/count not clear for a faithful solecall; source-only genuinepending0calls, no broadfamilyban.',4086:'Genuine muted darksourcepaint thin diagonal footprint with dim separate areas/bends; accurate tinytonal shape hierarchy needs furtherproof, source-only genuinepending0calls.',4089:'Genuine muted graybrown upright soft painted footprint plus separate small rightdim bits; whole original sourceart inspected but strict separateweakbits not established for this boundedcall. Pending0calls, no automatic technicalfamily exclusion.',4092:'Genuine sourcepaint subdued vertical brown-gray footprint, complex tiny original light/dark pigment phase; detailed subfield/weakpixel fidelity not clear enough for boundedsolecall, genuinepending0calls.'}
for r in proof:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];l=rgb.mean(2);groups.setdefault(r['source_rgba_sha256'],[]).append(i)
 r['full_source_RGB_private_view']=True;r['actual_source_RGBA_extrema']=[list(z)for z in o.getextrema()];r['previous_source_only_views']=[p.relative_to(B.parents[2]).as_posix()for p in sorted(B.rglob(f'{i}-*source*.png'))if ST not in p.as_posix()][:12];r['view_novelty']='Honest fresh re-audit of earlier source-only0call views, not never-viewed. Accepted/raw/call/generated/held/refusal/exactRGBA guards separately passed.';r['source_only_reason']=reasons.get(i,'Eligible FIRST faithful wholecanvas paintedsource edit after exactnative matrix/count/weakpixel/zeroshade/phase and whole sourceRGB/A views, no physicalshape interpretation.')
 if i not in CALL:continue
 y,x=np.unravel_index(l.argmax(),l.shape);expected={4091:([20,14],[74,50,46,255]),4094:([13,14],[145,123,123,255])};assert o.size==(32,32) and [int(x),int(y)]==expected[i][0] and a[y,x].tolist()==expected[i][1] and a[:,:,3].min()==0 and a[:,:,3].max()==255
 zero=rgb.max(2)==0;c={'id':i,'before_prompt':True,'native_size':list(o.size),'source_RGBA_sha256':hashlib.sha256(o.tobytes()).hexdigest(),'actual_RGBA_extrema':[list(z)for z in o.getextrema()],'whole_native_RGBA_matrix':a.tolist(),'complete_original_zero_RGB_xy':[[int(x),int(y)]for y,x in zip(*np.where(zero))],'complete_weak_RGB_max_le5_positive_xy_RGBA':[[int(x),int(y),*a[y,x].tolist()]for y,x in zip(*np.where((rgb.max(2)>0)&(rgb.max(2)<=5)))],'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l.T],'native_source_max_mean_RGB_xy':[int(x),int(y)],'native_source_max_mean_RGBA':a[y,x].tolist(),'source_feature_counts':{'entire_original_painted_footprint':1,'qualification':'ONE complete bitmap paintedfootprint with all original asymmetrical tonal projections/notches. Not a physicalparticle/part count fromRGBA mask or guessed hardware. Exactnative fullmatrix and zeropixel/weakpigment/maxima maps define entire field/count/phase.'},'source_description':descs[i],'source_domains':[],'semantic_qualification':'Native source-only ENTIRE RGB NNguide; allboxes numericdiagnostic only, never crop/fit/BBox/composite/artistpatch. SourceA0..255 separately restored. MissingactualParticles200 semantics/Wrap notinvented, presentresolved records exact.'}
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=rgb[y0:y1,x0:x1];aa=a[y0:y1,x0:x1,3];c['source_domains'].append({'name':name,'bbox':b,'native_RGB':v.tolist(),'mean_RGB':v.mean((0,1)).tolist(),'max_RGB':v.max((0,1)).tolist(),'sourceA_extrema':[int(aa.min()),int(aa.max())],'original_zero_RGB_pixels':int((v.max(2)==0).sum())})
 cons.append(c)
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in proof],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in proof if r['id']not in CALL]});save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Edit the existing historical Silent Storm original SOFT PAINTED COLOR footprint into a faithful higherresolution bitmap. Not new realistic physical object or new effectsimulation.', 'Image1 is EXACT ENTIRE native storedRGB solely wholecanvas NEAREST enlargement from32x32 to512x512, opaque to expose originalpaint. Preserve complete edge-to-edge normalizedUV, all original positions/shape/width/count/phase/nativepaintscale/palette/localrelative strengths. Nearest pixels prove originalpositions only: render original smooth softwash, NOT grid/squaredcells/mosaic/granules/stipple. Original fullA is restored independently downstream; only ONE global brightness scalar, no crop/padding/frame/zoom/recenter/BBox/fitting/repacking.',descs[i],f'Exact original nativeRGBA extrema are {c["actual_RGBA_extrema"]}; source maximum mean pigment native xy{c["native_source_max_mean_RGB_xy"]} is exact RGBA{c["native_source_max_mean_RGBA"]}. Keep all original darkbrown/gray vsmoderate lightgray source relationships, original verydimpaint and sourceblack gaps. Do not assign255/white peaks or locally strengthen lightgray edges. NativeTransparent A0..255 is restored separately; guide staysopaque.','Source material is deliberately matte and softly blurred, with broad subtle painted washes. Add only finer depiction of EXISTING softly blended paint, no new physicalfinegrain or granular/powdery/furry/coarse mottled noise. No photometal/shine/glints/whiteplates/bevels/rims/scratches/etchedtexture/rust/bolts/rods/knurl/cracks/rings/raisedhardware/rocks/flametongues/curls/sparks/new fragments or new darkholes. Do not regularize asymmetry or sharpen originalshade. No new symbols/text/logos.', 'Output ONLY ENTIRE SAME opaque RGB square canvas with exactwholeUV/original count/material/sourceblur/patternscale/colorhierarchy. No whitespace/border/crop/zoom/cutout/composites; complete originalA/nativeType restored downstream, never altered originalcomposition.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Immutable BEFORE12sourceproof/2FIRST calls',CALL)
