from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='heads-twentieth';CALL=[6697,6700,6722]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];cons=[];groups={}
boxes={6697:[('whole existing soft beard paint',[20,38,107,104]),('original central dark opening',[47,60,79,76]),('original dim upper side tips',[20,38,107,64]),('original lower paint band',[29,73,101,99]),('original flat lower background',[8,108,120,124]),('original lower-left white corner',[0,127,1,128])],6700:[('whole existing soft gray beard paint',[18,46,107,103]),('original central dark opening',[45,63,82,79]),('original two side tips',[18,46,107,74]),('original lower paint band',[28,76,100,103]),('original flat lower background',[8,108,120,124]),('original lower-left white corner',[0,127,1,128])],6722:[('original left grayblue hairpaint bank',[0,0,41,76]),('original right grayblue hairpaint bank',[84,0,128,78]),('original dim left brow stroke',[42,34,62,45]),('original dim right brow stroke',[65,34,86,45]),('original flat lower background',[8,87,120,124]),('original lower-left authored corner',[0,127,1,128])]}
counts={6697:{'existing_connected_soft_curved_beard_color_field':1,'existing_central_background_colored_opening':1,'existing_upper_lateral_tips':2,'authored_white_corner':1},6700:{'existing_soft_curved_gray_beard_color_field':1,'existing_central_background_colored_opening':1,'existing_upper_lateral_tips':2,'authored_white_corner':1},6722:{'existing_separated_upper_lateral_hairpaint_banks':2,'existing_verydim_short_browpaint_strokes':2,'authored_lowerleft_corner':1}}
descs={6697:'Keep ONE existing small curved softly painted muted golden-brown BEARD COLOR field, ONE central dark background-colored opening, TWO existing taller upper side tips. Preserve original tiny interleaving pale brown brushpaint and dim stippled wash at EXACT native phase/count/position/width/scale; do not add individual physical hairs, new locks or grain. Background stays the original flat matte RGB[64,35,20], present at14004 nativepixels: no new mottle/cloud/texture there. The actual whole native matrix includes the ONE tiny bottomleft RGBA255/255/255/255 pixel[0,127]; keep its exact normalized tiny extent, not a highlight in the beard.',6700:'Keep ONE existing small curved softly painted gray BEARD COLOR field, ONE central darker background-colored opening and TWO existing upper side tips, retaining their lower height and asymmetry in this original. Preserve the irregular softly interleaved pale gray sourcepaint as dim matte paint at EXACT native phase/count/width/scale, no new physical hairs/strand pattern/coarse cells/metallicgloss. Background stays the original flat matte RGB[87,83,80], present at13663 nativepixels; do not add new cloud/grain. Preserve the ONE original bottomleft RGBA255/255/255/255 pixel[0,127] at its exact tiny normalized extent.',6722:'Keep exactly TWO SEPARATED original upper/lateral grayblue softly painted HAIR COLOR banks with the SAME original central gap and original uneven contours. Keep exactly TWO original verydim short curved BROW COLOR strokes below the gap, at their actual original positions, small widths and faint bluishgray strengths. This is an original color-overlay bitmap, not a face: no new eyes/pupils/iris/anatomy/ears/teeth. Retain all existing irregular source brushpaint waves at SAME phase/count/width/scale, without photo fibers/individual hairs/new tufts/locks/curls/stipples. Keep the lower and central original flat RGB[62,68,71] background (12764 nativepixels), no grain/cloudwash there. Preserve the actual ONE tiny lowerleft nativepixel[0,127] and its exact sourceRGBA tint/alpha; not a white new catchlight.'}
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];lum=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['source_RGBA_RGB_A_NN_privately_inspected']=True
 r['source_only_reason']='Genuine source-color artwork pending exact native mark/count/material fidelity; current0call source-first audit honest previous source-only re-audit when listed, no family/type/human blanket ban.'
 if i==6692:
  assert (rgb.max(2)>0).sum()==1 and (a[127,0]==255).all()
  r['source_only_reason']='Individual ORIGINAL-ONLY recommendation: exact RGBblack at16383 nativepixels and ONE bottomleft RGBA255/255/255/255 pixel; original nontrivial fullalpha contains beardmask. Not constantRGBA. Actual TransformableFaceTextures row22/THMID/Heads color-mask retains original completeRGBA; no new color detail to generate. Root only decides structural disposition.'
 if i not in CALL:continue
 assert r['fresh_actual_dynamic_consumers'] and not r['fresh_actual_static_consumers']
 regions=[]
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);regions.append({'name':name,'bbox':b,'native_pixels_ref':{'source_matrix_key':str(i),'matrix_file_SHA256':r['native_matrix_ref']['file_SHA256'],'slice_native_xyxy':b},'mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'min_RGB':v[:,:,:3].min((0,1)).tolist(),'max_RGB':v[:,:,:3].max((0,1)).tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())],'native_peak_xy':[x0+int(x),y0+int(y)],'native_peak_RGBA':v[y,x].tolist()})
 cons.append({'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':list(o.size),'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':regions,'source_feature_counts':counts[i],'authored_lowerleft_corner_RGBA':a[127,0].tolist(),'count_qualification':'Observed broad source COLOR paint fields/openings/tips/browstrokes/corner only, not inferred physical strand anatomy. Every weakmark/native phase exact common fullRGBA matrix. Diagnosticbboxes not crop or registration.','native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_positive_weak_RGB_max_le5_pixel_count':int(((rgb.max(2)>0)&(rgb.max(2)<=5)).sum()),'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'source_description':descs[i],'actual_consumer':'Actual TransformableFaceTextures COLOR→THMID1→Heads dynamic source. Ordinary straightRGB, original fullA distinct from RGB; no static hair Model/photographic anatomy inference.'})
 r['source_only_reason']='FIRST sole builtin eligible after exact full nativeRGB/A/NN privateview, native count/weakphase/palette/flatbackground/corner and actual dynamicTHMID/history-release fullRGBA proof.'
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[6692]});save(f'source-check-{ST}.json',P);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Faithfully edit this exact original Silent Storm softly painted HEAD COLOR bitmap at higher resolution, retaining all of its original art.', 'Image1 is the edit target: EXACT ENTIRE original native128x128 storedRGB made opaque at its ORIGINAL resolution, no upscaling/grid/pixelguide. Preserve entire normalized original UV and ALL sourceRGB even where originalA0; original fullalpha restored separately downstream and only one global numerical brightness scalar applied. Ordinary straightRGB, no premultiplication. Keep the existing sourceblur and matte fine native paint scale, softly resolve same source brushpaint without sharpening.',descs[i],f'Exact original fullRGBA extrema {c["actual_RGBA_extrema"]}; original lowerleft nativepixelRGBA {c["authored_lowerleft_corner_RGBA"]}. Preserve original relative brightness/hue strengths of every weak local field/mark versus its peaks, not just mean brightness. Preserve background flatness. No added fibers/photo hair/pores/anatomy/newglints/mosaic/outlinedcells/etchedgrain/raisedrim/curls/coarse pigment/new stipples or grain; no conversion of the soft wash into physical texture.','Output ONLY same ENTIRE opaqueRGB squarecanvas at identical normalized sourceUV. No crop/whitespace/border/cutout/padding/fitting/zoom/recenter/autoBBox/repack/composite or new geometry. No new colors/lines/parts/text/glyph/symbol. DefaultfullsourceA restored separately.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Immutable Heads20 beforeproof12/3 possibleFIRST calls',[(c['id'],c['source_feature_counts'],c['authored_lowerleft_corner_RGBA'])for c in cons])
