from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='heads-fourteenth';CALL=[1126,3323,3324]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'));constraints=[]
reasons={1127:'Genuine static face diffuse with inverted identity/hair/ears/moustache fields; detailed identity/strand count proof deferred in this bounded scope, zero calls. Not blanket human exclusion.',1128:'Genuine skin/eyelash/upper-lower tooth atlas. Original tooth and thin eyelash count needs separate exact phase proof before call; zero calls, not blanket dental exclusion.',6691:'Actual dynamic TransformableEye THMID source. Almost erased iris/pupil soft wash is genuine paint; no clear complete eye structure to specify without invention, zero calls.',3322:'Actual diffuse brown hair with many intertwined curled locks; exact native lock phase/count not yet resolved, genuine pending zero calls.',5259:'Actual diffuse brown hair with intertwined fine strokes; exact lock phase/count remains pending, zero calls.',6772:'Actual alpha_test brown hair source with A255. Native lock-phase detail pending, zero calls.',6773:'Actual gray hair with mixed opaque/alpha_test material consumers and sourceA255; original fine lock detail pending, zero calls.',1897:'Genuine static inverted face/eye/teeth atlas with mixed sourceA. Exact teeth and identity detail proof deferred; zero calls, not absent-THMID technical exclusion.',2183:'Genuine static inverted face/eye/teeth atlas with mixed sourceA. Detailed original teeth/identity phases pending before a faithful call, zero calls.'}
boxes={1126:{'iris_pigment':[20,21,47,47],'dark_pupil':[29,30,37,39],'upper_tinted_iris_patch':[29,24,36,29],'lower_tinted_iris_patch':[30,38,35,42],'left_broad_pale_wash':[14,25,23,34],'right_broad_pale_wash':[42,24,52,35]},3323:{'upper_soft_hair_bank':[0,0,128,53],'middle_soft_hair_bank':[0,53,128,93],'lower_small_whorl':[25,91,102,119],'left_existing_polygonal_paint':[0,20,23,60],'right_existing_polygonal_paint':[105,20,128,61]},3324:{'whole_original_curled_hair_field':[0,0,128,128],'original_central_part_phase':[51,0,77,91]}}
for r in proof['source_checks']:
 i=r['id'];r['full_original_and_helper_privately_inspected']=True;r['source_only_reason']=reasons.get(i,'Whole native original+source-only helper privately inspected. Full native pigment phase/palette and broad source fields recorded BEFORE prompt; one FIRST builtin call planned. No generated/held source retry.')
 if i not in CALL:continue
 a=np.asarray(Image.open(B/f'original/{i}.png').convert('RGBA'));assert (a[:,:,3]==255).all();regions={}
 for n,b in boxes[i].items():
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1,:3];yy,xx=np.unravel_index(v.mean(2).argmax(),v.shape[:2]);regions[n]={'native_bbox':b,'exact_RGB_matrix':v.tolist(),'mean_RGB':v.mean((0,1)).tolist(),'max_RGB':v.max((0,1)).tolist(),'max_mean_source_xy':[x0+int(xx),y0+int(yy)],'max_mean_source_RGB':v[yy,xx].tolist()}
 lum=a[:,:,:3].mean(2);rowphase=[np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0].astype(int).tolist()for v in lum];rowphase=[[x+1 for x in xs]for xs in rowphase]
 colphase=[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T]
 c={'id':i,'source_RGBA_SHA256':hashlib.sha256(a.tobytes()).hexdigest(),'source_whole_RGBA_matrix':a.tolist(),'native_size':[a.shape[1],a.shape[0]],'native_RGB_extrema':[a[:,:,:3].min((0,1)).tolist(),a[:,:,:3].max((0,1)).tolist()],'sourceA_extrema':[255,255],'region_diagnostics':regions,'every_native_row_local_mean_RGB_maximum_x':rowphase,'every_native_column_local_mean_RGB_maximum_y':colphase,'phase_qualification':'All native per-row/per-column pigment maxima exact BEFORE prompt. These are bitmap pigment phase diagnostics, NOT invented physical lock counts. Numeric domains only; no crop, insertion or source artistic RGB repair.','source_feature_counts':{'iris':1,'pupil':1,'inside_iris_tinted_reflection_patches':2,'outside_iris_broad_pale_washes':2}if i==1126 else {'large_soft_hair_banks':2,'lower_small_whorl':1,'existing_thin_polygonal_paint_shapes':2}if i==3323 else {'complete_curled_painted_hair_field':1,'central_part':1,'individual_physical_lock_count':'Not interpreted from blurred native bitmap; preserve every exact original stroke/phase in full matrix, no new locks.'},'actual_binding':'Actual static Materials diffuse, not dynamic THMID eye layer. SourceA255 restored whole.'}
 constraints.append(c)
save(f'pattern-constraints-{ST}.json',constraints);save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
save(f'scope-{ST}.json',{'ids':[r['id']for r in proof['source_checks']],'call_ids':CALL,'source_only_ids':list(reasons),'prior_sourceonly_reaudit_allowed':True,'no_previous_generated_held_retry':True})
for c in constraints:
 i=c['id'];common=['Use case: precise-object-edit. Asset: faithful historical Silent Storm softly PAINTED COLOR diffuse bitmap, not a photo.','Input1 is exact entire native original RGBA. Input2 is identical whole original storedRGB nearest-neighbor enlargement, source-only with no crops/patches. Refine this exact whole source bitmap with restrained fine painted detail only. Preserve full normalized UV, original pigment positions/phase/scale, broad soft blur, muted source palette, weak local relationships and every existing shape. The original complete alpha will be restored and brightness corrected by one scalar only.']
 if i==1126:
  desc='Keep ONE original round iris and ONE dark pupil at their exact native source footprints. Preserve TWO tinted patches INSIDE the iris (upper native[29,24,36,29), lower[30,38,35,42)) and TWO broad pale washes OUTSIDE the iris (left[14,25,23,34), right[42,24,52,35)). The broad outside washes are original diffuse paint, not extra sharp catchlights. Keep all original gray-brown eyelid/sclera washes and the subtle dark lower brown shadow. No new anatomy, face, iris ring, radial fibers, veins, crystalline/mosaic cells, pores or new glossy reflections. Keep tinted patches soft/dim, not white shine.'
 elif i==3323:
  desc='Keep the original DARK softly painted hair atlas: TWO broad curved banks (upper/middle) and ONE smaller horizontal whorl at the bottom. Preserve every original softly brushed strand direction and native phase in place, without adding locks or photoreal fibers. Keep exactly TWO existing thin pale polygonal PAINT shapes, one near each side native x0..22 and105..127, y20..60; trace the SAME original line vertices and segments without adding or identifying clips, hardware or wires. Keep original black regions and soft near-black pigment; do not brighten them into gray fill. No new strands, regular comb-ribs, gloss, reflective fiber ribbons or sharp outlines.'
 else:
  desc='Keep the ONE complete brown/golden softly painted curled hair field with ONE original central part. Exactly retain the source winding strokes, small curl shapes, their native positions/count/phase, broad paired pigment banks and uneven dark outer border. This is the SAME source bitmap, not a redesigned hairstyle or photograph. Do not add new locks or curls, regularize the original irregular pigment into uniform waves, replace it with straight gray fill, sharpen it into radial fibers, enlarge the light bands or make glossy metal-like ribbons. Preserve muted brown local washes and fine painterly softness.'
 tail='Output ENTIRE square source canvas edge-to-edge with precisely the same normalized UV. No crop, BBox, fitting, zoom, padding, margins, transparent cutout, registration, artistic RGB repairs, new text/symbols/parts, weave/grain, photonoise or invented relief. Keep source relative brightness and soft edges; no locally strengthened white highlights.'
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(common+[desc,tail]).encode('utf-8'))
print('Saved whole original BEFORE-call pattern/palette proof and exact CRLF prompts:',CALL)
