from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='weapons-sixteenth';CALL=[1945,1951,2429]
read=lambda p:json.loads(p.read_text(encoding='utf8'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];C=[];R={}
boxes={1945: [('left warmbrown woodpaint and broad upper shadow', [0, 0, 76, 64]), ('upper-middle darkgray painted field and cutout', [76, 0, 141, 34]), ('upper-right gray pale fields and original narrow source marks', [159, 0, 256, 34]), ('central brownpaint strip with old dim dark dashes', [72, 30, 217, 43]), ('lower-middle framed gray field and tiny fine cadence', [72, 39, 169, 64]), ('lower-right grayfield with existing narrow pale strips', [210, 34, 256, 64])], 1951: [('left broad original warmbrown stock paint', [0, 0, 126, 64]), ('upper-middle original gray tube-colored paint', [79, 0, 207, 32]), ('upper-middle lower darkpaint cutout and original light marks', [115, 25, 194, 41]), ('lower middle brown field and dim horizontal source bands', [115, 42, 211, 64]), ('right original gray vertical frame and fine edge strips', [207, 0, 256, 64])], 2429: [('upper-left original olive panels and small softshade', [0, 0, 83, 39]), ('upper-middle original brown grip field and tiny dim marks', [84, 0, 151, 38]), ('upper-right original gray pointed tube paint', [143, 0, 256, 21]), ('middle-right original brown grip panel and dark dotwash', [167, 20, 214, 40]), ('right small original olive paint fields', [215, 20, 256, 40]), ('lower original olive horizontal painted tube with fine pale seams', [0, 40, 256, 64])]}
descriptions={1945: 'Preserve the SAME entire rifle woodbrown/gray atlas. Keep broad original warmbrown left stock paint, its upper dark wash, original uppermiddle darkgray panel/cutout, existing upperright gray/pale bands and thin shaded marks, central brown strip with its original weak dark dashes, lower-middle gray framed field and its original tiny fine gray cadences, lower-right gray rectangular field with its old tiny pale edge ticks. Preserve weak source phase in all dark dashes and tiny gray ticks; none becomes a label, knob, bead or new physical assembly. The old small gray/dark mark in left brown lower field around native x40..56,y48..63 stays the same indistinct sourcepaint wash. Uppergray and wood remain dim fine hand-painted shading, never hard engraved or photographed grain.', 1951: 'Preserve the SAME entire source submachinegun woodbrown/gray atlas. Keep ONE broad left brown stock paint with its original irregular broad upperboundary/softshadow, ONE original upper-middle horizontal gray tube paint with its old circular-gray left edge and existing dim long inset shading, original dark lowergray/cutout field and tiny source spots, lower middle brown band with its original weak horizontal dark/pale strokes, and right vertical gray painted frame plus exact old thin edge strips. Small round pale pigment near native x91,y11 and small patches above/around the cutout remain soft original paint at their exact native positions, not newly detailed screws. Do not regularize the old tiny right edge cadence. Gray is soft matte steel-colored paint, woodbrown is dim old brushpaint without woodrings/knots/photo grain.', 2429: 'Preserve the SAME entire olive/brown/gray bazooka painted atlas. Keep original upperleft olive rectangles and small soft-shadow fields, original uppermiddle broad brown grip paint field and its tiny weak pale/dark spots, existing upperright pointed gray horizontal tube paint, original second smaller brown grip field at middle-right with its weak old dark dots, the original small right olive panels, and the complete lower horizontal olive tube paint with its original pale seam positions and tiny subtle paint ticks. Every existing dim dot/fleck remains sourcepaint at the same count/phase; no new fasteners, engraved symbols or extra hardware. Both brown fields retain the original soft mottled brown brushwash, lower olive field retains original broad dim gradients and thin original pale seams. Gray pointed field is source painted gray silhouette, not a newly modeled projectile. Preserve black authored support and the true upperleft sourceA0 cutout independently; do not call all black transparent.'}
pending={1965: 'Genuine soft brown/gray Suomi atlas, circular drumlike paint domain and tiny internal marks; sourcefullview done but exact tiny radial phase needs further qualification, zero calls.', 2430: 'Genuine gray/olive/brown launcher atlas with several small shaded fields and geometric endpaint; fullsource viewed, exact weak contours/cadence not yet fully qualified, zero calls.', 4594: 'Exactly constant fullRGBA green storedRGB/A0 reflection-capable source; freshactualconsumer purpose qualification recorded separately before original-only recommendation, zero calls. A0 usefulRGB is not treated as empty.', 5185: 'Genuine gray MG34 crash painted atlas with repeated old dark dot pattern and long fine gray strips; fullsource viewed, exact pattern/terminalphase qualification remains pending, zero calls.', 1930: 'Honest source-only0call re-audit of full brown/gray rifle atlas from Weapons14; original tiny gray field cadence needs further qualification, no raw/call/held/accepted donor.', 1933: 'Honest source-only0call re-audit of full brown/gray rifle atlas from Weapons15; tiny original fine cadence/pigment pending before any eventual FIRST call.', 1934: 'Honest source-only0call re-audit from Weapons15, gray/wood complete rifle atlas; tiny source part contour/cadence not yet fully qualified, genuine pending.', 1935: 'Honest source-only0call re-audit from Weapons15, warmer brown/gray rifle atlas; fullsource viewed, exact tiny original lines/marks need further proof, no technical ban.', 1969: 'Honest source-only0call re-audit from Weapons14, genuine brown/gray128x64 Thompson drum atlas; tiny radial/strip source marks pending exact qualification, no call.'}
audition=read(B/f'before-native-count-audition-{ST}.json')
for p in P:
 i=p['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];l=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix']
 p['source_RGBA_RGB_A_NN_privately_inspected']=True;p['source_RGB_whole_survey_privately_viewed']=True;p['source_only_reason']=pending.get(i,'First sole eligible weapon painted-atlas candidate after exact full source/weakcount/phase/material/sourceA and actual typed/historical-release proof. No previousraw/call/held/accepted/sameRGBA donor.')
 if i not in CALL:continue
 assert p['fresh_actual_static_consumers']and not p['fresh_actual_dynamic_consumers'];assert p['material_evidence']['actual_source_native_type']=='Ordinary'
 helper=B/f'generated/{i}-{ST}-source-rgb-native.png'
 if o.width/o.height>3:
  helper=B/f'generated/{i}-{ST}-source-rgb-affine3x1.png';guide=o.convert('RGB').resize((384,128),Image.Resampling.NEAREST);assert guide.resize(o.size,Image.Resampling.NEAREST).tobytes()==o.convert('RGB').tobytes();guide.save(helper)
  p['helper_recipe'].update({'operations':'ENTIRE exact original nativeRGB256x64→ENTIRE384x128 using NEAREST source-only affine4:1→3:1. Whole normalized canvas only, no crop/padding/BBox/islandfit/recenter/artRGB. All original pixelRGB values retained, exact NEAREST inverse→native RGB roundtrip verified. Private originalNN phase separately, guide coordinates differ from originalnative.', 'helper_size':[384,128],'helper_bbox':[0,0,384,128],'source_native_to_helper_affine_xy_scale':[1.5,2.0],'source_RGB_NEAREST_guide_inverse_native_byteexact':True,'output':helper.relative_to(B.parents[2]).as_posix(),'inverse':'ENTIRE service raw RGB-FIRST LANCZOS→original4x1024x256, inverse whole guide aspect. Complete originalA independent4xLanczos/defaultpad/oneglobalscalar/Ordinary straightRGB. No artistRGB/registration/crop/BBox/padding/optout.'})
 rt=np.array(o.convert('RGB').resize((o.width*4,o.height*4),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS));R[str(i)]={'id':i,'source_RGB_LANCZOS4x_then_native_RGB_matrix':rt.tolist(),'sourceA_independent':True,'no_PIL_RGBA_implicitpremul':True};ds=[]
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);ds.append({'name':name,'bbox':b,'native_pixels_ref':{'matrix_ref':p['native_matrix_ref'],'source_slice_native_xyxy':b},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())],'source_peak_xy':[x0+int(x),y0+int(y)],'source_peak_RGBA':v[y,x].tolist()})
 fields={name:1 for name,b in boxes[i]};fields['whole_source_canvas']=1
 special={}
 if i==1967:
  profile=next(r for r in audition if r['id']==i);row61=next(r for r in profile['profiles']if r['fixed']==61);separate=[x for x in row61['literal_maxima']if 29<=x<=53];assert separate==list(range(29,54,2))and len(separate)==13;assert 55 in row61['literal_maxima']
  fields.update({'lower_separate_pale_column_strokes':13,'existing_terminal_gray_edge_column':1});special={'separate_source_stroke_centers_native_x':separate,'source_native_y_rows':[61,62],'native_pitch':2,'terminal_gray_border_native_x':55,'terminal_border_not_detached_new_tooth':True,'qualification':'13 separate literal pale strokes plus existing graypanel terminal edge; row61 has14 mathematical maxima counting edge, NOT fourteen standalone hardwareteeth. Source fullRGBA/NN/private visually checked before prompt.'}
 if i==1931:fields['lower_right_pale_rectangular_panels']=2
 masks={'sourceA0_count':int((a[:,:,3]==0).sum()),'sourceA255_count':int((a[:,:,3]==255).sum()),'source_blackRGB_A255_count':int(((rgb.max(2)==0)&(a[:,:,3]==255)).sum()),'source_A0_positiveRGB_count':int(((rgb.max(2)>0)&(a[:,:,3]==0)).sum())}
 c={'id':i,'before_prompt':True,'native_size':list(o.size),'native_matrix_ref':p['native_matrix_ref'],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':ds,'source_feature_counts':fields,'prompt_feature_counts':dict(fields),'assert_prompt_constraints_equal_source':True,'source_fullA_black_support_masks':masks,'native_repeat_count_phase_evidence':next(r for r in audition if r['id']==i),'special_exact_source_evidence':special,'count_qualification':'Known broad paint domains and explicit literal source cadence only, not guessed gun-component or screw count. Full original matrices retain every weak source spot/pigment/alpha. Diagnostic rectangles are read-only, not crop/register/fit/regiongain.','source_description':descriptions[i]};assert c['source_feature_counts']==c['prompt_feature_counts'];C.append(c)
save(f'natural-RGB-roundtrip-{ST}.json',{'recipe':'ENTIRE originalRGB first Lanczos4x then native, originalA independent. Naturalcodec diagnostic only/no artistrepair.','sources':R})
for c in C:c['natural_RGB_roundtrip_ref']={'path':f'assets/terrain-hd/expanded/natural-RGB-roundtrip-{ST}.json','file_SHA256':sha(B/f'natural-RGB-roundtrip-{ST}.json'),'source_key':str(c['id'])}
save(f'pattern-constraints-{ST}.json',C);save(f'scope-{ST}.json',{'selected_ids':[p['id']for p in P],'unique_native_RGBA_count':len({p['source_rgba_sha256']for p in P}),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'genuine_pending_uncalled_ids':[p['id']for p in P if p['id']not in CALL and p['id']!=4594],'original_only_recommendation_candidate_ids':[4594]});save(f'source-check-{ST}.json',P);before=B/f'source-check-{ST}-before-call.json';assert not before.exists();shutil.copyfile(B/f'source-check-{ST}.json',before)
for c in C:
 i=c['id'];w,h=c['native_size'];affine=w/h>3
 ref=f'Image1 is the SAME entire native original storedRGB{w}x{h}'+(' mapped by whole-source-only NEAREST affine to384x128 (3:1). Original native x/y counts in this prompt refer to the original256x64; helper x/y scales are1.5 and2.0. This is the same normalized wholeUV canvas, NOT cropped, repacked or new material. Original full nativeRGB pixels roundtrip from this guide exactly.' if affine else' madeopaque at originalresolution, no enlarged NN blockguide.')
 parts=['Use case: precise-object-edit. Asset type: original hand-painted weapon diffuse UV texture. Edit the SAME entire source bitmap into a faithful finer painted HD texture. Keep sourceUV, original native paintscale/blur, layout, materials, palette and exact original marks. Flat complete texture atlas, not a photographic gun or newly assembled physical object.',ref,'Source has mixed alpha: ONLY original explicit alpha0 cutout stays a cutout after complete originalalpha restoration downstream. Other black RGB areas are opaque authored sourcepaint/support with alpha255 and must stay black, never treated as a transparent or cropped border. Reference is opaque RGB to preserve all original stored pigment. Numerical brightness/sourceA are restored separately; do not remove or lighten black support.',descriptions[i],f'Confirmed source-painted-domain constraints, not guessed physical component counts: {json.dumps(c["prompt_feature_counts"],ensure_ascii=False)}. Preserve original pale/dim hierarchy and every small old source mark. Strongest native source RGBA{c["native_source_max_mean_RGBA"]} at original native{c["native_source_max_mean_RGB_xy"]}; all source alpha/paint boundaries remain at original normalizedUV. Uncertain tiny paint marks remain equally indistinct soft paint, never interpreted as new letter, screw, rivet, bead, button, hole or raised plate.', 'HD improvement ONLY finer original handpaint transitions and understated native pigment. Preserve existing wood/metal paint palette and sourceblur scale. NO photographic woodgrain/metal abrasion/pores/coarsegrain/new scratches/woodrings/knots/checkergrid/engravedgrip/threadweave/polished reflective machining/new hardware/raisedrelief/glossybevel/new whiteglints/new rivets/straps/screws/regularized geometry/stronger outlines. Tiny seams/stripes remain exact old number/spacing/phase/localsoftcontrast.',('Output ONLY the SAME ENTIRE opaqueRGB 3:1 helper canvas; original4:1 normalized UV is represented by the whole affine and will be inverted to1024x256 after generation. Keep every reference field at the same normalized coordinate; do not change framing or island positions.' if affine else'Output ONLY the SAME ENTIRE opaqueRGB 2:1 canvas. Keep every original reference field at the same normalized position.')+' NO padding/letterbox/whitemargins/crop/zoom/recenter/registration/UVfitting/UVrepack/BBox/new parts/photo. Keep entire source A/black support/material/nativepaintscale/blur.']
 arg='\n\n'.join(parts);assert not arg.endswith('\n');pp=B/f'generated/{i}-prompt.txt';assert not pp.exists();pp.write_bytes(arg.encode('utf8'))
print('Weapons16 BEFORE12/max3FIRST',CALL,'native counts asserted beforeprompt; helpers whole only')
