from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='effects-twenty-eighth';CALL=[4089,4092]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];survey={r['id']:r for r in read(B/f'source-count-survey-{ST}.json')};cons=[];groups={}
boxes={4089:[('original dim uppergraybrown stroke',[10,7,15,14]),('original grayviolet middle thinstripe',[12,12,16,19]),('original stronger lower main graypaint',[12,18,16,25]),('original dimright separate paintedfield',[17,21,24,28])],4092:[('original upperleft dimredgray wash',[9,2,16,12]),('original upperright graybrown paint',[16,2,22,13]),('original dark middle pigmentnotch',[15,10,18,16]),('original warmer lower paintedwash',[10,13,22,24])]}
descs={4089:'EXACT original muted gray/brown PAINTED COLOR source with TWO literal positiveRGB bitmap domains. Original thin slightly irregular upright mainpaint (nativepositivepixel extent[10,7,22,25]) has dimuppergraybrown shade, original gray-violet middle tone and stronger lowergray patch, sourcebrightest native[13,20] RGB129/114/117. Original SEPARATE DIM lower-right softly shaded paintfield (extent[17,21,24,28], actualmax49/42/44) stays exactly original faintstrength/position/size/phase, not removed or made a brighter newpart. Retain all originalverydim connecting-looking nativebits/blackgaps asactually referenced; counts are paintedbitmap domains, not physical rods/wires/particleparts. Do not straighten or turn mainpaint into shinyrod/metalhighlight or invent new fragments.',4092:'EXACT original ONE compact asymmetric upright soft brown-gray PAINTED COLOR footprint (positivepixel extent[9,2,22,24]). Keep original dimredgray upper-left projection, original graybrown upper-right projection, existing black upper notch/darkmiddle pigment gap, original warmer lower softpaint and lowerdimtaper. Original brightest meanpaint native[19,12] RGB119/80/73, not white/shinymetal. Preserve exact source irregular projectionwidths/positions/asymmetry and softwashes. Darkpigment notch stays originalsoft shade only, not newly outlined physicalhole/bevel/ring. Do not interpret this as hardware, brokenplate, rock, leaf, armor or U-shaped mechanism.'}
for r in P:
 i=r['id'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['previous_source_only_views']=[p.relative_to(ROOT).as_posix()for p in sorted(B.rglob(f'{i}-*source*.png'))if ST not in p.as_posix()][:12];r['view_novelty']='Honest fresh readonly source-only re-audit of prior0call views. Accepted/raw/call/held/refusal/generated/exactRGBA guards separate, no never-viewed fiction.'
 reason='Genuine complex painted sourcecolor; strict weakpixel/count/localshade preservation unclear for forced boundedcall, genuinepending0calls. Actual compact fullnative matrices establish everypixel, not a technical/family ban.'
 if i in [5391,5392]:reason='Individually wholeview smooth verticalbluegray tonefield; no independently visible finepaint detail to synthesize while keeping original softblur. Genuinepending0calls, not analytic/technical solely fromsimpleappearance/name. Fullnative matrix/common actualtyped records retained.'
 if i==2627:reason='Genuine sparsebluegray originalpaint, A0 TransparentAdd usefulRGB notempty. Manyfaintbits/thinstreaks require faithful localrelative strength, source-only genuinepending0calls, no familyban.'
 if i==4101:reason='Genuine tinyverydim separated graybrown paintstreaks; would risk strengthening/dropping faintbits despite exactpixel coordinates, genuinepending0calls.'
 if i==2523:reason='Genuine complex brown/violet paintedfield with numerous narrowrays/tinyweakflecks. Weakfleck hierarchy/formphase not suitable for forcedcall inthisscope, genuinepending0calls.'
 if i==2575:reason='Genuine softly painted brown/orange field with complex interior brightknots/darkgaps and sixisolated RGB1 pixels. No forced complexcall, genuinepending0calls; not A0-empty/technical.'
 r['source_only_reason']=reason
 if i not in CALL:continue
 o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];rgb=a[:,:,:3];l=rgb.mean(2);y,x=np.unravel_index(l.argmax(),l.shape);expected={4089:([13,20],[129,114,117,249]),4092:([19,12],[119,80,73,255])};assert [int(x),int(y)]==expected[i][0]and a[y,x].tolist()==expected[i][1]
 zero=rgb.max(2)==0;weak=(rgb.max(2)>0)&(rgb.max(2)<=5);domains=survey[i]['native_positive_RGB_8connected_domains'];assert len(domains)==(2 if i==4089 else 1)
 c={'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':list(o.size),'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':[int(x),int(y)],'native_source_max_mean_RGBA':a[y,x].tolist(),'source_feature_counts':{'literal_positive_RGB_8connected_bitmap_domains':len(domains),'domains':domains,'qualification':'Exact bitmap topology only, NOT physicalparticle/metalparts count fromRGBA mask. Whole sourceRGBA matrix stored once/read by sourcekey+fileSHA. Allzeroweak pixels included; no inferred hardware.'},'native_zero_RGB_pixel_count':int(zero.sum()),'native_positive_weak_RGB_max_le5_pixel_count':int(weak.sum()),'complete_zero_and_weak_pixel_evidence':'Derive everynative zero/weak xy/RGBA from immutable referenced matrix: RGBmax==0, or0<RGBmax<=5. Matrix is EXACT decoded entire original and contains originalA separately, not an artthreshold guide. Avoidduplicating matrix/raster arrays perconsumer.', 'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l.T],'source_description':descs[i],'source_domains':[],'semantic_qualification':'Allregionboxes numericdiagnostics only, never crop/referencefitting/BBox/composite/artistRGB. FulloriginalA/UV/sourceblur/nativepatternscale retained; unknown absentdefinitions explicit.'}
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=rgb[y0:y1,x0:x1];aa=a[y0:y1,x0:x1,3];c['source_domains'].append({'name':name,'bbox':b,'native_pixels_ref':{'source_matrix_key':str(i),'matrix_file_SHA256':r['native_matrix_ref']['file_SHA256'],'slice_native_xyxy':b},'mean_RGB':v.mean((0,1)).tolist(),'max_RGB':v.max((0,1)).tolist(),'sourceA_extrema':[int(aa.min()),int(aa.max())],'original_zero_RGB_pixels':int((v.max(2)==0).sum())})
 cons.append(c);r['source_only_reason']='One FIRST faithful edit eligible after fullactualnative weakzero/count/palette/maxphase evidence and originalRGB/A/NN views; no sourcecrop/physicalhardware inference.';r['full_original_RGBA_RGB_A_NN_privately_inspected_BEFOREtool']=True
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL]});save(f'source-check-{ST}.json',P);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Faithfully edit the existing historical Silent Storm SOFT PAINTED COLOR bitmap at higher resolution; do not render new realistic objects/effectparticles/hardware.', 'Image1 is EXACT ENTIRE original native storedRGB solely wholecanvas NEAREST32x32→512x512 madeopaque. Preserve complete normalizedUV/positions/width/shapes/count/nativephase/patternscale/sourceSOFTBLUR/palette/relativeweak strengths, every original pixelpaintfield/blackgap. Nearestblock sampling proves originalUV only, NOT squaredcells/grid/mosaic. Render the same original smooth subdued mattewash without inventing physicalgrain/stipples/furryedge/coarsecloudcells/mottle. Fulloriginalalpha restored independently, brightness only one globalnumerical scalar. No crop/padding/frame/recenter/BBox/fitting/repack/zoom.',descs[i],f'Actual original nativeRGBA extrema are {c["actual_RGBA_extrema"]}; maxmean nativexy{c["native_source_max_mean_RGB_xy"]} is exact RGBA{c["native_source_max_mean_RGBA"]}. Keep ORIGINAL dimgray/brown/grayviolet hierarchy and nativepeak strengths, not manual255/white. Do not strengthen original dimfield, lighten blackgaps or make newreflectiveedges. OriginalTransparent A0..255 stays separately source-restored; guideopaque RGB is originalusefulpaint.','Add only finer softly blended depiction of EXISTING paint. No physicalshine/glints/whiteplates/rims/bevels/raisedhardware/rust/etchedscratches/rods/wires/knurl/bolts/rocks/rings/newholes/fibers/photo texture/cloudgranules/stipples/furryedge/coarsemottle or addedfragments. Do not make new sparks/rays/tongues/curls, remove weak originalpaintfield or regularize originalasymmetry. Keep sourceblur/plainmatte material. No symbols/text/logos.', 'Output ONLY ENTIRE SAME opaqueRGB square canvas with exact normalizedUV/sourcepaint scale/count/tonalphase/material/sourceA downstream. No whitespace/cutout/crop/zoom/framing/fitting/BBox/UVrepacking/composites or inventedparts.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Immutable compact BEFORE12 sources/2FIRST count weakzero proof',CALL)
