from pathlib import Path
import json,shutil,hashlib
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='clothing-forty-eighth';CALL=[4425]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];cons=[];groups={};rounds={}
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];lum=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['source_RGBA_RGB_A_NN_privately_inspected']=True
 r['source_only_reason']='Genuine actual Materials→TemplateID→Models/Heads diffuseCOLOR source. FullstoredRGB/A/nativeexpression/weakphase/sourceblur preserved; source-only0call pending exactidentity/detail/material fidelity, not technical from Face/Head name. Honest allraw/call/held/accepted/exactRGBA guards pass; native source facepaint not automatically reconstructed into anatomy/photoportrait.'
 if i==4449:r['source_only_reason']='Genuine actual staticMaterials→TemplateID→Models coloredleaf/camouflage/maskedface diffuseUV with TWO actualeye alpha holes andcomplexoriginalleafpaint, fullRGB/variableA0/255. Exactsmall leafpaintcount/roles notfullyresolved here, genuinepending0call; not technical by Scout/name/mask/A or falseoriginalpurpose recommendation.'
 if i==4425:r['source_only_reason']='Individual actualstatic color diffuse source has186 distinctRGB values, nearflatwarmtanpaint plus TWO upperbandedbrown/lightpatches and a weaklefttonalmark, A255. FullRGBA notconstant and no provenanalyticpurpose. Genuinepending0call preservingweakpaint/nativephase ratherthan technical/name/family/nearflatness ban or inventedmissing face.'
 if i not in CALL:continue
 assert o.size==(128,128)and r['material_evidence']['actual_source_native_type']=='Ordinary'and o.getchannel('A').getextrema()==(255,255)and r['fresh_actual_static_consumers'];s=o.convert('RGB');rnd=np.array(s.resize((512,512),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS));rounds[str(i)]={'id':i,'source_size':[128,128],'source_RGB_LANCZOS4x_then_native_RGB_matrix':rnd.tolist(),'recipe':'Whole nativeRGB FIRST LANCZOS4x and entire native inverse independently originalA; no implicit PILRGBApremul/unpremultiply/rotation/crop/artistRGB.'}
 boxes=[('ONE original large nearflat warmbrown diffusefield',[0,28,128,128]),('ONE original darker top bandedpaintpatch',[58,0,83,24]),('ONE original lighter top bandedpaintpatch',[96,0,123,27]),('ONE original weakleftvertical pale pigmentdab',[0,6,13,28])]
 domains=[]
 for name,b in boxes:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);domains.append({'name':name,'bbox':b,'native_pixels_ref':{'matrix_ref':r['native_matrix_ref'],'slice_native_xyxy':b},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_std_RGB':v[:,:,:3].std((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'source_peak_xy':[x0+int(x),y0+int(y)],'source_peak_RGBA':v[y,x].tolist(),'sourceA_extrema':[255,255]})
 patterns=[]
 for axis,coord,z0,z1 in [('column',65,1,25),('column',108,1,25),('column',5,1,28),('row',8,48,123),('row',14,48,123),('row',64,1,127),('row',120,1,127)]:
  v=lum[coord]if axis=='row'else lum[:,coord];xs=[z for z in range(z0,z1)if v[z]>v[z-1]and v[z]>=v[z+1]];patterns.append({'axis':axis,'native_fixed_coordinate':coord,'native_axis_interval':[z0,z1],'literal_paintshade_maximum_axis_coordinates':xs,'literal_count':len(xs),'native_successive_pitch':[b-a for a,b in zip(xs,xs[1:])],'qualification':'Literal weakpigment/nativephase profiles only, not numbers of physicalhair/teeth/fingers/anatomicalparts or acceptance thresholds.'})
 description='Image1 is ENTIRE original128square warmbrown FLATPAINT diffuseUV artwork, NOT a facephoto or portrait. The sourcehasNOvisibleface/ears/eyes/mouth/hair/body andNONE maybe invented despite resourceheadname. Keep ONE dominant nearflat matte warmbrown field RGB162/106/71 overmostcanvas (14236 exactnativepixels); no grain/no surface/lighting/backgroundgradient/newmottle. Keep ONLY the existing THREE localpaint features: TWO faintsmall horizontalbandedpatches near TOP (darker x58..82,y0..23; lighterx96..122,y0..26) andONE weakpaleverticaldab atLEFT x0..12,y6..27. Keep EXACT existing softedges, sourcefilteredblur, horizontalbandstroke count/pitch/phase andweakpigmentstrength; no new horizontalstrokes/rectangles/buttons/metal/grids/numbers/glyphs. Native darkbandcolumn65 literalshade maxima y7,10,14,18 andlightbandcolumn108 y4,7,10,14,24; these exactsourcepaintprofiles are NOT physicalfingers/teeth/anatomy. Preserveoriginalweakleftdab insteadof addingnewstripe or turningitwhite. No new forms, no roughpaper/fibers/weave/photo pores/anatomy/skin lighting/relief/bevel/glare/rust/etchedlines/hair locks or decorativepattern; entireclearflatfield staysflatpaint, NO artisticdetail beneath sourceblur.'
 cons.append({'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':[128,128],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':{'dominant_nearflatpaintfield':1,'existing_top_bandedpaintpatches':2,'weakleftverticalpigmentdab':1,'visibleface_or_hair_parts':0},'native_repeat_count_phase_evidence':patterns,'native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_sourceA0_pixel_count':0,'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'source_description':description,'qualification':'Literal nativeCOLOR painting features, not anatomyanalysis/physicalhair/fingers/teeth counts. Descriptiveoverlappingbboxes not crop/repack. ExactweaknativeRGBA/phase/blur/palette beforetool, source orientation fixed wholecanvas without rotation/registration.'})
 r['source_only_reason']='EligibleFIRST originalnearflatcolorpaint with TWO topbandedpatches/ONEweakleftdab, fullnative exactRGBA/historyrelease/POT/TypeOrdinaryA255/actualMaterial2721→Template1760→Models4585.Material1, nativeopaqueRGB reference +privateNN counts. SourceRGB186distinct/weakexistingpigment notconstantRGBA/technicalbyname. No invisibleface reconstruction/grain/materialreinterpretation; sourceblur/nativephase/fullUV preserved.'
rp=B/f'natural-RGB-roundtrip-{ST}.json';save(rp.name,{'sources':rounds,'before_call':True})
for c in cons:c['natural_RGB_roundtrip_ref']={'path':rp.relative_to(ROOT).as_posix(),'file_SHA256':sha(rp),'source_key':str(c['id'])}
save(f'pattern-constraints-{ST}.json',cons);save(f'original-only-proof-{ST}.json',[]);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[],'all_selected_outside_previousClothing1to47':True,'pending_exactRGBA_alias_qualification':'Selected12ID exactpayload groups enumerated fromnativeSHA. Any pendingonly sameRGBA groups are NOTaccepted/generateddonors; sole4425 FIRSTcall. Allaccepted/generatedexactRGBA excluded.'});save(f'source-check-{ST}.json',P);assert not(B/f'source-check-{ST}-before-call.json').exists();shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Asset type: softlyfiltered painted diffuse COLOR UV map. Refine SAME existing tiny paintedmarks while strictly retaining nativeblur/count/phase/scale andnearflatpaint.', 'Image1 edit target: ENTIRE nativeoriginal128square storedRGBmadeopaque atnative resolution, not NN reference. ActualMaterial2721 Template1760 Models4585.Material1 colorasset. Ordinary straightRGB/sourceA255 separately restored; no premise of invisibleface/anatomy fromfilename.', c['source_description'], f'ExactnativeRGBA extrema {c["actual_RGBA_extrema"]}; oldstrongestRGBA {c["native_source_max_mean_RGBA"]} at{c["native_source_max_mean_RGB_xy"]}. Keep those SAME olddim patches, sameoriginalwarmbrown/palegraybrown palette and SMALLpeak. Do NOT brighten towhite255 or increaseoldmarkstrength. DominantbackgroundRGB162/106/71 remains flatuniformpaint with onlytheoriginalweakcompressedvariations, NO addedgrain/dither/coarsecells/tonalclouds.', 'Output SAME ENTIRE SQUARE opaqueRGB UVcanvas at higherresolution. Preserve exact normalizedUVpositions/relativeareas/sourceblur/nativepatternscale; no crop/zoom/rotate/recenter/padding/whitespace/border/BBox/islandmoves/fitting. Do NOT create a face or limbs/hair/eyes/teeth/anatomy/physicalmaterial/lights/text/glyphs/brushcurl/texturegrain. Onlytheexisting TWObandedpaintpatches plusONEweakleftdab ontheoriginalnearflatwarmfield.']
 arg='\r\n\r\n'.join(parts);p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes((arg+'\n').encode('utf-8'));(B/f'generated/{i}-{ST}-exact-call-argument.txt').write_bytes(arg.encode('utf-8'))
print('Cl48 immutable12ID/uniquegroups/ONEprospectiveFIRST',[(c['id'],c['native_source_max_mean_RGBA'],c['native_source_max_mean_RGB_xy'])for c in cons])
