from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='clothing-forty-third';CALL=[6813,6814,6817]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];C=[];R={}
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];l=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];assert r['fresh_actual_static_consumers']and not r['fresh_actual_dynamic_consumers'];r['source_RGBA_RGB_A_NN_privately_inspected']=True
 r['source_only_reason']='Genuine actual clothing/cloth accessory diffuse Material→TemplateID→Models source COLOR. FulloriginalRGB/A/NN/historyrelease exactparity/privatewhole view, honest old0call re-audit. Tinyemblems/uncertainmarks/chainfasteners/camopattern exact nativecounts require bounded faithfulreview, not guessed letters/hardware. Genuinepending0call, not blanket material/type/family exclusion.'
 if i not in CALL:continue
 assert o.size==(256,128)and r['material_evidence']['actual_source_native_type']=='Ordinary'and(a[:,:,3]==255).all()
 rt=np.array(o.convert('RGB').resize((1024,512),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS));R[str(i)]={'id':i,'source_RGB_LANCZOS4x_then_native_RGB_matrix':rt.tolist(),'sourceA_independent':True,'no_RGBA_implicitpremul':True};middle='lightgray'if i==6817 else'khakigreen';warm='darkwarmbrown'if i==6814 else'warmochrebrown'
 boxes=[('ONE subdued darkgray leftpaintfield',[0,0,95,128]),(f'ONE subdued {middle} middlewash',[95,0,186,100]),(f'ONE smooth {warm} rightupperplane',[186,0,256,83]),('TWO original dimbrown ovalpaintmarks',[29,107,70,127]),('ONE lowercenter graycurvedpaint region',[95,100,193,128]),('originalrightlower grayfields',[193,83,256,128])];domains=[]
 for name,b in boxes:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);domains.append({'name':name,'bbox':b,'native_pixels_ref':{'matrix_ref':r['native_matrix_ref'],'slice_xyxy':b},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'source_peak_xy':[x0+int(x),y0+int(y)],'source_peak_RGBA':v[y,x].tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())]})
 d=f'Keep ONE original subdued darkgrayleftpaintfield, ONE original {middle} middlefield with original softbroadfoldwash, ONE smooth {warm} rightupperplane, original lowercenter graycurvedpaint region and rightlowergrayfields at SAME UV. Middlefield native x95..185,y0..99, warmrightplane x186..255,y0..82. TWO original little dimbrown ovalpaintmarks atnative x29..69,y107..126 stay EXACTLY TWO same shape/size/localstrength, not brightercircularhardware or decoratedeyes. Preserve sourcefaintleftgray and middle{middle} wash paths, original weak horizontal middletonaltransition at y33 and every tiny original edgepaint. Broadwash stays softbrushpaint, never new folds/weave/diagonalfibers/granulatedmaterial. Rightupperwarmplane remains smooth paintedshading with its original two broadsoft lightlobes at SAME nativepositions/strength, no new anatomicalforms/pores/speckle/grain/gloss. Lowergray curves remain original indistinctmattepaint, no clarified mechanisms or newraisedwhiteedge. Exact opaque authoredblack UVgaps remain sourceblack; dimRGBpositive is not emptiness.'
 patterns=[]
 for axis,coord,z0,z1 in [('row',116,29,69),('column',42,107,127),('column',61,107,127),('column',134,1,99),('row',20,188,254)]:
  v=l[coord]if axis=='row'else l[:,coord];zs=[z for z in range(z0,z1)if v[z]>v[z-1]and v[z]>=v[z+1]];patterns.append({'axis':axis,'native_fixed_coordinate':coord,'native_axis_interval':[z0,z1],'literal_paintshade_maximum_axis_coordinates':zs,'literal_paintshade_maximum_count':len(zs),'native_successive_pitch':[b-a for a,b in zip(zs,zs[1:])],'source_meanRGB_profile':v[z0:z1].tolist(),'qualification':'Source COLORpigment maxima only, not physicalparts/ovalcounts/fibers nor automaticcriterion. BEFOREliteral TWOovals fromwholeview/fullmatrix, naturalRGB roundtrip separately.'})
 c={'id':i,'before_prompt':True,'native_size':[256,128],'native_matrix_ref':r['native_matrix_ref'],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':{'source_darkgrayleft_paintfield':1,'source_middle_softwashfield':1,'source_warmrightupperplane':1,'source_small_brown_ovalpaintmarks':2,'source_lowercenter_graycurvedpaintfield':1,'source_rightlower_paintfields':'Exactentire originalmatrix, no uncertain physicalhardware count inferred.'},'native_repeat_count_phase_evidence':patterns,'count_qualification':'Literalpaintfield/countphase/weaknativepixel evidence only. FullnativeRGBA once includes everydim/zero/localpigment. Diagnosticregions never cropping/fitting/registration/regiongain. ActualM→TemplateID→Models bindings, staticruntime/meshUV/physicalsemantic unknown.','native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_blackRGB_A255_pixel_count':int(((rgb.max(2)==0)&(a[:,:,3]==255)).sum()),'native_positive_weak_RGB_max_le5_pixel_count':int(((rgb.max(2)>0)&(rgb.max(2)<=5)).sum()),'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l.T],'source_description':d};C.append(c)
 r['source_only_reason']='FIRST solebuiltin eligible after wholeoriginalnativeRGB/A/privateNN/count/weakphase/matteblur/actualMaterial bindings/historyrelease exactRGBA. Honest prior0callviews, no previousaccepted/raw/call/jobs/held/sameRGBA donor. ReferenceoriginalnativeopaqueRGB256x128, NNprivate only.'
save(f'natural-RGB-roundtrip-{ST}.json',{'recipe':'FulloriginalRGB-FIRST LANCZOSwhole4x then entirenativeinverse; originalA separately, no PILRGBA premul. Naturaloperator diagnostic only, not artistpatch.','sources':R})
for c in C:c['natural_RGB_roundtrip_ref']={'path':f'assets/terrain-hd/expanded/natural-RGB-roundtrip-{ST}.json','file_SHA256':sha(B/f'natural-RGB-roundtrip-{ST}.json'),'source_key':str(c['id'])}
save(f'pattern-constraints-{ST}.json',C);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_count':len({r['source_rgba_sha256']for r in P}),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[]});save(f'source-check-{ST}.json',P);assert not (B/f'source-check-{ST}-before-call.json').exists();shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in C:
 i=c['id'];oval=next(d for d in c['source_domains']if d['name'].startswith('TWO'));plane=next(d for d in c['source_domains']if'rightupperplane'in d['name']);parts=['Use case: precise-object-edit. Asset type: original handpainted CLOTHING diffuse fullUV bitmap. Faithfully render SAME complete originalpainted sourceart at higherresolution with restrained finerpaint, SAME sourceblur/nativepaintscale/material/normalizedUV/countphase/palette. This remains a flat PAINTED texturemap, no assembledobject orphoto.', 'Image1 is exact ENTIRE originalnative256x128 storedRGB madeopaque at ORIGINAL resolution, no nearest enlargedblockguide. NativeOrdinary straightRGB/noPremul; complete sourceA255/defaultwhole numericalbrightnessscalar separately restored byroot. OriginalblackRGB A255 is authoredUVpaint, not emptynewhole. Originalvariablepaint includingevery weakpositivepixel retained.',c['source_description'],f'Original TWO ovalpaintmarks RGBmax only {oval["source_max_RGB"]}, ROImean {oval["source_mean_RGB"]}; preserve those dim relativelevels, not newbrighter outlines. Original smoothupperrightplane mean {plane["source_mean_RGB"]}, extrema {plane["source_min_RGB"]}..{plane["source_max_RGB"]}, retain SAME dimbroadlocalshading without adding grain. ActualfullnativeRGBA extrema {c["actual_RGBA_extrema"]}; strongestsourceRGBA {c["native_source_max_mean_RGBA"]} at {c["native_source_max_mean_RGB_xy"]}; keep SAME strengths/positions/extent, no newbrighterglints or whiteedge. Nativecoordinate examples refer to wholeoriginalUV, not fitting/crop.', 'Keep source softwash/foldtrajectories and flatpaint backgrounds smooth. Add only verysubtle finerMATTEPAINT in existingfields. NO newphysicalweave/fibers/coarsecells/knurl/castmetal/photo leathergrain/stitchedlines/embroidery/newwrinkles/folds/pores/anatomy/newcloudtonalfields/granulation/rust/etchedmarks/bevel/rim/gloss/newwhiteedges/hardware/bolts/straps/buttons/glyphs/logos. Never regularize faintwashed marks into new geometry.', 'Output ONLY SAME ENTIRE original2:1 OPAQUE RGB sourceUVcanvas, no whitespace/padding/border/frame/cutout/zoom/crop/recenter/BBox/fitting/registration/repacking/islandmoves/objectphotograph. Preserve fullsource material/count/phase/paintscale/blur/localintensity/UV/A.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Clothing43 immutablebefore12/FIRSTpossible3',[(c['id'],c['native_source_max_mean_RGBA'],c['native_zero_RGB_pixel_count'],c['native_positive_weak_RGB_max_le5_pixel_count'])for c in C])
