from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='effects-twenty-ninth';CALL=[4086,2626]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];survey={r['id']:r for r in read(B/f'source-count-survey-{ST}.json')};cons=[];groups={}
boxes={4086:[('original upper graybrown strongest patch',[9,6,16,13]),('original narrow muted middle paint',[11,12,18,20]),('original dim irregular lower taper',[16,20,24,30])],2626:[('original upper bluegray soft peak region',[31,8,45,24]),('original softer left bluegray core region',[12,12,30,32]),('original lower soft bluegray pigment',[35,32,49,48]),('original dim right patch',[52,22,64,38]),('original very dim broad lower tail',[12,42,42,64])]}
descs={4086:'EXACT original ONE thin irregular slanting muted graybrown PAINTED COLOR footprint. Literal native positiveRGB bitmap domain has93 pixels extent[9,6,24,30], not a physical metalpart count. Keep original soft upper graybrown patch, narrow darker and faintly warmer middle paint, original dim irregular lower taper and every interior original blackshade. Original strongest mean shade native[12,11] RGB111/94/92 stays subdued. Do not straighten, thicken, whiten or turn this soft uneven paint into a shiny metalrod/wire/beveled mechanism; do not interpret weak native bits as new parts. Retain source width, exact diagonal phase and weak lower tint, no sharpened edge/raised ridge/physicalgrain.',2626:'EXACT original ONE connected softly painted bluegray diffuse color bitmap field, positiveRGB3182 pixels across entire64x64 source extent[0,0,64,64]. That is bitmap topology, NOT number of physical clouds/spray particles. Keep the exact referenced original broad asymmetric diffuse silhouette/soft outer haze, existing left softly bright patch, existing upper grayblue patch, dim middle shade, lower-right softly shaded field, original separate-looking dim right extension and very dim lower falloff. Native strongest mean shade[39,15] RGB179/185/200, keep the original cold bluegray muted palette without whiteglints. Every original tone knot/blur patch/gap stays at original normalized position, size, width and relative intensity; do not subdivide broad paint into more cloudy cells, stipples, hard rings, rocks, spray droplets or cauliflower turbulence. Source has very faint RGB bits near canvas boundaries; preserve entire original canvas, not auto-bounding, cropping or adding a black margin.'}
for r in P:
 i=r['id'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['previous_source_only_views']=[p.relative_to(ROOT).as_posix()for p in sorted(B.rglob(f'{i}-*source*.png'))if ST not in p.as_posix()][:12];r['view_novelty']='Honest fresh readonly source-only re-audit of prior0call views. Accepted/raw/call/held/refusal/generated/exactRGBA guards separate, no never-viewed fiction.'
 reason='Genuine complex painted sourcecolor; strict weakpixel/count/localshade preservation unclear for forced boundedcall, genuinepending0calls. Actual compact fullnative matrices establish everypixel, not a technical/family ban.'
 if i in [5391,5392]:reason='Individually wholeview smooth verticalbluegray tonefield; no independently visible finepaint detail to synthesize while keeping original softblur. Genuinepending0calls, not analytic/technical solely fromsimpleappearance/name. Fullnative matrix/common actualtyped records retained.'
 if i==2627:reason='Genuine sparsebluegray originalpaint, A0 TransparentAdd usefulRGB notempty. Manyfaintbits/thinstreaks require faithful localrelative strength, source-only genuinepending0calls, no familyban.'
 if i==4101:reason='Genuine tinyverydim separated graybrown paintstreaks; would risk strengthening/dropping faintbits despite exactpixel coordinates, genuinepending0calls.'
 if i==2523:reason='Genuine complex brown/violet paintedfield with numerous narrowrays/tinyweakflecks. Weakfleck hierarchy/formphase not suitable for forcedcall inthisscope, genuinepending0calls.'
 if i==2575:reason='Genuine softly painted brown/orange field with complex interior brightknots/darkgaps and sixisolated RGB1 pixels. No forced complexcall, genuinepending0calls; not A0-empty/technical.'
 r['source_only_reason']=reason
 if i not in CALL:continue
 o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];rgb=a[:,:,:3];l=rgb.mean(2);y,x=np.unravel_index(l.argmax(),l.shape);expected={4086:([12,11],[111,94,92,246]),2626:([39,15],[179,185,200,200])};assert [int(x),int(y)]==expected[i][0]and a[y,x].tolist()==expected[i][1]
 zero=rgb.max(2)==0;weak=(rgb.max(2)>0)&(rgb.max(2)<=5);domains=survey[i]['native_positive_RGB_8connected_domains'];assert len(domains)==1
 c={'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':list(o.size),'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':[int(x),int(y)],'native_source_max_mean_RGBA':a[y,x].tolist(),'source_feature_counts':{'literal_positive_RGB_8connected_bitmap_domains':len(domains),'domains':domains,'qualification':'Exact bitmap topology only, NOT physicalparticle/metalparts count fromRGBA mask. Whole sourceRGBA matrix stored once/read by sourcekey+fileSHA. Allzeroweak pixels included; no inferred hardware.'},'native_zero_RGB_pixel_count':int(zero.sum()),'native_positive_weak_RGB_max_le5_pixel_count':int(weak.sum()),'complete_zero_and_weak_pixel_evidence':'Derive everynative zero/weak xy/RGBA from immutable referenced matrix: RGBmax==0, or0<RGBmax<=5. Matrix is EXACT decoded entire original and contains originalA separately, not an artthreshold guide. Avoidduplicating matrix/raster arrays perconsumer.', 'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l.T],'source_description':descs[i],'source_domains':[],'semantic_qualification':'Allregionboxes numericdiagnostics only, never crop/referencefitting/BBox/composite/artistRGB. FulloriginalA/UV/sourceblur/nativepatternscale retained; unknown absentdefinitions explicit.'}
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=rgb[y0:y1,x0:x1];aa=a[y0:y1,x0:x1,3];c['source_domains'].append({'name':name,'bbox':b,'native_pixels_ref':{'source_matrix_key':str(i),'matrix_file_SHA256':r['native_matrix_ref']['file_SHA256'],'slice_native_xyxy':b},'mean_RGB':v.mean((0,1)).tolist(),'max_RGB':v.max((0,1)).tolist(),'sourceA_extrema':[int(aa.min()),int(aa.max())],'original_zero_RGB_pixels':int((v.max(2)==0).sum())})
 cons.append(c);r['source_only_reason']='One FIRST faithful edit eligible after fullactualnative weakzero/count/palette/maxphase evidence and originalRGB/A/NN views; no sourcecrop/physicalhardware inference.';r['full_original_RGBA_RGB_A_NN_privately_inspected_BEFOREtool']=True
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL]});save(f'source-check-{ST}.json',P);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Faithfully edit the existing historical Silent Storm SOFT PAINTED COLOR bitmap at higher resolution; do not render new realistic objects/effectparticles/hardware.', 'Image1 is EXACT ENTIRE original native storedRGB solely wholecanvas nearest source sampling to512x512 madeopaque. Preserve complete normalizedUV/positions/width/shapes/count/nativephase/patternscale/sourceSOFTBLUR/palette/relativeweak strengths, every original pixelpaintfield/blackgap. Nearestblock sampling proves originalUV only, NOT squaredcells/grid/mosaic. Render the same original smooth subdued mattewash without inventing physicalgrain/stipples/furryedge/coarsecloudcells/mottle. Fulloriginalalpha restored independently, brightness only one globalnumerical scalar. No crop/padding/frame/recenter/BBox/fitting/repack/zoom.',descs[i],f'Actual original nativeRGBA extrema are {c["actual_RGBA_extrema"]}; maxmean nativexy{c["native_source_max_mean_RGB_xy"]} is exact RGBA{c["native_source_max_mean_RGBA"]}. Keep ORIGINAL muted source color hierarchy and nativepeak strengths, not manual255/white. Do not strengthen original dimfield, lighten blackgaps or make newreflectiveedges. Full original alpha stays separately source-restored exactly, including actual original max219 for2626 and max255 for4086; guideopaque RGB is originalusefulpaint.','Add only finer softly blended depiction of EXISTING paint. No physical shine, glints, whiteplates, rims, bevels, raisedhardware, rust, etchedscratches, rods, wires, knurl, bolts, rocks, rings, newholes, fibers, photo texture, cloudgranules, stipples, furryedge, coarse mottle or addedfragments. Do not make new sparks/rays/tongues/curls, remove weak originalpaintfield or regularize originalasymmetry. Keep sourceblur/plainmatte material. No symbols/text/logos.', 'Output ONLY ENTIRE SAME opaqueRGB square canvas with exact normalizedUV/sourcepaint scale/count/tonalphase/material/sourceA downstream. No whitespace/cutout/crop/zoom/framing/fitting/BBox/UVrepacking/composites or inventedparts.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Immutable compact BEFORE12 sources/2FIRST count weakzero proof',CALL)
