from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='heads-fifteenth';CALL=[6710,6711,6712]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'));constraints=[]
reasons={6695:'Genuine dynamic brown mouth/beard softly painted layer with thin existing hair/pigment detail. Exact beard detail count/phase pending, zero calls.',6697:'Genuine dynamic brown beard/chin layer with bilateral rising pigment, many original fine strands. Detailed native phase pending, zero calls.',6702:'Genuine softly painted olive directional skin-mark layer; native exact stroke separation/count not established in bounded scope, zero calls. Not declared analytical or technical from name alone.',6704:'Genuine flat red skin-mark pigment plus one existing small pale diagonal patch and weaker dim fine marks. Exact weak-mark count/material proof pending, zero calls. No invented open wound or relief.',6713:'Genuine dynamic muted brown gender/skin color layer with almost invisible native face wash. Own exact weak phase/count pending, zero calls; not flat technical by name.',6714:'Genuine dynamic muted brown gender/skin layer with dim washes; exact weak-field phase/count pending, zero calls.',6717:'Genuine dynamic brown hair/skin color overlay with source hair field and two faint eyebrow-like strokes. Original lock count/phase pending, zero calls.',6718:'Genuine dynamic golden hair/skin color overlay with two faint brow strokes; native irregular strand phase pending, zero calls.',6722:'Genuine dynamic gray-blue hair/skin color overlay with two separate lateral hair fields and two weak brow strokes. Exact individual brush phase/count pending, zero calls.'}
boxes={6710:{'left_soft_pink_cheek_and_eye_halo':[22,38,61,72],'right_soft_pink_cheek_and_eye_halo':[66,38,106,73],'left_dark_eye_patch':[40,39,61,53],'right_dark_eye_patch':[66,39,85,54],'one_original_closed_lip_wash':[53,62,76,77],'weak_bottom_left_corner_pigment':[0,120,9,128]},6711:{'one_upper_warm_skin_wash_with_two_brow_lobes':[35,27,93,55],'left_dark_eye_patch':[40,40,59,51],'right_dark_eye_patch':[68,40,86,51],'left_soft_pink_cheek':[21,39,60,75],'right_soft_pink_cheek':[70,39,108,75],'one_closed_lip_chin_wash':[51,62,79,84],'weak_bottom_left_corner_pigment':[0,119,11,128]},6712:{'whole_almost_constant_brown_pigment':[0,0,128,128],'faint_face_wash_not_new_anatomy':[39,38,91,83],'faint_left_eye_wash':[43,42,60,53],'faint_right_eye_wash':[68,42,85,53],'faint_closed_mouth_wash':[53,65,76,76]}}
for r in proof['source_checks']:
 i=r['id'];r['full_original_and_helper_privately_inspected']=True;r['source_only_reason']=reasons.get(i,'Actual dynamic TransformableFaceTextures color overlay, exact native soft pigment/weak regions/fullA matrices and palette saved BEFOREprompt, one FIRST sole builtin planned. No static material Alpha or eyeTHMID classification assumed.')
 if i not in CALL:continue
 a=np.asarray(Image.open(B/f'original/{i}.png').convert('RGBA'));assert a.shape==(128,128,4);regions={}
 for n,b in boxes[i].items():
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];yy,xx=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);regions[n]={'native_bbox':b,'exact_source_RGBA_matrix':v.tolist(),'mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'min_RGB':v[:,:,:3].min((0,1)).tolist(),'max_RGB':v[:,:,:3].max((0,1)).tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())],'max_mean_source_xy':[x0+int(xx),y0+int(yy)],'max_mean_source_RGB':v[yy,xx,:3].tolist()}
 lum=a[:,:,:3].mean(2);phase=[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum];c={'id':i,'native_RGBA_SHA256':hashlib.sha256(a.tobytes()).hexdigest(),'source_whole_RGBA_matrix':a.tolist(),'native_RGB_extrema':[a[:,:,:3].min((0,1)).tolist(),a[:,:,:3].max((0,1)).tolist()],'nativeA_extrema':[int(a[:,:,3].min()),int(a[:,:,3].max())],'region_diagnostics':regions,'every_native_row_pigment_maximum_x':phase,'source_feature_counts':{'main_pink_cheek_washes':2,'dark_eye_areas':2,'closed_lip_wash':1,'existing_weak_corner_pigment':1}if i==6710 else {'main_pink_cheek_washes':2,'dark_eye_areas':2,'upper_warm_skin_wash_with_two_lobes':1,'closed_lip_chin_wash':1,'existing_weak_corner_pigment':1}if i==6711 else {'complete_muted_brown_color_canvas':1,'barely_visible_original_face_wash':1,'faint_eye_wash_locations':2,'faint_closed_mouth_location':1,'qualification':'Weak native wash positions only; not inferred anatomical features/teeth. RGB min64/30/12 max73/38/20 across whole canvas, no manual255. SourceA is nontrivial0..232 independently preserved.'},'count_phase_limits':'Whole native field/matrix + source weak corner marks + actual pigment rowphase established before prompt. Numeric rectangles diagnostic only, not exact segmentation of physical anatomy and never cropped/composited references.','actual_consumer':'TransformableFaceTextures→THMID1→actual Heads/ComplexHeads; dynamic COLOR overlay, no fake static material sampler/alpha mode. Exact original sourceA/layerweights/UV preserved.'};constraints.append(c)
save(f'pattern-constraints-{ST}.json',constraints);save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json');save(f'scope-{ST}.json',{'ids':[r['id']for r in proof['source_checks']],'call_ids':CALL,'source_only_ids':list(reasons),'honest_prior_sourceonly_reaudit_allowed':True})
for c in constraints:
 i=c['id'];ext=c['native_RGB_extrema'];parts=['Use case: precise-object-edit. Asset: historical Silent Storm softly painted COLOR facial overlay bitmap, not a photograph or new face.','Input1 is the exact ENTIRE native128square source RGBA, with its variable original alpha. Input2 is identical whole original storedRGB NEAREST6x768 source-only enlargement. Keep the COMPLETE full square color bitmap edge-to-edge at EXACT same normalized UV. Only restrained fine source paint, no new anatomy or reconstruction. Preserve original soft blur, every original pigment footprint/position/count/phase, relative weak washes, palette and expression. Original COMPLETE alpha will be independently restored; brightness only one global scalar. Do not invent an alpha cutout or fit/crop individual shapes.']
 if i==6710:
  desc='Keep exactly TWO original soft PINK cheek washes (nativeleft22..60,y38..71; right66..105,y38..72), TWO already existing dark eye/halo areas at40..60,y39..52 and66..84,y39..53, and ONE closed softly painted lip wash at53..75,y62..76. Keep original faint blue-violet shading under each dark eye, its muted non-white tint, and all original almost-black gaps. Do not paint eyes/pupils/catchlights or teeth into these dark fields; they are the SAME existing washes only. Preserve the weak tiny reddish source pigment at bottom-left0..8,y120..127, not omitted as irrelevant. The rest is original black color canvas. No nose/forehead/ears/anatomy added. Preserve exactly existing asymmetry and dim lower-lip shade, no new lip shine.'
 elif i==6711:
  desc='Keep TWO original soft pink cheeks, TWO dark closed eye-area shapes, ONE upper warm orange-brown skin wash with its TWO original broad lobes, and ONE closed lip/chin wash at the source native locations/proportions. There is no whole face outline to invent: preserve the exact original isolated washes and black gaps. Retain original dark small split upper-lip segments within the SAME single closed-lip wash, no open mouth/teeth. Preserve the weak tiny reddish bottom-left source pigment near0..10,y119..127. No new nose/eye/pupil/white reflection/anatomy/pores; keep soft original expression, source blurred transitions and muted relative intensity.'
 else:
  desc='Keep the ENTIRE nearly constant DARK BROWN original canvas. The actual source is deliberately almost invisible, RGB whole MIN[64,30,12] MAX[73,38,20], not a visible face render. Preserve exactly its very faint brown face-like wash centered native39..90,y38..82, faint paired eye washes and faint closed mouth wash WITHOUT making them more visible, outlined, anatomical or structured. Use a nearly flat brown field with only those exact original tiny low-contrast pigment variations. Do not replace the original subtle wash with a completely flat fill; do not invent new pores, beard hairs, nostrils, cheeks, lips, wrinkles, skin contours or a reconstructed face. Do not add any grain/mottle or specular highlights. Native sourceA0..232 is preserved separately, never enlarge/contrast-enhance the barely visible source.'
 parts += [desc,f'Exact original whole RGB extrema are {ext}; preserve its muted pigment hierarchy, especially weak fields. No photoanatomy/photofibers/pores/radialpattern/mosaic/newglints/hair/teeth/curls/raised rims or cosmetic glare. No text/logo, hardware, new geometry, local highlighting or sharper edges.','Output the whole source square with same normalized UV, no margins/whitespace/padding/crop/zoom/BBox/rearrangement/sourceRGB artistic repairs. Keep original blur, paint scale, expression and weak source marks. Entire sourceA and default padding restored downstream, not by inventing new alpha.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('BEFOREcall source nativeRGBA/weak marks/palette and exact CRLF prompts saved',CALL)
