from pathlib import Path
import json,shutil,hashlib
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='clothing-forty-fifth';CALL=[4502]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];cons=[];groups={};rounds={}
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];lum=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['source_RGBA_RGB_A_NN_privately_inspected']=True
 r['source_only_reason']='Genuine actual Materials→TemplateID→Models diffuse COLOR source, not technical by Robot/armor/clothing name. WholeoriginalRGBA/sourceA255/weaknativepaint patterns remain exact. Fullpainted512wide atlases contain individually visible tiny marks and many curved/round/thinmechanical paintfields; literal little forms/phase not sufficiently resolved for FIRST here, so genuinepending0call rather than interpreting tinyglyphs/newhardware.'
 if i in [5683,5695]:r['source_only_reason']='Genuine actualBody diffuse COLOR wholelayout with softdarkclothpaint and warmbrown or graypolygon field, samecomplex existingbelt/angularpaint/detailcount as4502. Source-onlypending0call initially, no quota or material/grain inference; new source outside priorCl1–44selected scopes honestly audited. No blanket Robot/clothing ban.'
 if i==5688:r['source_only_reason']='Genuine Body diffuse colorpaint source includes ONE prominent existing pale angularverticalstroke inside flatdarkpolygon. Its exact semantic glyph/control interpretation unknown; exactwholepixels/A preserved,0calls, not regenerating guessed symbol or classifying all Body/Robot family technical.'
 if i not in CALL:continue
 assert o.size==(256,256)and r['material_evidence']['actual_source_native_type']=='Ordinary'and o.getchannel('A').getextrema()==(255,255)and r['fresh_actual_static_consumers'];s=o.convert('RGB');rnd=np.array(s.resize((1024,1024),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS));rounds[str(i)]={'id':i,'source_size':[256,256],'source_RGB_LANCZOS4x_then_native_RGB_matrix':rnd.tolist(),'recipe':'ENTIRE native storedRGB FIRST LANCZOS4x then whole native inverse independentlyA; no implicit PILRGBApremul/unpremultiply/crop/artistrepair. SourceA255 separately restored.'}
 boxes=[('ONE original darksoftwashed mainclothpaint field',[23,2,219,168]),('ONE original flat warmbrown polygonpaint',[40,28,117,113]),('FIRST original small thin rectangularpaintoutline',[108,53,126,70]),('SECOND original small thin rectangularpaintoutline',[95,94,111,113]),('ONE continuous original dark lowerbeltpaintfield',[45,130,199,167]),('ONE narrow original upperleft uprightgraypaintfield',[2,2,25,69]),('ONE original leftcurvedgraypaint belowbar',[0,80,49,168]),('ONE original rightcurvedweakgraypaintfield andslivers',[199,3,256,165]),('ONE original lowerleftgrayarchpaintfield',[0,168,119,224]),('ONE original roundpaintpatch withinlowerarch',[39,189,93,220]),('THREE original slantedthinpaintpaths groupedbelowarch',[47,222,117,252]),('ONE original broadlowerrectangularpaintpanel TWO interiorbands',[120,170,199,249]),('ONE original farright uprightgraypaintfield',[199,165,255,250])]
 domains=[]
 for name,b in boxes:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);domains.append({'name':name,'bbox':b,'native_pixels_ref':{'matrix_ref':r['native_matrix_ref'],'slice_native_xyxy':b},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_std_RGB':v[:,:,:3].std((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'source_peak_xy':[x0+int(x),y0+int(y)],'source_peak_RGBA':v[y,x].tolist(),'sourceA_extrema':[255,255]})
 patterns=[]
 for axis,coord,z0,z1 in [('column',80,222,255),('column',145,175,249),('row',143,46,199),('row',148,46,199),('row',61,108,126),('row',103,95,111),('row',109,199,255),('column',210,165,249)]:
  v=lum[coord]if axis=='row'else lum[:,coord];xs=[z for z in range(z0,z1)if v[z]>v[z-1]and v[z]>=v[z+1]];patterns.append({'axis':axis,'native_fixed_coordinate':coord,'native_axis_interval':[z0,z1],'literal_paintshade_maximum_axis_coordinates':xs,'literal_count':len(xs),'native_successive_pitch':[b-a for a,b in zip(xs,xs[1:])],'qualification':'Literal fullbitmap weakpigment maxima only, not physicalribs/bolts/hardware/glyph interpretation or acceptance thresholds.'})
 description='Keep ONE dark graygreen softlywashed upperclothpaint field with exactly its original broadshadow/fold trajectories, ONE flat warmbrownpolygon paint around nativex40..116,y28..112, TWO original small thin rectangularpaintoutlines atx108..125,y53..69 andx95..110,y94..112, ONE continuousoriginal lowerdarkbeltpaintfield x45..198,y130..166 with its existingtinybrown/gray rectangles/marks exactly in place. Existing tiny beltmark meanings unknown: do not inventbuckles/links/holes/glyphs or regular columns, preserve every originalsourcepixelphase/number/spacing from reference. Keep ONE originalupperleft uprightgrayfield, ONE leftconvexgraypaintfield, ONE weakrightcurvedgrayfield plus existing tinygraystrokes, ONE lowerleftgrayarch with ONE originalroundpaintpatch, THREE existing thin slantedpaint paths beneath it x47..116,y222..251 (sourcecrossings atx80 aroundy228/240/248; otherlowcontrast tonalmaxima are not additionalphysicalbars), ONE lowerrectangulargraypaintpanel with TWO existing horizontalinterior bandpaths aroundy188/232 and originalboundarylines, andONE original farrightuprightgrayfield. Everything is existing flat diffusepaint/materialshade, not newlymodeled armor/rod/hinge. Keep originaldarkblackUV/A255 and nativeweakgray/brown relationships; no increasing contrast/rims/rust/weave/grain/shine. ExactallnativeRGB/A weakpixel/phase proof retained; fieldboxes explanatory only, wholecanvas reference/no region fitting.'
 cons.append({'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':[256,256],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':{'flatwarmbrownpolygon':1,'smallthinrectangularpaintoutlines':2,'continuouslowerdarkbeltpaintfield':1,'lowergrayarch':1,'roundpaintpatchwithinarch':1,'slantedthinpaintpaths':3,'interiorhorizontalpanelbands':2},'native_repeat_count_phase_evidence':patterns,'native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_sourceA0_pixel_count':0,'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'source_description':description,'qualification':'Literal original COLOR domains/paths, not invented physicalparts/glyphs/runtimeassembly. THREE slantedpaintpaths have extra weakshade localmaxima, so rawmatrices authoritative and maxima not physicalcomponent counter. Exactpositions/countphase/localtones beforetool; no technical/clothing/Robot familyban.'})
 r['source_only_reason']='EligibleFIRST on freshnewwholelayout after fullsourceRGBA/RGB/A/NN/nativePOT/history-release/sourcebytes/actualMaterial→TemplateID→Models/completeweaknativephase/palette/fieldcount audit. Native256square opaqueRGB toolreference, no NNenlargedblocks. AllsourceblackA255 remains authoredpaint, not holes.'
rp=B/f'natural-RGB-roundtrip-{ST}.json';save(rp.name,{'sources':rounds,'before_call':True})
for c in cons:c['natural_RGB_roundtrip_ref']={'path':rp.relative_to(ROOT).as_posix(),'file_SHA256':sha(rp),'source_key':str(c['id'])}
save(f'pattern-constraints-{ST}.json',cons);save(f'original-only-proof-{ST}.json',[]);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[],'all_selected_outside_previousClothing1to44':True,'source_layout_novelty':'Fresh actualBody/RoboBody diffuse wholeUV maps, individual artcount clarity—not classified technical by Robotname.'});save(f'source-check-{ST}.json',P);assert not(B/f'source-check-{ST}-before-call.json').exists();shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Asset type: original softlypainted BODY/CLOTHING wholeUV diffuse COLOR bitmap. Faithfully refine SAME complete sourcebitmap at higherresolution while preserving fullUV/fieldcount/nativepaintphase/sourceblur/mattepaint/material/palette/weakshades.', 'Image1 is ENTIRE nativeoriginal256square storedRGB madeopaque, originalresolution/no NNenlargedblocks. NativeOrdinary straightRGB/noPremul/sourceA255 restored separately with defaultwholepadding/standardscalar. Actualsource Material→TemplateID→Models wholeBody diffuse, no inferred anatomical object or newlyassembled robot. BlackRGB/A255 is authoredUVpaint, not transparencyhole.',c['source_description'],f'Exactfullnative RGBAextrema {c["actual_RGBA_extrema"]}; strongestnativeRGBA {c["native_source_max_mean_RGBA"]} at{c["native_source_max_mean_RGB_xy"]}. Preserve originalrelative lightstrength/hue hierarchy/weakgraywash/line softness/material. Existing lowerpanel brightpaintspots stay same smallwidth/position/palette/strength, no newglints. Originalfiltered cloth folds staysame broadwash, not new embossedwrinkles, materialgrain or seams.', 'Only subtle fine SAME sourcepaint rendition, keep source nativefilteredbrushscale. NO photo-weave/mesh/individualfibers/clothgrain/mosaic/coarsecells/backgroundmottle/metalgrain/etchedgrain/castmetal/newrust/bevel/raisedrim/shinywhiteedge/hardware/bolts/pockets/newseams/straps/newmarks/newglyphs/text/letters/logo/anatomy. Existing angular/roundgrayfields remain flat originalpaintshades, not inventedmechanisms or physicalparts; preserve all existing smallmarks ratherthan guessing them.', 'Output SAME ENTIRE SQUARE opaqueRGB originalUVcanvas, no whitespace/padding/border/frame/cutout/crop/zoom/recenter/BBox/fitting/registration/islandrepack. FulloriginalA/sourceblur/material/count/phase/nativepatternscale/localpalette unchanged.']
 arg='\r\n\r\n'.join(parts);p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes((arg+'\n').encode('utf-8'));(B/f'generated/{i}-{ST}-exact-call-argument.txt').write_bytes(arg.encode('utf-8'))
print('Cl45 immutablebefore12/ONEprospective/noquota',[(c['id'],c['native_source_max_mean_RGBA'],c['native_source_max_mean_RGB_xy'])for c in cons])
