from pathlib import Path
import json,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='equipment-forty-first';CALL=[5431,5333]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def cc(mask):
 seen=set();out=[]
 for y,x in zip(*np.where(mask)):
  y=int(y);x=int(x)
  if (y,x)in seen:continue
  seen.add((y,x));todo=[(y,x)];px=[]
  while todo:
   yy,xx=todo.pop();px.append((yy,xx))
   for dy,dx in [(1,0),(-1,0),(0,1),(0,-1)]:
    z=(yy+dy,xx+dx)
    if 0<=z[0]<mask.shape[0]and 0<=z[1]<mask.shape[1]and mask[z]and z not in seen:seen.add(z);todo.append(z)
  ys,xs=zip(*px);out.append({'literal_pixels':len(px),'bbox':[min(xs),min(ys),max(xs)+1,max(ys)+1]})
 return out
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];cons=[];groups={}
boxes={5431:[('original left darkpaint endfield',[0,0,21,32]),('original entire finely alternating brownpaint repeatfield',[21,0,119,32]),('original top right shadedendcap',[119,0,128,15]),('original bottom right shadedendcap',[119,17,128,32]),('original small right dark dividergap',[119,15,128,17])],5333:[('original whole dim green broadpaint field',[0,0,128,64]),('original irregular bluegray edgepaint wash',[0,42,128,64]),('original lowerleft graypaint island',[0,69,28,127]),('original lower middle graypaint strips',[28,69,60,128]),('original lowerright polygonal greenpaint field',[81,72,128,120]),('original thin gray looppaint within greenpolygon',[99,77,121,103])]}
counts={5431:{'original_left_darkpaint_endfield':1,'original_continuous_brown_fine_repeatfield':1,'original_right_shadedcapfields':2},5333:{'original_broad_dim_green_upperpaintfield':1,'original_irregular_gray_edge_washfield':1,'original_lowerleft_graypaint_field':1,'original_lower_middle_graypaint_strips_field':1,'original_lowerright_polygonalgreen_field':1,'original_thin_looppaint_within_greenpolygon':1}}
descs={5431:'Keep ONE original left darkgray shaded endfield, ONE original continuous fine alternating subdued reddishbrown checker/diamond PAINT field spanning native x21..119, and TWO original gray/dark shaded right endcap colorfields in the exact existing tiny normalized positions. Keep EVERY original tiny alternating paintshade at SAME native phase/count/pitch/width/scale and original dark/brown strengths. This is fine flat sourcecolor pattern, NOT new physical raisedknurl/metalstuds/coarsewovenfibers; do not add manufacturedgrids/outlinedbiggerdiamonds or regularize any small irregularsourcepaint phase. Original leftwhite/gray diffusepatch stays originaldim extent/strength, no newglints. Preserve original black/dimright gaps including sourceA255, no addedcaps/rings/bolts/letters/holes.',5333:'Keep ONE original broad dim muted green upperpaint field, its ONE existing irregular faint bluegray loweredge paintwash, original lowerleft graypaint island/lower middle graystrips and ONE lowerright polygonal greenpaint field with its original thin gray looppaint and little short pale marks. These are existing bitmap colorpaintforms, NOT an invitation to invent mechanisms/hardware/text. Preserve EVERY original little weakgraypatch/pigmentfleck at its exact sourceUV position/count/relativeweakstrength and tiny nativepaintscale, including source darkgreen/bluewash/blackUV. Do not turn diffuse dullgreen into new physical coarsegrain/mottledcells/metalshine/rust/scratches/corrosion or add new grayflakes/glints. Keep the gray edgepaint irregularity/holes/phase unchanged, no new flakes or stronger fragment rims. Lower existing colorislands and graylinepaint retain exact native silhouettes/widths/dimness; no new bolts/levers/hardware interpreted from vague lowres sourceforms.'}
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];lum=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['source_RGBA_RGB_A_NN_privately_inspected']=True;assert r['fresh_actual_static_consumers'] and not r['fresh_actual_dynamic_consumers']
 r['source_only_reason']='Genuine actualequipment paintedCOLOR source, exact native everyweakpixel/marks/count/phase/UV/material requires faithful bounded review. Honest previoussource-only0calls reaudit permitted. Remains genuinepending0call; no type/family/print/regularpattern technicalban and no vaguehardware interpretation.'
 if i in [5236,5239,6901]:r['source_only_reason']='Actual fullsource diffuse art has indistinct printed/codedsmallmarks. Originalcontent cannot be guessed from blur; genuinepending0call retains everyoriginalRGBA, not declaredtechnical or constant from appearance.'
 if i==2213:r['source_only_reason']='Genuine actualcloth/camouflage/leaf-shaped sourcecolor layout; exact many small sourceforms/count/asymmetry/weakpaintphase complex. Source-only0call genuinepending, not familyban/technicalclassification.'
 if i not in CALL:continue
 assert r['material_evidence']['actual_source_native_type']=='Ordinary'and(a[:,:,3]==255).all()
 regions=[]
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);regions.append({'name':name,'bbox':b,'native_pixels_ref':{'source_matrix_key':str(i),'matrix_file_SHA256':r['native_matrix_ref']['file_SHA256'],'slice_native_xyxy':b},'mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'min_RGB':v[:,:,:3].min((0,1)).tolist(),'max_RGB':v[:,:,:3].max((0,1)).tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())],'native_peak_xy':[x0+int(x),y0+int(y)],'native_peak_RGBA':v[y,x].tolist()})
 pattern=[];pixels={}
 if i==5431:
  for y in [0,4,8,12,16,20,24,28,31]:
   xs=[x for x in range(22,118)if lum[y,x]>lum[y,x-1]and lum[y,x]>=lum[y,x+1]];pattern.append({'native_y':y,'native_x_interval':[22,118],'literal_row_brightness_maximum_count':len(xs),'native_maximum_x':xs,'native_successive_pitch':[b-a for a,b in zip(xs,xs[1:])],'qualification':'Exact colorpaint rowmaxphase/count only, not inferred physical cells/studs/hardware.'})
  descs[i]+=' Native source row4 has '+str(pattern[1]['literal_row_brightness_maximum_count'])+' exact paintshade maxima x='+str(pattern[1]['native_maximum_x'])+'; row16 has '+str(pattern[4]['literal_row_brightness_maximum_count'])+' maxima x='+str(pattern[4]['native_maximum_x'])+'. Match SAME normalizedUV/nativealternation phase, not newlargercheckers.'
 else:
  # Individual coolgray pigment selection for reproducible weakpixel evidence, not physical fragment/anatomy count.
  mask=(rgb[0:64,:,2]>=rgb[0:64,:,0])&(rgb[0:64].min(2)>=25)&(rgb[0:64].mean(2)>=45);pixels={'literal_cool_gray_source_selection_recipe':'upper native[0:128,0:64], B>=R and minRGB>=25 and meanRGB>=45','literal_selected_pixel_count':int(mask.sum()),'literal_4connected_components':cc(mask),'all_subthreshold_weak_pigment_qualification':'Thresholds descriptive source-only evidence, NOT physical fragment count nor omitweakpaint authorization. EVERY originalweakpixel inclsubthreshold/darkfields exactRGBA matrix authoritative; no newflecks/strengthenedpigment.'}
 cons.append({'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':list(o.size),'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':regions,'source_feature_counts':counts[i],'native_repeat_count_phase_evidence':pattern,'literal_source_weak_graypaint_evidence':pixels,'count_qualification':'Counts observed original COLOR regions/paintfields/grayloops/endcaps only, no physicalhardware inferred. Allnativebrush/pigment/weakzero/RGB/sourceA and phase exactfullRGBA once immutablematrix. Diagnosticbboxes notUV fitting/crop/BBox, no synthetic cleanpattern assumed.','native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_blackRGB_A255_pixel_count':int(((rgb.max(2)==0)&(a[:,:,3]==255)).sum()),'native_positive_weak_RGB_max_le5_pixel_count':int(((rgb.max(2)>0)&(rgb.max(2)<=5)).sum()),'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'source_description':descs[i],'actual_consumer':'ActualMaterials.TextureID/TemplateID/Models.MaterialN diffuse roles/Geometries/ModelTemplates refs. Source Ordinary/nativeA255 actualopaqueClamp, meshUV/runtime/hardwaresemantics unknown.'})
 r['source_only_reason']='FIRST solebuiltin eligible after complete original nativeRGB/A/NN/sourceblur/count/phase/palette/weakzero fullpixel proof + actualmaterialTemplate/modelroles/history-release parity.'
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[]});save(f'source-check-{ST}.json',P);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];w,h=c['native_size'];parts=['Use case: precise-object-edit. Faithfully edit this exact existing Silent Storm PAINTED equipment COLOR bitmap at higher resolution preserving original colorart/UV/sourceblur/material/nativepatternscale/count.',f'Image1 is ENTIRE exact edit target originalnative{w}x{h} storedRGB madeopaque at original resolution, NO NNtool enlargement/pixelblockguide. Preserve complete normalized sourceUVcanvas, all sourceblack/dimRGB even A255. Original completeA255 restored separately downstream; only one global numericbrightnessscalar. NativeOrdinary straightRGB, no premultiplication. Nativepatternphase/weakpigment/blur/color strength must stayoriginal.',descs[i],f'Exact source fullRGBA extrema {c["actual_RGBA_extrema"]}, strongest originalnativeRGBA {c["native_source_max_mean_RGBA"]} at {c["native_source_max_mean_RGB_xy"]}. Retain original localtone/palette/brightandweakpaint relationships. Add only subtle rendition of SAME existing fine mattepaint, NO photograin/rust/etchedscratches/weave/embossing/coarsecells/physicalknurl/raisedrims/newwhiteglints/sharperoutlinedfragmentedges/fibers or hardware; no newpaintflecks or cloudmottle in darkfields.', 'Output ONLY SAME ENTIRE opaqueRGB originalaspectcanvas with complete identical normalized sourceUV. No crop/whitespace/frame/padding/cutout/zoom/recenter/autoBBox/fitting/repack/islandmoves/composite. No newparts/lines/bolts/buttons/text/glyph/symbol/logo. FulloriginalA/defaultpadding/globalbrightnessnumeric preserved separately.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Eq41 immutablebeforeproof12/2FIRST candidates',[(c['id'],c['source_feature_counts'],len(c['native_repeat_count_phase_evidence']),c['literal_source_weak_graypaint_evidence'].get('literal_selected_pixel_count'))for c in cons])
