from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='heads-sixteenth';CALL=[6698,6719,6720]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'));constraints=[]
reasons={6692:'Actual dynamic face beard color layer: RGB is exactly black at16383/16384 native pixels, with ONLY ONE original white bottomleft pixel; alpha alone retains painted beard footprint. Source-only native black painted mask plus original cornerpixel, no new colored beard artwork invented.',6699:'Genuine softly painted beige beard with one connected curved field/two rising lobes/one dark oval center; bounded scope pending0calls, not analytical/technical by name. Full detailed native strand-phase not asserted from blurred brushwork.',6700:'Genuine gray painted beard with many original diagonal brush strokes and one dark oval gap. Full fine brush-pattern count/phase unresolved, pending0calls, not technical.',6701:'Genuine dim bluegray beard color field with existing mottled/stippled native RGB and sourceA0..87; exact stipple phase/count not proved for a first faithful call, pending0calls without inventing pores.',6703:'Actual dynamic face source layer: ENTIRE source RGB exactly[0,0,0], independently nontrivial painted alpha0..255. Source-only original black color mask preserves authored alpha footprint; no invented visibleRGB anatomy.',6709:'Genuine extremely dim painted gender/color layer with paired native alpha brow strokes and tiny corner pigment; exact weak RGB fields/phase not established in bounded calls, pending0calls. Not empty because dark storedRGB and original alpha are intentional.',6713:'Genuine dynamic muted brown face color layer with RGB64/30/12..73/38/20 and complex source face alpha; barely visible native wash remains pending0calls to avoid adding anatomy or new cloudy material.',6714:'Genuine dynamic muted brown face color layer with almost identical dark RGB range and different actual source alpha; full native weak phase not established, pending0calls, not constant technical classification.',6721:'Genuine gray softly painted hair/color layer with paired banks, short pale brow strokes and many diagonal source brushmarks; detailed brush phase not proved in bounded selected calls, pending0calls.'}
boxes={6698:{'whole_soft_beard_paint_field':[25,47,103,97],'source_left_rising_lobe':[26,48,40,78],'source_right_rising_lobe':[88,48,103,78],'one_existing_dark_oval_and_pale_boundary':[49,60,79,76],'source_lower_curved_paint_band':[31,72,98,96],'existing_bottomleft_corner_pixel':[0,127,1,128]},6719:{'left_soft_hair_paint_bank':[0,0,64,73],'right_soft_hair_paint_bank':[64,0,128,73],'original_central_soft_bridge':[51,14,79,33],'left_faint_brow_stroke':[43,37,63,45],'right_faint_brow_stroke':[65,37,86,45],'lower_plain_brown_paint_field':[12,80,116,120],'existing_bottomleft_corner_pixel':[0,127,1,128]},6720:{'left_soft_hair_paint_bank':[0,0,64,73],'right_soft_hair_paint_bank':[64,0,128,73],'original_central_soft_bridge':[51,14,79,33],'left_faint_brow_stroke':[43,37,63,45],'right_faint_brow_stroke':[65,37,86,45],'lower_plain_brown_paint_field':[12,80,116,120],'existing_bottomleft_corner_pixel':[0,127,1,128]}}
for r in proof['source_checks']:
 i=r['id'];r['full_original_and_helper_privately_inspected']=True;r['full_source_alpha_privately_inspected']=True;r['source_only_reason']=reasons.get(i,'Genuine actual dynamic TransformableFaceTextures color paint layer; full nativeRGBA/alpha/weakdomains/row-and-columnpaintphase recorded BEFORE FIRST sole builtin. No staticMaterial/Eye semantics invented.')
 a=np.array(Image.open(B/f'original/{i}.png').convert('RGBA'));r['native_RGBA_extrema']=[list(v)for v in Image.fromarray(a).getextrema()]
 if i==6692:assert np.count_nonzero(a[:,:,:3].max(2))==1 and (a[127,0,:3]==255).all()
 if i==6703:assert not a[:,:,:3].any()
 if i not in CALL:continue
 lum=a[:,:,:3].mean(2);regions={}
 for name,b in boxes[i].items():
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];yy,xx=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);regions[name]={'native_bbox':b,'exact_source_RGBA_matrix':v.tolist(),'mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'min_RGB':v[:,:,:3].min((0,1)).tolist(),'max_RGB':v[:,:,:3].max((0,1)).tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())],'max_mean_source_xy':[x0+int(xx),y0+int(yy)],'max_mean_source_RGB':v[yy,xx,:3].tolist()}
 rowphase=[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum]
 colphase=[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T]
 counts={'entire_soft_curved_beard_paint_field':1,'rising_side_paint_lobes':2,'existing_dark_oval_gap':1,'original_bottomleft_corner_pixel':1}if i==6698 else{'source_hair_paint_banks':2,'soft_central_bridge':1,'faint_brow_paint_strokes':2,'original_bottomleft_corner_pixel':1}
 constraints.append({'id':i,'native_RGBA_SHA256':hashlib.sha256(a.tobytes()).hexdigest(),'source_whole_RGBA_matrix':a.tolist(),'native_RGB_extrema':[a[:,:,:3].min((0,1)).tolist(),a[:,:,:3].max((0,1)).tolist()],'nativeA_extrema':[int(a[:,:,3].min()),int(a[:,:,3].max())],'region_diagnostics':regions,'every_native_row_pigment_maximum_x':rowphase,'every_native_column_pigment_maximum_y':colphase,'source_feature_counts':counts,'count_phase_limits':'Entire original bitmap and every observed pigment maximum saved BEFOREprompt, including dim brow/corner pigment. Field rectangles are diagnostic domains, not physical segmentation or cropped/placed/composited images. Individual blurred brushstrokes/physical hairs are NOT assigned a guessed physical strand count: exact native brush texture/scale/phase/color remains the original full matrix.','actual_consumer':'TransformableFaceTextures→actualTHMID→actualHeads/ComplexHeads dynamic COLOR layer. AllactualsourceA/layerweights/completeUV preserved; not staticMaterials/hairModel or TransformableEyeTextures.'})
save(f'pattern-constraints-{ST}.json',constraints);save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json');save(f'scope-{ST}.json',{'ids':[r['id']for r in proof['source_checks']],'call_ids':CALL,'source_only_ids':list(reasons),'maximum_call_count':4,'honest_sourceonly_reaudit_allowed':True})
for c in constraints:
 i=c['id'];parts=['Use case: precise-object-edit. Historical Silent Storm softly PAINTED COLOR head overlay bitmap, faithful subdued high-resolution source paint.','Image1 is the EXACT entire native128x128 original RGBA with variable alpha. Image2 is the SAME entire native storedRGB source, solely whole NEAREST6x768 enlargement to expose its painted color. Edit the complete bitmap edge-to-edge at identical normalizedUV, using Image2 for original full stored color. Preserve all original pigment footprints/native phase/scale/local weak intensity, source blur and complete palette. Final complete ORIGINAL alpha will be independently restored; brightness is only one global numerical scalar. No physical face/head render or reinterpretation.']
 if i==6698:
  desc='Preserve EXACTLY ONE existing soft gray-beige curved painted BEARD field in native approximatelyx25..102,y47..96, with its TWO original softly rising side paint lobes and ONE original central dark OVAL gap inside its existing pale soft boundary. Keep exact curve/lobe/oval shape and asymmetric dim painted edges. Source is blurred softly stippled brushpaint, not a photo: retain the SAME visible native brush pattern phase/scale and very weak lower patches, WITHOUT drawing new beard hairs, physical fibers, pores, curls, sharper individual bristles, additional teeth/mouth/lips/nostrils or anatomy. Original background is the same dark warm brown paint, not a face to fill in. Keep original ONE white source pixel in bottom-left native[0,127], at the SAME normalized size/location, not omitted or enlarged into a new glint.'
 else:
  tint='muted warm graybrown'if i==6719 else'soft muted beige/graybrown'
  desc=f'Preserve the TWO existing {tint} upper/lateral HAIR PAINT banks, their ONE original central soft bridge, complete original asymmetric outline and dark brown lower color field. Keep ALL exact source brush tufts/waves at their original location/count/phase/scale; do not add individual photohair fibers, new locks, curls, radial strands, pores, photographic grain, stipples, mosaic, coarse paintcells, glints or a face. The TWO existing faint short BROW paint strokes at nativeleft[43,37,63,45] andright[65,37,86,45] retain their EXACT width/native positions/dim tint/blur; no eyes/iris/pupils/catchlights beneath them. Keep original tiny lower-left single source paintpixel native[0,127] RGB176/160/156, equally tiny and dim, not a white glint. Entire lower warm brown paint field stays its original mostly flat shade and softness, no new cloudfields/skin anatomy/ears/teeth. All source darker gaps and paint-bank edges remain softly painted, not raised metallic rims or new outlines.'
 parts +=[desc,f'Actual whole source RGB extrema are {c["native_RGB_extrema"]}, nativeA{c["nativeA_extrema"]}. Preserve dim local pigment strength and original light hierarchy. Refine only very subtly the same soft fine paint, no sharpening/raised edges/gloss/new highlights/new materialgrain. Do not brighten pale source strokes or fill dark parts into anatomy.','Output ONLY the SAME complete full source square. No crop/zoom/padding/whitespace/frame/cutout/fitting/repack/autoBBox/sourceRGB repair/rearrangement/new shapes/count/material. No new text/glyphs/symbols. Full originalA and default padding restored downstream.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Immutable source beforecall,12 fullRGBA/alpha proofs; FIRST sole planned',CALL)
