from pathlib import Path
import json,shutil,hashlib
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='heads-twenty-second';CALL=[6718,6721];ORIGINAL=[6703,6783]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def cc(m):
 seen=set();out=[]
 for y,x in zip(*np.where(m)):
  y=int(y);x=int(x)
  if(y,x)in seen:continue
  seen.add((y,x));todo=[(y,x)];ps=[]
  while todo:
   yy,xx=todo.pop();ps.append((yy,xx))
   for dy,dx in[(1,0),(-1,0),(0,1),(0,-1)]:
    z=(yy+dy,xx+dx)
    if 0<=z[0]<m.shape[0]and 0<=z[1]<m.shape[1]and m[z]and z not in seen:seen.add(z);todo.append(z)
  ys,xs=zip(*ps);out.append({'literal_alpha_positive_pixel_count':len(ps),'native_bbox':[min(xs),min(ys),max(xs)+1,max(ys)+1]})
 return out
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];actual=read(B/f'actual-records-{ST}.json');cons=[];groups={};rounds={};originals=[]
codeproof={'qualification':'Source-code binding evidence separately from actualDB rows: CFaceTexture.Import TextureID/THMID pushes owner.face; BuildTexLayers resolvesactual pTexture via GetSWTex, GetTextureWeights uses actualTextureName channel/priority; MixTexture completeRGB/sourceA perweighted src-over into face bake. Present registration doesnot imply measuredruntimeweight. Source0RGB+varA masks stillaffectopacity; fulloriginalRGBA mustremain.','files':[{'path':n,'file_SHA256':sha(ROOT/n),'relevant_lines':lines}for n,lines in[('DBFormat/DataFaceGen.cpp',[12,55]),('Main/LSHead.cpp',[970,1047]),('Main/FaceGenTextureSampling.h',[1,220])]]}
save(f'consumer-code-proof-{ST}.json',codeproof)
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];lum=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['source_RGBA_RGB_A_NN_privately_inspected']=True
 r['source_only_reason']='Genuine actual dynamicFaceGen COLOR layer or provedstaticMaterial source, completeRGB/A/nativeweakpattern complex. Honestprevioussource-only0call reaudit; remainsgenuinepending0call, not head/hair/human/A0/teeth/blacktexture familyban. Sourceweakpaint unchanged, no forced call or unknownanatomy interpretation.'
 r['FaceGen_binding_code_ref']={'path':(B/f'consumer-code-proof-{ST}.json').relative_to(ROOT).as_posix(),'file_SHA256':sha(B/f'consumer-code-proof-{ST}.json')}
 r['actual_FaceGen_layer_channels']=[{'table':v['actual_layer_table'],'id':v['actual_layer_ref']['id'],'THMID':v['actual_THMID_owner_ref']['id'],'TextureName':actual['tables'][v['actual_layer_table']][str(v['actual_layer_ref']['id'])]['TextureName'],'Priority':actual['tables'][v['actual_layer_table']][str(v['actual_layer_ref']['id'])]['Priority'],'full_THMID_sibling_layer_count':len(v['all_actual_THMID_texture_sibling_refs']),'actual_runtimeweight':'unknown/unmeasured'}for v in r['fresh_actual_dynamic_consumers']]
 if i in ORIGINAL:
  assert r['fresh_actual_dynamic_consumers'] and not r['fresh_actual_static_consumers'];assert a[:,:,3].min()!=a[:,:,3].max()
  if i==6703:assert(rgb==0).all();reason='Individualactualsource nativeRGB ALL0 across16384pixels; completeRGBA NOTconstant because sourceAvariable. ActualTransformableFaceTextures33/THMID1/Heads colorlayer/sourcealpha mask stillmeaningful src-over. No artisticRGBdetail beyondconstantblack for imagegen to improve, and sourceA silhouette cannot be changed. Retain exactfulloriginalRGBA/dimensions/nativeType/DB/opacitymask,0calls; NOTgeneric damage/head/alpha ban.'
  else:
   nz=rgb.max(2)>0;assert int(nz.sum())==1 and list(rgb[127,0])==[255,255,255];assert list(a[127,0])==[255,255,255,255];reason='Individualactualsource nativeRGB16383black+ONEwhite255authoringcorner(0,127), fullAvariable TWO originalbrowmask regions pluscorner. FullRGBA NOTconstant; actualTransformableFaceTextures43/THMID1/Heads weightedCOLOR layer. Blackbrowmask/sourcewhitecorner/fullA native authoringstructure retained exactly,0imagegen, not flat-grayfill or blackhair/headfamily ban. SourceRGBA notdiscarded or inferredempty fromblack.'
  r['source_only_reason']=reason
  originals.append({'id':i,'status':'recommended-original-only-individual-native-color-mask','reason':reason,'before_prompt':True,'call_count':0,'native_matrix_ref':r['native_matrix_ref'],'common_actual_records':r['common_actual_records'],'actual_dynamic_consumers':r['fresh_actual_dynamic_consumers'],'actual_FaceGen_layer_channels':r['actual_FaceGen_layer_channels'],'native_RGBA_nonconstant':True,'native_RGB_distinct_count':r['native_RGB_distinct_count'],'complete_native_alpha_SHA256':hashlib.sha256(a[:,:,3].tobytes()).hexdigest(),'literal_positive_alpha_4connected_components':cc(a[:,:,3]>0),'component_count_qualification':'Literalalpha bitmap domains only, no physicalparticle/anatomy count; exactallA native matrix retained.','corner_native_RGBA':a[127,0].tolist(),'no_builtin_call':True})
 if i not in CALL:continue
 assert r['material_evidence']['actual_source_native_type']=='Ordinary'and o.size==(128,128)and r['fresh_actual_dynamic_consumers']and not r['fresh_actual_static_consumers'];assert r['actual_FaceGen_layer_channels'][0]['table']=='TransformableFaceTextures'
 source=o.convert('RGB');roundtrip=source.resize((512,512),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS);rnd=np.array(roundtrip);rounds[str(i)]={'id':i,'source_size':[128,128],'recipe':'ENTIRE native storedRGB FIRST LANCZOS512 then entire LANCZOS128 independently fromsourceA, natural numericalblur diagnostic BEFORE call; noRGBA implicit premul or RGBartistpatch.','complete_native_RGB_roundtrip':rnd.tolist(),'source_corner_RGBA':a[127,0].tolist(),'natural_RGB_roundtrip_corner':rnd[127,0].tolist()}
 domains=[]
 boxes=[('complete original upper continuous hairpaint arch',[0,0,128,67]),('original left hairpaint bank',[0,0,56,67]),('original central upper hairpaint connector',[56,0,75,34]),('original right hairpaint bank',[75,0,128,67]),('original weak left browpaint',[43,36,62,45]),('original weak right browpaint',[67,36,86,45]),('original flat lower sourceRGB field',[2,69,128,127])]
 for name,b in boxes:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];rn=rnd[y0:y1,x0:x1];domains.append({'name':name,'bbox':b,'native_pixels_ref':{'source_matrix_key':str(i),'matrix_file_SHA256':r['native_matrix_ref']['file_SHA256'],'slice_native_xyxy':b},'mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'std_RGB':v[:,:,:3].std((0,1)).tolist(),'min_RGB':v[:,:,:3].min((0,1)).tolist(),'max_RGB':v[:,:,:3].max((0,1)).tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())],'natural_RGB_roundtrip_mean':rn.mean((0,1)).tolist()})
 pattern=[]
 for name,x0,x1 in [('leftbank',1,55),('rightbank',76,127)]:
  for y in[8,16,24,32,40,48]:
   xs=[x for x in range(x0,x1)if lum[y,x]>lum[y,x-1]and lum[y,x]>=lum[y,x+1]];pattern.append({'axis':'row','paintdomain':name,'native_y':y,'native_x_interval':[x0,x1],'literal_paintshade_maximum_count':len(xs),'native_maximum_x':xs,'native_successive_pitch':[b-a for a,b in zip(xs,xs[1:])],'qualification':'SourceCOLOR paint maxima/phase only, NOTnumberofphysicalstrands/locks/individualhairs nor allowance tonewlocks/fibers.'})
 dominant=r['dominant_RGB_count_values'][0]['RGB'];description=f'Keep ONE original connected upper hairCOLOR painted arch with same left/right banks and centerconnector/irregularoutline; exactly TWO original existing faint browpaint patches around native x43..62 and67..86,y36..45, same nativeUV/weakness/width. These are existing COLOR fields of FaceGen layer, not newmesh/curl/locks or anatomicalface. Preserve EVERY existing original directional brushshade/softwave and its tiny nativepositions/phase/paintscale; no newphysical hairstrands/radialfibers/mosaic/checkerpattern/coarse outlinedlocks/individualhaircount interpretation. Keep lower nativefield x2..128,y69..127 FLAT originalRGB {dominant}, even sourceA0 RGB remains authored/useful, no mottledbackground/grayreplacement/coloredgrain. Preserve exact ONE original authored cornerpigment sample atnative(0,127), actualRGBA {a[127,0].tolist()}, without addingglints elsewhere; no reinterpretation asface. NativeOrdinary straightRGB/noPremul, originalcompletevariableA separatelyrestored. Do notstrengthen dim existingbrow/graypaintpatches or sharpen originalhairblur.'
 cons.append({'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':[128,128],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':{'upper_continuous_hair_COLOR_arch':1,'original_weak_browpaint_patches':2,'source_authored_corner_pigment_sample':1},'native_repeat_count_phase_evidence':pattern,'count_qualification':'Observed nativeCOLORpaintfields only, ONEupperarch/TWObrows+authoringcorner. ExactallsourceRGB/A/weakpigment proof authoritative once. Diagnosticdomain bboxes not crop/UV/islandfitting, literalmaxima nothair physicalstrandcounts. All original directionalwave counts/sourcephase/weakstrength preserved.','native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_sourceA0_pixel_count':int((a[:,:,3]==0).sum()),'sourceA0_native_storedRGB_mean':rgb[a[:,:,3]==0].mean(0).tolist(),'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'source_description':description,'actual_consumer':r['actual_FaceGen_layer_channels'],'natural_RGB_roundtrip_pending_common_ref':True})
 r['source_only_reason']='EligibleFIRSTafterexactfull nativeRGB/A/NN/weakphase/count/material/palette/sourceblur/actualTransformableFaceTextures→THMID→Heads/ALLsibling layer sourceproof/historyrelease parity. Genuine FaceGenhair COLOR layer, notstaticHairmodel/geometry inference.'
rp=B/f'natural-roundtrip-{ST}.json';save(rp.name,{'sources':rounds,'before_call':True})
for c in cons:c.pop('natural_RGB_roundtrip_pending_common_ref');c['natural_RGB_roundtrip_ref']={'path':rp.relative_to(ROOT).as_posix(),'file_SHA256':sha(rp),'source_key':str(c['id'])}
save(f'pattern-constraints-{ST}.json',cons);save(f'original-only-proof-{ST}.json',originals);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL+ORIGINAL],'recommended_original_only_ids':ORIGINAL});save(f'source-check-{ST}.json',P);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Asset type: existing softpainted FaceGen hair/brow COLOR UV bitmap. Faithfully edit the exact ENTIRE original bitmap at higher resolution, preserving originalsoftpaint/material/nativebrushscale/sourceblur/palette/weakpigment/normalizedUV, no newgeometry or reinterpretation.', 'Image1 is ENTIRE exact edit target original128x128 storedRGB madeopaque at ORIGINALnative resolution. No NN enlargedtoolguide; nativepaintsoftness is authoritative. Original completevariableA separatelyrestored withstandardwholebrightnessscalar/defaultpadding; NativeOrdinary uses straightRGB/noPremul. ActualTransformableFaceTextures→THMID1→Heads dynamichair COLOR blendinglayer, NOTstatic hairmesh/anatomicalface.',c['source_description'],f'Exact source fullRGBA extrema {c["actual_RGBA_extrema"]}; source globalstrongestRGBA {c["native_source_max_mean_RGBA"]} at {c["native_source_max_mean_RGB_xy"]}. This includes ONEexistingauthored cornerpigment sample, notnewhairhighlight. Keep originalupperhair localbright/dim patches/sourcehuehierarchy/brushphase and browweakstrength. No brighter gray rims/gloss/glare/newcatchlights/pores/teeth/skin/anatomy/hairfiber reinterpretation/addedlocks/sharpstrand outlines.', 'Add only subtle fine rendition of SAME existing sourcepaint brushdetail. No photohair/syntheticstrand/fibertexture/directionalgrid/mosaic/coarsecells/backgroundmottle/newpaint-clouds or losing flatcolored storedRGB under sourceA0. Every nativepaint/weakgray/brown patch and fullsourceA kept; no grayfill replacinghairpaint.', 'Output ONLY SAME ENTIRE SQUARE opaqueRGB originalUVcanvas. No crop/whitespace/border/frame/padding/cutout/zoom/BBox/fitting/recenter/islandmove/photographichead/portrait. Preserve originalirregularhair silhouette, fullflatlowerfield and ONEoriginalauthored cornerpigment sample. No newparts/letters/glyph/logo or multipliedbrows.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Heads22 immutablebefore12/2FIRST/2originalrecommend8genuinepending',[(c['id'],c['actual_consumer'],c['native_sourceA0_pixel_count'],c['native_source_max_mean_RGBA'])for c in cons]);print('Originalonly alpha components',[(r['id'],r['literal_positive_alpha_4connected_components'])for r in originals])
