from pathlib import Path
import json,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='equipment-forty-second';CALL=[1915,1919,1920]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];cons=[];groups={}
boxes={1915:[('source complete dark diagonal brownpaint field',[0,0,34,45]),('source top right bluishgray horizontalpaint rectangle',[25,4,64,18]),('source original central gray darklooppaint',[30,28,53,49]),('source complete lowergray paintband',[2,43,64,64]),('source weak upperleft gray angledpaint',[4,5,16,17])],1919:[('source reddishbrown soft vertical curvedpaint band',[0,0,34,45]),('source upperright grayhorizontalpaint rectangle',[31,12,61,23]),('source central darkgray loopoutlinepaint',[29,27,54,45]),('source lowergray horizontalpaint band',[1,41,64,64])],1920:[('source upperleft gray rectangularpaint',[0,0,43,15]),('source upperright mutedolive finealternating paintfield',[41,1,64,42]),('source middleleft gray paintfield with originaldarkcurve',[0,13,45,42]),('source lowerleft gray field surrounding originaldarkquadrilateral',[0,35,39,64]),('source lower middlegraygreen paintfield',[25,42,48,64]),('source lowerrightgray horizontalpaint band',[45,51,64,64])]}
counts={1915:{'source_dark_brown_broad_paintfield':1,'source_top_right_gray_paintrectangle':1,'source_central_gray_darkloop_paint':1,'source_lower_gray_paintband':1,'source_weak_upperleft_gray_angledpaint':1},1919:{'source_brown_broad_vertical_paintband':1,'source_upperright_gray_paintrectangle':1,'source_central_gray_darkloop_paint':1,'source_lowergray_paintband':1},1920:{'source_upperleft_gray_paintrectangle':1,'source_upperright_grayolive_fine_repeatpaint':1,'source_middleleft_graypaintregion':1,'source_lowerleft_graypaintregion':1,'source_lower_middlegraygreen_paint':1,'source_lowerright_graypaintstrip':1}}
descs={1915:'Keep the SAME ONE soft diagonal darkbrown paintfield on the left, ONE bluishgray horizontalpaint rectangle at top right, ONE original faint gray angledpatch upperleft, ONE centralgray darkloop paintform, and ONE broad lowergray paintband with ALL of its existing tiny irregular sourcepaint shapes/black gaps and short pale segments. Preserve original dim charcoal/brown/coolgray palette and fullsource flatblackUV including opaque A255. These are source bitmap paintforms ONLY, not an assembled object nor newlyinterpreted mechanisms/bolts/levers. Keep soft brownwash and faintbluegray paint exactly at source coordinates and strength; no photosurface/hair/grain/carvedline/brightwhiteedge. Every original weakpaint and blackfield remains, no wash-to-physicalparts.',1919:'Keep SAME ONE original warm muted brown curvedvertical paintband occupying leftupper/center, its existing softlypainted shallow horizontal pigment variations at identical native pitch/phase/number and weakcontrast, ONE original small bluishgray horizontalpaint rectangle upperright, ONE centralgray darkloop paintoutline and ONE original lowergray horizontalpaintband with its exact black gaps/short pale lines and tiny original marks. The upperleft darkbrown paintedmark/pigment must stay as the original uncertain sourcepaint, not become a screw/logo/glyph/engraving. Preserve brownwash as matte fine PAINT, no raisedribs/carvedwood/physicalgrain/rust/new shine. No new stripedtexture pattern or strengthened shallowwash lines. Entiresource flatblackUV/A255 remains opaque authoredblack, not newholes/backgroundnoise.',1920:'Keep SAME ONE source upperleft graypaint rectangle, ONE upperright slanted irregular mutedolive/darkgray finealternating paintfield, source middleleftgray field around its original darkcurvedoutline, original lowerleftgray field around a blackquadrilateral, original lower middlegraygreen field and lowerrightgray paintstrip. Preserve every original diagonal tiny paintshade at exactly same normalized nativephase/pitch/count and weakpaintstrength; it is fine shaded bitmap paint, not new raisedknurl/physicalstuds/coarse wovenfiber/etchedgrid. Preserve original upperright irregular silhouette and softlylit oliveedge without making newbright raisedrim. No regularization of source irregularrepeat/width. Every original vague graypatch/shortline stays sourcepaint, not added hardware. Preserve blackopaqueUV holes/gaps at exact source locations and existingtiny localhighlight extent/strength; do not invent bolts/levers/whiteedge/physical bevel.'}
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];lum=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];assert r['fresh_actual_static_consumers']and not r['fresh_actual_dynamic_consumers'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['source_RGBA_RGB_A_NN_privately_inspected']=True
 r['source_only_reason']='Genuine actual Material→TemplateID→Models diffuse painted COLOR bitmap. Complete originalRGBA/RGB/A/NN nativeview/historyrelease/actualroles fresh re-audit, earlier0call views acknowledged. Fine irregularpaint/weakpigment/native countphase requires faithful firstgeneration review; pending genuine sourceart0call, not technical/familyban. No unknownhardware interpretation.'
 if i in [3035,3039,3914,5402]:r['source_only_reason']='Actual genuine painted diffuse with tiny indistinct coded/ornamental sourcepaintmarks and precise partlayouts; their contents cannot be guessed or replaced by invented glyph/hardware. FullnativeRGBA remains genuinepending0call; no technical/analytic ban.'
 if i not in CALL:continue
 assert r['material_evidence']['actual_source_native_type']=='Ordinary'and(a[:,:,3]==255).all()and o.size==(64,64)
 domains=[]
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);domains.append({'name':name,'bbox':b,'native_pixels_ref':{'source_matrix_key':str(i),'matrix_file_SHA256':r['native_matrix_ref']['file_SHA256'],'slice_native_xyxy':b},'mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'min_RGB':v[:,:,:3].min((0,1)).tolist(),'max_RGB':v[:,:,:3].max((0,1)).tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())],'native_peak_xy':[x0+int(x),y0+int(y)],'native_peak_RGBA':v[y,x].tolist()})
 pattern=[]
 if i==1919:
  for x in [8,12,16,20,24]:
   ys=[y for y in range(12,41)if lum[y,x]>lum[y-1,x]and lum[y,x]>=lum[y+1,x]];pattern.append({'axis':'column','native_x':x,'native_y_interval':[12,41],'literal_paintshade_maximum_count':len(ys),'native_maximum_y':ys,'native_successive_pitch':[b-a for a,b in zip(ys,ys[1:])],'qualification':'Exact faint COLOR pigment maxima only, not physicalribs/strands/hardware.'})
  descs[i]+=' Exact original nativecolumn16 shallowpaint maxima in y12..41: '+str(pattern[2]['native_maximum_y'])+' (count '+str(pattern[2]['literal_paintshade_maximum_count'])+'), retain identical shallowstrength/phase.'
 if i==1920:
  for y in [8,12,16,20,24,28,32]:
   xs=[x for x in range(43,61)if lum[y,x]>lum[y,x-1]and lum[y,x]>=lum[y,x+1]];pattern.append({'axis':'row','native_y':y,'native_x_interval':[43,61],'literal_paintshade_maximum_count':len(xs),'native_maximum_x':xs,'native_successive_pitch':[b-a for a,b in zip(xs,xs[1:])],'qualification':'Exact shaded sourcepaint maxima/phase within irregularfield, NOTphysicaldiamonds/studs nor additionalgrid authorization.'})
  descs[i]+=' Exact originalpaint maxima row16 within native x43..61: '+str(pattern[2]['native_maximum_x'])+' (count '+str(pattern[2]['literal_paintshade_maximum_count'])+'); row24 '+str(pattern[4]['native_maximum_x'])+' (count '+str(pattern[4]['literal_paintshade_maximum_count'])+'). Keep SAME original tinyphase/count/scale, no newlargerchecker.'
 cons.append({'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':list(o.size),'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':counts[i],'native_repeat_count_phase_evidence':pattern,'count_qualification':'Counts observed original COLOR paintfields only, no mechanisms/physicalparts inferred from blur. Fullnative exactRGB/A/weakpigment matrix authoritative once; these diagnosticdomains NOT UV fitting/cropping/island registration. Everypaintshape/weakphase preserved; no inventedsemantic partcounts.','native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_blackRGB_A255_pixel_count':int(((rgb.max(2)==0)&(a[:,:,3]==255)).sum()),'native_positive_weak_RGB_max_le5_pixel_count':int(((rgb.max(2)>0)&(rgb.max(2)<=5)).sum()),'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'source_description':descs[i],'actual_consumer':'Fresh actualMaterials.TextureID→TemplateID→Models.MaterialN withModelTemplates/Geometries refs. Ordinary/sourceA255; Alpha/AddressMode exactsourceproof, mesh/runtime UV/hardware interpretation unknown.'})
 r['source_only_reason']='FIRST solebuiltin eligible after full originalnativeRGB/A/NN/blur/count/phase/weakzero/color proof and exactactualMaterials→TemplateID→Models/historyreleaseRGBA. No previous raw/call/jobs/held or exactRGBA donor; prior0call source-only re-audit honest.'
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[]});save(f'source-check-{ST}.json',P);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Asset type: existing handpainted color diffuse equipment UV bitmap. Faithfully edit the exact ENTIRE original bitmap at higherresolution, retaining SAME sourcepaint/material/blur/nativepatternscale/color palette and precise normalizedUV/count/phase. This remains a PAINTED UV texturemap, not a physicalobject photo or assembly.', 'Image1 is ENTIRE exact edit target original64x64 storedRGB madeopaque at original resolution, NO NN enlargement/toolpixelblockguide. OriginalcompleteA255 and standardwhole numericalbrightnessscalar restored separately downstream; NativeOrdinary straightRGB/noPremul. Preserve fullsource canvas with every irregular authoredblack/dimRGB region including A255; no addedmottle or brightenedUVgaps.',descs[i],f'Actual fullsource RGBA extrema {c["actual_RGBA_extrema"]}; strongest originalnativeRGBA {c["native_source_max_mean_RGBA"]} at {c["native_source_max_mean_RGB_xy"]}. Keep exact original weak localpaint relationships/dimness/blur, preserve strongest patches SAME extent/strength rather than brighterglints. Nativecoordinates given as original64pixels mapped to normalizedwholecanvas. Everyweakpigment/zero/color patch is authoritative, no newparts from ambiguous shapes.', 'Add only subtle fine rendering of SAME existing matte sourcepaint, retain original softshading/sourceblur. NO photoetchedmetal/shinymetal/grain/newknurl/weave/embossing/hardraisedrims/rust/scratches/fiber/mosaic/coarsecells/newregularlines/newhighlight/white edge/bolts/straps/mechanisms/letters/glyph/symbol/logo. No sharpened silhouette or new repeatedshapes.', 'Output ONLY SAME entire originalaspect SQUARE opaqueRGB sourceUVcanvas. No white/graypadding/borders/whitespace/frame/cutout/cropping/zoom/recenter/BBox/fitting/repacking/islandmoves/physicalassembledobject/photograph. Preserve complete original blackfield; materialcounts/phase/patternscale/blur/sourceA unchanged.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Eq42 immutable BEFORE12/3FIRST eligible native64/ordinaryA255',[(c['id'],c['native_source_max_mean_RGBA'],c['native_zero_RGB_pixel_count'],c['native_positive_weak_RGB_max_le5_pixel_count'],[(p.get('native_x',p.get('native_y')),p['literal_paintshade_maximum_count'])for p in c['native_repeat_count_phase_evidence']])for c in cons])
