from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='effects-twenty-third';CALL=[5261,2118]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'));cons=[]
reasons={2523:'Genuine orange/violet explosion paintfield with many original thin rays and sparse weak flecks; exact fragment/weakfleck phase not established for bounded call, source-only pending0calls, no analytic/technical classification byname.',2575:'Genuine softly painted orange-brown irregular firefield with multiple dim lobes/cores/gaps. Original complex lobe/finepigment counts not fully proved here, source-only pending0calls; missing actual definitions remain unknown independently.',2577:'Genuine orange-brown looping soft firefield with original darkvoids/asymmetric strokes; exact sublobe/weakedge phase not established, source-only pending0calls, no blanket familyban.',2626:'Genuine bluegray watery softpaint field with original multiple brighter cores/weakfragments; all original weakfields/counts need separate detailed proof, pending0calls.',2627:'Genuine bluegray diffuse with many separate dim small painted water/fragments; exact smallcomponent phase/count not established, pending0calls, not analytical byname orA0.',2628:'Genuine bluegray sparse soft painted waterstreaks and weakbits; exact streak count/phase unresolved, pending0calls.',2629:'Genuine bluegray many thin dim diagonally painted waterstreaks; exact count/pitch/phase unresolved, pending0calls.',717:'Genuine sparse dim brown remnant paintpatches/weakbits; no new fragments/intensity strengthening, source-only pending0calls.',901:'Genuine sparse dim brown cloudremnants, allweakbits/count unresolved for faithfulcall, pending0calls; sameRGBA source-only siblings are not accepted donors.',902:'Genuine sparse dim brown remnant clouds/weakspots; every original faintbit matters, fullbounded count proof not established, source-only pending0calls.'}
boxes={5261:[('entire original asymmetric beige soft field',[0,0,16,16]),('original upper left dim beige lobe',[3,3,9,8]),('one original brighter center',[6,6,10,10]),('original lower right beige extension',[7,8,13,14]),('original very dim perimeter',[0,0,16,16])],2118:[('original upper right soft gray field',[14,1,28,14]),('original left center soft gray field',[1,9,14,20]),('original stronger lower center soft gray field',[6,17,21,32]),('original very weak lower right gray field',[22,19,31,30]),('all original weak discrete paintpixels and dark gaps',[0,0,32,32])]}
for r in proof:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];l=rgb.mean(2)
 r['full_original_RGBA_private_view']=True;r['full_source_RGB_private_view']=True;r['actual_source_RGBA_extrema']=[list(z)for z in o.getextrema()]
 r['previous_source_only_views']=[p.relative_to(B.parents[2]).as_posix()for p in sorted(B.rglob(f'{i}-*source*.png'))if ST not in p.as_posix()][:10]
 r['view_novelty']='Honest source-only fresh re-audit where earlier native views exist; raw/calls/jobs/accepted/held/exactRGBA guards separate. No first-ever-view claim.'
 r['source_only_reason']=reasons.get(i,'Genuine sourcepainted soft color fields, exact complete nativeRGBA/weakpigment/phase/localstrength/count BEFORE firstsolecall. SourceA independently preserved and nativeType semantics explicit, no structural sourceclassification fromA0.')
 if i not in CALL:continue
 y,x=np.unravel_index(l.argmax(),l.shape)
 c={'id':i,'before_prompt':True,'native_size':list(o.size),'source_RGBA_sha256':hashlib.sha256(o.tobytes()).hexdigest(),'actual_RGBA_extrema':[list(z)for z in o.getextrema()],'whole_native_RGBA_matrix':a.tolist(),'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l.T],'native_source_max_mean_RGB_xy':[int(x),int(y)],'native_source_max_mean_RGBA':a[y,x].tolist(),'semantic_qualification':'Counts mean sourcepaint tonefootprints, NOT physicalparticles/feathers inferred fromthresholdRGBA components. All weak nativeRGB/A pixels preserved in complete matrix; regionboxes only numeric diagnostics, NEVER cropped/composited/fitted/artistrepair references.','source_domains':[]}
 if i==5261:
  assert [x,y]==[8,8]and rgb[y,x].tolist()==[214,190,120]and not a[:,:,3].any()
  c['source_feature_counts']={'complete_asymmetric_beige_softpaint_footprint':1,'brighter_center':1,'qualification':'One whole compact soft painted field, slightly elongated diagonal lobed tone; no new physical flame tongues or count frompositivepixelmask. A0TransparentAdd usefulRGB, no packpremultiply.'}
 else:
  c['source_feature_counts']={'original_broad_soft_gray_paint_fields':4,'qualification':'Upperright/leftcenter/lowercenter/veryweaklowerright bitmap domains; source shapes overlap faint pixels. This is not exact physical feather/particle count. Weak sourcepixels outside four main fields also retained; no invented finefibers.'}
  c['before_prompt_survey_correction']='Initial smallsurvey description3grayfields corrected BEFOREprompt/tool: whole storedRGB/alpha reveals FOUR, including faintlowerright. Old frozen source-only audits untouched; complete nativeRGBA authoritative.'
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=rgb[y0:y1,x0:x1];aa=a[y0:y1,x0:x1,3];c['source_domains'].append({'name':name,'bbox':b,'native_RGB':v.tolist(),'mean_RGB':v.mean((0,1)).tolist(),'max_RGB':v.max((0,1)).tolist(),'sourceA_extrema':[int(aa.min()),int(aa.max())]})
 cons.append(c)
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in proof],'sole_call_ids':CALL,'maximum_call_count':3,'pending_uncalled_ids':[r['id']for r in proof if r['id']not in CALL]});save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for i in CALL:
 c=next(x for x in cons if x['id']==i)
 parts=['Use case: precise-object-edit. Historical Silent Storm soft PAINTED diffuse COLOR effect source bitmap, faithful higher resolution shade; not new physical smoke/fire/object rendering.', 'Image1 is the EXACT ENTIRE native storedRGB source, solely whole NEAREST enlargement to512, made opaque to expose original color. Preserve COMPLETE edge-to-edge normalizedUV/field positions/shapes/count/phase/nativepaintscale/palette/relativeweak strengths. Keep original SOFT BLUR and smooth subdued painted shade. Final FULL ORIGINALalpha is restored independently and brightness only ONE global numeric scalar. No padding/crop/cutout/fitting. The nearest support visible sourcepixel sampling is only for exactUV: do not add squaredcells/grid/mosaic/granules or coarse mottledpaint. Render same gently blurred source tones, never make cells/stipples visible.' ]
 if i==5261:
  desc='Native16x16 source is EXACTLY ONE compact softly blurred asymmetrical BEIGE/GOLD diffuse paint field on black, with ONE original broader brighter center at native[8,8] RGB214/190/120, dimmer upper-left lobe and lower-right soft extension. Keep EXACT native diagonal elongation/soft footprint, core size/position/shape, subdued beige/brown hierarchy and every verydim original perimeter pixel. It is not a white-hot fireball; do not whiten core or add new glowstrength, firetongues, rays, sparks, granules, curls, clouds, holes or fragments. Keep palette warm beige/gold, not orangeflame. Original nativealpha is0 across WHOLE canvas but RGB is useful visibleTransparentAdd source; no newalpha mask or opaque black border geometry.'
 else:
  desc='Native32x32 source has EXACT FOUR existing softly blurred DARK GRAY paint fields: original upper-right field nativeapproximately[14,1,28,14], left-center[1,9,14,20], stronger lower-center[6,17,21,32] and VERY WEAK lower-right[22,19,31,30]. Keep exact complete asymmetric silhouettes/positions/width/phase/scale and all original faint nativepixels beyond these fields. Lower-right stays extremely faint, not omitted or strengthened into a brighter new fragment. These are source painttone footprints, NOT a request to draw physical feathers or clouds. SourceRGB is dim MAX53/54/57 and originalalpha0..81, notwhite; do not brighten cores locally. Preserve smooth original darkgray softness, relative hierarchy and black gaps; no new strands/fibers/featherbarbs/veins/rockgeometry or differentmaterial, no added stipples/cells/cloudlobes/dots.'
 parts +=[desc,f'Exact original wholeRGBA extrema are {c["actual_RGBA_extrema"]}. Preserve actual dim sourcechannel maxima/relative localstrength, not manual255 or cosmeticcontrast. No newparticles/forms/rays/tongues/flecks/photonoise/paintgrain/hairfibers/raisedrims/highlights/whiteglints/text/symbols. Source is deliberately soft, no highpass/sharpenededges.','Output ONLY ENTIRE SAME opaqueRGB square canvas, identical wholeUV/no frame/whitespace/padding/recenter/crop/zoom/BBox/repacking/artistpatches. Entire originalsourceA/nativeType restored downstream, no sourcealpha or composition changes.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
for filename in ['preview_effects_twenty_third.py','detail_effects_twenty_third.py']:
 p=B/filename;p.write_text(p.read_text(encoding='utf-8').replace('IDS=[5261]','IDS=[5261,2118]'),encoding='utf-8')
print('Immutable BEFOREcall12proof,2FIRST planned, FOUR2118 grayfields inclweakright')
