from pathlib import Path
import json,shutil,hashlib
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='clothing-fiftieth';CALL=[2353];ORIG=[1885,1893]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];groups={};rounds={};constraints=[];original=[]
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];lum=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['source_RGBA_RGB_A_NN_privately_inspected']=True
 r['source_only_reason']='Genuine actualstaticMaterials→TemplateID→Models paintedCOLOR source. Exactfullnative/history/release/A/type/consumers proven; complex existingweakmarks/sourceblur/material/nativephase requireliteralcounts beforeanyFIRST, genuinepending0call without name/type/familyban or inferredphysicalparts.'
 if i in [801,1760,1761,1762,2446]:r['source_only_reason']='Genuinecolored smallinsignia/diamond/oldglyphpaint onblacksource withvariableA; fullstoredRGB/alpha preserved, not technical fromOrders/name orA0. Specific tiny existingglyph/oldstroke identities andweakphase needexactliteralproof; no symboliccontent reinterpretation/newlettering, pending0call.'
 if i in [5682,5689]:r['source_only_reason']='Genuine full512x256 mattepainted red orgray metalatlas witholdwear/arcs/smallribs/markedglyphs andmanytinyshadefields. Sourceparts/count/pitch/phase notfullydescribed here beyondcompleteRGBA matrix, pending0call without Robot/name/materialban; notguesshardware orinventgrain/relief.'
 if i==2016:r['source_only_reason']='Individualsource27RGB browncoloredpolygon withvariableA0/255 onblack128canvas, actualdiffuseconsumer. NotconstantRGBA andno provenanalyticalpurpose; preserving exactflatpaint/boundary/UV/materialrequiresclarification, genuinepending0call NOToriginal-onlytechnical frompolygon/name/A.'
 if i==6365:r['source_only_reason']='Genuine471RGB originaldeliberatelyinverted face/hair warmdimpaint withintentionalblur, actualstaticdiffuse. Exactweakidentity/paintphase/material retained; genuinepending0call, no face/human/nameban.'
 if i in ORIG:
  assert np.all(a==0)and r['material_evidence']['actual_source_native_type']=='Ordinary'and r['fresh_actual_static_consumers'][0]['actual_Alpha_AddressMode']==['alpha_test','Clamp'];r['source_only_reason']='Individual ORIGINAL-ONLYrecommendation pendingroot: EVERYnativeRGBAbyte0 andALLstoredRGB0, Ordinary sourceA0; fullhistorical/release exactRGBA/binary andactualalpha_test Clamp Materials→TemplateID→Models consumer. ConstantRGBA exactpixels, no hiddenusefulRGB orpaint inferred. Rootfunctional/nativefinalclassification required; no group/type/A blanketban.'
  original.append({'id':i,'status':'individual-original-only-fullconstant-zeroRGBA-recommendation-rootreview','call_count':0,'reason':r['source_only_reason'],'fullconstantRGBA_proof':{'native_size':list(o.size),'pixel_count':o.width*o.height,'one_distinct_RGBA':[0,0,0,0],'sourcehistorical_release_exact':True},'native_matrix_ref':r['native_matrix_ref'],'common_actual_records':r['common_actual_records'],'actual_consumers':r['fresh_actual_static_consumers'],'previoussource_only_exactRGBA':{'id':4518,'call_count':0,'qualification':'1885 sameFULLRGBA/dims/Type asprevioussource-only4518 recommendation, noaccepted/generated donor claim. 1893 hasdifferent64x128 dimensions. Individualfreshactualconsumers/sourcepayload re-audit, not neverviewedpayload fiction.'},'not_runtimeaccepted':True})
 if i not in CALL:continue
 assert o.size==(128,128)and o.getchannel('A').getextrema()==(255,255)and r['fresh_actual_static_consumers'];rnd=np.array(o.convert('RGB').resize((512,512),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS));rounds[str(i)]={'id':i,'source_RGB_LANCZOS4x_then_native_RGB_matrix':rnd.tolist(),'recipe':'EntireRGB FIRST independentlyA 4x LANCZOS thenwhole nativeinverse/noPILpremul/crop/registration/patch.'}
 boxes=[('ONE upperleft verticalpaintstrip',[0,0,27,61]),('ONE lowerleft verticalpaintstrip',[0,58,27,128]),('ONE rightverticalpaintstrip',[100,0,128,128]),('ONE centralconnectedkhakipaintfield',[27,0,101,128]),('ONE smalltopcentralpolygonpaint',[39,16,79,33]),('ONE oldcentraldarktrapezoidpaint',[45,53,80,77]),('ONE existingleftthin horizontalpale line',[0,57,28,62]),('ONE existingthin grayrectangularoutlinepaint withONEstem',[0,64,24,80]),('FIRSTexistingpalesquarepaint',[32,70,40,77]),('SECONDexistingpalesquarepaint',[87,70,95,77]),('FIRSTexistinglowerhorizontalgraystroke',[49,78,62,87]),('SECONDexistinglowerhorizontalgraystroke',[63,78,77,87]),('ONE existingpale roundpaintpatch',[46,92,78,114]),('ONE existingredpluspaint insideoldroundpatch',[54,96,70,111])]
 domains=[]
 for name,b in boxes:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);domains.append({'name':name,'bbox':b,'native_pixels_ref':{'matrix_ref':r['native_matrix_ref'],'slice_native_xyxy':b},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_std_RGB':v[:,:,:3].std((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'source_peak_xy':[x0+int(x),y0+int(y)],'source_peak_RGBA':v[y,x].tolist(),'sourceA_extrema':[255,255]})
 profiles=[]
 for axis,coord,z0,z1 in [('column',12,64,125),('column',110,1,125),('row',59,1,29),('row',73,1,101),('row',82,45,83),('row',102,46,79),('column',63,92,116)]:
  v=lum[coord]if axis=='row'else lum[:,coord];xs=[z for z in range(z0,z1)if v[z]>v[z-1]and v[z]>=v[z+1]];profiles.append({'axis':axis,'native_fixed_coordinate':coord,'native_axis_interval':[z0,z1],'literal_paintshade_maximum_axis_coordinates':xs,'literal_count':len(xs),'native_successive_pitch':[b-a for a,b in zip(xs,xs[1:])],'qualification':'Literalpaintpigment weakmarks/nativephase, NOTphysicalbelt holes/fasteners/rivets/buckles counts oracceptance thresholds. FullRGBApixels authoritative.'})
 desc='ENTIRE original128square softlyfiltered MATTEkhaki/olivebrown cloth-leather paintedUVatlas. Preserve exactly ONE connectedcentralpaintfield anditsold darktrapezoid/topsmallpolygon; upperleft/lowerleft/rightlongpaintstrips inSAMEpositions/nativewidths; ONE existingthin horizontalpaleline leftx0..27,y57..61; ONE oldthin grayrectangularoutline/stem leftx0..23,y64..79; TWOexistingpalesquarepatches x32..39 and87..94,y70..76; TWOexistinglowergrayhorizontalstrokes x49..61 and63..76,y78..86; ONEexisting paleROUNDpaintpatch x46..77,y92..113 withONEoldredPLUSpaint x54..69,y96..110 inside it. Preserve thisSAME oldplus FOURarms/matteflatpalette/proportions, no newlogo/text/number/characters. These are literaloldpaintdomains, not license to inventphysicalhardware/rivets/buttons/bucklemechanisms. Keep allsourceblackUV asoriginalauthoredA255paint, allsourceweakstrap specks/creasewashes EXACTnativecount/spacing/phase. Existinggrayoutline remains thinflatfilteredpaint, no chrome/raisedrim/metallikegrain/extra screws. Existingredplus andpalecircle remain softflatpaint, not embroideredpatch/glow or badgegeometry. Keeporiginaldimkhaki/olivebrownrelativevalues/softblur/nativepaintscale, NO newlyrendered clothweave/fibers/roughleather/photo grain/castmetal/highcontrastgloss/strongwhiteedges/newseams/raisedcreases/extra pockets/straps/bars/dots/holes/loops or decorativepatterns.'
 c={'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':[128,128],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':{'centralpaintfield':1,'verticalpaintstrips_upperleft_lowerleft_right':3,'leftthinpaleline':1,'grayrectangularoutline_stem':1,'palesquarepaintfields':2,'lowerhorizontalgraystrokes':2,'paleroundpaintpatch':1,'existingredpluspaint':1,'existingplusarms':4},'native_repeat_count_phase_evidence':profiles,'native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_sourceA0_pixel_count':0,'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'source_description':desc,'qualification':'LiteraloriginalCOLOR painting regions/weakcounts/phase beforetool, not assumedphysicalmechanism. Descriptiveoverlappingbboxes notcrop/registration. CompleteRGBA/nativepalette/sourceblur authoritative.'};constraints.append(c)
 r['source_only_reason']='EligibleFIRST originalwhole mattekhaki cloth-leather128 UVpaint withliteralparts/weakmarks/nativephase/count/oldplus Fourarms beforeproof; nativeRGBA/historyrelease/POT/OrdinaryA255/actualstaticMaterials→TemplateID→Models. No symbolreinterpretation orphysicalhardware/newweave/gloss/grain; sourceblur/nativepaintscale preserved.'
save(f'natural-RGB-roundtrip-{ST}.json',{'sources':rounds,'before_call':True});rp=B/f'natural-RGB-roundtrip-{ST}.json'
for c in constraints:c['natural_RGB_roundtrip_ref']={'path':rp.relative_to(ROOT).as_posix(),'file_SHA256':sha(rp),'source_key':str(c['id'])}
save(f'pattern-constraints-{ST}.json',constraints);save(f'original-only-proof-{ST}.json',original);selected=read(B/f'selected-{ST}.json');save(f'selected-original-only-{ST}.json',[{**r,'worker_original_only_recommendation':next(o for o in original if o['id']==r['id'])}for r in selected if r['id']in ORIG]);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL+ORIG],'recommended_original_only_ids':ORIG,'all_selected_outside_previousClothing1to49':True,'pending_exactRGBA_alias_qualification':'12newIDs, commonpendingpayload groups disclosed. 1885 exactRGBA toprevioussource-only4518 zero recommendation0calls, noaccepted/generated donor. No artisticcalls onanyaccepted/generated/heldsameRGBA.'});save(f'source-check-{ST}.json',P);assert not(B/f'source-check-{ST}-before-call.json').exists();shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in constraints:
 i=c['id'];parts=['Use case: precise-object-edit. Asset type: full softlyfiltered MATTEcloth/leather UVdiffusecolor painting. SubtleHD versionofSAMEoriginalpaint only, preserving blur/nativepaintscale/material/count/weakphase/UV/sourcepalette.', 'Image1 edit target is ENTIRE native128square storedRGBopaque atoriginalresolution, NO NN enlargement. ActualstaticMaterials→TemplateID→Models diffuse original; Ordinary straightRGB/noPremul/sourceA255 separatelyrestored. BlackUVpaint authoredoriginal, no emptyareas tofill.', c['source_description'],f'ActualnativeRGBA extrema {c["actual_RGBA_extrema"]}; strongestsourceRGBA {c["native_source_max_mean_RGBA"]} at{c["native_source_max_mean_RGB_xy"]}. KeepthatSMALLoldpalepaint peak/sourceweakgrayline strengths/relativekhakifields; do NOT turn into white255/glints or re-light. Originalfilteredpaint softness is deliberate. No coarsergrain/cloth fibers/leatherpores/newbumps/etchedhardware/embroidery/photoTexture; softold shading NOTnew physicalcreases.', 'Output SAME ENTIRE SQUARE opaqueRGB UVcanvas withALL originalpaintfields andblackgaps inSAME normalizedpositions/areas. No rotate/crop/portrait/zoom/recenter/padding/frame/whitespace/border/BBox/islandregistration/fitting. Keepalloldparts/oldpluspaint Fourarms exactly; no new glyph/symbol/text ormaterial interpretation. Higherresolution fineSAMEfilteredpainting withoutextra detail beneathsourceblur.']
 arg='\r\n\r\n'.join(parts);p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes((arg+'\n').encode('utf-8'));(B/f'generated/{i}-{ST}-exact-call-argument.txt').write_bytes(arg.encode('utf-8'))
print('Cl50 BEFORE12; sole2353/originalrec1885+1893',[(c['id'],c['native_source_max_mean_RGBA'],c['native_source_max_mean_RGB_xy'])for c in constraints])
