from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='effects-thirtieth';CALL=[4101,2575]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];survey={r['id']:r for r in read(B/f'source-count-survey-{ST}.json')};cons=[];groups={}
boxes={4101:[('original extremely dim tiny upper-right field',[22,9,24,12]),('original dim warmgray uppermain field',[17,11,21,18]),('original dim coolgray lower field',[16,19,18,26])],2575:[('original dim broad upper loop',[12,4,43,23]),('original dark upper-middle pigmentgap',[22,14,37,29]),('original central warmer paint',[20,27,47,42]),('original strongest lower warm paint',[28,40,45,54]),('original right softer lobe',[45,31,62,47]),('original verydim lower falloff',[22,53,49,62])]}
descs={4101:'EXACT original THREE literal positiveRGB painted bitmap domains on complete black native32 canvas, not three physical particles/objects. TWO subdued main paint areas plus a much fainter original tiny upper-right area. Exact native domain1 FOUR pixels bbox[22,9,24,12] maxRGB8/5/5; keep this ORIGINAL tiny faint brown-gray paint at exact normalized coordinates and dim strength, without turning it into a bright new spark or removing it. Domain2 SEVENTEEN pixels bbox[17,11,21,18] maxRGB29/18/18, original warmgray slightly irregular upper-middle soft stripe. Domain3 THIRTEEN pixels bbox[16,19,18,26] maxRGB40/39/45, original cool gray/violet narrow lower soft stripe. Original strongest mean paint[16,23] RGBA40/39/45/251 remains the brightest but still VERY DIM muted pigment. Preserve exact widths, softblur, phase, spaces, all blackRGB even where originalA is positive; no connecting new line, new mechanism, glare, metalrod or raised edge. Very faint upper-right native field is original, not an optional decoration.',2575:'EXACT original softly painted orange/brown COLOR field with original broad upper loop/dark center, original darker inner pigment gaps, warmer middle paint, stronger lower patch and softer right lobe. Preserve the EXACT original knot/foldlike colorwash positions, widths, asymmetric silhouette, blur and relative strengths; do not reinterpret source shades as newly raised folds/firetongues/cloud cells. Literal bitmap count is ONE broad2145-pixel positiveRGB domain extent[5,2,62,62], plus SIX isolated nativeRGB[1,0,0] pixels at[50,17],[5,19],[18,47],[56,52],[52,54],[49,55]. These six are almost black source bits, NOT six physical sparks; keep them almost black, no glints/additional flecks. Native strongest mean[36,45] RGBA218/123/30/0; actual source channel extremaR218/G124/B30. Keep original brown-orange palette, dim upper wash, existing darkgaps and subdued relative weak falloff, no whitening/orange glare or blue cast. SourceA0 TransparentAdd uses visible storedRGB, not an empty mask and not premultiplied by zero. Entire guide is original storedRGB only.'}
for r in P:
 i=r['id'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['previous_source_only_views']=[p.relative_to(ROOT).as_posix()for p in sorted(B.rglob(f'{i}-*source*.png'))if ST not in p.as_posix()][:12];r['view_novelty']='Honest fresh readonly source-only re-audit of prior0call views. Accepted/raw/call/held/refusal/generated/exactRGBA guards separate, no never-viewed fiction.'
 reason='Genuine complex painted sourcecolor; strict weakpixel/count/localshade preservation unclear for forced boundedcall, genuinepending0calls. Actual compact fullnative matrices establish everypixel, not a technical/family ban.'
 if i in [5391,5392]:reason='Individually wholeview smooth verticalbluegray tonefield; no independently visible finepaint detail to synthesize while keeping original softblur. Genuinepending0calls, not analytic/technical solely fromsimpleappearance/name. Fullnative matrix/common actualtyped records retained.'
 if i==2627:reason='Genuine sparsebluegray originalpaint, A0 TransparentAdd usefulRGB notempty. Manyfaintbits/thinstreaks require faithful localrelative strength, source-only genuinepending0calls, no familyban.'
 if i==4101:reason='Genuine tinyverydim separated graybrown paintstreaks; would risk strengthening/dropping faintbits despite exactpixel coordinates, genuinepending0calls.'
 if i==2523:reason='Genuine complex brown/violet paintedfield with numerous narrowrays/tinyweakflecks. Weakfleck hierarchy/formphase not suitable for forcedcall inthisscope, genuinepending0calls.'
 if i==2575:reason='Genuine softly painted brown/orange field with complex interior brightknots/darkgaps and sixisolated RGB1 pixels. No forced complexcall, genuinepending0calls; not A0-empty/technical.'
 if i in [2372,2373]:reason='Actual thin bluegray branching paintedcolor line, individual original tiny branch/tip/relativeglow layout clear in complete matrix, but forced newdetail risks changing existing narrowphase. Genuine pending0calls, not analytically classified from name/appearance; typedconsumer and fullnative proof retained.'
 if i in [717,718]:reason='Actual sparse dim brown painted fragments and tinyweak RGB bits over original completeRGBA canvas. Exact matrix/counts/phase retained; faithful relative weak strength/gaps uncertain for forced scope call. Genuine pending0calls, no physicalparticle count from alpha or technicalfamilyban.'
 r['source_only_reason']=reason
 if i not in CALL:continue
 o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];rgb=a[:,:,:3];l=rgb.mean(2);y,x=np.unravel_index(l.argmax(),l.shape);expected={4101:([16,23],[40,39,45,251]),2575:([36,45],[218,123,30,0])};assert [int(x),int(y)]==expected[i][0]and a[y,x].tolist()==expected[i][1]
 zero=rgb.max(2)==0;weak=(rgb.max(2)>0)&(rgb.max(2)<=5);domains=survey[i]['native_positive_RGB_8connected_domains'];assert len(domains)==(3 if i==4101 else 7)
 c={'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':list(o.size),'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':[int(x),int(y)],'native_source_max_mean_RGBA':a[y,x].tolist(),'source_feature_counts':{'literal_positive_RGB_8connected_bitmap_domains':len(domains),'domains':domains,'qualification':'Exact bitmap topology only, NOT physicalparticle/metalparts count fromRGBA mask. Whole sourceRGBA matrix stored once/read by sourcekey+fileSHA. Allzeroweak pixels included; no inferred hardware.'},'native_zero_RGB_pixel_count':int(zero.sum()),'native_positive_weak_RGB_max_le5_pixel_count':int(weak.sum()),'complete_zero_and_weak_pixel_evidence':'Derive everynative zero/weak xy/RGBA from immutable referenced matrix: RGBmax==0, or0<RGBmax<=5. Matrix is EXACT decoded entire original and contains originalA separately, not an artthreshold guide. Avoidduplicating matrix/raster arrays perconsumer.', 'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l.T],'source_description':descs[i],'source_domains':[],'semantic_qualification':'Allregionboxes numericdiagnostics only, never crop/referencefitting/BBox/composite/artistRGB. FulloriginalA/UV/sourceblur/nativepatternscale retained; unknown absentdefinitions explicit.'}
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=rgb[y0:y1,x0:x1];aa=a[y0:y1,x0:x1,3];c['source_domains'].append({'name':name,'bbox':b,'native_pixels_ref':{'source_matrix_key':str(i),'matrix_file_SHA256':r['native_matrix_ref']['file_SHA256'],'slice_native_xyxy':b},'mean_RGB':v.mean((0,1)).tolist(),'max_RGB':v.max((0,1)).tolist(),'sourceA_extrema':[int(aa.min()),int(aa.max())],'original_zero_RGB_pixels':int((v.max(2)==0).sum())})
 cons.append(c);r['source_only_reason']='One FIRST faithful edit eligible after fullactualnative weakzero/count/palette/maxphase evidence and originalRGB/A/NN views; no sourcecrop/physicalhardware inference.';r['full_original_RGBA_RGB_A_NN_privately_inspected_BEFOREtool']=True
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL]});save(f'source-check-{ST}.json',P);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Faithfully edit the existing historical Silent Storm SOFT PAINTED COLOR bitmap at higher resolution; do not render new realistic objects/effectparticles/hardware.', 'Image1 is EXACT ENTIRE original native storedRGB solely wholecanvas nearest original sampling to512x512 madeopaque. Preserve complete normalizedUV/positions/width/shapes/count/nativephase/patternscale/sourceSOFTBLUR/palette/relativeweak strengths, every original pixelpaintfield/blackgap. Nearestblock sampling proves originalUV only, NOT squaredcells/grid/mosaic. Render the same original smooth subdued mattewash without inventing physicalgrain/stipples/furryedge/coarsecloudcells/mottle. Fulloriginalalpha restored independently, brightness only one globalnumerical scalar. No crop/padding/frame/recenter/BBox/fitting/repack/zoom.',descs[i],f'Actual original nativeRGBA extrema are {c["actual_RGBA_extrema"]}; maxmean nativexy{c["native_source_max_mean_RGB_xy"]} is exact RGBA{c["native_source_max_mean_RGBA"]}. Keep ORIGINAL muted source color hierarchy and nativepeak strengths, not manual255/white. Do not strengthen original dimfield, lighten blackgaps or make newreflectiveedges. Original fullA stays separately source-restored exactly:4101 Transparent A0..255;2575 TransparentAdd entireA0 but useful storedRGB/no premultiplication; guideopaque RGB is originalusefulpaint.','Add only finer softly blended depiction of EXISTING paint. No physicalshine/glints/whiteplates/rims/bevels/raisedhardware/rust/etchedscratches/rods/wires/knurl/bolts/rocks/rings/newholes/fibers/photo texture/cloudgranules/stipples/furryedge/coarsemottle or addedfragments. Do not make NEW sparks/rays/tongues/curls, remove weak originalpaintfield or regularize originalasymmetry. Keep sourceblur/plainmatte material. No symbols/text/logos.', 'Output ONLY ENTIRE SAME opaqueRGB square canvas with exact normalizedUV/sourcepaint scale/count/tonalphase/material/sourceA downstream. No whitespace/cutout/crop/zoom/framing/fitting/BBox/UVrepacking/composites or inventedparts.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Immutable compact BEFORE12 sources/2FIRST count weakzero proof',CALL)
