from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='heads-twenty-fourth';CALL=[6705]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
def ref(p):return {'path':rel(p),'file_SHA256':sha(p)}
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];A=read(B/f'actual-records-{ST}.json');rounds={};cons=[]
code={'qualification':'Actual source static Materials/TemplateID/Heads versus TransformableFaceTextures→THMID→Heads explicit; complete straightRGB/sourceA in LSHead weightedlayers/source-over. Layer registration does not prove runtimeweight. No inferred anatomy/mesh UV/dental count.','files':[ref(ROOT/n)for n in ['DBFormat/DataFaceGen.cpp','Main/LSHead.cpp','Main/FaceGenTextureSampling.h']]};save(f'consumer-code-proof-{ST}.json',code)
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];r['source_RGBA_RGB_A_NN_privately_inspected']=True;r['FaceGen_binding_code_ref']=ref(B/f'consumer-code-proof-{ST}.json')
 r['source_only_reason']='Genuine fullface colorUVatlas remains pending0call: ONE inverted sourceface/hair field, ONE separate eyeiris/pupil field and TWO small upperdental/eyelash strip fields in samecanvas. Exactweak native marks and allA retained; physical tooth/eyelash/glint counts not confidently enumerated before a faithful solecall, sourcepixel maxima not physicalpartcounts. No human/dental/head/type/variableA familyban or analytical classification. Actual staticMaterial/TemplateID/Heads bindings separate from dynamic THMID layer; runtimeweights/mesh UV unknown.'
 if i==1133:r['source_only_reason']='Individual entire16x16 constant redRGBA proved pixelby pixel, actual directMaterial743 opaque Wrap→Template518; no staticModel/Heads row found, runtimedispatch unknown. Source-only original recommendation for this single constant colorfill, not family/name/type ban.'
 if i!=6705:continue
 rgb=a[:,:,:3];lum=rgb.mean(2);rnd=np.array(o.convert('RGB').resize((512,512),Image.Resampling.LANCZOS).resize((128,128),Image.Resampling.LANCZOS));rounds[str(i)]={'id':i,'source_size':[128,128],'recipe':'ENTIRE straightRGB FIRST LANCZOS4x then entire native independentlyA, no implicitRGBApremul/repair.','source_RGB_LANCZOS4x_then_native_RGB_matrix':rnd.tolist()}
 domains=[]
 boxes=[('ONE full mutedred sourcebackground',[0,0,128,128]),('ONE originalsoft redmagenta centralwash',[50,43,78,65]),('THREE existinggraypaintpeaks combinedsoftfield',[57,50,70,56]),('LEFT existinggraypaintpeak',[57,50,61,55]),('MIDDLE existinggraypaintpeak',[62,50,66,55]),('RIGHT existinggraypaintpeak',[67,50,70,55]),('original bottomright weakRGBcorner field',[118,118,128,128])]
 for name,b in boxes:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);domains.append({'name':name,'bbox':b,'native_pixels_ref':{'matrix_ref':r['native_matrix_ref'],'slice_native_xyxy':b},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'source_peak_xy':[x0+int(x),y0+int(y)],'source_peak_RGBA':v[y,x].tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())]})
 patterns=[]
 for y,x0,x1 in [(51,57,70),(52,57,70),(53,57,70),(47,50,78),(60,50,78),(120,118,127)]:
  v=lum[y];xs=[x for x in range(x0,x1)if v[x]>v[x-1]and v[x]>=v[x+1]];patterns.append({'axis':'row','native_fixed_coordinate':y,'native_axis_interval':[x0,x1],'literal_paintshade_maximum_axis_coordinates':xs,'literal_count':len(xs),'native_successive_pitch':[b-a for a,b in zip(xs,xs[1:])],'qualification':'Literal coloredpigment maxima, not physicalteeth/particle/anatomy counts or thresholds.'})
 assert patterns[0]['literal_paintshade_maximum_axis_coordinates']==[59,63,68]
 description='Keep SAME ENTIRE128square sourceUV: ONE muteddarkred fullcanvas background, ONE blurred redmagenta smallcentralwash native x50..77/y43..64 with its existing darkerlowercore, and THREE existing SOFT graypaintpeaks native x59/63/68 atrow51 (LEFT x57..60/y50..54, MIDDLE x62..65/y50..54, RIGHT x67..69/y50..54). Their unequalpeak strengths andgaps exactreference, not newteeth or anatomy. Keep original smallweak bottomright RGBfield native118..127/y118..127 and otherwiseflat darkred background. OriginalstrongestRGB200/201/194 at63,51 remains dimgraypaint not white255/gloss; left59,51 andright68,51 both165/166/160, dips61,51=88/71/78 and66,51=94/80/82 retained; no equalizing3peaks/no extra brightpatch. Entire originalA separately restored, includingA0usefulRGB andhidden corner; no erasure because transparent.'
 cons.append({'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':[128,128],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':{'original_softgray_pigment_peaks':3,'original_softredmagenta_wash':1},'native_repeat_count_phase_evidence':patterns,'native_sourceA0_pixel_count':int((a[:,:,3]==0).sum()),'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'qualification':'THREE observedgray softpaint maxima/groupfields in wholeoriginal, NOT guessed physicalteeth. AllsourceRGB/A/nativeweakcount/phase complete BEFORE; bboxes descriptive notcrop/registration. Nativepaintblur, no anatomicalinterpretation.','source_description':description,'actual_dynamic_consumers':r['fresh_actual_dynamic_consumers']});r['source_only_reason']='Eligible FIRST6705 actualdynamicFaceColor35→THMID1→Head90; THREE clearsoftgraypaintpeaks/ONE magentawash, not inferred physicalteeth; fullvariableA/straightRGB/nativeblur/background/nativeweakfield proof. No clinicalanatomy/teeth reconstruction.'
save(f'natural-RGB-roundtrip-{ST}.json',{'sources':rounds,'before_call':True})
for c in cons:c['natural_RGB_roundtrip_ref']=dict(ref(B/f'natural-RGB-roundtrip-{ST}.json'),source_key=str(c['id']))
save(f'pattern-constraints-{ST}.json',cons)
p=next(r for r in P if r['id']==1133);o=Image.open(B/'original/1133.png').convert('RGBA');colors=o.getcolors(257);assert colors and len(colors)==1 and colors[0][0]==256
orig={'id':1133,'status':'individual-original-only-entireconstantRGBA-recommendation-rootreview','logical_size':[16,16],'pixel_count':256,'every_RGBA':list(colors[0][1]),'fullRGBA_constant':True,'actual_consumer':p['fresh_actual_static_consumers'],'historical_release_original_parity_ref':dict(ref(B/f'source-check-{ST}.json'),id=1133),'native_matrix_ref':p['native_matrix_ref'],'qualification':'ActualMaterial743 opaqueWrap→Template518, no actualModels/Heads found; runtime dispatch unknown. Entire source constantRGBA onecolor independentlyproven, retainoriginal no inventedtexture/colorparts. Root sole classification/runtime acceptance; sourcequeue nameLSHeadRed is not proof.'}
# Final source proof saved before originalproof refs and no call yet.
save(f'source-check-{ST}.json',P);orig['historical_release_original_parity_ref']=dict(ref(B/f'source-check-{ST}.json'),id=1133);save(f'original-only-proof-{ST}.json',[orig]);sel=read(B/f'selected-{ST}.json');v=next(r for r in sel if r['id']==1133);v['worker_original_only_recommendation']=orig;save(f'selected-original-only-{ST}.json',[v])
save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_count':len({r['source_rgba_sha256']for r in P}),'fresh_ID_scope_ids':[r['id']for r in P],'previous_scope_sourceonly_reaudit_ids':[],'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL+[1133]],'recommended_original_only_ids':[1133]})
assert not(B/f'source-check-{ST}-before-call.json').exists();shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Asset type: original softlypainted facial COLOR UV overlay bitmap, not a portrait/photo/anatomy study. Faithfully edit SAME ENTIREbitmap at higherresolution keeping exact softnativepaint/count/phase/UV/palette/localintensity/backgroundflatness.', 'Image1 is exact ENTIREoriginal128square straight storedRGB madeopaque at ORIGINALnative resolution, no NN enlargement. NativeOrdinary straightRGB, fullsourceA0..255 separately restored downstream plusstandardwhole scalar/defaultpadding. Actualsource TransformableFaceTextures35→THMID1→Head90, registration not runtimeweight/anatomy inference. ExistingredRGB evenA0 is authoritative, no erasing/filling interpretation.',c['source_description'],'Keep original filtered blurry brushpaint and original unequalweakredgray tonalhierarchy. Subtle finer rendition of SAME originalpaint only; no newvisualmaterial/sharperoutline/rim, no whiteningpeaks. NativeRGBA extrema '+str(c['actual_RGBA_extrema'])+'. Fullsourcecount/positions/gaps/relativepeakstrength fixed; do not transform these originalgraypaintpatches into reconstructed anatomicalteeth.', 'NO newparts/teeth/anatomy/face/mouth/eyes/irisglints/pores/skin/photo hairfibers/mesh/weave/cells/mosaic/granules/grain/cloudmottle/decorativecurls/rays/gloss/whiteglare/droplets/rings/raisedrim/etchedscratches/symbols/glyph/logo. No extra grayorbrightpatch. Background remains original flatdarkred, no newtonalclouds. Keep allweakfield/nativeblur and original bottomright subduedRGBfield.', 'Output SAME ENTIRE SQUARE opaqueRGB originalUVcanvas; no transparentcutout/frame/whitespace/padding/border/crop/zoom/recenter/rotation/BBox/fitting/islandmoves/registration. ONE originalsoftredwash/THREE unequalsoftgraypaintpeaks, originalcorners/fullA/sourceUV/material/nativepaintscale.']
 arg='\r\n\r\n'.join(parts);f=B/f'generated/{i}-prompt.txt';assert not f.exists();f.write_bytes((arg+'\n').encode('utf-8'));(B/f'generated/{i}-{ST}-exact-call-argument.txt').write_bytes(arg.encode('utf-8'))
print('Immutable BEFORE12,prospective FIRST6705,original1133RGBA',orig['every_RGBA'],'pending10')
