from pathlib import Path
import json,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='equipment-fortieth';CALL=[5237,5383]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];cons=[];groups={}
boxes={5237:[('original upperleft darkbodypaint lattice',[0,0,45,51]),('original central darkcolumn',[22,12,23,42]),('original existing upper horizontal separator',[0,11,45,12]),('original existing middle horizontal separator',[0,27,45,28]),('original existing lower horizontal separator',[0,42,45,44]),('original upperright annular paint',[44,0,64,22]),('original right vertical graypaint strip',[46,22,64,52]),('original lowerleft hexagonal paint',[0,51,15,64]),('original bottom middle shadedpaint',[15,51,34,64]),('original bottomright brightpaint',[34,51,64,64])],5383:[('original softlydiamondpainted gripfield',[16,0,110,27]),('original darklight left tapered paintcap',[0,0,16,27]),('original subdued right endpointpaint',[110,0,128,27]),('original lowerleft flat hexagonal grayfield',[0,31,28,64]),('original lower main mattegray bladepaint',[29,31,128,64]),('original verydark gap undergrip',[29,27,110,31])]}
counts={5237:{'original_upperleft_lattice_colorfield':1,'original_native_dark_center_column_x':22,'original_native_dark_horizontal_separator_rows':[11,27,42],'original_upperright_annular_colorfield':1,'original_right_vertical_colorstrip':1,'original_lowerleft_hexagonal_colorfield':1,'original_bottom_middle_shaded_region':1,'original_bottomright_brightpaint_region':1},5383:{'original_upper_diamondpaint_gripfield':1,'original_left_tapered_endpoint':1,'original_right_endpoint':1,'original_lowerleft_hexagonal_field':1,'original_lower_main_mattegray_bladefield':1}}
descs={5237:'Preserve the EXACT existing dark gray/purple matte painted body/lattice UVfield in the upperleft, including ALL original thin shaded diagonal paintlines/crossings at their native phases/positions/counts and original width. ONE original central dark divider is centered nativecolumn22 across y12..42; THREE original horizontal dark separators at native rows11,27,42 stay exactly there. Do NOT regularize or interpret sourcewash as new physical mechanisms. Keep ONE existing upperright annular colorfield, ONE existing right vertical shaded graystrip, ONE original lowerleft hexagonal colorfield, ONE original bottommiddle shadedpaint region, ONE original bottomright brighterpaint region. Preserve existing bottomright white sourcepeak native[46,56] RGBA[255,255,255,255] without newbrightdots elsewhere; all original black/dimUV gaps remain black/dim even sourceA255. Existing relative darkbody versus brightermiddle/bottompaint hierarchy must remain. No new bolts/holes/arms/buttons/letters/hardware/rust/knurledphysicalgrain/etchededges.',5383:'Keep the ONE original upper softly painted graydiamond gripfield, ONE existing left tapered paintendpoint, ONE existing right shaded endpoint, ONE original lowerleft flat gray hexagonal colorfield, and ONE original lower main mattegray bladepaint field. Retain ALL original diamondshade marks at exact native phase/count/pitch/width; the original pattern is slightly irregular quantified paint, not a new perfectlyregular manufactured raisedknurl. Keep its sourceblur/smallpaintscale: do NOT turn it into white embossedmetal studs, thick outlined diamonds/new reflective scratches/photograin or regularize cellphase. Preserve subdued gray/cyan original localpalette/strength, the blade existing broadsoftgray gradient and exact original curvedsilhouette/thin pale edge width/shape. No new slots/bolts/bladebevels/shine/newwhiteedge highlights, no coarsecells. Original black opaqueUV gaps stayblack, not newpaint.'}
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];lum=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['source_RGBA_RGB_A_NN_privately_inspected']=True;assert r['fresh_actual_static_consumers']and not r['fresh_actual_dynamic_consumers']
 r['source_only_reason']='Genuine sourceequipment paintedcolor artwork, exact fullcanvas/matte/parts/weakpigment/pattern phase requires faithful rootartreview. Honest prior0call reaudit allowed; not technical/groupban or noMaterial because actual typedMaterial is present. Remains genuinepending0call in bounded scope.'
 if i==5382:r['source_only_reason']='Genuine painted cloth/annularUV material; private sourceNN shows two indecipherable printed lines on annularregion. Exact glyph content cannot be proven from originalblur; keep genuinelypending0call, not structural/technical or repeatpattern familyban.'
 if i in [5236,5239,5372,675]:r['source_only_reason']='Genuine fullsource painted material has small printed/marking regions or distinct existing symbolfields requiring exact content/count/nativephase. Remains genuinepending0call; no blanket technical/glyph/type ban or inferred hardware. Preserve all originalRGBA/UV/palette/material until faithfulbounded sourceart review.'
 if i not in CALL:continue
 assert r['material_evidence']['actual_source_native_type']=='Ordinary'
 regions=[]
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);regions.append({'name':name,'bbox':b,'native_pixels_ref':{'source_matrix_key':str(i),'matrix_file_SHA256':r['native_matrix_ref']['file_SHA256'],'slice_native_xyxy':b},'mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'min_RGB':v[:,:,:3].min((0,1)).tolist(),'max_RGB':v[:,:,:3].max((0,1)).tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())],'native_peak_xy':[x0+int(x),y0+int(y)],'native_peak_RGBA':v[y,x].tolist()})
 pattern=[]
 if i==5383:
  for y in [5,8,11,14,17,20,23]:
   xs=[x for x in range(17,106)if lum[y,x]>lum[y,x-1]and lum[y,x]>=lum[y,x+1]];pattern.append({'native_y':y,'native_x_interval':[17,106],'literal_row_brightness_maximum_count':len(xs),'native_maximum_x':xs,'native_successive_maximum_pitch':[b-a for a,b in zip(xs,xs[1:])],'meaning':'Literal exact sourcepaint rowmax count/phase/pitch only; NOT physicalstud counts, not assumed regulargrid.'})
  descs[i]+=' Exact native source row5 has '+str(pattern[0]['literal_row_brightness_maximum_count'])+' brightnesspaint maxima x='+str(pattern[0]['native_maximum_x'])+'; row14 has '+str(pattern[3]['literal_row_brightness_maximum_count'])+' maxima x='+str(pattern[3]['native_maximum_x'])+'. Retain nativepatternphase/pitch; these are coordinatesofexisting softlypainted shades, not new physicalknobs.'
 if i==5237:
  assert lum[12:42,22].mean()<min(lum[12:42,20].mean(),lum[12:42,24].mean())
  pattern=[{'native_dark_column_x':22,'native_y_interval':[12,42],'literal_meanRGB':float(lum[12:42,22].mean()),'neighbor20_meanRGB':float(lum[12:42,20].mean()),'neighbor24_meanRGB':float(lum[12:42,24].mean())},{'native_dark_separator_rows':[11,27,42],'native_x_interval':[1,43],'literal_row_meanRGB':[float(lum[y,1:43].mean())for y in [11,27,42]]}]
 cons.append({'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':list(o.size),'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':regions,'source_feature_counts':counts[i],'native_repeat_count_phase_evidence':pattern,'count_qualification':'Observed original bitmap colorfields/paintlines/annularUV/endpoint/broadblade only, NOT interpreted new hardware. Every native weakpaint mark/rowcolumnphase/palette once immutable fullRGBA matrix. Diagnosticbboxes/counts not fitting/crop/BBox/UV islandsregistration. Actualrepeat maxima/pitch explicitly beforeprompt, no inventedregulargrid.','native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_blackRGB_A255_pixel_count':int(((rgb.max(2)==0)&(a[:,:,3]==255)).sum()),'native_positive_weak_RGB_max_le5_pixel_count':int(((rgb.max(2)>0)&(rgb.max(2)<=5)).sum()),'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'source_description':descs[i],'actual_consumer':'ActualMaterials.TextureID/TemplateID/Models.MaterialN diffuse role, exactDB/Geometries/ModelTemplates refs. Source5237 actualalpha_testClamp/fullnativeA0..255;5383 actualopaqueClamp/nativeA255. NativeOrdinary straightRGB/noPremul; meshUV/runtime unknown, no hardware anatomy inferred.'})
 r['source_only_reason']='FIRST solebuiltin eligible after complete originalRGBA/RGB/A/privateNN/everyweaknativepixel/count/phase/palette/sourceblur/matte/material actual typedconsumer/history-release parity beforeprompt.'
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[]});save(f'source-check-{ST}.json',P);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];w,h=c['native_size'];parts=['Use case: precise-object-edit. Faithfully edit this exact existing Silent Storm PAINTED equipment COLOR bitmap at higher resolution preserving all original art/UV/material/paintscale, no new physical detail.',f'Image1 is ENTIRE edit target EXACT ORIGINAL native{w}x{h} storedRGB madeopaque at ORIGINAL resolution, no enlargedNNguide/pixelblocks. Preserve every normalized sourceUV coordinate and complete originalcanvas. OriginalA restored downstream separately, only one global numericalbrightness scalar; sourceOrdinary straightRGB/no premultiplication. Keep original softmatte sourceblur/nativepatternscale, weak localfields/localdarkpaintstrength and all actualsourceA0 storedRGB.',descs[i],f'Exact original fullRGBA extrema {c["actual_RGBA_extrema"]}; brightest source nativeRGBA {c["native_source_max_mean_RGBA"]} at {c["native_source_max_mean_RGB_xy"]}. Keep originaldimness/subduedgraypalette/material/lightstrength/weaktones. Add only subtle rendition of SAME existing paint, no metallicgrain/weave/rust/scratches/etchededges/raisedrims/bevels/shine/glints/new coarsecells/newphysicaltexture. Native sourcepatterns keep exactcount/phase/width/scale, not newuniformgrid.', 'Output ONLY SAME ENTIRE opaqueRGB originalaspectcanvas at same normalizedUV. No crop/padding/whitespace/zoom/frame/cutout/recenter/fitting/autobbox/rearrangement/UVrepack/composite. No new parts/buttons/bolts/hardware/text/glyph/symbol/logos. Entire originalsourceA/defaultpadding/scalar restoredseparately.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Equipment40 immutablebeforeproof12/2FIRST',[(c['id'],c['source_feature_counts'])for c in cons])
