from pathlib import Path
import json, hashlib, shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent; ST='equipment-forty-fourth'; CALL=[1826,5652]
def read(p): return json.loads(p.read_text(encoding='utf-8'))
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v): (B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json'); M=read(B/f'native-matrices-{ST}.json')['sources']; C=[]; R={}
domains={1826:[('upper-left gray painted field with original top-edge black area',[0,0,27,16]),('lower-left dimgray painted field with original bottom-edge black area',[0,16,29,32]),('upper-right gray band and original soft dark patch',[26,0,64,11]),('central-to-right brown recessed paint wash and pale existing boundary',[21,10,64,29]),('bottom-right pale warm painted field',[31,28,64,32])],5652:[('left upper olive field and original red star',[0,0,32,15]),('left middle olive field with original two broad gray-olive washes',[0,12,29,27]),('left lower rounded olive-gray paint wash',[1,34,27,50]),('right upper gray curved field with existing soft black outline',[33,0,61,37]),('right lower irregular darkgray pigment field',[33,34,54,64]),('right edge dim olive marks and bands',[54,28,64,48]),('lower authored black round field and existing faint olive paint to its left',[26,48,64,64])]}
description={1826:'Preserve the same complete 64 by 32 wide painted atlas. At upper-left and lower-left keep the two separate original black pigment areas reaching the canvas top and bottom boundaries, with exactly the same soft gray surrounds. Keep the original upper-right gray painted band, its existing irregular dark patch, and its tiny weak pale horizontal marks at unchanged positions and local strength. Keep the central-to-right long dark brown paint wash, its lighter brown transition, and the existing pale cream-gray boundary on its left and upper/lower edges. Keep the pale warm lower-right field reaching the exact canvas edges. These are bitmap paint domains; do not reconstruct an assembled clip, add holes, rivets, engraved grip, ribs, polished metal, hard relief, or sharpen faint source patches into hardware. Maintain subdued gray/brown painted material and existing soft highlights, with no new reflective grain or black margins.',5652:'Preserve the same complete 64 by 64 square painted atlas. Keep exactly ONE original red star-shaped painted mark in the upper-left olive field, with the identical source contour, size, position, subdued red palette and soft shading. Keep the original two broad soft gray-olive horizontal washes underneath it, the single rounded olive-gray lower-left wash, and the original curved gray field with its soft dark border in the upper-right. Keep the irregular dim mottled gray pigment in the right/bottom field at its original spatial frequency, irregular phase and local contrast; this is existing painterly pigment, not a regular checker grid or physically counted woven fibers. Preserve every faint olive patch and band at the right edge, and the large original opaque black round area lower-right plus the small dim olive marks to its left. No new emblem, no new star points, seams, threads, cells, shiny rim, scratch pattern or hardware; do not make the original material photographic leather or steel.'}
pending={675:'Full native gas-mask atlas contains faint small marking at right; genuine painted diffuse pending precise marking/weak-material interpretation, zero calls. No technical classification.',2213:'Full native olive camouflage atlas genuine artwork; irregular paint-domain phase and small outer islands need further individual proof, zero calls. No camo/material blanket ban.',3035:'Full native knife atlas contains existing small lettering and several tiny strap-edge marks. Genuine art pending exact marking fidelity; zero calls.',3039:'Full native machete atlas includes small badge-like source marking and finely spaced ridged pigment. Genuine pending individual contour/phase proof; zero calls.',3914:'Full native katana atlas includes existing diamond cadence and detailed gold guard ornament. Genuine source artwork pending literal contour/count proof; zero calls, no pattern blanket ban.',5239:'Full source grenade atlas includes indistinct source marking across pale band; genuine art pending exact source marking, zero calls.',5240:'Full source grenade atlas includes two existing small source text lines; genuine pending literal marking fidelity, zero calls.',5245:'Full source grenade atlas includes small original lettering in olive field; genuine pending literal marking fidelity, zero calls.',5372:'Full bandage atlas includes original small table/label text and red cross; genuine artwork pending exact label/fold-paint fidelity, zero calls.',5382:'Full plaster atlas includes curved faint printed marking and existing fine cloth pigment cadence; genuine art pending literal mark/phase proof, zero calls.'}
for r in P:
 i=r['id']; o=Image.open(B/f'original/{i}.png').convert('RGBA'); a=np.array(o); rgb=a[:,:,:3]; l=rgb.mean(2)
 assert a.tolist()==M[str(i)]['native_RGBA_matrix']; assert r['fresh_actual_static_consumers'] and not r['fresh_actual_dynamic_consumers']
 r['source_RGBA_RGB_A_NN_privately_inspected']=True; r['source_RGB_whole_survey_privately_viewed']=True
 r['source_only_reason']=pending.get(i,'First sole built-in candidate after full original/native/weak-domain/count-phase/material proof. Honest prior source-only re-audit, no previous calls/accepted/held/exactRGBA donor.')
 if i not in CALL: continue
 assert o.size==({1826:(64,32),5652:(64,64)}[i]); assert r['material_evidence']['actual_source_native_type']=='Ordinary' and (a[:,:,3]==255).all()
 rt=np.array(o.convert('RGB').resize((o.width*4,o.height*4),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS)); R[str(i)]={'id':i,'source_RGB_LANCZOS4x_then_native_RGB_matrix':rt.tolist(),'sourceA_independent':True,'no_PIL_RGBA_implicitpremul':True}
 ds=[]
 for name,b in domains[i]:
  x0,y0,x1,y1=b; v=a[y0:y1,x0:x1]; y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2])
  ds.append({'name':name,'bbox':b,'native_pixels_ref':{'matrix_ref':r['native_matrix_ref'],'source_slice_native_xyxy':b},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())],'source_peak_xy':[x0+int(x),y0+int(y)],'source_peak_RGBA':v[y,x].tolist()})
 profiles=[]
 for axis,coord,z0,z1 in ({1826:[('row',2,0,63),('row',10,0,63),('row',16,0,63),('row',30,0,63),('column',15,1,31),('column',25,1,31)],5652:[('row',9,1,31),('row',15,1,31),('row',21,1,31),('row',38,1,63),('row',53,1,63),('column',44,1,63),('column',58,1,63)]}[i]):
  v=l[coord] if axis=='row' else l[:,coord]; zs=[z for z in range(max(1,z0),min(len(v)-1,z1)) if v[z]>v[z-1] and v[z]>=v[z+1]]
  profiles.append({'axis':axis,'native_fixed_coordinate':coord,'native_axis_interval':[z0,z1],'literal_paintshade_maxima_coordinates':zs,'literal_paintshade_maxima_count':len(zs),'successive_native_pitch':[y-x for x,y in zip(zs,zs[1:])],'source_meanRGB_profile':v[z0:z1].tolist(),'qualification':'Literal weak native bitmap maxima, NOT physical ridges/cells/fibers/parts. No numeric repeat-count claim beyond proven source profiles; whole fullRGBA matrix is authoritative.'})
 feature_counts={'whole_canvas':1,'opaque_source_alpha':1}
 special={}
 if i==1826:
  feature_counts.update({'top_edge_black_pigment_area':1,'bottom_edge_black_pigment_area':1,'long_brown_painted_field':1})
  for name,b in [('top_edge_black',[10,0,20,7]),('bottom_edge_black',[11,25,21,32])]:
   x0,y0,x1,y1=b; mask=rgb[y0:y1,x0:x1].max(2)<=8; yy,xx=np.where(mask)
   special[name]={'source_diagnostic_bbox':b,'threshold':8,'black_pigment_native_pixels_xy':[[x0+int(x),y0+int(y)] for x,y in zip(xx,yy)],'native_pixels_count':int(mask.sum()),'connected_at_canvas_edge':bool(mask[0 if name=='top_edge_black' else -1].any()),'qualification':'Original authored near-black RGB with A255, NOT transparency; two local bitmap areas, not invented count of physical holes.'}
   assert special[name]['connected_at_canvas_edge']
 else:
  feature_counts.update({'red_star_painted_mark':1,'left_broad_horizontal_washes':2,'left_lower_rounded_wash':1,'right_upper_curved_gray_field':1,'lower_right_opaque_black_round_field':1})
  mask=(rgb[:,:,0]>rgb[:,:,1]+25)&(rgb[:,:,0]>rgb[:,:,2]+25)&(np.indices(l.shape)[1]<32)&(np.indices(l.shape)[0]<15); yy,xx=np.where(mask); assert len(xx)>0
  special['single_red_star']={'threshold':'R>G+25 AND R>B+25, upperleft x<32,y<15; exact sourceRGB matrix also records weak antialias pigmentation','source_red_pixel_bounds':[int(xx.min()),int(yy.min()),int(xx.max()+1),int(yy.max()+1)],'source_red_pixel_coordinates':[[int(x),int(y)] for x,y in zip(xx,yy)],'source_RGBA_pixels':[a[y,x].tolist() for x,y in zip(xx,yy)],'qualification':'Single original painted star silhouette privately viewed, not inferred new emblem or regularized anatomy. Threshold does not replace soft source contour.'}
 c={'id':i,'before_prompt':True,'native_size':list(o.size),'native_matrix_ref':r['native_matrix_ref'],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':ds,'source_feature_counts':feature_counts,'prompt_feature_counts':dict(feature_counts),'assert_prompt_constraints_equal_source':True,'native_repeat_count_phase_evidence':profiles,'special_exact_source_evidence':special,'count_qualification':'Counts describe directly visible painted bitmap domains/mark only. Literal weak maxima retain exact native phase and contrast, never guessed physical fibers/ribs/cells/hardware. Diagnostic bounds never crop/fit/register. All source weak paint and opaqueblack support preserved.','native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_blackRGB_A255_pixel_count':int(((rgb.max(2)==0)&(a[:,:,3]==255)).sum()),'native_positive_weak_RGB_max_le5_pixel_count':int(((rgb.max(2)>0)&(rgb.max(2)<=5)).sum()),'source_description':description[i]}
 assert c['source_feature_counts']==c['prompt_feature_counts']; C.append(c)
save(f'natural-RGB-roundtrip-{ST}.json',{'recipe':'ENTIRE originalRGB FIRST Lanczos4x then native dimensions, originalA independently. Diagnostic natural roundtrip only, no artistic repair.','sources':R})
for c in C: c['natural_RGB_roundtrip_ref']={'path':f'assets/terrain-hd/expanded/natural-RGB-roundtrip-{ST}.json','file_SHA256':sha(B/f'natural-RGB-roundtrip-{ST}.json'),'source_key':str(c['id'])}
save(f'pattern-constraints-{ST}.json',C); save(f'scope-{ST}.json',{'selected_ids':[r['id'] for r in P],'unique_native_RGBA_count':len({r['source_rgba_sha256'] for r in P}),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'genuine_pending_uncalled_ids':[r['id'] for r in P if r['id'] not in CALL],'recommended_original_only_ids':[]})
save(f'source-check-{ST}.json',P); before=B/f'source-check-{ST}-before-call.json'; assert not before.exists(); shutil.copyfile(B/f'source-check-{ST}.json',before)
for c in C:
 i=c['id']; w,h=c['native_size']; shape='wide 2:1' if w==2*h else 'square 1:1'
 parts=['Use case: precise-object-edit. Asset type: original hand-painted equipment diffuse UV bitmap. Edit the SAME complete painted bitmap to a faithful finer painted HD texture. Preserve all source normalized UV, material, layout, source-scale pigment and soft shading. This is a flat texture canvas, not a photograph or assembled physical object.',f'Image 1 is the ENTIRE exact native original stored RGB, {w} by {h}, opaque at original resolution. Do not treat black RGB as a transparent hole: the COMPLETE original alpha is 255 everywhere and will be restored separately. Maintain every authored black/dim area, including black at the canvas edges. Native source reference contains original soft paint, not enlarged nearest-neighbor cells.',description[i],f'Confirmed painted-domain counts: {json.dumps(c["prompt_feature_counts"],ensure_ascii=False)}. Keep those existing marks and broad fields only. Original strongest source RGBA is {c["native_source_max_mean_RGBA"]} at native coordinates {c["native_source_max_mean_RGB_xy"]}; keep the same local tonal hierarchy and subdued palette, including weak gray/brown/olive pigment. Native coordinate references mean normalized whole canvas positions, not instructions to draw geometric rectangles.', 'Improve only subtle painterly transitions and fine existing pigment at four times the resolution. Keep the original soft edge width at its native scale, low contrast and matte material. Do not invent coarse mottling, regular grids, photographic leather pores, woven fibers, metal grain, scratches, engraved relief, raised rims, beads, rivets, extra folds, glints, letters or mechanisms. Do not sharpen uncertain paint into new parts. Keep every original weak mark and its irregular source phase.', f'Output ONLY the SAME complete {shape} opaque RGB texture canvas. No padding, letterboxing, margins, white background, cropping, zoom, recentering, UV island movement, bounding-box fitting, registration, new objects or photographic rendering. Preserve whole original aspect and complete full source material/blur/UV/native pigment scale.']
 arg='\n\n'.join(parts); assert not arg.endswith('\n'); p=B/f'generated/{i}-prompt.txt'; assert not p.exists(); p.write_bytes(arg.encode('utf-8'))
print('Before-proof12; FIRST sole planned2:',[(c['id'],c['source_feature_counts']) for c in C])
