from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='heads-nineteenth';CALL=[6695,6717]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];cons=[];groups={}
boxes={6695:[('original entire soft curved beard paint',[35,56,94,95]),('original dark central pigment gap',[50,63,78,77]),('original lower mottled brown paint band',[41,76,88,94]),('original dim upper curved paint',[46,60,84,70]),('original mostly flat lower background',[12,100,116,124]),('original bottom-left white pixel',[0,127,1,128])],6717:[('original left brown hairpaint bank',[0,0,64,75]),('original right brown hairpaint bank',[64,0,128,75]),('original soft central bridge',[51,14,79,34]),('original dim left brow paint',[43,37,63,45]),('original dim right brow paint',[65,37,86,45]),('original mostly flat lower background',[12,80,116,124]),('original single lower-left colored pixel',[0,127,1,128])]}
counts={6695:{'existing_curved_soft_beard_paint_field':1,'existing_dark_central_pigment_opening':1,'original_bottom_left_white_pixel':1},6717:{'existing_upper_lateral_hairpaint_banks':2,'existing_soft_central_bridge':1,'existing_verydim_brow_paint_strokes':2,'original_bottom_left_colored_pixel':1}}
descs={6695:'Preserve EXACTLY ONE existing small softly painted dark brown curved BEARD COLOR field with ONE existing central dark pigment gap at its original native position and asymmetric soft shape. Retain existing softly mottled paintmarks, dark internal spots, curved upper wash and stronger lower paint at the SAME source native count/phase/scale/relative strength. This is a bitmap color overlay, not a face render: no physical hairs/fibers/bristles, no new stipples or marks beyond the actual original, no teeth/mouth/lips/nose/skin/pores/anatomy or new shaped objects. Almost all background is ORIGINAL EXACT mostly flat RGB[26,20,16] (15078 native pixels); preserve its plain flat matte shade, including alpha-zero storedRGB, no grain/new cloudwash there. The ONE original bottom-left nativepixel[0,127] is exact RGBA[255,255,255,255]; preserve it at the SAME tiny normalized position/size, neither missing nor enlarged into a new highlight/frame. Keep original sourceblur and dim brown tonal hierarchy, not a brighter realistic beard.',6717:'Preserve the TWO original muted brown softly painted upper/lateral HAIR COLOR banks, ONE original soft central bridge and TWO original very dim short brow paintstrokes. Keep all existing source brushwaves/tufts/tonalmarks at the SAME native positions/count/phase/width/scale; do not add physical photo hairs/fibers/new curls/new locks/individual strands or straighten the irregular softly painted boundaries. Existing browstrokes remain just original faint colorwash at exact original native regions, not new eyebrows/eyes/iris/pupils/catchlights below them. Preserve the mostly flat original lower/background RGB[74,49,33] (10847 native pixels), even sourceA0: no new grain/cloudfields/skin/face/anatomy/ears/teeth. Original ONE tiny bottom-left pixel[0,127] exact RGBA[112,92,84,55] retains same tiny normalized position/size/dim tint, not a whiteglint. Keep original subdued palette/sourceblur; existing pale paintmarks must not turn bright/glossy or sharper raised lines.'}
for r in P:
 i=r['id'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];rgb=a[:,:,:3];lum=rgb.mean(2)
 r['source_RGBA_RGB_A_NN_privately_inspected']=True
 reason='Genuine original softly painted color layer; complex exact native marks/phase require faithful bounded artreview, remains pending0call rather than a family/Type/human technical ban.'
 if i==6691:reason='Actual64x64 TransformableEyeTextures source, full blurred grayscale/color field and weak reflection paint lack clear anatomically separate iris/pupil details. Genuine pending0call: do not invent iris anatomy/glints/radialfibers; not structural merely because softblur.'
 if i==6701:reason='Actual Ordinary dynamic beard color has original full-canvas bluegray stippled/mottled RGB phase and A0..87, exact matrix retained. Genuine pending0call because adding detail could create new stipples/pores or change native weakphase; not A0-empty.'
 if i==6780:
  assert np.count_nonzero(rgb.max(2))==1 and (a[127,0]==255).all()
  reason='INDIVIDUAL ORIGINAL-ONLY recommendation with exact native proof: RGB[0,0,0] at16383/16384 pixels; sole bottom-left pixelRGBA255/255/255/255. Nontrivial original alpha contains paired brow paint, but color has no additional RGB detail to generate. Actual TransformableFaceTextures→THMID1→Heads color mask retained source-only without inventing colored anatomy. Not a blanket dark/A0/human classification; root only may adopt original-only.'
 if i==6781:reason='Actual near-flat brown dynamic brow color has8 distinct RGB values with dominant RGB55/20/0 at16286 native pixels; exact full matrix/counts retained; original weak RGB variation is genuine pending0call. Not claimed constant/technical. Preserve existing small tint phases/fullalpha, no invented colorgrain.'
 r['source_only_reason']=reason
 if i not in CALL:continue
 assert r['material_evidence']['actual_source_native_type']=='Ordinary' and r['fresh_actual_dynamic_consumers'] and not any(v['missing_owner_or_Heads']for v in r['fresh_actual_dynamic_consumers'])
 regions=[]
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);regions.append({'name':name,'bbox':b,'native_pixels_ref':{'source_matrix_key':str(i),'matrix_file_SHA256':r['native_matrix_ref']['file_SHA256'],'slice_native_xyxy':b},'mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'min_RGB':v[:,:,:3].min((0,1)).tolist(),'max_RGB':v[:,:,:3].max((0,1)).tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())],'native_peak_xy':[x0+int(x),y0+int(y)],'native_peak_RGBA':v[y,x].tolist()})
 cons.append({'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':list(o.size),'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':regions,'source_feature_counts':counts[i],'count_qualification':'Exact observed broad paint fields/darkgap/brow/corner counts only, not guessed physical strand/anatomy count. Every original native brushmark/weakpixel/phase included in immutable entireRGBA matrix, no crop/helper repair/artist RGB. Source ranges and count beforeprompt exact, diagnostic bboxes not UV fitting.','native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_positive_weak_RGB_max_le5_pixel_count':int(((rgb.max(2)>0)&(rgb.max(2)<=5)).sum()),'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'source_description':descs[i],'actual_consumer':'Actual TransformableFaceTextures COLOR→THMID1→Heads dynamic source, not static hair Model and not Eye definition. Original fullA/count/palette/wholecanvas UV unchanged; Ordinary straight RGB/noPremul.'})
 r['source_only_reason']='FIRST faithful builtin eligible after full native RGBA/RGB/Alpha/NN original views, exact original broadcounts/weakpaint/flatbackground/corner/phase/actualTHMID owner/Heads consumer proof.'
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[6780]});save(f'source-check-{ST}.json',P);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Faithfully edit this exact historical Silent Storm softly PAINTED HEAD COLOR overlay bitmap at higher resolution. No realistic face render/anatomy reinterpretation.', 'Image1 is the EXACT ENTIRE original native128x128 storedRGB, made opaque solely by fullcanvas nearest4x512 enlargement. Native source alpha and imageType are separately preserved exactly by downstream originalA restoration and one global numerical brightness scalar. Ordinary source uses straightRGB, no implicit premultiplication; preserve ALL original storedRGB including alpha-zero background/colored pixels. Match complete normalized UV/count/native pattern scale/material/palette/dimness/sourceblur. Nearest sourceblocks prove coordinates only, do not draw grid/mosaic.',descs[i],f'Actual source fullRGBA extrema {c["actual_RGBA_extrema"]}; visible paint local minima/maxima/means/corner strength must stay original. Preserve original dimness/softly blended native brushpaint. Add only very subtle fine rendition of the SAME existing marks; no new hairfibers/physical anatomy/pores/coarse cells/new stipples/radialfibers/newglints/glare/etchedgrain/curls or relief. Preserve source flat fields and every weak tonalmark exactly relative to stronger ones.', 'Output ONLY SAME entire opaqueRGB square canvas at identical normalized UV. No crop/whitespace/frame/cutout/padding/fitting/zoom/recenter/autoBBox/rearrangement/repack/composites. No new count/geometry/lines/text/glyph/symbol/logo, no sourceRGB repair or omission of tiny original cornerpixel. Full exact originalA and defaultpadding restored separately; keep original blur/nativepaintscale.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Immutable compact Heads19 source12/2 FIRST calls beforeproof',[(c['id'],c['source_feature_counts'])for c in cons])
