from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='effects-twenty-fourth';CALL=[4093,4095,4098]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'));cons=[]
boxes={4093:[('upper dim redgray paint',[16,4,23,14]),('middle warmer patch and left branch',[13,13,23,21]),('lower dim right taper',[16,20,23,27])],4095:[('left graybrown field',[10,13,18,23]),('upper low brown-red extension',[15,11,27,17]),('middle existing dark pixel pocket',[19,15,21,17]),('lower subdued warm field',[16,17,26,24])],4098:[('upper dim brown-gray stripe',[13,5,17,13]),('middle extremely dim stripe',[13,13,17,22]),('lower warm gray stripe and bottom bend',[13,22,18,28])]}
descs={4093:'ONE original narrow asymmetric vertically oriented muted dark brown-gray PAINT FOOTPRINT, upper dim redgray patch, a middle warmer brown patch with its existing short leftward soft branch, and the original lower dim rightward taper. This is just the original painted fragment bitmap: no interpretation as a rod, mechanism, leaf, armor or realistic metal. Preserve all original irregular source widths and soft patch transitions; no new holes, branch, ridges or tiny grains.',4095:'ONE original compact horizontally extended muted brown-gray PAINT FOOTPRINT. Keep the existing broader left graybrown field, dim upper brown-red extension, lower subdued warmer patch and the original small dark sourcepixel pocket around native[19,15] exactly where it is. Do not turn that existing dark pigment pocket into a new physical hole/ring/bevel/cavity. No realistic broken plate or rock geometry. Preserve original subdued flat blurred paint shading and irregular perimeter, every weak original right/lower edge.',4098:'ONE original thin upright gently asymmetric muted brown-gray PAINT STRIPE on black. Keep its exact original x/y native phase, narrow width, very dim middle segment, upper patch, lower warmer patch and very small original bottom-right bend. Do not turn it into a shiny rod, metallic edge, wire, straight ruled line, crack, rim or mechanism. Original source is soft, narrow and irregular, not an instruction to regularize it; no new glints, rings, knots or grain.'}
reasons={5298:'Native source shows one centered near-radial smooth green glow with monotone soft falloff, not sourcepaint detail. Individual analytic shading proof: full nativeRGBA matrix and symmetric falloff survey, source-only0calls, no invented glowgrain.'}
for r in proof:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];l=rgb.mean(2)
 r['full_source_RGB_private_view']=True;r['actual_source_RGBA_extrema']=[list(z)for z in o.getextrema()]
 r['previous_source_only_views']=[p.relative_to(B.parents[2]).as_posix()for p in sorted(B.rglob(f'{i}-*source*.png'))if ST not in p.as_posix()][:12]
 r['view_novelty']='Fresh actual source-only re-audit when earlier source-only views exist; no claim of never-viewed source. Raw/call/job/accepted/held/exactRGBA guards independently passed.'
 r['source_only_reason']=reasons.get(i,'Genuine muted soft sourcepaint fragment, remaining exact tiny tonal geometry not fully established for bounded call; pending0calls, no blanket family or technical classification.')
 if i not in CALL:continue
 y,x=np.unravel_index(l.argmax(),l.shape);assert o.size==(32,32) and a[:,:,3].min()==0 and a[:,:,3].max()==255
 c={'id':i,'before_prompt':True,'native_size':list(o.size),'source_RGBA_sha256':hashlib.sha256(o.tobytes()).hexdigest(),'actual_RGBA_extrema':[list(z)for z in o.getextrema()],'whole_native_RGBA_matrix':a.tolist(),'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l.T],'native_source_max_mean_RGB_xy':[int(x),int(y)],'native_source_max_mean_RGBA':a[y,x].tolist(),'source_feature_counts':{'complete_painted_footprint':1,'qualification':'One complete sourcepaint footprint only, not a physical particle/object count inferred from threshold alpha. Complete native matrix and all maxima preserve every weak pixel/phase; no new metal structure inferred.'},'source_description':descs[i],'source_domains':[],'semantic_qualification':'Boxes are ONLY numeric diagnostics, never cropped/composited/fitted guide inputs. Actual complete alpha remains separately source-restored; no blend/Wrap invented for missing Particle definitions.'}
 expected={4093:([19,18],[70,42,31,252]),4095:([15,15],[43,36,35,255]),4098:([15,11],[76,53,55,255])};assert c['native_source_max_mean_RGB_xy']==expected[i][0]and c['native_source_max_mean_RGBA']==expected[i][1]
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=rgb[y0:y1,x0:x1];aa=a[y0:y1,x0:x1,3];c['source_domains'].append({'name':name,'bbox':b,'native_RGB':v.tolist(),'mean_RGB':v.mean((0,1)).tolist(),'max_RGB':v.max((0,1)).tolist(),'sourceA_extrema':[int(aa.min()),int(aa.max())]})
 cons.append(c);r['source_only_reason']='Eligible one FIRST wholecanvas edit after actual RGB/A views and complete nativeRGBA/localstrength/phase proof; no interpretive physical metal geometry, no family ban.'
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in proof],'sole_call_ids':CALL,'maximum_call_count':3,'pending_uncalled_ids':[r['id']for r in proof if r['id']not in CALL]});save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Edit the historical Silent Storm sourcepaint COLOR fragment bitmap into a faithful higher resolution bitmap. This is not a new physical-object rendering and not a test diagram.', 'Image1 is the EXACT ENTIRE original storedRGB, solely wholecanvas NEAREST enlargement to512 made opaque for color visibility. The source nearest block sampling is UV evidence only: render the same soft subdued sourcepaint shade, not pixelgrid/mosaic/cells. Retain identical complete edge-to-edge normalizedUV, positions/widths/shape/count/nativepaintscale, source SOFT BLUR, dim localcolor hierarchy. No crop, pad, cutout, recenter, framing, fitting or UV repacking. Downstream restores FULL original alpha independently and uses only one global brightness scalar.',descs[i],f'Actual original nativeRGBA channel extrema are {c["actual_RGBA_extrema"]}; max mean pigment native xy{c["native_source_max_mean_RGB_xy"]} is exact RGBA{c["native_source_max_mean_RGBA"]}. Keep these sourceweak relationships and palette, do not replace maxima by255, do not locally brighten white edges or make glinty metal. Black source gaps remain black original shadow. Original Transparent source alpha0..255 is restored downstream; this guide stays opaque to expose storedRGB.', 'Preserve every weak brown/gray wash and irregular soft tonal patch. Add only subtle finer depiction of EXISTING paint, with no new physical grain, cells, coarse mottle, stipples, cracks, scratches, texture fibers, bevel, rim, shine, plate, ring, knot, wire, flame, rays, spark, cloud or hardware. No new holes/forms/flecks/text/symbols. No photorealistic metallurgy. Output only SAME full opaque RGB square canvas with exact normalizedUV/source material and pattern scale; no border/whitespace/zoom or added objects.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Prepared BEFOREcall native proof12, planned FIRST3',CALL)
