from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='effects-twenty-second';CALL=[1078,4739,4744]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def comps(m):
 seen=np.zeros_like(m);out=[]
 for y,x in zip(*np.where(m)):
  if seen[y,x]:continue
  q=[(int(y),int(x))];seen[y,x]=True;xy=[]
  while q:
   yy,xx=q.pop();xy.append([xx,yy])
   for dy in [-1,0,1]:
    for dx in [-1,0,1]:
     ny,nx=yy+dy,xx+dx
     if 0<=ny<m.shape[0]and 0<=nx<m.shape[1]and m[ny,nx]and not seen[ny,nx]:seen[ny,nx]=1;q.append((ny,nx))
  v=np.array(xy);out.append({'native_area':len(xy),'bbox':[int(v[:,0].min()),int(v[:,1].min()),int(v[:,0].max()+1),int(v[:,1].max()+1)],'all_native_xy':xy})
 return out
reasons={2485:'Genuine small warm diffuse source color field, actual nonparticle consumer direct proof; same sourcefilename as1078 is not accepted alias automatically (nativeRGBA independently differs). Zero calls, own exact local intensity/phase proof pending.',2118:'Genuine dim gray-blue feather-color fields, sourceTransparent/A0..81; notalpha0empty or physical count from connectedRGBA mask. Detailed weak multi-field palette/phase/defaultscalar preservation pending, zero calls.',2575:'Genuine complex original orange/brown hollow flame pigment with many dim internal bridges. Exact source inner tonal crest/silhouette detail pending, zero calls; no repeat of prior held otherfamily IDs.',2577:'Genuine complex brown curved flame pigment with dim inner openings/weak edgepatches. Exact irregular component intensity/phase pending, zero calls, no new curls/rays.',5261:'Genuine native16x16 warm beige soft diffuse field, sourceAdd/A0 usefulRGB. Detailed localpeak/color softness proof pending, zero calls; not analytical by filename or blur alone.',5391:'Genuine sourceTransparent/A0..98 thin gray-blue water-color field with soft irregular inner shade. Exact weak longitudinal pigment phase pending, zero calls; no declared analytical mask withoutproof.',5392:'Genuine sourceTransparent/A0..62 longitudinal muted water-color field with two close original pigment bands. Exact weak phase/strength pending, zero calls.',2523:'Genuine complex source-painted brown/violet flare cloud with original thin peripheral rays/sparse dim flecks. Exact ray/fleck position/intensity count not solved, zero calls; nottechnical by complexity.',2626:'Genuine blue-gray irregular water/puff-color bitmap sourceTransparent/A0..219. Actual typed ParticleInstances1270 references absentParticles177, allslots proof recorded. Missing row not automatically technical; Wrap/semantic dispatch remain unknown. Exact inner paint crest/weak texture phase pending, zero calls.'}
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'));constraints=[]
boxes={1078:{'one_main_yellow_orange_soft_field':[2,3,12,13],'upper_dim_halo':[0,0,16,6],'lower_dim_halo':[0,10,16,16]},4739:{'one_main_warm_orange_soft_field':[8,8,26,26],'all_dim_outer_support':[0,0,32,32]},4744:{'one_main_diagonal_peach_orange_soft_field':[19,20,45,44],'dim_outer_support':[0,0,64,64]}}
for r in proof:
 i=r['id'];a=np.asarray(Image.open(B/f'original/{i}.png').convert('RGBA'));rgb=a[:,:,:3];r['full_source_RGB_private_view']=True;r['full_original_RGBA_private_view']=True;r['full_source_only_NN_private_view']=True;r['source_only_reason']=reasons.get(i,'ONE main softly painted warm diffuse field, all weak support and native palette/phase saved BEFOREprompt. FIRST sole built-in planned; unresolved individual consumers explicitly preserved, no fake Wrap/missing definitions semantics.')
 r['previous_sourceonly_views']=[rel.relative_to(ROOT).as_posix()for rel in sorted(B.rglob(f'{i}-*source*.png'))if ST not in rel.as_posix()][:12];r['view_novelty']='Honest previous source-only re-audit if earlier evidence exists; accepted/raw/jobs/toolcalls/held/refused/exactRGBA guards independently prohibit repeats. Not a first-ever view claim.'
 r['sameRGBA_pending_siblings']=[z['id']for z in proof if z['id']!=i and z['source_rgba_sha256']==r['source_rgba_sha256']]
 if i not in CALL:continue
 assert r['material_evidence']['actual_source_native_type']=='TransparentAdd'and(a[:,:,3]==0).all();regions={}
 for name,b in boxes[i].items():
  x0,y0,x1,y1=b;v=rgb[y0:y1,x0:x1];yy,xx=np.unravel_index(v.mean(2).argmax(),v.shape[:2]);regions[name]={'native_bbox':b,'exact_RGB_matrix':v.tolist(),'mean_RGB':v.mean((0,1)).tolist(),'max_RGB':v.max((0,1)).tolist(),'peak_mean_xy':[int(x0+xx),int(y0+yy)],'peak_mean_RGB':v[yy,xx].tolist()}
 g=rgb.mean(2);yy,xx=np.unravel_index(g.argmax(),g.shape);rowphase=[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in g]
 constraints.append({'id':i,'before_prompt':True,'native_size':[a.shape[1],a.shape[0]],'source_RGBA_SHA256':hashlib.sha256(a.tobytes()).hexdigest(),'native_RGBA_matrix':a.tolist(),'actual_nativeType':'TransparentAdd','complete_originalA_extrema':[0,0],'native_RGB_extrema':[rgb.min((0,1)).tolist(),rgb.max((0,1)).tolist()],'whole_peak_mean_xy':[int(xx),int(yy)],'whole_peak_mean_RGB':rgb[yy,xx].tolist(),'positive_RGB_connected_native_regions':comps(rgb.max(2)>0),'positive_A_connected_native_regions':[],'whole_native_row_pigment_maximum_x':rowphase,'regions':regions,'source_visually_proved_major_field_count':1,'count_limits':'ONE observed major soft source pigment field with original dim halo/weak code support. PositiveRGB code connectivity is numerical footprint proof, NOT number of physical flames/particles. All values/positions preserved, including weak source edge pixels. NativeA0 usefulRGB is visible in Add mode, not empty. Numeric domains never crop/repair/insert anything.','reference_proof':r['helper_recipe']})
save(f'pattern-constraints-{ST}.json',constraints);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in proof],'sole_call_ids':CALL,'pending_uncalled_ids':list(reasons),'max_calls':3,'source_count_semantics':'Source2407/q2869 task baseline includes root33seven pendingfinalvalidation; publishedvalidated2400/c30f7b43. Twelve real genuine sourcecolor audit, no forcedcalls on remainingcomplex.3distinctRGBA solecalls planned.'});save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in constraints:
 i=c['id'];size=c['native_size'];maximum=c['native_RGB_extrema'][1];peak=c['whole_peak_mean_RGB'];xy=c['whole_peak_mean_xy']
 descriptions={1078:'ONE original compact softly painted yellow-orange diffuse color field in its exact native16x16 footprint. Preserve its original asymmetric central lighter yellow/cream area and dim reddish-brown soft lower/outer halo, no new field or flare. It is the same tiny warm blurred pigment, not a flame photograph. No flame tongues, bright-white center, rough largecells or individual sparks. Smooth only original sampling into fine subtle paint while retaining the original soft low-frequency blur and all existing code-value support.',4739:'ONE original softly painted orange diffuse color field, native32x32. Keep original subtly diagonal elongated orange middle and asymmetric dark-red/brown outer diffuse halo, exact footprint and soft irregular intensity phase. No new flames, luminous curls, white core, dust granules, rocks, sparks, isolated points or secondary puffs. It remains only the SAME plain blurred orange painted field, not a physical fire image or photograph.',4744:'ONE original softly painted diagonal peach-orange elongated diffuse field, native64x64. Keep exactly original short upper-left to lower-right brighter color footprint and soft dark-red/brown outer haze. Retain original brighter peach center and uneven source endshape at identical UV/scale, no whitecore, shiny metallicrod, new tongue, ray, glare streak, halo ring, spark or second cloud. Original softness and asymmetry remain; no granular/cauliflower texture or photographic lightbeam.'}
 parts=['Use case: precise-object-edit. Asset: exact historical Silent Storm soft painted COLOR effect bitmap edit, restrained finer original paint.','Image1 is the ENTIRE actual storedRGB original texture made opaque only by wholecanvas nearest-neighbor enlargement. Native originalA is zero but this RGB is genuinely useful in TransparentAdd, not an empty texture. Original COMPLETE A0 will be restored downstream; do not generate a transparent cutout or alpha premultiplication. Keep same entire square source canvas edge-to-edge and normalized UV, every source pigment value relationship, black gap, count/position/phase/scale and ORIGINAL SOFT BLUR.',descriptions[i],f'Exact native dimensions are {size}; original whole CHANNEL maxima RGB{maximum} (individual channel extrema, not permission for a newwhite point). Original brightest mean-RGB location native{xy} has RGB{peak}. Preserve that same source local dominance and all dim original halos. One global scalar corrects brightness later, so do NOT locally strengthen the center, make dim edge support brighter, or add tonal fields. No new coarsecells/photonoise/materialgrain, sharpened rims, rays, curls or cauliflowerturbulence.','Output the ENTIRE opaque source storedRGB COLOR canvas at exactly same normalized fullUV; all original black/dim color support remains. No crop/zoom/padding/whitespace/frame/recenter/fit/BBox/registration/sourceRGB artistic patch. No new forms/text/marks/physical anatomy. Retain original material softness, native relative palette and pattern scale.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print([(c['id'],c['native_RGB_extrema'],c['whole_peak_mean_xy'],c['whole_peak_mean_RGB'],len(c['positive_RGB_connected_native_regions']))for c in constraints])
