from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='effects-twenty-seventh';CALL=[4096,4097]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'));cons=[];groups={}
boxes={4096:[('original upperleft graybrown broadwash',[8,8,16,17]),('original warm middle paintpatch',[14,12,23,22]),('original small darkmiddle pigment pocket',[20,16,23,19]),('original lowerleft dimgray taper',[10,16,17,24]),('original irregular dim righttail touching canvasedge',[21,16,32,26])],4097:[('original dim upperleft graybrown paint',[10,9,17,19]),('original upperright warmer patch',[16,11,25,20]),('original dark middle paintpocket',[20,17,22,20]),('original lowerleft darkgray wash',[10,18,19,26]),('original lower right dim brown taper',[18,21,28,32])]}
descs={4096:'ONE original flat softly painted asymmetric graybrown COLOR FOOTPRINT running diagonally down-right. Preserve original upper-left broader dimgraybrown patch, the original middle warmer brownwash, existing tiny darkpigment pocket near native[20,16,23,19], original dimgray lower-left taper and original irregular subdued righttail. Original righttail reaches/clips the RIGHT ORIGINALCANVAS EDGE: keep identical source clipping/normalizedUV, do not complete, shorten, pad or recenter it. Exact original fieldpositions/widths/blacknotches and all tiny dim sourcepixels retained. These are original tonalpaint domains, not an instruction to render metalplates/objects/rings or physicalgeometry. Original darkpocket stays paintshade only, no rim or outlined hole.',4097:'ONE original compact softly PAINTED asymmetric dim dark brown-gray COLOR FOOTPRINT with original dimupperleft graybrown patch, warmer upper-right brownpatch, existing tiny darkmiddle pigment pocket near native[20,17,22,20], dimgray lower-left wash and original subdued lower-right browntaper. Keep every native tonal projection/notch/width/position and very weaksourcepixel; do not regularize original diagonal/asymmetric silhouette. Preserve darkpaint pocket as soft shade, not a newphysical hole/ring/bevel. This is original flat subdued paint, not a realistic brokenrock/metalplate/furry cloud or any hardware.'}
reasons={4086:'Genuine dim softbrown thin diagonal paintedfootprint with nativebends/separatefaint regions. Tiny tonaldomain/weakpixel hierarchy not proved clear enough for a bounded call, genuinepending0calls.',4089:'Genuine mutedgraybrown upright softpaint field with separate tiny dimrightbits. Precise weakbit intensity/shape fidelity not clear enough for solecall; source-only genuinepending0calls, no simplepattern ban.',4092:'Genuine soft mutedgraybrown verticalpaint footprint with subtlewarmerareas and tiny darkpigment gaps. Exactlocalshade preservation still unclear for boundedsolecall; genuinepending0calls, not technical bysource name.',4101:'Genuine verysmall dimgray/brown separate paintedstreaks, largest lowerstreak plus tinyveryweak upperbits. Pixel topology/phase alone does not ensure veryweakpaint intensity fidelity, source-only genuinepending0calls.',2626:'Genuine broad softbluegray paintedfield with multiple original brightcores/unevenshade and dimperimeter. Internal tonalpattern is complex to preserve without newcells/lobes; source-only genuinepending0calls, not technical bymissingdefinitions.',2627:'Genuine bluegray sparsely painted originalstreaks with many verydim bits. SourceA0 TransparentAdd RGB visibleuseful, notempty. Faintcomponent/materialphase remains complex for faithfulsolecall; genuinepending0calls.',2628:'Genuine bluegray soft narrowpaint streaks and multiple small faintbits. Allcomponent relativebrightness/phase/count fidelity not clear enough for boundedcall; genuinepending0calls.',2629:'Genuine bluegray manythin diagonal paintedstreaks and dimfragment fields. Exact weakbit hierarchy/softblur not established for call, source-only genuinepending0calls.',5391:'Individually fullsource inspected as one smooth verythin bluegray verticaltonefield, A0..98. No independent finepaint detail to add while keeping original softblur, genuinepending0calls; not declared analytical/technical solely fromsimpleappearance/name.',5392:'Individually fullsource inspected as one smooth broader bluegray verticaltonefield, A0..62. Adding grain changes originalsoftblur; source-only genuinepending0calls, no fakeempty/technical/analytic blanketclassification.'}
for r in proof:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];l=rgb.mean(2);groups.setdefault(r['source_rgba_sha256'],[]).append(i)
 r['full_source_RGB_private_view']=True;r['actual_source_RGBA_extrema']=[list(z)for z in o.getextrema()];r['previous_source_only_views']=[p.relative_to(B.parents[2]).as_posix()for p in sorted(B.rglob(f'{i}-*source*.png'))if ST not in p.as_posix()][:12];r['view_novelty']='Fresh readonly re-audit of previous0call source-only views, no never-viewed claim. Accepted/raw/call/held/refusal/generated/exactRGBA guards passed beforetool.';r['source_only_reason']=reasons.get(i,'Eligible FIRST faithful entire-source paintedcolor edit after exactnativeRGBA/weakpigment/zerogaps/tonalmaxima/countphase proof and whole originalRGB/A/NN view, no hardware inference.')
 if i not in CALL:continue
 y,x=np.unravel_index(l.argmax(),l.shape);expected={4096:([14,12],[80,67,64,255]),4097:([18,13],[69,36,21,255])};assert o.size==(32,32) and [int(x),int(y)]==expected[i][0] and a[y,x].tolist()==expected[i][1] and a[:,:,3].min()==0 and a[:,:,3].max()==255
 zero=rgb.max(2)==0;mask=~zero;seen=np.zeros(mask.shape,bool);domains=[]
 for yy,xx in zip(*np.where(mask)):
  if seen[yy,xx]:continue
  seen[yy,xx]=True;stack=[(int(yy),int(xx))];pts=[]
  while stack:
   ay,ax=stack.pop();pts.append((ay,ax))
   for dy in [-1,0,1]:
    for dx in [-1,0,1]:
     ny,nx=ay+dy,ax+dx
     if 0<=ny<32 and 0<=nx<32 and mask[ny,nx]and not seen[ny,nx]:seen[ny,nx]=True;stack.append((ny,nx))
  ay,ax=zip(*pts);domains.append({'pixel_count':len(pts),'native_bbox':[min(ax),min(ay),max(ax)+1,max(ay)+1],'source_max_RGB':rgb[list(ay),list(ax)].max(0).tolist(),'complete_pixel_xy_RGBA':[[px,py,*a[py,px].tolist()]for py,px in pts]})
 assert len(domains)==1
 c={'id':i,'before_prompt':True,'native_size':list(o.size),'source_RGBA_sha256':hashlib.sha256(o.tobytes()).hexdigest(),'actual_RGBA_extrema':[list(z)for z in o.getextrema()],'whole_native_RGBA_matrix':a.tolist(),'complete_original_zero_RGB_xy':[[int(x),int(y)]for y,x in zip(*np.where(zero))],'complete_weak_RGB_max_le5_positive_xy_RGBA':[[int(x),int(y),*a[y,x].tolist()]for y,x in zip(*np.where((rgb.max(2)>0)&(rgb.max(2)<=5)))],'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l.T],'native_source_max_mean_RGB_xy':[int(x),int(y)],'native_source_max_mean_RGBA':a[y,x].tolist(),'source_feature_counts':{'entire_original_painted_footprint':1,'literal_native_positive_RGB_connected_domains':1,'pixel_domains':domains,'qualification':'ONE complete original imagepaint footprint, literal nativeRGB connected pixels also1. Not physicalparticle/hardware count fromRGBA thresholds. AllweaknativeRGB/A pixels and arbitrarypaintphase preserved in complete matrix; no inferred geometry.'},'source_description':descs[i],'source_domains':[],'semantic_qualification':'All domainboxes are numericdiagnostic ONLY, never cropped guide/composite/BBox/fitted artistrepair. Helper is entire sourceonlyopaqueRGB NN; sourceA0..255 independently restored, actual absentParticles200 Wrap/blend unknown.'}
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=rgb[y0:y1,x0:x1];aa=a[y0:y1,x0:x1,3];c['source_domains'].append({'name':name,'bbox':b,'native_RGB':v.tolist(),'mean_RGB':v.mean((0,1)).tolist(),'max_RGB':v.max((0,1)).tolist(),'sourceA_extrema':[int(aa.min()),int(aa.max())],'original_zero_RGB_pixels':int((v.max(2)==0).sum())})
 cons.append(c)
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in proof],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in proof if r['id']not in CALL]});save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Faithfully edit the original historical Silent Storm SOFT PAINTED COLOR effect bitmap at higher resolution. Not a new realistic physicalobject, metalrendering or simulation.', 'Image1 is EXACT ENTIRE native storedRGB source solely wholecanvas NEAREST from32x32 to512x512, opaque to show usefuloriginalpaint. Keep complete edge-to-edge normalizedUV, all exact originalshape/positions/width/count/phase/patternscale/sourceblur/palette and relative localtone strengths. Nearest blocks are UV sampling evidence only, NOT squaredcells/grid/mosaic/texture. Render the same original smooth blurred broadwash, not pixelgrid. FullsourceA independently restored; brightness only one global numeric scalar. No crop/pad/BBox/frame/zoom/recenter/composition fitting or UV repacking.',descs[i],f'Original actual nativeRGBA extrema {c["actual_RGBA_extrema"]}; highestmean native xy{c["native_source_max_mean_RGB_xy"]} is exact RGBA{c["native_source_max_mean_RGBA"]}. Preserve original muted gray/warmbrown relationships and exactsource peaks/weakpigment hierarchy, not white255/highcontrast shine. Original sourceblack gap/shadow stays exact and dark, not newlyoutlined blackhole. NativeTransparent sourceA0..255 restored separately. Do not adjust localgraylight spots or brighten newedges.','Add only finer depiction of EXISTING softly blended original mattepaint. No new noisyphysicalgrain/furryedge/powdergranules/stipples/coarsemottle/cloudcells, no etchedscratches/photo metal/rust/rings/holes/beveledrims/knurls/raisedrods/mechanisms/bolts/hardware/rocks/strands. No new glints/whiteplates/flametongues/curls/sparks/rays/particles/fragment count. Preserve original slightly uneven muted shade/softblur without sharpening or regularizing silhouette. No text/symbols/logos.', 'Output ONLY ENTIRE SAME opaqueRGB square canvas, same originalsource artwork material and normalizedUV, sourcepatternscale and softtonalform. No whitespace/framing/cutout/zoom/crop/recenter/padding/BBox or artistRGBcomposites. Original fullA and nativeType restored downstream, never newparts or completed offcanvas tails.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Immutable BEFORE12 sourceproof/2FIRST nativecount+weak phase',CALL)
