from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='effects-twentieth';CALL=[1067,1578,2119]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def components(mask):
 seen=np.zeros_like(mask);out=[]
 for y,x in zip(*np.where(mask)):
  if seen[y,x]:continue
  q=[(int(y),int(x))];seen[y,x]=1;pts=[]
  while q:
   py,px=q.pop();pts.append([px,py])
   for dy in [-1,0,1]:
    for dx in [-1,0,1]:
     yy,xx=py+dy,px+dx
     if 0<=yy<mask.shape[0]and 0<=xx<mask.shape[1]and mask[yy,xx]and not seen[yy,xx]:seen[yy,xx]=1;q.append((yy,xx))
  a=np.array(pts);out.append({'area':len(pts),'bbox':[int(a[:,0].min()),int(a[:,1].min()),int(a[:,0].max()+1),int(a[:,1].max()+1)],'native_xy':pts})
 return out
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'));cons=[]
reasons={1086:'Genuine soft orange/yellow scattered fire remnants, original weak patch positions/palette clear; exact individual blurred component count and relative intensity require further audit. Zero calls, no analytic/control classification.',1620:'Genuine transparent-add usefulRGB gray glass fragment fields and weak sparse flecks; full source component count/weak patch hierarchy not established for an edit. Zero calls, not a Bump/analytic mask claim.',2118:'Genuine four broad muted gray feather-color fields with blurred overlap/tails; preserve native paint blur without interpreting new shafts or fibers. Pending source-only, zero calls.',2626:'Genuine blue-gray painted water diffuse cluster, not a technical mask. Previous water-family local highlight/material drift and fresh unresolved actual particle/sibling texture rows retained explicitly; no new call.',2627:'Genuine painted thin blue-gray water ripple/fleck field; exact fine loop/fleck count unresolved and sibling rows absent. Pending source-only, no call.',2628:'Genuine muted separate water fragment/color fields; exact weak count/shape not established, sibling definitions/texture rows incomplete. Pending source-only, no call.',2629:'Genuine blue-gray thin painted water marks; count/phase weak/sparse and actual sibling rows incomplete. Pending source-only, no call.',5391:'One genuine very narrow source-painted dark blue-gray water fragment with a soft tapered silhouette; not classified as analytical solely by shape. Pending0call because its native width/local painted shape needs precise count proof, no added highlight.',5397:'Genuine muted dark-red flat diffuse spatter with many standing weak droplets/streaks. Not excluded by blood name; exact weak component count not established, pending0calls with no added wet highlights or droplets.'}
for r in proof:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.asarray(o);rgb=a[:,:,:3];g=rgb.mean(2)
 old=[p for p in B.rglob(f'{i}-*source*.png')if ST not in p.name and f'private-{ST}' not in p.as_posix()]
 r['previous_source_only_views']=[p.relative_to(B.parents[2]).as_posix()for p in sorted(old)[:10]]
 r['view_novelty']='Honest source-only re-audit where prior support/views exist; no prior accepted/generated/raw/call/held/sourceRGBA aliases allowed by fresh guard.'
 r['full_source_RGB_private_view']=True;r['full_original_RGBA_private_view']=True
 r['source_only_reason']=reasons.get(i,'Genuine painted color source, complete original and source-only helper privately viewed. Native footprint/material/paint blur/count and whole matrices saved before first prompt; one separate built-in edit planned.')
 c={'id':i,'before_prompt':True,'native_size':list(o.size),'source_RGBA_SHA256':hashlib.sha256(o.tobytes()).hexdigest(),'source_RGB_extrema':[list(x)for x in o.convert('RGB').getextrema()],'source_A_extrema':list(o.getchannel('A').getextrema()),'whole_source_RGBA_matrix':a.tolist(),'source_positive_RGB_components':components(rgb.max(2)>0),'source_positive_A_components':components(a[:,:,3]>0),'diagnostic_qualification':'Positive-codec RGB/A connected components are exact native byte diagnostics, not automatically physical fragment counts. Full source matrices preserve ALL weak tails/tints/positions. No threshold is an acceptance rule and no clipped reference or artistic RGB patch is used.'}
 if i==1067:
  c['painted_field_count']=1;c['description']='Exactly ONE small soft irregular warm flame color mass centered slightly right of midcanvas. Its ONE narrow brighter tip is above-left of its ONE broad peach lower-right lobe, connected by a weak warm neck. No separate sparks/rays/holes/other colored marks; native A entirely0 is retained separately.'
  boxes=[('one complete flame body and soft halo',[29,25,40,36]),('one narrow upper tip',[33,25,35,29]),('one lower peach lobe',[33,29,38,34])]
 elif i==1578:
  c['painted_field_count']=3;c['description']='Exactly THREE original paper fragment silhouettes: upper-left short diagonal pointed scrap; upper-right ONE long folded/tapering scrap with attached descending lower flap; lower-left compact curled scrap with existing dark center. Upperright flap is part of ONE original piece, not a fourth new detached fragment. Preserve all existing gray folds/shade changes, no new creases/printed markings.'
  boxes=[('upperleft original paper piece',[9,10,28,22]),('upperright folded original paper piece with attached tail',[35,9,56,43]),('lowerleft curled original paper piece',[6,38,26,53])]
 elif i==2119:
  c['painted_field_count']=1;c['description']='Exactly ONE original broad soft grayblue feather-color mass low of center, with rounded top shoulder, gently tapering lower tails blending into black, and original muted center. This native source has no resolved feather shaft/barbs/individual fibers; preserve its blurry original paint and silhouette instead of adding feather anatomy or a white core.'
  boxes=[('one source soft grayblue field and complete dim taper',[7,10,25,30]),('muted central source patch',[13,17,22,24])]
 else:boxes=[]
 c['source_domains']=[]
 for name,b in boxes:
  x0,y0,x1,y1=b;v=rgb[y0:y1,x0:x1];c['source_domains'].append({'name':name,'bbox':b,'mean_RGB':v.mean((0,1)).tolist(),'native_RGB':v.tolist(),'max_RGB':v.max((0,1)).tolist()})
 if i in CALL:cons.append(c)
 else:r['zero_call_source_numeric_audit']={'source_RGB_extrema':c['source_RGB_extrema'],'source_A_extrema':c['source_A_extrema'],'positive_RGB_components':[{'area':x['area'],'bbox':x['bbox']}for x in c['source_positive_RGB_components']]}
save(f'pattern-constraints-{ST}.json',cons)
save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in proof],'sole_call_ids':CALL,'maximum_call_count':3,'pending_uncalled_ids':[r['id']for r in proof if r['id']not in CALL],'category_claim':'Actual source color art audit; no automatic Particle-only classification, no fake Bump or analytic classification. Historical/release/wholeRGBA parity fresh.'})
save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
base=['Use case: precise-object-edit. Asset type: faithful Silent Storm source-painted particle COLOR texture, higher resolution edit.','Image1 is the exact ENTIRE original storedRGB texture exposed by whole nearest-neighbor source-only enlargement. Output the identical complete opaqueRGB canvas, edge-to-edge with the SAME normalized UV, source size/placement/softness and every original black gap. Very subtly refine only existing source paint; keep the same low-resolution artwork/material and relative weak local shading. Source alpha is independently retained and final brightness globally calibrated numerically. This is a flat source diffuse texture, not a scene, object render or invented interpretation.','Keep the original native blur and restrained palette, the exact original component count/positions/size and local bright-to-dim relationships. No new shapes, brighter centered cores, sparks/flecks/glints, rays, curl/cauliflower turbulence, cracks, folds, veins, fiber/barb/shaft anatomy, pores, photo grain, wet geometry, edge highlight or sharpened luminous outline. Do not turn unresolved native color transitions into new physical detail. Preserve the original soft paint scale instead of sharpening features.','Output ENTIRE opaque storedRGB source canvas only. No zoom/crop/padding/frame/recenter/repacking/autobbox/cutout/newtransparentbackground. Whole original alpha restored separately; preserve usefulRGB even where original alpha0.']
special={1067:'Keep exactly ONE very small warm soft flame color mass, centered slightly right of the complete canvas center. It has exactly ONE narrow pale brighter tip at original native x33..34,y25..28 and ONE broader muted peach lobe at native x33..37,y29..33, connected by the original weak warm neck. Body and soft rusty-orange halo stay confined to the exact original footprint. Original maxRGB255/255/247 belongs only to the tiny original tip, not a widened white core. Lower lobe remains peach and less intense. Do not enlarge this tiny flame, invent flames/sparks/tongues/rays or details outside its original narrow halo; entire rest canvas stays the original black.',1578:'Keep exactly THREE existing gray PAPER fragment shapes with every source gray fold and all black space in the same location. (1) upperleft short diagonally pointing scrap; (2) upperright ONE long gray folded/tapering scrap with its existing attached lower descending flap, still ONE piece, not an extra fourth detached scrap; (3) lowerleft compact curved/curl-like scrap with its original dark center. Preserve exact native fragment outlines, orientation, fold boundaries, tail widths and gray intensity hierarchy. No new paper pieces/holes/creases/fold networks/fiber grain/printed marks. Source shading stays softly painted muted gray; do not add bright white rims or stronger black fold grooves.',2119:'Keep exactly ONE broad original softly blurred grayblue feather-color mass below the complete canvas center. Preserve its existing rounded upper shoulder, slightly irregular sides, weak lower taper/tails and muted blue-gray center in precisely the same source footprint. The native source has NO resolved feather shaft/barbs or fine fiber anatomy: do NOT create them, and do not turn the field into a realistic feather/cauliflower/smoke swirl. Keep the same complete soft paint blur, original grayblue tint and source relative weak shading, no centered white spot/core, crisp boundary, highlights or additional pieces.'}
for i in CALL:
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(base[:2]+[special[i]]+base[2:]).encode('utf-8'))
print([(c['id'],c['painted_field_count'],[(x['area'],x['bbox'])for x in c['source_positive_RGB_components']])for c in cons])
