from pathlib import Path
import json,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='heads-twenty-first';CALL=[3322,5259,6691]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];cons=[];groups={}
boxes={3322:[('whole original left warmhairpaint bank',[0,0,64,128]),('whole original right warmhairpaint bank',[64,0,128,128]),('original central darkpart and descending softpaint',[54,0,75,100]),('original lower curlpaint field',[5,79,123,121]),('original nearblack lowerUVfield',[0,120,108,128])],5259:[('whole original left brownhairpaint bank',[0,0,64,128]),('whole original right brownhairpaint bank',[64,0,128,128]),('original central darkpart',[52,0,71,105]),('original lower mattepaint field',[10,75,120,128]),('original subdued upperbackground',[0,0,128,11])],6691:[('original soft dark upper eyeCOLOR haze',[0,0,64,30]),('original brighter upper soft reflectionpaint',[28,17,39,29]),('original fainter lower soft reflectionpaint',[28,29,39,43]),('original dim left reddishgray weakpaint',[0,28,23,45]),('original lower softly varying graybrown field',[0,42,64,64])]}
counts={3322:{'observed_broad_lateral_painted_banks':2,'observed_central_dark_part':1,'observed_lower_cascade_paint_region':1},5259:{'observed_broad_lateral_painted_banks':2,'observed_central_dark_part':1,'observed_lower_paint_region':1},6691:{'observed_upper_dark_soft_color_haze':1,'observed_soft_existing_reflection_paint_patches':2,'reflection_patch_relative_strength':'upper stronger, lower fainter; count means blurred COLORpaint patches, not inferred iris/glints anatomy'}}
descs={3322:'Keep the TWO original softly painted warmgold/brown lateral hairpaint banks around the ONE original central dark part. Preserve each existing upper sweeping softband, original lower tapered paintcascade and all original lower softly looped curls at the SAME native phase/count/width/positions/scale/asymmetry. Do not add curls/locks/individual hairs/fibers or regularize the original paint. This is an original matte painted UV bitmap, not realphotohair: the source short blended brown/gold brushwaves remain short blended paint, not long individual glossy fibers. Preserve existing opaque black/nearblack UVgaps and original dark lower/side regions; do not crop or lighten them.',5259:'Keep TWO original softly painted muted warmbrown lateral banks and ONE original central darkpart, with all original curved short paintwaves/irregular tufts/brushmarks at their SAME native count/phase/width/scale/positions. Preserve the original lower fanpaint, asymmetric little dim pigmentmarks, original dark upper/side fields and subdued brownbackground. Do not add tufts/newcurls/locks/individual long hairfibers/shiny strands/physical grain; resolve only the existing softly blended mattepaint, retaining its original blur and local strength.',6691:'This is the ACTUAL original64x64 blurred EYE COLOR bitmap, not a request to render a new eyeball. Keep ONE original soft dark upper hazefield and the TWO original softly painted central reflectionpaint patches: stronger upper patch at original native[28:39,17:29], fainter lower patch at[28:39,29:43]. Preserve their native positions, tiny relative extents, indistinct blurred edges, exact subtlewarmgray/pink tint and upper-versus-lower weakness. Keep original dim reddishgray leftwash and softly varying lower graybrown field, not flatgrayfill. NO new iris/pupil/eyeball/eyelids/anatomy/glints/catchlights/veins/radialpattern/fibers/polygon/mosaic. Do not interpret the blur as missing detail; sourceblur is required material/scale.'}
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];lum=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['source_RGBA_RGB_A_NN_privately_inspected']=True
 r['material_evidence']['unknowns']='Exact staticMaterials/templates/Models only when present in fresh_actual_static_consumers; exact dynamicTHMID/Heads only when present in fresh_actual_dynamic_consumers. Mesh registration/runtime/weights not measured by worker. Root native/runtime/final acceptance.'
 r['source_only_reason']='Genuine original color artwork pending faithful weakpixel/nativepaintphase/material review, source-only0calls honest re-audit permitted, no family/type/human/A0 technical ban.'
 if i==6701:r['source_only_reason']='Full storedRGB genuine bluegraystippled beardcolor field with actual mixedA0..87, immutable every nativepixelfullRGBA. Remains genuinepending0call, not empty/A0 or masktechnical; new stipples/changedpatternphase prohibited.'
 if i in [6781,6782]:r['source_only_reason']='Genuine very weak subtly varying browCOLOR (distinctRGB/counts proven), full originalAlpha contains pairedbrow sourcepaint; NOT constantRGBA/color or technical from apparentflatness. Pending0call, preserve tinyoriginal weakpigment/phase rather than invent newcolored hairs/cloudwash.'
 if i==6921:r['source_only_reason']='Actual TransformableFaceTextures sourceCOLOR red/brown irregular damagepaint, exact original irregularpaint/holes/fullvariableA retained. Genuinepending0call, no new anatomy/wound geometry/gloss/granules; not technical because human/damage name.'
 if i not in CALL:continue
 assert (a[:,:,3]==255).all()
 if i in [3322,5259]:assert r['fresh_actual_static_consumers'] and not r['fresh_actual_dynamic_consumers']
 if i==6691:assert r['fresh_actual_dynamic_consumers'] and r['fresh_actual_dynamic_consumers'][0]['actual_layer_table']=='TransformableEyeTextures' and not r['fresh_actual_static_consumers']
 regions=[]
 for name,b in boxes[i]:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);regions.append({'name':name,'bbox':b,'native_pixels_ref':{'source_matrix_key':str(i),'matrix_file_SHA256':r['native_matrix_ref']['file_SHA256'],'slice_native_xyxy':b},'mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'min_RGB':v[:,:,:3].min((0,1)).tolist(),'max_RGB':v[:,:,:3].max((0,1)).tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())],'native_peak_xy':[x0+int(x),y0+int(y)],'native_peak_RGBA':v[y,x].tolist()})
 cons.append({'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':list(o.size),'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':regions,'source_feature_counts':counts[i],'count_qualification':'Counts only observed broad colorpaint regions/softpatches, NOT inferred anatomical hairs or physicalstrands. Exact EVERY native shortbrush/weakmark/palette/rowcolumnphase once immutable fullRGBA matrix; diagnostic regions not crop/BBox registration. Original count/phase wholecanvas muststay, no invented geometry/detail interpreted from blurred shapes.','native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_positive_weak_RGB_max_le5_pixel_count':int(((rgb.max(2)>0)&(rgb.max(2)<=5)).sum()),'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'source_description':descs[i],'actual_consumer':'Actual staticMaterials/template/Models source diffuse/hair for3322/5259; actual dynamicTransformableEyeTextures→THMID1→Heads for6691. NativeOrdinary straightRGB/fullA255 verified, no registration runtime measured.'})
 r['source_only_reason']='FIRST solebuiltin eligible after complete originalRGB/A/privateNN/nativeweakpixel/count/phase/palette/blur/actualconsumer/historyrelease parity proof.'
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[]});save(f'source-check-{ST}.json',P);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];w,h=c['native_size'];parts=['Use case: precise-object-edit. Faithfully edit this exact original Silent Storm softly PAINTED COLOR texture bitmap at higher resolution while preserving the original art, material and blur.',f'Image1 is the ENTIRE edit target: EXACT ORIGINAL native{w}x{h} storedRGB madeopaque at original resolution, no enlargement/grid/NNblocks. Preserve entire normalized original UV and original native pattern scale/phase/count. Original completeAlpha is255 and will be restored downstream with only one global numerical brightness scalar. Ordinary straightRGB, no premultiplication. Keep original nativeblur as artwork, not missing anatomy/detail.',descs[i],f'Exact original fullRGBA extrema {c["actual_RGBA_extrema"]}; strongestoriginalpaint nativeRGBA {c["native_source_max_mean_RGBA"]} at native {c["native_source_max_mean_RGB_xy"]}. Retain original peakandweaklocalpaint strength and hue relationships, every original softbrushphase/nativepatternsize. Gently resolve SAME fine matte sourcepaint only. No photo texture/hairfibers/fineparallelstrands/pores/anatomy/newglints/newcatchlights/mosaic/newmottle/cloudwash/sharperoutlinedrims/physicalgrain/relief.', 'Output ONLY SAME ENTIRE opaqueRGB squarecanvas at identical normalized sourceUV: no crop/whitespace/border/cutout/padding/fitting/zoom/recenter/autoBBox/repack/composite. No new parts/tufts/curls/counts/text/glyph/symbol/colors or sharp outlines. Original source alpha restored separately; defaultpadding preserved.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
print('Heads21 immutable BEFORE source12/candidate3',[(c['id'],c['source_feature_counts'],c['native_source_max_mean_RGBA'])for c in cons])
