from pathlib import Path
import json,hashlib,shutil,re
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='heads-thirteenth';CALL=[6688,6689,6690]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'));constraints=[]
reasons={6691:'Original Eyes_Old has soft almost erased source iris/pupil, not1clear iris/pupil/two glints. Zero calls to avoid inventing an eye. Genuine source paint pending, not missing typed definition.',1126:'Actual Materials745/opaque ordinary static eye diffuse; no TransformableEye THMID chain claimed. Source includes iris plus broad sclera/eyelid paintfields with more complex lower highlight marks; exact full detail proof deferred, zero calls.',5259:'Genuine actual Material3409/opaque hair diffuse with many intertwined original locks/part and native soft fine paint; exact lock detail/phase deferred, zero calls.',6772:'Genuine material4696/alpha_test hair, full native sourceA255; original brown curls and finer strokes not fully counted in this scope. Zero calls, not blanket complexity exclusion.',6773:'Genuine gray hair source, mixed actual Materials4697 alpha_test and5851 opaque. NativeA255 exact; count/phase of curls deferred, zero calls.',6775:'Genuine brown hair actual diffuse with two existing thin polygonal edge shapes; detailed original strand and wire counts not fully established, zero calls.',6776:'Genuine gray hair actual diffuse with two existing thin polygonal edge shapes; detailed original strand/wire counts deferred, zero calls.',1897:'Genuine inverted head/teeth/eye native atlas, actual Material1299. Need exact tooth-count/identity/UV detail proof before a faithful call; zero calls, no reinterpretation of face.',2183:'Genuine inverted head/teeth/eye native atlas, actual Material1462. Exact identity/teeth detail counts deferred, zero calls.'}
for r in proof['source_checks']:
 i=r['id'];r['full_original_and_helper_privately_inspected']=True;r['source_only_reason']=reasons.get(i,'Original64square eye layer with1iris/1pupil/2painted patches verified against full native source and matrix BEFOREprompt. One FIRST builtin call planned. Previous Heads11/12 source-only reviews are readonly re-audit, not previous generation.')
 if i not in CALL:continue
 a=np.asarray(Image.open(B/f'original/{i}.png').convert('RGBA'));assert a.shape==(64,64,4)and (a[:,:,3]==255).all()
 boxes={'one_iris':[20,16,47,43],'one_dark_pupil_with_original_upper_patch_overlap':[28,24,38,35],'upper_original_reflection':[31,21,35,27],'lower_original_tinted_reflection':[29,35,34,39]};regions={}
 for n,b in boxes.items():
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1,:3];yy,xx=np.unravel_index(v.mean(2).argmax(),v.shape[:2]);regions[n]={'native_bbox':b,'exact_source_RGB_matrix':v.tolist(),'mean_RGB':v.mean((0,1)).tolist(),'max_RGB':v.max((0,1)).tolist(),'max_mean_source_xy':[x0+int(xx),y0+int(yy)],'max_mean_source_RGB':v[yy,xx].tolist()}
 assert regions['upper_original_reflection']['max_mean_source_xy']==[33,24];assert regions['lower_original_tinted_reflection']['max_mean_source_xy']==[31,36]
 assert regions['lower_original_tinted_reflection']['max_mean_source_RGB']!=[255,255,255]
 c={'id':i,'count_evidence':'Full original+helper private view BEFOREtool: ONE source iris, ONE source dark pupil, TWO already existing softly painted reflection patches. Native original matrix, centers/scale and tinted intensity recorded; not generated photoreal fiber inference. Bboxes only numeric domains, never cropped/composited references.','source_RGBA_SHA256':hashlib.sha256(a.tobytes()).hexdigest(),'source_feature_counts':{'iris':1,'pupil':1,'reflection_patches':2},'region_diagnostics':regions,'source_pupil_core_RGB_native31_30':a[30,31,:3].tolist(),'source_whole_RGBA_matrix':a.tolist(),'source_whole_corner_RGBA':{f'{x},{y}':a[y,x].tolist()for x,y in [(0,0),(63,0),(0,63),(63,63)]},'actual_mode':'Dynamic TransformableEyeTextures THMID1→TransformableHeadMaterials→actual Heads, not static opaque or alpha_test material. Original TypeOrdinary/sourceA255, native4x whole256square, root unchanged layers/weights/CPU sampler.'}
 constraints.append(c)
save(f'pattern-constraints-{ST}.json',constraints)
save(f'scope-{ST}.json',{'ids':[r['id']for r in proof['source_checks']],'call_ids':CALL,'previous_sourceonly_reaudit_ids':[6688,6689,6690,6691],'coordinator_clarification':'Source-only audit with no raw/call does not prohibit first generation. Only previously accepted/called/generated/held IDs cannot repeat. Fresh global aliases/sameRGBA/queue/alljobs/raw/calls guarded separately.','pending_uncalled_ids':[r['id']for r in proof['source_checks']if r['id']not in CALL]})
save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in constraints:
 i=c['id'];up=c['region_diagnostics']['upper_original_reflection']['max_mean_source_RGB'];low=c['region_diagnostics']['lower_original_tinted_reflection']['max_mean_source_RGB']
 parts=['Use case: precise-object-edit. Asset type: exact historical softly painted Silent Storm eye COLOR UV layer.', 'Input image1 is the exact whole64x64 source RGBA. Image2 is the IDENTICAL whole storedRGB nearest12x source-only guide. Faithfully refine this same complete bitmap at higher resolution, with only very subtle finer original paint. Keep exactly the reference full square composition, every original location, pupil/iris proportions, all soft gray-brown filler and the gentle broad light/dark washes, native pattern scale and original tinted palette. No face, eyelids or new anatomy. This is a softly painted game texture, not a realistic photograph.', f'Keep ONE original iris centered near33,30 and ONE original dark central pupil at exactly the original footprint. Preserve TWO already existing softly painted reflection patches only: upper weak vertical patch near native[31,21,35,27) with source peak33,24 RGB{up}; lower SMALL DIM TINTED patch near[29,35,34,39), peak31,36 RGB{low}. The lower patch is weaker and tinted as in source, never a white glossy catchlight. Preserve their exact native center/size/color relationship/softness. Do not create any third light spot, white glint, specular ring or new radial iris design.', 'Keep the iris original softly mottled subdued pigment distribution and soft dark border, not sharp crystalline jewel/mosaic/stripes. No photofibers, etched radial fibers, spokes, capillaries/veins, checker/mosaic/noise/weave, harsh glossy bevel, enlarged highlights, new iris rings, invented pores or glossy wet geometry. Do not sharpen the existing pale patches into white photoglare. Do not change shadow/fill colors or brighten black native pigment; retain the source local hierarchy and original gray-brown sclera softness.', 'Output the ENTIRE square source canvas edge to edge with EXACT same normalized UV. Full original sourceA255 will be restored independently and brightness corrected with one pure scalar; avoid local highlight strengthening. No crop, zoom, padding, whitespace, fitting individual iris, BBox registration, isolated eye cutout or UV rearrangement. No text/logos/new markings. Actual dynamic eye color layer remains unchanged.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
# One save mechanism only, exact original/reference identity portable in metadata.
s=(B/'save_equipment_thirty_third_call.py').read_text(encoding='utf-8').replace('equipment-thirty-third',ST)
s=s.replace("proof=next(x for x in json.loads((BASE/'source-check-heads-thirteenth.json').read_text(encoding='utf-8')) if x['id']==id_)","proof=next(x for x in json.loads((BASE/'source-check-heads-thirteenth.json').read_text(encoding='utf-8'))['source_checks'] if x['id']==id_)")
s=s.replace("record['source_transform_recipe']=proof['helper_recipe']","record['source_transform_recipe']=proof['reference_recipe']").replace("record['source_rgba_sha256']=proof['source_rgba_sha256']","record['source_rgba_sha256']=proof['source_RGBA_SHA256']")
s=s.replace("([f'assets/terrain-hd/expanded/original/{id_}.png'] if premultiply else [])","[f'assets/terrain-hd/expanded/original/{id_}.png']")
(B/'save_heads_thirteenth_call.py').write_text(s,encoding='utf-8')
for fn in ['preview_equipment_thirty_third.py','detail_equipment_thirty_third.py']:
 s=(B/fn).read_text(encoding='utf-8').replace('equipment-thirty-third',ST);s=re.sub(r'(?m)^IDS=.*$', 'IDS='+repr(CALL),s)
 (B/fn.replace('equipment_thirty_third','heads_thirteenth')).write_text(s,encoding='utf-8')
print('Saved BEFORE prompts/calls: ONEiris/ONEpupil/TWO tinted patches for',CALL)
