from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='heads-twenty-sixth';CALL=[3113]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
def ref(p):return {'path':rel(p),'file_SHA256':sha(p)}
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];cons=[];rounds={}
code={'qualification':'Actual staticMaterials.TextureID→TemplateID→Heads MaterialID consumers verified, Models unknown/none found, not unused. Dynamic FaceGen registrations distinct; no THMID for selectedstatic3117. Whole sourcecanvas remains original atlas/A. Code describes sampling only, not anatomical meanings or measured runtimeweights/meshUV.','files':[ref(ROOT/n)for n in ['DBFormat/DataFaceGen.cpp','Main/LSHead.cpp','Main/FaceGenTextureSampling.h']]};save(f'consumer-code-proof-{ST}.json',code)
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];r['source_RGBA_RGB_A_NN_privately_inspected']=True;r['FaceGen_binding_code_ref']=ref(B/f'consumer-code-proof-{ST}.json')
 r['source_only_reason']='Genuine static headCOLOR fullUVatlas, not technical or excludedby human/dental/hair/family/variableA. Complex existinghair/beard/eyedental weakpaint/grouping requires additional source-specific literalbeforecount/phase proof for FIRST here; preserve fullRGBA and sourceblur/identity. Source-only pending0call, no original-only recommendation, no name-based anatomical reconstruction.'
 if i!=3113:continue
 assert o.size==(256,256)and r['fresh_actual_static_consumers']and not r['fresh_actual_dynamic_consumers']
 rgb=a[:,:,:3];lum=rgb.mean(2);rnd=np.array(o.convert('RGB').resize((1024,1024),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS));rounds[str(i)]={'id':i,'source_size':[256,256],'recipe':'ENTIRE sourceRGB FIRST LANCZOS4x then whole native separatelysourceA; no implicitpremul/artistrepair.','source_RGB_LANCZOS4x_then_native_RGB_matrix':rnd.tolist()}
 boxes=[('ONE inverted mutedskin sourcehead UVfield',[0,128,128,256]),('ONE sourceface closedmouth center',[16,175,113,222]),('ONE lower broad softwarmbrown backgroundpaint field',[0,218,128,256]),('ONE separate sourceeye iris/pupilpaint field',[64,64,128,128]),('ONE upper source lash/dental strip field',[0,0,64,49]),('ONE lower source dental strip field',[0,50,64,64]),('ONE sourceflatred rectangular field',[0,64,64,128]),('sourceblack rightcanvas',[128,0,256,256]),('ONE existing dimpale eye RGBpatch',[96,103,98,104])]
 domains=[]
 for name,b in boxes:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);domains.append({'name':name,'bbox':b,'native_pixels_ref':{'matrix_ref':r['native_matrix_ref'],'slice_native_xyxy':b},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_std_RGB':v[:,:,:3].std((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'source_peak_xy':[x0+int(x),y0+int(y)],'source_peak_RGBA':v[y,x].tolist(),'sourceA_extrema':[int(v[:,:,3].min()),int(v[:,:,3].max())]})
 patterns=[]
 for y,x0,x1 in [(44,1,63),(54,1,63),(59,1,63),(103,86,110),(94,86,110),(185,40,85),(207,15,112),(235,1,127)]:
  v=lum[y];xs=[x for x in range(x0,x1)if v[x]>v[x-1]and v[x]>=v[x+1]];patterns.append({'axis':'row','native_fixed_coordinate':y,'native_axis_interval':[x0,x1],'literal_paintshade_maximum_axis_coordinates':xs,'literal_count':len(xs),'native_successive_pitch':[b-a for a,b in zip(xs,xs[1:])],'qualification':'Literal sourcepigment maximum coordinates/nativephase, NOT physical tooth/eyelash/hairstrand/component counts or acceptance thresholds.'})
 patches=[{'xy':[x,y],'sourceRGBA':a[y,x].tolist()}for x,y in [(96,103),(97,103),(97,98),(20,100),(0,255),(255,255),(64,185),(42,208),(83,208)]]
 assert a[103,96,:3].tolist()==a[103,97,:3].tolist()==[198,178,173]
 desc='Keep full256square original atlas normalizedUV/orientation. ONE inverted softmutedskin headFIELD atnative x0..127/y128..255; same TWO sourceeyes/TWO brows/TWO ears/ONE nose/ONE CLOSED mouth already inthatfield, same expression/identity/sourceblur and original unequalshadows. Do NOTrotate/upright/fill mouth/teeth/reshape ears/face/brows. Same original broad softwarmbrown lowerbackgroundpaint/nativephase, no inventedhair/fibers. ONE separate oldeyeFIELD x64..127/y64..127 withONE mutedbluegray iris/ONE blackpupil atsamepositions. Keep existingdim reflectionpaint: a singlepale2pixel patch x96..97/y103 RGB198/178/173 stays tinted/soft and samefootprint, preserve every other weakbluegrayringpixel, no extra catchlights/veins/radialfibers/whitegloss. TWO existing separate upperstripFIELDS upperx0..63/y0..48 including sparseoldlash pixels and graydentalpaint, lowerx0..63/y50..63 with originalrow49gap. EVERY originalmicrograytooth/stripshape/spacing/weakpigment from source stays same, no invented dental anatomy/extra rows/newtooth detail. These are TWO observedUVstripFIELDS, not a claim of physicaltoothnumber from luminancemaxima. ONE flatdarkred field x0..63/y64..127 remains completelyflat SAME sourceRGB, no grain. Wholeblackright x128..255/y0..255 and otherblackUV sourceRGB staysblack; A0color/weakoldlashes neitherfillnornewmaterial. Keep allsourcevalues/alpha authoritative, evenhiddenRGB.'
 cons.append({'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':[256,256],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':{'inverted_original_sourcehead_fields':1,'original_head_eyes':2,'original_head_brows':2,'original_head_ears':2,'original_head_nose':1,'original_closedmouth':1,'separate_eye_iris':1,'separate_eye_pupil':1,'original_uv_dental_lash_strip_fields':2,'observed_pale_two_pixel_eyepigment_patch':1},'source_probe_RGBA':patches,'native_repeat_count_phase_evidence':patterns,'native_sourceA0_pixel_count':int((a[:,:,3]==0).sum()),'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'qualification':'Literal fullnative anatomy/domain shape from sourceview, no reinterpretation/photoanatomy. Pigment extrema do not prove physical tooth/hair/eyelash counts. Descriptive fullUVbboxes notcrop/islandregistration. Sameunknown runtime/modelmeshUV, actualstaticHeads/material proof only.','source_description':desc,'actual_static_consumers':r['fresh_actual_static_consumers']});r['source_only_reason']='Eligible FIRST3113 sourceclosedmouth/blurrednativepaint/invertedUV/identity literal; ONE facefield/ONE separateeye/TWO upperstrips preserve everytiny sourcepigmentshape with exactfullnativephase evidence, not inferred toothstrand counts. Actual staticMaterials1921/5554→Template1288/3036→Heads41/94/98, no model/dynamicTHMID invented.'
save(f'natural-RGB-roundtrip-{ST}.json',{'sources':rounds,'before_call':True})
for c in cons:c['natural_RGB_roundtrip_ref']=dict(ref(B/f'natural-RGB-roundtrip-{ST}.json'),source_key=str(c['id']))
save(f'pattern-constraints-{ST}.json',cons);save(f'original-only-proof-{ST}.json',[]);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_count':len({r['source_rgba_sha256']for r in P}),'fresh_ID_scope_ids':[r['id']for r in P],'previous_scope_sourceonly_reaudit_ids':[],'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[]});save(f'source-check-{ST}.json',P);assert not(B/f'source-check-{ST}-before-call.json').exists();shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Asset type: softlypainted original HEAD COLOR UV atlas, not a portrait or photo. Faithful finer rendition of SAME ENTIREbitmap preserving exactsourceidentity/orientation/blur/nativepaintscale/material/palette/relativeweakpigment/UV/shape/count.', 'Image1 is ENTIREnative original256square straight storedRGB madeopaque at SOURCEresolution. NativeOrdinary straightRGB/fullvariableoriginalA restored separately plusstandardwhole scalar/defaultpadding downstream. NNusedprivateonlyforcount, NOT toolreference. Actual static diffuseMaterials/Template→Heads, not dynamicTHMID or photoanatomy inference.',c['source_description'],'Native sourceRGBA extrema '+str(c['actual_RGBA_extrema'])+', strongest source meanRGB '+str(c['native_source_max_mean_RGBA'])+' at'+str(c['native_source_max_mean_RGB_xy'])+' authoritative. Sourcefilteredmatte pigment and bluntsoft transitions retained. Keepdimgray/brown localpeaks tinted atsame footprint; notwhite255/uniform reconstructedcatchlight. Source backgroundflatred andblackUV remainflat, no mottle.', 'Subtle SAME sourcepaint ONLY. NO photographicpores/hairfibers/beardgrain/individualhair reconstruction/newlocks/skintexture/stipple/mesh/weave/mosaic/granules/grain/sharperraisedrims/etchedlines/anatomy changes/irisradialfibers/veins/newcatchlights/gloss/glare/whiteglints/teeth count changes/newrows/implants/newtoothcontours/neweyebrows/newears/newmouthshape/bodyparts/glyphs/logo. Do not infer imaginarymicrodetail hidden by originalblur. Preserve oldsoftbackgroundbrushshape and allnative dental/graypaint weakphase.', 'Output SAME ENTIRE SQUARE opaqueRGB atlas. No whitespace/padding/frame/border/transparentcutout/crop/zoom/recenter/rotate/upright/BBox/fitting/islandmoves/registration. Sourceface remains inverted, ONEface/ONEseparateeye/TWOupperstrips/flatred/blackUV exactnormalizedpositions and ORIGINALmaterial/blur/sourceA/paintscale.']
 arg='\r\n\r\n'.join(parts);f=B/f'generated/{i}-prompt.txt';assert not f.exists();f.write_bytes((arg+'\n').encode('utf-8'));(B/f'generated/{i}-{ST}-exact-call-argument.txt').write_bytes(arg.encode('utf-8'))
print('Immutable BEFORE12/prospectiveFIRST3113/nooriginalrec',[(p['native_fixed_coordinate'],p['literal_paintshade_maximum_axis_coordinates'])for p in cons[0]['native_repeat_count_phase_evidence']])
