from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='equipment-thirty-sixth';CALL=[5390]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'))
pending={5235:'Existing tiny checker patch and two gray oval fields contain fine slots/holes whose exact count and phase need additional source proof; genuine art pending0calls.',5236:'Full original shows existing tiny printed marking on right gray field. Printed content not regenerated; genuine source-only pending0calls. No affine helper or call.',5237:'Existing gray atlas includes line-network field, upper round field and lower gray washes; exact native line-network count/phase not established, genuine pending0calls.',5243:'Existing brown checker field, two round fields and tiny printed label; native glyph/mark content not regenerated, genuine pending0calls.',5244:'Existing olive checker field, two round fields and tiny printed label; native glyph/mark content not regenerated, genuine pending0calls.',5248:'Existing olive atlas has tiny printed central content and several soft round fields; exact source content/count unresolved, genuine pending0calls.',5249:'Existing grayblue atlas includes elongated fields and tiny printed label; native content unresolved, genuine pending0calls.',5329:'Existing olive round/hexagonal field and many small gray polygonal fields contain very dim marks; exact phase and content unresolved, genuine pending0calls.',5331:'Existing graybrown atlas contains printed tiny labels and small holes/paint fields; exact microcontent unresolved, genuine pending0calls.',5333:'Existing olive atlas has fine gray washes and tiny lower gray panel marks; exact dim content/phase unresolved, genuine pending0calls.',5383:'Existing gray capsule-like painted field has repeated checker pattern, plus two gray lower fields; exact repeated count/phase not proved in this scope, genuine pending0calls.'}
for r in proof:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA')
 r['full_original_RGBA_private_view']=True;r['full_source_RGB_private_view']=True
 r['previous_source_only_views']=[p.relative_to(B.parents[2]).as_posix()for p in sorted(B.rglob(f'{i}-*source*.png'))if ST not in p.as_posix()][:10]
 r['view_novelty']='Honest source-only re-audit where earlier views exist; accepted/generated/called/held/exactRGBA-to-called guarded. No first-ever-view claim.'
 r['source_only_reason']=pending.get(i,'Genuine matte graybrown/olive diffuse wholecanvas: source native tonal band phase, completeRGBA matrix and source palette proven before sole first call; no new hardware interpretation.')
 r['zero_call_native_RGBA_extrema']=[list(z)for z in o.getextrema()]
o=Image.open(B/'original/5390.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];l=rgb.mean(2)
v=l[24:31,11:18].mean(1);peaks=[24]+[y+24 for y in range(1,len(v)-1)if v[y]>v[y-1]and v[y]>v[y+1]]
assert peaks==[24,26,29],peaks
c={'id':5390,'before_prompt':True,'native_size':list(o.size),'source_RGBA_sha256':hashlib.sha256(o.tobytes()).hexdigest(),'actual_RGBA_extrema':[list(z)for z in o.getextrema()],'whole_native_RGBA_matrix':a.tolist(),'semantic_qualification':'Domains describe the ENTIRE native bitmap, not cropped references, placement, physical mechanisms or artistic repairs. Opaque black native pixels remain source paint/shadow. Three graycyan tonal paint bands are measured source intensity lobes, not inferred physical vents/steps/fasteners.','source_canvas_observation':'Native32x32 ONE entire muted graybrown/olive painted atlas. Existing softly shaded round gray field upper left; broad gray lower-left rectangular field; small graycyan lower-middle field; right warm brown/olive flat shadow and lower warm lighter wedge field. Exact original all pixel fields/edges remain wholecanvas.','source_tonal_band_count':3,'source_band_native_y_phase':peaks,'source_band_profile_domain':[11,24,18,31],'source_band_rows_meanRGB':[{'y':y,'mean_RGB':rgb[y,11:18].mean(0).tolist(),'native_RGB':rgb[y,9:20].tolist()}for y in range(21,32)],'source_domains':[]}
for name,b in [('upper left gray round painted field',[0,0,18,21]),('lower left gray painted rectangle',[0,21,8,32]),('lower middle three original graycyan tonal paint bands',[9,21,20,32]),('right dark warm brown olive source field',[18,0,32,21]),('lower right warm source paint wedge',[20,21,32,32])]:
 x0,y0,x1,y1=b;z=rgb[y0:y1,x0:x1];c['source_domains'].append({'name':name,'bbox':b,'native_RGB':z.tolist(),'mean_RGB':z.mean((0,1)).tolist(),'max_RGB':z.max((0,1)).tolist()})
save(f'pattern-constraints-{ST}.json',[c]);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in proof],'sole_call_ids':CALL,'maximum_call_count':3,'pending_uncalled_ids':[r['id']for r in proof if r['id']not in CALL]})
save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
p='\r\n\r\n'.join(['Use case: precise-object-edit. Faithful Silent Storm matte painted accessory diffuse UV COLOR texture edit, subtle higher-resolution source paint.', 'Image1 is the EXACT ENTIRE native32x32 storedRGB original, solely whole NEAREST16x opaqueRGB enlargement. Preserve identical edge-to-edge normalizedUV/composition, palette, complete source tonal field positions/counts/scale/phase and original softness. Final source alpha is restored separately; brightness matched globally numerically. Output the entire same source canvas.', 'Preserve existing upper-left softly shaded gray round painted field, lower-left broad flat gray rectangular paint field, small lower-middle graycyan field and entire right dim warm brown/olive field with its existing lower warm wedge shade. Graycyan field native[9,21,20,32] has EXACT THREE original softly painted tonal horizontal bands: top at native y24, second y26, lower broad band y28..30 peaking y29. Retain exact native pitch/phase and original width, contrast, tint, flat paint softness. They are source tonal marks, not new vents, mechanical steps, grilles, ridges, buckles or fasteners. Keep every weaker native pixel wash and shadow where it already is. Actual source RGB maxima '+str(list(o.getextrema())[:3])+ ' are local existing paint pixels, not permission for bright rims or white accents.', 'Refine only the same subdued matte painted source color with very fine gentle brush transitions. Do not add physical/photo grain, new weave, etching, scratches, shine, bevel, raised rims, embroidery, new lines, hardware, bolts, rivets, straps, buttons, holes, patterns, printed marks, or interpret vague gray washes as mechanisms. Keep original dim local strengths and softly painted boundaries. Opaque native black remains shadow/paint, not a cutout hole.', 'Output ONLY the ENTIRE opaqueRGB texture canvas. No crop, zoom, whitespace, padding, frame, recenter, cutout, repacking, autoBBox, new parts/counts/material, altered UV/scale, photo anatomy or physical object rendering. Preserve full original composition and relative dark/light fields.'])
pp=B/'generated/5390-prompt.txt';assert not pp.exists();pp.write_bytes(p.encode('utf-8'))
print('Before-call immutable proof:12 sources,1 planned first call,band phase',peaks)
