from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='clothing-fifty-third';CALL=[7615]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];constraints=[];rounds={};groups={}
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];lum=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['source_RGBA_RGB_A_NN_privately_inspected']=True
 r['source_only_reason']='Genuine actual Materials→TemplateID→Models complete diffuse COLOR source, previous source-only ZEROcall honestly freshly reaudited. NativeRGBA/history/release/type/A/POT/material roles proven. Exact weakshade/old tiny marks/pattern count and phase/intentional sourceblur require literal further sourceproof before FIRST; genuine pending0call without name/type/family ban or guessed physicalmeaning.'
 if i in [1870,2933,3256,3306,3313,3314]:r['source_only_reason']+=' Specific fullatlas small existing text-like marks, painted scratches/gray contours and many differently shaded parts need exact literal count/UV/sourcepaint-scale proof. No blanket Robot/material ban; sourceblackA255 authored paint, not presumed holes.'
 if i in [2005,4451]:r['source_only_reason']+=' Source repetitive irregular camouflage/barklike shade pattern is genuine paint, not prohibited because repeated. Complete pixel phase/count/sourceblur retained; local tiny old marks and irregular pattern-scale not simplified into a new regular grid.'
 if i==6835:r['source_only_reason']+=' Two sides of old center graywash with many dim marks may not be reinterpreted as new hardware/lacing/grid; existing sourcepaint count/phase must remain.'
 if i not in CALL:continue
 assert o.size==(128,128) and o.getchannel('A').getextrema()==(255,255) and r['material_evidence']['actual_source_native_type']=='Ordinary'
 rnd=np.array(o.convert('RGB').resize((512,512),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS));rounds[str(i)]={'id':i,'source_RGB_LANCZOS4x_then_native_RGB_matrix':rnd.tolist(),'recipe':'ENTIRE originalRGB FIRST independentlyA LANCZOS4x→native whole inverse; no implicitRGBA premul/crop/artistpatch.'}
 yy,xx=np.mgrid[36:56,80:128];warmphase=(xx+yy)%2==0;roi=rgb[36:56,80:128];actualwarm=roi[:,:,0].astype(int)-roi[:,:,2].astype(int)>20
 assert np.array_equal(actualwarm,warmphase) and int(actualwarm.sum())==480 and np.all(roi[~warmphase]==[24,28,33])
 checker={'source_bbox':[80,36,128,56],'source_interior_size':[48,20],'interior_pixel_count':960,'warm_pixel_count':480,'gray_pixel_count':480,'native_cell_pitch_xy':[1,1],'literal_phase_rule':'warm if (native_x+native_y)%2==0, gray if odd','ALLodd_interior_sourceRGB':[24,28,33],'source_exact_phase_asserted':True,'qualification':'Actual existing painted pixelchecker interior/count/nativephase. Not physical textile fibers/mesh holes/beads/stitches. Source whole field boundary aroundx78..127/y35..56 remains exact fullRGBA, no isolatedchecker insertion/registration.'}
 boxes=[('ONE upper-left red vertical striped painted field',[0,0,78,88]),('ONE original shoe-like darkpaint field with old ONEhorizontal grayline',[27,26,78,67]),('ONE upper-right dark gray painted rectangle',[78,0,128,35]),('ONE original warm-gray checkerpaint rectangle with source boundary',[78,35,128,57]),('Actual exact checkerinterior phase diagnostic',[80,36,128,56]),('TWO existing narrow vertical brown marks belowchecker',[78,57,128,67]),('ONE existing tiny open triangular paintoutline',[2,80,7,86]),('ONE lower central softlyfiltered dark gray field',[27,67,108,128]),('ONE lower-right graypaint vertical field with old tinyblackmark',[108,67,128,128]),('ONE oldtinyblackpaintmark within grayfield',[112,115,117,120]),('Original lower-left blackpaint and old smallcyan-gray line',[0,88,27,128])]
 domains=[]
 for name,b in boxes:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);domains.append({'name':name,'bbox':b,'native_pixels_ref':{'matrix_ref':r['native_matrix_ref'],'slice_native_xyxy':b},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_std_RGB':v[:,:,:3].std((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'source_peak_xy':[x0+int(x),y0+int(y)],'source_peak_RGBA':v[y,x].tolist(),'sourceA_extrema':[255,255]})
 profiles=[]
 for axis,coord,z0,z1 in [('row',8,0,74),('row',40,80,128),('row',41,80,128),('column',96,36,56),('row',60,78,127),('column',2,79,87)]:
  v=lum[coord] if axis=='row'else lum[:,coord];xs=[z for z in range(max(1,z0),min(z1,len(v)-1))if v[z]>v[z-1]and v[z]>=v[z+1]];profiles.append({'axis':axis,'native_fixed_coordinate':coord,'native_axis_interval':[z0,z1],'literal_paintshade_maximum_axis_coordinates':xs,'literal_count':len(xs),'native_successive_pitch':[b-a for a,b in zip(xs,xs[1:])],'qualification':'Source pixel pigment maxima only, not physicalfolds/shoeparts/holes/fasteners or acceptance thresholds. Source fullmatrix/parity interior is authoritative.'})
 desc='ENTIRE native128square original matte red/charcoal/dark gray clothing COLOR UV painting. Keep ONE original red vertical stripepaint field occupying upper-left x0..77/y0..87, with its uneven source vertical soft stripes/native paintperiod unchanged; ONE original softly shaded dark shoe-like paintfield x27..77/y26..66 and its original ONE thin horizontalgrayline; ONE darkgray upper-right rectangle x78..127/y0..34; ONE existing warmtan/darkgray pixelchecker painting at x78..127/y35..56, not new cloth weave or mesh. Its precisely proven interior x80..127/y36..55 is48columns×20rows at ONE-native-pixel pitch:480 originalwarm colorpixels and480 oldgray pixels, alternating by (native_x+native_y)%2; all oddgray interiorpixels are originallyRGB24/28/33. Preserve SAME existing smallcell scale/count/phase, soft existing painted-color edges and original rowwise warmshade gradient; NO new checker rows/columns, larger cells, beads, weave, embroidery, mesh or physicalrelief. Keep TWO original narrow vertical brown paintmarks belowchecker atx81 and104 in y57..66 with old brownhorizontalfield; ONE existing tiny dim open rightpointing triangular paintoutline x2..6/y80..85 EXACTLY, never make a newletter/logo/symbol or add another. Keep ONE broad original lowercentral darkgray soft mottled paintedfield x27..107/y67..127, ONE original lowerright darkgray verticalfield x108..127/y67..127 and its ONE original tinyblackpaintmark aroundx113/y117. Keep original lowerleftblackpaint and its originaltiny dim cyan-gray line, all blackRGB/A255 authoredpainting remains. Literal region positions and complete reference are exactUV; box coordinates descriptive, no cropping or separate field composites. Keep original filtered soft mattepaint rather than photo clothfibers/leathergrain/castmetal/newgrids/etchedlines/pores/mosaic/raised seams. No new parts, new anatomy, straps, buttons, wrinkles, logos, physicalholes or edgehighlights. Source checker alreadyexists; retaining it is not permission to place checker/weave on any other field. Redstripes and charcoalgrayfield remain SOURCE-dim and smooth with old nativebrushscale, not highcontrast texturedfibers. Preserve source contour softness, localweakshade strengths and full palette.'
 c={'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':[128,128],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':{'red_striped_paintfield':1,'dark_shoe_like_paintfield':1,'old_horizontal_grayline':1,'darkgray_upperright_field':1,'checker_paint_rectangle':1,'checker_interior_columns':48,'checker_interior_rows':20,'checker_interior_warm_pixels':480,'checker_interior_gray_pixels':480,'old_brown_vertical_marks_below_checker':2,'tiny_existing_open_triangular_outline':1,'lowercentral_darkgray_paintfield':1,'lowerright_gray_stripfield':1,'oldtinyblackpaintmark':1},'source_checker_exact_pixel_phase':checker,'native_repeat_count_phase_evidence':profiles,'native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_sourceA0_pixel_count':0,'source_description':desc,'qualification':'Complete original/nativeopaqueRGB/NN/A privately inspected BEFORE. Literal paintregion counts and exact pixelchecker phase from original native values, not guessed physical material/hardware. Sourcepeaks/extrema exact actualsource, no guessed255.'};constraints.append(c)
 r['source_only_reason']='Eligible FIRST7615 honest prior ZEROcall re-audit of matte red/charcoal Legs painting, exact128RGBA/history-release/Ordinary/A255/opaqueClamp actual Materials→TemplateID→Models. ONE redstripefield/ONE darkshoelikepaintfield/ONEcheckerrectangle/TWO oldnarrowbrownmarks/ONE tiny oldtriangularoutline/ONElowergrayfield/ONErightgraystrip/ONEtinyblackmark source-first literal. Native checkerinterior48×20,480warm+480gray,pitch1/parity proven BEFORE, not new physicalweave/mesh. Fullsourceblur/nativepaintscale/dimlocalpalette retain.'
save(f'natural-RGB-roundtrip-{ST}.json',{'sources':rounds,'before_call':True})
for c in constraints:c['natural_RGB_roundtrip_ref']={'path':rel(B/f'natural-RGB-roundtrip-{ST}.json'),'file_SHA256':sha(B/f'natural-RGB-roundtrip-{ST}.json'),'source_key':str(c['id'])}
save(f'pattern-constraints-{ST}.json',constraints);save(f'original-only-proof-{ST}.json',[])
save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'previous_scope_sourceonly_reaudit_ids':[r['id']for r in P],'fresh_ID_scope_ids':[],'maximum_call_count':3,'not_forced_calls':True,'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[],'qualification':'All12 honest previous source-only ZEROcall reaudits. No actualcalled/accepted/generated/held/raw/exactRGBA donor repeated; no family/name/typeban. Preaudit guard parsing correction separately disclosed before selection/nativeproof/toolcalls.'})
code=[]
for name in ['DBFormat/DataFormat.cpp','Main/LSHead.cpp','assets/terrain-hd/prepare_sources.py','assets/terrain-hd/match_brightness.py']:
 p=ROOT/name;lines=p.read_text(encoding='utf-8').splitlines();code.append({'path':name,'complete_file_SHA256':sha(p),'relevant_line_references':[{'line':k+1,'text':s}for k,s in enumerate(lines)if any(t in s for t in ['ImportField( "TextureID"','ImportField( "TemplateID"','ImportField( "Material0"','pMaterials[','pad_rgb_under_source_mask','def match_cell'])],'qualification':'Exact source code registration/slots/numerichelpers only. Actual consumers independently exactDBrefs; no fake dynamicHead/meshUV/runtime proof.'})
save(f'consumer-code-proof-{ST}.json',code);save(f'source-check-{ST}.json',P);assert not(B/f'source-check-{ST}-before-call.json').exists();shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in constraints:
 i=c['id'];arg='\r\n\r\n'.join(['Use case: precise-object-edit. Complete UV diffuseCOLOR texture edit: subtleHD of SAME original filtered matte painted material/sourceblur/nativepatternscale/literalcounts and weaklocalphase; all original content preserved.', 'Image1 edit target ENTIRE exactnative128square storedRGBopaque originalresolution reference. Native originalRGB, not NNenlarged blocks. Ordinary straightRGB/noPremul; complete sourceA255 separatelyrestored downstream. Fullsource only, no border/crop/zoom/UVregistration.',c['source_description'],f'Actual nativeRGBA extrema {c["actual_RGBA_extrema"]}, strongest meanRGB nativeRGBA {c["native_source_max_mean_RGBA"]} at{c["native_source_max_mean_RGB_xy"]}. Keep originaldim peaks, oldtinyoutline sourcepale189/170/165, never white255/gloss/etchedraisedrim. Fullweakpigment/softpaint preserved, no new coarsegrain or photo fibers.', 'Output SAME ENTIRE SQUARE opaqueRGB canvas, complete originalnormalizedUV/paintcount/checkerpitch-phase/material and shadehierarchy unchanged. No padding/whitespace/frame/crop/rotate/islandmoves/recenter/fitting/BBox. No new checker/weave on oldgrayredfields, no newpart/glyph/letter/anatomy/catchlight/button/seam/strap/holes/folds/stitching/metaltexture/leathergrain/embossing/glare. Keep sourcechecker as flat oldcolored paintedpattern at same scale only, not a wovenphotomaterial. Keep deliberate sourceblur elsewhere rather than inventing physicalgrain.'])
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes((arg+'\n').encode('utf-8'));(B/f'generated/{i}-{ST}-exact-call-argument.txt').write_bytes(arg.encode('utf-8'))
print('BEFORE12 complete sourceproof67DBrows; soleFIRST7615 checkerasserted480+480',[(c['native_source_max_mean_RGB_xy'],c['native_source_max_mean_RGBA'])for c in constraints])
