from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='clothing-fifty-fifth';CALL=[6806]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
def ref(p):return {'path':rel(p),'file_SHA256':sha(p)}
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];aliases=read(B/f'before-alias-proof-{ST}.json');am=read(B/f'before-alias-native-matrices-{ST}.json')['sources'];groups={};constraints=[];rounds={}
reasons={2016:'ONE old brown pointedpaint field with variablealpha, samecompressed sourceRGBA as5456. Highbit whole storedRGB includes brown background rather than canonicalblack; 14A pixels differ acrossaliases. Actualcolor/sourcepurpose not constantRGBA. Genuine pending firstcall0, no original-only classification, fullalpha/aliasdisposition requires root.',5456:'Same canonical and highbitRGBA as2016 within selectedpending scope. ONE oldbrown pointedpainting with variableA; fullhighbitalias brownRGB acrosscanvas and14A differences. No imagegen/no structural inference from Orders name.',5673:'Actual painted dark/bodyatlas with centralgray loop/brown diagonalfields and smallold diagonalgray repeats. Highbit alias exposes upper hiddenchain and bottomsmallwhite marking absent in canonical storedRGB although fullA matches; exactdual-source color disposition and tinyrepeat/literalmark fidelity unresolved, pending0call not alpha/nameban.',7641:'Soft darkbluegray cloth/bodywholeatlas with mutedredstripe/lowergray printing and smalloldmarks. Literal tinyoldprintedfield precision unresolved, genuinepending0 not unused/technical.',4442:'Soft gray/bodyatlas with twofoldfields and palegray repeat rectangles, smallgold/dark column+roundpaint emblem. Counts/nativephase of tinycolumn andprintedpaint unresolved, genuinepending0, no cloth/familyban.',4451:'Full graybrown/golden linearprinted/surface artwork with MANY existing vertically staggered dashes, centraldarkoval. Exact detailed stagger/nativephase needs further literalpaint proof; no repeatedpattern ban or newweave.',6835:'Darkgray wholebodyfield with centralmutedgray/khaki double-column narrow repeatpaint and lowerbrownstrip. Literal weakrepeat counts and nativephase not inferred as newly built laces/teeth; pending0 genuinecolor.',3892:'Graybodyatlas contains oldchain/grayverticalfields and smallwhite printedmarks. Highbit storedRGB reveals bodypainting belowchain differentfrom canonical, sameA. Exactchain andtinyprint/nativealias disposition unresolved; pending0 genuinelycoloredmaterial, not alpha/nameban.',801:'Exactsource oldgray insignia/markfields with variableA. HighbitRGB includes broadbodypainting underA0, canonical predominantlyblackbackground; not emptyRGB/constantRGBA. Existing outlinedmarks/glyph details needprecision anddual-aliasRGB disposition;0call genuinepending.',1760:'VariableA gray/gold/red oldmarkatlas, highbit hiddenbodyRGB differs and154A pixels differ acrossaliases. Tinyoriginalglyph/marks uncertain;0call genuinepending not name/alpha familyban.',1761:'VariableA gray/gold/red oldinsignia andlongchevronatlas; highbit hiddenbodyRGB unequal with samefullA. Glyph count/phase needsfurther literalproof;0call genuinepending, no source-onlyoriginal purpose claim.'}
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];groups.setdefault(r['source_rgba_sha256'],[]).append(i)
 row=next(v for v in aliases['rows']if v['id']==i);assert len(row['aliases'])==2 and all(v['historical_baseline_payload_exact']and v['historical_baseline_RGBA_exact']for v in row['aliases'])
 r['source_RGBA_RGB_A_NN_privately_inspected']=True;r['both_aliases_RGBA_RGB_A_whole_privately_inspected_before_call']=True;r['source_only_reason']=reasons.get(i,'FIRST6806 eligible afterfull literalpainting/palette/countphase proof below; no acceptance implied.')
 r['both_alias_native_proof']={'matrix_ref':ref(B/f'before-alias-native-matrices-{ST}.json'),'highbit_resource_key':str(i|0x01000000),'canonical_native_matrix_ref':r['native_matrix_ref'],'actual_Format':row['actual_Texture_Format'],'import_bIsDXT':row['CTexture_Import_bIsDXT'],'resource_when_gfx_texture_usedxt_0':row['resolved_resource_if_gfx_texture_usedxt_0'],'actual_dispatch_code_ref':ref(B/f'before-runtime-alias-code-{ST}.json'),'cross_alias_comparison':row['cross_alias_comparison'],'qualification':'BOTH fullRGBA/payload/sourceA/historyrelease beforecall individually, different RGB not conflated. Parent gfx0 runtime report and actualFormat dispatchpredicate; worker runtimeunknown/noGame.'}
 if i not in CALL:continue
 assert o.size==(256,128)and o.getchannel('A').getextrema()==(255,255)and r['material_evidence']['actual_source_native_type']=='Ordinary'
 alt=np.array(am[str(i|0x01000000)]['complete_original_alias_RGBA_matrix'],dtype=np.uint8);assert (alt[:,:,3]==a[:,:,3]).all()
 rgb=a[:,:,:3];lum=rgb.mean(2);profiles=[]
 for name,x0,x1,expect in [('left oldgraypaint cluster',23,29,[41,48,54,59]),('right oldgraypaint cluster',74,80,[41,48,54,58])]:
  z=rgb[34:65,x0:x1].mean((1,2));regions=[(40,42),(47,49),(53,55),(58,60)];peaks=[lo+int(np.argmax(z[lo-34:hi-34]))for lo,hi in regions];assert peaks==expect
  al=alt[34:65,x0:x1,:3].mean((1,2));profiles.append({'name':name,'native_bbox':[x0,34,x1,65],'whole_native_row_mean_RGB':[{'y':34+j,'mean':float(v)}for j,v in enumerate(z)],'four_existing_pale_paint_band_intervals':[list(v)for v in regions],'four_band_source_peak_rows':peaks,'source_peak_values':[float(z[y-34])for y in peaks],'highbit_alias_same_bbox_row_mean_RGB':[{'y':34+j,'mean':float(v)}for j,v in enumerate(al)],'qualification':'Four exact source graypaint shade-band anchors, not a newly inferred physical buckle/stitch/fastener count. Other weaknative maxima remain present in complete matrix. Preserve nativeblur and pitch/relativecolor, do not regularize left59/right58 into uniform4-row mechanism.'})
 boxes=[('TWOfront darkvertical paintingfields with TWO oldsmall graymark clusters',[17,0,84,122]),('ONE uppergray/dark horizontalfield and ONEold gray squarepaint',[0,0,173,18]),('ONEfront softlywashed gray field',[0,12,90,128]),('ONEback grayfield with ONE oldYlike painting THREEbranches',[85,0,174,108]),('FOUR separate ochrepaint fields around oldgraycutouts',[0,40,174,128]),('ONEright upper mutedbrown/blackwash stripfield',[174,0,256,43]),('ONEright lower olivebrown softwash rectangularfield',[174,43,256,128])]
 domains=[]
 for name,bb in boxes:
  x0,y0,x1,y1=bb;v=a[y0:y1,x0:x1];yy,xx=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);domains.append({'name':name,'bbox':bb,'native_pixels_ref':{'matrix_ref':r['native_matrix_ref'],'slice_native_xyxy':bb},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_std_RGB':v[:,:,:3].std((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'source_peak_xy':[x0+int(xx),y0+int(yy)],'source_peak_RGBA':v[yy,xx].tolist(),'sourceA_extrema':[255,255]})
 ochre_boxes=[[0,45,22,128],[23,89,76,128],[82,44,111,128],[149,43,174,128]]
 rounds[str(i)]={'id':i,'source_RGB_LANCZOS4x_then_native_RGB_matrix':np.array(o.convert('RGB').resize((1024,512),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS)).tolist(),'recipe':'Whole originalRGB LANCZOS4x→native inverse separatelyA, never implicitpremul or crop/repair.'}
 desc=('Edit ONLY the ENTIRE existing256x128 landscape color UVpainting. It is filtered mattegray/ochre/olivebrown paint, NOT a newly manufactured garment or photographicmaterial. Keep exact fullUV shape/positions/nativepatternscale and relativeweakshade. Left two-thirds have TWO existinggray largepaint fields, TWO long darkvertical frontpaint stripes with TWO small original graypaint markclusters, ONE oldupper gray squarepaint, ONE oldbackY-shaped darkpainting with THREEbranches, and FOUR oldochrepaint regions around the existinggraycutouts. Rightthird has ONE upper darkbrown washedstripfield and ONE lower softlyshaded olivebrown rectangle. Keep originalblackwash and gaps, originalgraycontoursoftness and irregularwaves. At nativeleft x23..28/y34..64 andright x74..79/y34..64 retain the existing graypaint clusters exactly; four old pale shadebands have sourcepeak rows41,48,54,59 left and41,48,54,58 right. Those are literal smallpaint shade positions, not instructions to fabricate four new buckles or regularlyspaced hardware. Keep all weaker shadedpixels and oldblur, no uniformmechanicalrepeat, no newloops/teeth/bars/seams. Preserve ONE original uppergray square and its existingtinysoftcentralpainting; no newlogo/text. Preserve FOUR ochrepaint regions including soft flatcolor, no skinpores/anatomy reinterpretation. Graywashed fields retain originalsoftbrush/filtering; darkbrownrightfield keeps its lowcontrast oldfold/tonalwash with no explicit fibers/weave/mesh/physicalgrain. Oldtinygraypeaks may reach255 at nativepixel(29,58), but mostpaint stays subduedgray and brown; do not expand oldpalepeaks into shining rims/whiteplates/etchedchrome/glints. Subtle higher-resolution filteredpaint of same image only, no brightening/photographicclothgrain/leathergrain/pores/newhardware/newstraps/stitches/buttons orsharp metalbevels.')
 constraints.append({'id':i,'before_prompt':True,'native_size':[256,128],'native_matrix_ref':r['native_matrix_ref'],'both_alias_native_proof':r['both_alias_native_proof'],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':{'large_graypaint_fields':2,'front_dark_vertical_fields':2,'oldgray_cluster_fields':2,'four_pale_shadeband_anchors_per_graycluster':4,'back_Ypaint_field':1,'Ypaint_branches':3,'olduppergray_square':1,'ochrepaint_regions':4,'rightupper_brownwash_strip':1,'rightlower_olivewash_field':1},'ochrepaint_region_native_bboxes':ochre_boxes,'native_repeat_count_phase_evidence':profiles,'native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_sourceA0_pixel_count':0,'source_description':desc,'qualification':'Literal nativewholepainting viewed beforetool, no name/anatomy/hardware interpretation substituted. BOTH aliases have equalA255 but unequalRGB; moderate quantization differences explicitlyproved beforecall. Fullcanonical source painting usedtool; actual highbit palette/sourceblur separatelyreviewed, not claim runtimeequal.'})
save(f'natural-RGB-roundtrip-{ST}.json',{'sources':rounds,'before_call':True})
for c in constraints:c['natural_RGB_roundtrip_ref']=ref(B/f'natural-RGB-roundtrip-{ST}.json')
save(f'pattern-constraints-{ST}.json',constraints);save(f'original-only-proof-{ST}.json',[])
save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'previous_scope_sourceonly_reaudit_ids':[r['id']for r in P],'fresh_ID_scope_ids':[],'maximum_call_count':3,'not_forced_calls':True,'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[],'qualification':'All12 honest priorZEROcall re-audits. SIX? countcomputed fromfullRGBA below, never assumedunique. Bothbaseline resourcealiases guarded againstaccepted/raw/call/held/donors beforeselection; pending sameRGBA2016/5456 withinselecteddisclosed. ONEFIRST6806 only, no quota.'})
code=[]
for name in ['DBFormat/DataFormat.cpp','Main/GTexture.cpp','Main/LSHead.cpp','assets/terrain-hd/prepare_sources.py','assets/terrain-hd/match_brightness.py']:
 p=ROOT/name;ls=p.read_text(encoding='utf-8').splitlines();code.append({'path':name,'complete_file_SHA256':sha(p),'relevant_line_references':[{'line':k+1,'text':s}for k,s in enumerate(ls)if any(t in s for t in ['ImportField( "TextureID"','ImportField( "TemplateID"','bIsDXT =','GetRealTextureID','pMaterials[','pad_rgb_under_source_mask','def match_cell'])],'qualification':'Full sourceSHA+exact relevantlines. ActualDB typedroles independentlyrefs; runtime/meshUV notinvented.'})
save(f'consumer-code-proof-{ST}.json',code);save(f'source-check-{ST}.json',P);assert not(B/f'source-check-{ST}-before-call.json').exists();shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in constraints:
 i=c['id'];arg='\r\n\r\n'.join(['Use case: precise-object-edit. Subtle HD of same full256x128 LANDSCAPE diffuseCOLOR UVpainting. Preserve literal existingfilteredpaint/UV/sourceblur/nativepaintscale/weakshade/material/count and pitch; no redesign.', 'Image1 ENTIRE exactnative256x128 opaque original storedRGB reference, not NNenlarged. Ordinary straightRGB/noPremul; fulloriginalA255 restored separately. Output SAME2:1 wholecanvas ratio and normalizedUV, no whitespace/crop/padding/fitting/islandmovement/rotation/recentering.',c['source_description'],f'Original completeRGBA extrema {c["actual_RGBA_extrema"]}, brightestmeanRGBA {c["native_source_max_mean_RGBA"]} at{c["native_source_max_mean_RGB_xy"]}. Preserve existing tinywhitepixel strength/size but no newwhite edges or glossy metal; retain softmattegray and mutedbrown/ochre hierarchy.', 'Keep entire oldpainting faithfully. HDrefinement remains softly filteredpaint, not clothfibers/photo skin/metalgrain/etchedmachining/rust/raisedrim/mesh/crosshatch/bevel/hardware. Existingweakfolds and irregularwashedshades stay soft at originalpatternscale. No new symbols, text, stripes, buckles, closures, pockets, seams, buttons or parts.'])
 pp=B/f'generated/{i}-prompt.txt';assert not pp.exists();pp.write_bytes((arg+'\n').encode('utf-8'));(B/f'generated/{i}-{ST}-exact-call-argument.txt').write_bytes(arg.encode('utf-8'))
print({'sources':12,'RGBAgroups':list(groups.values()),'FIRST':CALL,'literalfourbandleft':[41,48,54,59],'literalfourbandright':[41,48,54,58]})
