from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='equipment-thirty-fifth';CALL=[4867,5676,7653]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'));cons=[]
pending={675:'Genuine painted darkgray gasmask atlas; existing narrow pale field contains native printed N/8-like content and tiny circular details. Exact content/count unresolved, pending source-only0calls; no new hardware interpretation.',2213:'Genuine yellow-green painted foliage/cloth accessory with many original leaf fragments/folds; exact leaf/fold count/phase unresolved, pending0calls, not blanket complexity technical exclusion.',3384:'Genuine darkgray/brown painted robot-optic atlas; tiny rims/marks and hardware count unresolved, pending0calls, not a Bump/control classification.',3783:'Genuine olive/gray accessory atlas with existing tiny red star-like paint and regular gray surface pattern; exact tiny mark/pattern counts not established, pending0calls.',3784:'Genuine darkgray cloth field with existing ONE blue oval and tiny red native paintmark; cloth pattern phase/tiny mark content not established, pending0calls.',4948:'Genuine muted green/gray cap atlas with original pale curved edging and tiny brown right motif; fine motif/line phase counts not established, pending0calls, no shiny metal edge invented.',5652:'Genuine olive/gray accessory atlas with pale original material/shadows and tiny red mark; patternphase/weak details not fully proven, pending0calls.',5677:'Genuine gray/olive accessory atlas with multiple original gray panels and small red/star-like paint; exact panel/mark/regularpattern count pending0calls, no false technical classification.',6669:'Genuine brown soft-painted cloth accessory with existing full source red star-like mark; exact tiny content/count and fold phase not established here, pending0calls; no new badge or weave.'}
for r in proof:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.asarray(o);rgb=a[:,:,:3];l=rgb.mean(2)
 r['full_original_RGBA_private_view']=True;r['full_source_RGB_private_view']=True
 old=[p for p in B.rglob(f'{i}-*source*.png')if ST not in p.as_posix()]
 r['previous_source_only_views']=[p.relative_to(B.parents[2]).as_posix()for p in sorted(old)[:10]];r['view_novelty']='Honest source-only re-audit where prior views exist; raw/accepted/called/held/sameRGBA-to-called guarded. No first-ever-view claim.'
 r['source_only_reason']=pending.get(i,'Genuine muted painted full sourceRGB diffuse; exact original native matrices/local tone/phase/count saved before first built-in call. No unknown source shapes concretized as hardware; sourceA255 directly measured.')
 r['zero_call_native_RGBA_extrema']=[list(z)for z in o.getextrema()]
 if i not in CALL:continue
 c={'id':i,'before_prompt':True,'native_size':list(o.size),'source_RGBA_sha256':hashlib.sha256(o.tobytes()).hexdigest(),'actual_RGBA_extrema':[list(z)for z in o.getextrema()],'whole_native_RGBA_matrix':a.tolist(),'semantic_qualification':'Field boxes are exact bitmap diagnostic domains, NEVER references cropped/placed or artistic RGB patches. Source opaque dark pixels remain original paint/shadows, not holes inferred by color. Soft original shade areas are not asserted as new physical parts/hardware. Counts/phase/native matrix observed before prompt.'}
 if i==4867:
  v=l[28:41,0:3].mean(1);peaks=[y+28 for y in range(1,len(v)-1)if v[y]>v[y-1]and v[y]>v[y+1]];assert peaks==[29,31,33,35,37,39]
  c['source_left_partial_roundfield_horizontal_stroke_count']=6;c['source_stroke_exact_native_y_phase']=peaks;c['left_partial_roundfield_all_native_RGB']=rgb[20:53,0:15].tolist();c['source_roundfield_shape']='ONE existing clipped left graybrown round painted field with EXACT SIX original pale horizontal painted strokes y29,31,33,35,37,39. Existing curved/rim shade peaks at41/43 are separate boundary shading, not added strokes or metal hardware.'
  c['main_material']='ONE entire dim flat olive source paint field with existing very weak diagonal X-shaped olive wash below/around left roundfield, smooth plain olive background elsewhere; no source grain/physical cloth/rust/raised X seams to invent.'
  boxes=[('left partial roundpaint field and six existing pale strokes',[0,20,15,53]),('source weak olive X-like wash',[0,35,47,64]),('source plain olive field',[17,0,64,35])]
 else:
  c['source_canvas_observation']='ONE entire softly shaded dark grayblue/brown source accessory bitmap. Original left elongated shadow, top elongated horizontal shadow, broad lower rounded darkwash/soft curved outlines retained. These are existing bitmap shadows/edges, not an assertion of extra straps or material cutout/holes.'
  c['tiny_source_marks']='Exactly ONE existing small pale triangular/loop-like pixel paintoutline native[26,22,32,27], and ONE existing short dim horizontal painted line native[26,34,31,35], both no logos/glyph interpretation or new metal fasteners. Existing ONE round upper gray-shaded source paintfield native[30,8,46,24] retains every original light fleck/position/hierarchy, not a newly interpreted metallic button/rivet.'
  c['tiny_outline_all_native_RGB']=rgb[22:27,26:32].tolist();c['tiny_horizontalstroke_all_native_RGB']=rgb[34:35,26:31].tolist();c['upper_roundfield_all_native_RGB']=rgb[8:24,30:46].tolist()
  c['tiny_mark_native_row_maxima_phase']=[{'y':y,'native_RGB':rgb[y,25:33].tolist(),'strict_meanRGB_peak_x':[x+25 for x in range(1,7)if l[y,x+25]>l[y,x+24]and l[y,x+25]>l[y,x+26]]}for y in range(21,36)]
  boxes=[('left elongated source darkwash and original softgray/brown border',[0,8,21,60]),('top horizontal original shadow wash',[24,0,61,10]),('upper roundfield exact original gray paintflecks',[30,8,46,24]),('one tiny original triangular/loop paintoutline',[26,22,32,27]),('one short dim original pale stroke',[26,34,31,35]),('lower original rounded darkwash and soft broad border',[22,32,55,62])]
 c['source_domains']=[]
 for name,b in boxes:
  x0,y0,x1,y1=b;z=rgb[y0:y1,x0:x1];c['source_domains'].append({'name':name,'bbox':b,'native_RGB':z.tolist(),'mean_RGB':z.mean((0,1)).tolist(),'max_RGB':z.max((0,1)).tolist()})
 cons.append(c)
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in proof],'sole_call_ids':CALL,'maximum_call_count':3,'pending_uncalled_ids':[r['id']for r in proof if r['id']not in CALL]})
save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
base=['Use case: precise-object-edit. Asset type: faithful Silent Storm softly source-painted accessory diffuse UV COLOR texture edit, higher resolution.','Image1 is the EXACT ENTIRE original native storedRGB source, solely whole nearest enlargement. Preserve identical complete edge-to-edge normalizedUV/composition/material, every original shadow, source field size/scale/shape/phase and local weak paint strength. Original source alpha is preserved independently and final brightness globally matched numerically. Very subtle refinement of the same source paint; no photo/physical object render/interpretation of unresolved shapes.','Keep the same matte source paint palette and softly blurred original edges and existing local gray/brown/olive strengths. No new hardware/bolts/rivets/straps/holes/buttons, raised stitching/embossed seams/bevel/rims, new white plates/glints/shine/rust/weave/etched scratches/photograin/grids/coarse paintcells. Do not turn soft washes or vague native pixels into physical relief or sharpened logos/text. Every source faint mark stays equally faint and at exact location; native opaque black/dark areas stay shadows/paint, not automatically cutout holes.','Output ONLY the ENTIRE opaqueRGB source diffuse canvas with the identical original composition. No crop/zoom/padding/frame/recenter/cutout/repacking/autobbox, no sourceUV/scale/count/nativeA/material changes.']
special={4867:'Native64x64 source is dim smooth OLIVE flat paint with one existing clipped left graybrown rounded painted field and SIX original short pale horizontal source strokes at native y29,31,33,35,37,39. Keep EXACT count6, 2nativepixel pitch/phase and source widths/flat color strength; existing roundfield boundary shade at y41/43 is not another horizontal stroke or shiny hardware. Entire rest canvas is the SAME dim plain olive field, with the existing VERY WEAK diagonal X-like olive color wash below/around that roundfield. Preserve wash width/strength/blur/native position. Do NOT make X into a raised seam, strap, crossed rods, engraving or add uniform grain to smooth field. Keep roundfield and stripes flat/subdued/source matte softness, not metallic vent/rivet/rim. Actual original RGB maxima132/134/132 are source pale boundary pixels, not permission to brighten olive background or create new white rim.',5676:'Native64x64 source is ONE softly shaded DARK GRAYBLUE accessory diffuse canvas. Preserve original left elongated darkwash, top horizontal darkwash and lower rounded darkwash with their existing softly painted borders exactly. Keep ONE original upper round gray-shaded paintfield at native[30,8,46,24] with all existing flecks/relative tint exactly, no new chrome button/rivet or extra white catch. Keep EXACT ONE tiny pale triangular/loop pixel paintoutline at native[26,22,32,27], and EXACT ONE short dim horizontal line at[26,34,31,35], at the same native widths/phase. They stay small FLAT painted marks, not logos/glyph redesign, new buckle/fastener/holes or embossed hardware. Do not add leather pores/stitching/weave/folds. Keep original grayblue matte shade softness and palette; actual source individual RGB channel maxima198/199/198 remain only on existing pale source pixels, not widened highlights/white borders.',7653:'Native64x64 source is ONE softly shaded DARK WARM BROWN accessory diffuse canvas. Same original left elongated darkwash, top horizontal darkwash and lower rounded darkwash/soft painted borders keep their full exact footprint. ONE upper round shaded paintfield native[30,8,46,24] retains the original dim GRAY source flecks in exactly their current native count/phase/positions/intensities; no new glint or button/rivet/hardware interpretation. EXACT ONE tiny pale triangular/loop-like native pixel paintoutline[26,22,32,27] and EXACT ONE short dim horizontal line[26,34,31,35] keep their native sizes/location/colors and stay FLAT paint, not enlarged logos/buckles/fasteners. Preserve warm brown soft palette, do not add coarse leather pores/photo grain/seams/stitches/etched scratches. Source individual RGB channel maxima173/154/148 are only existing pale source marks, not permission for new highlights/white rims or brighter brownwash.'}
for i in CALL:
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(base[:2]+[special[i]]+base[2:]).encode('utf-8'))
print([(c['id'],c['actual_RGBA_extrema'])for c in cons])
