from pathlib import Path
import json,shutil,hashlib
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='clothing-forty-seventh';CALL=[2440]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json');M=read(B/f'native-matrices-{ST}.json')['sources'];cons=[];groups={};rounds={}
for r in P:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.array(o);rgb=a[:,:,:3];lum=rgb.mean(2);assert a.tolist()==M[str(i)]['native_RGBA_matrix'];groups.setdefault(r['source_rgba_sha256'],[]).append(i);r['source_RGBA_RGB_A_NN_privately_inspected']=True
 r['source_only_reason']='Genuine actual Materials→TemplateID→Models/Heads diffuseCOLOR source. FullstoredRGB/A/nativeexpression/weakphase/sourceblur preserved; source-only0call pending exactidentity/detail/material fidelity, not technical from Face/Head name. Honest allraw/call/held/accepted/exactRGBA guards pass; native source facepaint not automatically reconstructed into anatomy/photoportrait.'
 if i==3085:r['source_only_reason']='Individual actualMaterials1897 TextureID3085 / Template1271 opaqueClamp diffuseCOLOR with no staticModels consumers resolved. StoredRGB has79 distinctvalues and sparse whitegray linearpaint across black field, variableA0/255. Exact sourcepurpose unresolved; no fake structuralclassification/faceanatomy or original-onlyrecommendation. Genuinepending0call, every storedRGB/A byte preserved.'
 if i==3400:r['source_only_reason']='Individual actualstatic color diffuse source has186 distinctRGB values, nearflatwarmtanpaint plus TWO upperbandedbrown/lightpatches and a weaklefttonalmark, A255. FullRGBA notconstant and no provenanalyticpurpose. Genuinepending0call preservingweakpaint/nativephase ratherthan technical/name/family/nearflatness ban or inventedmissing face.'
 if i not in CALL:continue
 assert o.size==(128,128)and r['material_evidence']['actual_source_native_type']=='Ordinary'and o.getchannel('A').getextrema()==(255,255)and r['fresh_actual_static_consumers'];s=o.convert('RGB');rnd=np.array(s.resize((512,512),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS));rounds[str(i)]={'id':i,'source_size':[128,128],'source_RGB_LANCZOS4x_then_native_RGB_matrix':rnd.tolist(),'recipe':'Whole nativeRGB FIRST LANCZOS4x and entire native inverse independently originalA; no implicit PILRGBApremul/unpremultiply/rotation/crop/artistRGB.'}
 boxes=[('ONE original inverted centralfacecolorpaint with sameexpression',[28,22,111,99]),('ONE original visibleearpaint upperleft',[8,0,38,30]),('ONE originalleft topnearflatpaintstrip',[0,0,14,31]),('ONE originalbrown topbandedpaintpatch',[48,0,82,27]),('ONE originallighter topbandedpaintpatch',[98,0,123,27]),('FIRST originaldim brown eyeshadowpaint',[44,65,65,83]),('SECOND originaldim brown eyeshadowpaint',[69,65,89,83]),('ONE originalnosepigment',[56,48,74,65]),('ONE originalclosedpinkmouthpaint',[54,36,73,50]),('ONE originalforeheadsoftpaint',[42,77,89,99]),('ONE originaldarkbrown connectedlowerhairpaint andUVtips',[0,80,128,128])]
 domains=[]
 for name,b in boxes:
  x0,y0,x1,y1=b;v=a[y0:y1,x0:x1];y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2]);domains.append({'name':name,'bbox':b,'native_pixels_ref':{'matrix_ref':r['native_matrix_ref'],'slice_native_xyxy':b},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_std_RGB':v[:,:,:3].std((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'source_peak_xy':[x0+int(x),y0+int(y)],'source_peak_RGBA':v[y,x].tolist(),'sourceA_extrema':[255,255]})
 patterns=[]
 for axis,coord,z0,z1 in [('column',65,1,25),('column',108,1,25),('row',72,40,93),('row',43,52,77),('row',61,49,79),('row',105,1,127),('row',120,1,127),('column',24,1,28)]:
  v=lum[coord]if axis=='row'else lum[:,coord];xs=[z for z in range(z0,z1)if v[z]>v[z-1]and v[z]>=v[z+1]];patterns.append({'axis':axis,'native_fixed_coordinate':coord,'native_axis_interval':[z0,z1],'literal_paintshade_maximum_axis_coordinates':xs,'literal_count':len(xs),'native_successive_pitch':[b-a for a,b in zip(xs,xs[1:])],'qualification':'Literal weakpigment/nativephase profiles only, not numbers of physicalhair/teeth/fingers/anatomicalparts or acceptance thresholds.'})
 description='ENTIRE originalUV facepainting is deliberately UPSIDE-DOWN in this sourcecanvas: KEEP EXACTLY this orientation, do NOT rotate or create an uprightportrait. Keep ONE same centralinverted facepaint x28..110,y22..98 with identical expression/identity/shape/softpalette; ONE existing visibleearpaint topLEFT x8..37,y0..29, ONE lefttopflatpaintstrip, TWO existing topbandedpaintpatches brownx48..81,y0..26 andlighterx98..122,y0..26, TWO original dimbrown eyeshadowpaintpatches x44..64 and69..88,y65..82, ONE originalsoftnosepigment x56..73,y48..64, ONE originalclosedpinkmouthpaint x54..72,y36..49 with SAME existinglipstroke/no addedteeth or opening, ONE originalforeheadsoftpaint andONE originaldarkbrown lowerhairpaint/irregulartriangularUVtips x0..127,y80..127. These are exactexisting flatCOLORpaint domains, not new ears/pupils/eye anatomy/hairstrands. Keep same dimshadoweyes WITHOUT new iris/pupil/catchlight reconstruction, same faintmouth/nose/skinmarks, ONE earonly and old hairblur/paintscale/UVtip pattern. Existing topbandedpaintfields keep ALL original weakhorizontalstripes/nativephase—not newfingers/nails/glyphs. Fullsource extrema/weakpatch strengths authoritative; preserve originalmutedwarmbrown/pink/tan hierarchy and opaque darkUV, no brighterwhite glints/skinpores/photo hairfibers/grayfill. No physicalanatomy reinterpretation or inventing detail beneath sourceblur.'
 cons.append({'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':[128,128],'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':{'existinginvertedfacepaint':1,'visibleearpaint':1,'dimpairedshadoweyepaint':2,'nosepaint':1,'closedmouthpaint':1,'topbandedpaintfields':2,'connectedlowerhairpaintfield':1},'native_repeat_count_phase_evidence':patterns,'native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_sourceA0_pixel_count':0,'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in lum.T],'source_description':description,'qualification':'Literal nativeCOLOR painting features, not anatomyanalysis/physicalhair/fingers/teeth counts. Descriptiveoverlappingbboxes not crop/repack. ExactweaknativeRGBA/phase/blur/palette beforetool, source orientation fixed wholecanvas without rotation/registration.'})
 r['source_only_reason']='EligibleFIRST on genuinelynew originalinvertedFace wholeUV layout after sourcehistorical/release/nativeRGBA/POT/TypeA255/actualstaticMaterials→TemplateID→Models/fullRGB+A+NN/identity/softpaint/nativeweakphase/count proof. Complete native128opaque RGBtoolref, no NN/toolrotate/register; one sourcemouth/ear andpaired shadowpaint unchanged, no photoanatomy or sharpenedfibers.'
rp=B/f'natural-RGB-roundtrip-{ST}.json';save(rp.name,{'sources':rounds,'before_call':True})
for c in cons:c['natural_RGB_roundtrip_ref']={'path':rp.relative_to(ROOT).as_posix(),'file_SHA256':sha(rp),'source_key':str(c['id'])}
save(f'pattern-constraints-{ST}.json',cons);save(f'original-only-proof-{ST}.json',[]);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'maximum_call_count':3,'not_forced_calls':True,'pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[],'all_selected_outside_previousClothing1to46':True,'pending_exactRGBA_alias_qualification':'Selected12ID exactpayload groups enumerated fromnativeSHA. Any pendingonly sameRGBA groups are NOTaccepted/generateddonors; sole2440 FIRSTcall. Allaccepted/generatedexactRGBA excluded.'});save(f'source-check-{ST}.json',P);assert not(B/f'source-check-{ST}-before-call.json').exists();shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in cons:
 i=c['id'];parts=['Use case: precise-object-edit. Asset type: original softlyfiltered painted CHARACTER FACE fullUV diffuse COLOR map. Faithfully refine SAME ENTIRE sourcepainting with the SAME existing features/identity/expression/material/nativepaintscale/sourceblur/palette/count/weakphase.', 'Image1 is ENTIRE exactnativeoriginal128square storedRGB madeopaque at originalresolution, NO NNtoolenlargement. ActualstaticMaterials→TemplateID→Models/Heads diffusebitmap, NOT newlyrenderedhumanportrait or dynamicFaceGen anatomy. NativeOrdinary straightRGB/noPremul/fullsourceA255 separatelyrestored/defaultwholebrightnessscalar andpadding downstream. All darksourceRGB/A255 is authoredUV paint, not holes.',c['source_description'],f'Exact originalnativeRGBA extrema {c["actual_RGBA_extrema"]}; strongestnativeRGBA {c["native_source_max_mean_RGBA"]} at{c["native_source_max_mean_RGB_xy"]}. Keep that same SMALL old topbandedpaint peak/localstrength/width and sourceweakdark/pinkfields, do not replace by white255 or multiplyglints. Sourceblur is intentionalfilteredpaint; originaldim eye/ear/skin/hair/closedmouth marks remain dimsoft, not sharper anatomy.', 'Only subtle SAME filteredpaint rendition at higherresolution, retain originalsoftness. NO skinpores/stubble/beardgrain/freckles/newscars/anatomy/eyelashes/newbrows/iris/pupil/catchlights/teeth/openmouth/expressionchange/lipsreconstruction/hairfibers/photo hair/newlocks/curls/newears/fingers/nails/newUVpatches/raisedrims/highmicrocontrast/skinphototexture/photo-portrait/mosaic/coarseblocks/backgroundmottle. Flatpaint fields and originalfilteredhair remain originalbitmapmaterial, not reconstructedphysicalfeatures.', 'Output SAME ENTIRE SQUARE opaqueRGB UVcanvas, deliberately originalUPSIDE-DOWN face plus originaltopbandedfields/lowerhairtips, NO rotation/uprightface/crop/portrait/framing/whitespace/padding/border/zoom/recenter/BBox/fitting/registration/islandmoves. FullsourceUV/A/nativecounts/weakphase/sourcepalette/blur/material unchanged.']
 arg='\r\n\r\n'.join(parts);p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes((arg+'\n').encode('utf-8'));(B/f'generated/{i}-{ST}-exact-call-argument.txt').write_bytes(arg.encode('utf-8'))
print('Cl47 immutable12ID/uniquegroups/ONEprospectiveFIRST',[(c['id'],c['native_source_max_mean_RGBA'],c['native_source_max_mean_RGB_xy'])for c in cons])
