from pathlib import Path
import json,hashlib,shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent;ST='equipment-thirty-seventh';CALL=[5238,5409]
def save(n,v):(B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
proof=json.loads((B/f'source-check-{ST}.json').read_text(encoding='utf-8'));cons=[]
reasons={i:'Genuine painted source atlas has existing tiny printed label/content; preserve exact original glyphs, pending source-only0calls without redesign. Not technical by material/name.'for i in [5239,5240,5241,5242,5245,5246,5247,5250,5251]}
reasons[5372]='Genuine painted rolled cloth/bandage atlas with TWO original round lowerfields and an existing red cross/tiny printed label. Existing label content and fine repeatedcloth phase unresolved, source-only genuine pending0calls, not ban on cloth/repeated patterns.'
for r in proof:
 i=r['id'];o=Image.open(B/f'original/{i}.png').convert('RGBA');a=np.asarray(o);rgb=a[:,:,:3];l=rgb.mean(2)
 r['full_original_RGBA_private_view']=True;r['full_source_RGB_private_view']=True;r['actual_source_RGBA_extrema']=[list(v)for v in o.getextrema()]
 r['previous_source_only_views']=[p.relative_to(B.parents[2]).as_posix()for p in sorted(B.rglob(f'{i}-*source*.png'))if ST not in p.as_posix()][:10]
 r['view_novelty']='Fresh source-only re-audit where older helpers/views exist; not first-ever view claim. Accepted/raw/calls/jobs/held/refusal/exactRGBA guards independent and authoritative.'
 r['source_only_reason']=reasons.get(i,'Genuine subdued sourcepaint full diffuse; exact native counts/phase/allRGBA/weakmark local strengths BEFORE sole FIRST call, not newhardware interpretation.')
 if i not in CALL:continue
 c={'id':i,'before_prompt':True,'native_size':list(o.size),'source_RGBA_sha256':hashlib.sha256(o.tobytes()).hexdigest(),'actual_RGBA_extrema':[list(v)for v in o.getextrema()],'whole_native_RGBA_matrix':a.tolist(),'every_native_row_pigment_maximum_x':[[int(x+1)for x in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l],'every_native_column_pigment_maximum_y':[[int(y+1)for y in np.where((v[1:-1]>v[:-2])&(v[1:-1]>=v[2:]))[0]]for v in l.T],'semantic_qualification':'Numeric domains and tonal crests describe original full bitmap, NEVER cropped source references/placement/composites or guessed physicalhardware. No inferred individual wireturn/mechanicalpart count from threshold components. Opaque native black is intentional sourcepaint/shadow, not alpha emptiness.','source_domains':[]}
 if i==5238:
  v=l[15:24,0:26].mean(1);peaks=[y+15 for y in range(1,len(v)-1)if v[y]>v[y-1]and v[y]>v[y+1]];assert peaks==[16,18,20,22]
  assert rgb[58,20].tolist()==[239,227,239]and rgb[58,21].tolist()==[131,125,131]
  c.update(source_upper_parallel_paint_stroke_count=4,source_upper_parallel_native_y_phase=peaks,source_single_upper_dim_line_native_y=7,source_original_tiny_pale_point_count=1,source_tiny_pale_point_native_bbox=[20,58,22,59],source_tiny_pale_point_RGBA=a[58:59,20:22].tolist(),source_field_counts={'upperright_dark_oval_gray_outline':1,'below_it_gray_roundpaintfield':1,'bottomright_darkred_roundfield':1,'lowerleft_gray_rectangularpaintfield':1,'tiny_existing_pale_point_with_two_native_tonal_pixels':1},source_count_limits='ONE source tiny pale paintspot has239/227/239 pixel native20,58 and131/125/131 adjacent21,58. Preserve both, never invent bolt/glint. FOUR parallel original upperleft lines at y16/18/20/22 and ONE dim upperline y7 are observed flat paintstrokes, not physical ribs. Existing gray separator field y27..33 and lower redfield pale line y41 separate from those4.' )
  boxes=[('upper darkred painted rectangle and original dimline y7',[0,0,36,16]),('four existing parallel upperleft paintstrokes',[0,15,36,24]),('middle gray separator paintfield',[0,27,36,34]),('lower warmred paintfield and original pale liney41',[0,34,36,48]),('upperright original gray oval outline and darkcenter',[40,5,61,31]),('gray roundpaintfield below upperoval',[35,31,58,51]),('lowerleft gray rectangularpaintfield',[0,50,31,64]),('one original tiny pale point',[18,55,24,61]),('bottomright darkred roundpaintfield',[43,47,64,64])]
 else:
  for y in [42,43]:
   v=l[y,0:11];peaks=[x for x in range(1,len(v)-1)if v[x]>v[x-1]and v[x]>v[x+1]];assert peaks==[2,4,7,9],peaks
  c.update(source_ringpaint_field_count=2,source_lowerleft_measured_interior_tonal_crest_count_on_ray=4,source_ray_native_y=[42,43],source_ray_crest_native_x=[2,4,7,9],source_ray_clipped_outerboundary_native_x=0,source_count_limits='TWO source dark-centered grayblue ringpaint fields (one small upperleft,one larger lowerleft). Exactly FOUR measured interior tonecrests x2/4/7/9 along nativey42/43 lowerleft ray, outerclipboundary x0 separate. Variable2/3/2pixel pitch must not regularize. This measures source paint phase, NOT invented exact number of physical wireloops. Complete allRGBA/native maxima preserve every other native curved segment and irregularity.')
  boxes=[('upperleft original small grayblue ringpaintfield',[10,7,27,23]),('lowerleft original large grayblue ringpaintfield',[0,28,40,64]),('four measured original interior tonecrests and clipped outerboundary',[0,42,11,44]),('top original grayblue vertical painted stripes',[0,0,10,31]),('central narrow vertical original grayblue shadefield',[35,22,48,64]),('right complete vertical original grayblue shadefield',[48,0,64,64]),('original lowerleft ring dark center',[10,38,25,57])]
 for name,b in boxes:
  x0,y0,x1,y1=b;z=rgb[y0:y1,x0:x1];c['source_domains'].append({'name':name,'bbox':b,'native_RGB':z.tolist(),'mean_RGB':z.mean((0,1)).tolist(),'max_RGB':z.max((0,1)).tolist()})
 cons.append(c)
save(f'pattern-constraints-{ST}.json',cons);save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in proof],'sole_call_ids':CALL,'maximum_call_count':3,'pending_uncalled_ids':[r['id']for r in proof if r['id']not in CALL]});save(f'source-check-{ST}.json',proof);shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for i in CALL:
 c=next(x for x in cons if x['id']==i)
 parts=['Use case: precise-object-edit. Historical Silent Storm softly matte PAINTED equipment UV diffuse COLOR bitmap, faithful subtle high-resolution sourcepaint.', 'Image1 is the EXACT ENTIRE original native64x64 storedRGB source, solely whole NEAREST8x512 opaqueRGB enlargement. Preserve the COMPLETE edge-to-edge normalizedUV/native fields/count/phase/scale/palette/shadows and original local weak strengths. Original fullsource alpha is separately restored, brightness only ONE global numerical scalar. No physical object render or interpretation of vague pixels as extra mechanisms/hardware.']
 if i==5238:
  desc='Same subdued DARK RED/BROWN and gray paint wholeatlas. Keep source upper-left red rectangle and ONE dim horizontal paintline y7; its FOUR original fine parallel flat paintstrokes at nativey16/18/20/22 retain EXACT count4, source2pixel pitch/phase/width/dim softness, not physical ribs. Keep middle gray separator field y27..33, lower warmred field and its ONE existing pale soft line y41, existing upper-right gray OVAL outline with darkcenter, ONE gray roundpaintfield below it, ONE lower-left gray rectangle and ONE dim darkred lower-right roundfield. Keep exact original gray irregular outlines, black gaps, shapes/positions and palette. Preserve ONE existing tiny PALE PAINT POINT in lowerleftgray field at native[20,58,22,59]: first pixelRGB239/227/239, next131/125/131, same exact two-pixel tiny footprint. It is a flat source paintpoint, not permission for a new white bolt/glint/fastener or any extra dots. Keep source softgray borders and subdued red strengths, no raised metal bevel/rims or new engravedlines.'
 else:
  desc='Same DARK MATTE GRAYBLUE source paint wholeatlas. Keep TWO original dark-centered grayblue ringpaintfields: ONE small upperleft,ONE larger lowerleft, every original irregular curved tonal line and darkcore gap; do not create physical shinywire/rings/cables/hardware. In large lowerleft sourcefield EXACT FOUR interior tonal crests lie at nativex2/4/7/9 on nativey42–43; original clipped outerboundary x0 is separate. Preserve EXACT4 measured interior crests and IRREGULAR2/3/2pixel phase/pitch, never regularize or add rings. Keep original top-left vertical pale/dark paintstripes, central narrow grayblue vertical shadefield and complete rightside original vertical grayblue shades; every tiny weak source highlight stays same strength/location. Native black throughout is original opaque paint/shadow, not cutout emptiness. Do not turn faint bluegray wash into new white rods/chrome bevels/coarse knurl/etchedgrooves or additional physical mechanisms. Preserve original softly painted boundary/material/detail scale; not a photo.'
 parts +=[desc,f'Actual source wholeRGBA extrema are {c["actual_RGBA_extrema"]}. Preserve original local light hierarchy and weak pigments. Very subtle fine PAINT only, no photograin/pores/stipple/mosaic/coarse brushcells/rust/weave/shine/sharperwhite outlines. No new bolts/rivets/straps/buttons/parts or new text/marks. Do not brighten shadow fields or create pale plates.','Output ONLY the SAME COMPLETE full opaqueRGB source square, same normalizedUV. No crop/zoom/padding/whitespace/frame/cutout/autobbox/repack/fitting/sourceRGB patches/newcount/shape/material. Entire originalalpha/defaultpadding restored downstream; no invented alpha.']
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes('\r\n\r\n'.join(parts).encode('utf-8'))
for filename in ['preview_equipment_thirty_seventh.py','detail_equipment_thirty_seventh.py']:
 p=B/filename;p.write_text(p.read_text(encoding='utf-8').replace('IDS=[5238]','IDS=[5238,5409]'),encoding='utf-8')
print('Immutable beforecall12sourceproof,exactnativephase, FIRST sole',CALL)
