from pathlib import Path
import json, hashlib, shutil
import numpy as np
from PIL import Image
B=Path(__file__).resolve().parent; ROOT=B.parents[2]; ST='clothing-fifty-second'; CALL=[5683]
def read(p): return json.loads(p.read_text(encoding='utf-8'))
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p): return p.relative_to(ROOT).as_posix()
def save(n,v): (B/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
P=read(B/f'source-check-{ST}.json'); M=read(B/f'native-matrices-{ST}.json')['sources']; constraints=[]; rounds={}; groups={}
for r in P:
 i=r['id']; o=Image.open(B/f'original/{i}.png').convert('RGBA'); a=np.array(o); rgb=a[:,:,:3]; lum=rgb.mean(2)
 assert a.tolist()==M[str(i)]['native_RGBA_matrix']; groups.setdefault(r['source_rgba_sha256'],[]).append(i)
 r['source_RGBA_RGB_A_NN_privately_inspected']=True
 r['source_only_reason']='Genuine actual Materials→TemplateID→Models full diffuse COLOR source, honest fresh re-audit of previous source-only ZEROcall. Full nativeRGBA/history/release/POT/Type/A/consumer proven. Existing tiny marks, complicated patterns or ambiguous physical meaning need literal complete native phase/material proof before any FIRST call. Genuine pending0call, not technical by family/name/type/alpha, no guessed parts.'
 if i in [3892,4442,4549,5688,7641]:r['source_only_reason']+=' Specific old small glyph/number/mark identities and adjoining weak paint are individually unresolved here; do not reinterpret their meaning or invent replacements.'
 if i not in CALL: continue
 assert o.size==(256,256) and o.getchannel('A').getextrema()==(255,255) and r['material_evidence']['actual_source_native_type']=='Ordinary'
 rounds[str(i)]={'id':i,'source_RGB_LANCZOS4x_then_native_RGB_matrix':np.array(o.convert('RGB').resize((1024,1024),Image.Resampling.LANCZOS).resize(o.size,Image.Resampling.LANCZOS)).tolist(),'recipe':'ENTIRE sourceRGB independentlyA LANCZOS4x then entire native inverse; no implicitRGBA premul/crop/patch.'}
 boxes=[('ONE muted rusty-red angular paintfield',[38,24,118,113]),('TWO existing adjacent upper/lower small gray paintpatches',[95,50,124,114]),('ONE upper broad softlyfiltered darkgray field',[22,0,220,139]),('ONE old lower horizontal brown-gray marked band',[49,124,195,160]),('ONE lower-left arched darkgray painting with inner semicircular lightpatch',[0,162,119,219]),('THREE existing thin tapering horizontal gray painted strips',[39,219,116,256]),('ONE lower middle rectangular gray field with existing two horizontal lightbands',[119,166,197,256]),('ONE lower right narrow vertical gray stripfield and adjoining original black field',[196,164,256,256]),('ONE upper right softly curved gray paintfield with old tiny strokes',[219,0,256,164]),('ONE left upper verticalgray strip and middle darkgray patch',[0,0,39,162])]
 domains=[]
 for name,b in boxes:
  x0,y0,x1,y1=b; v=a[y0:y1,x0:x1]; y,x=np.unravel_index(v[:,:,:3].mean(2).argmax(),v.shape[:2])
  domains.append({'name':name,'bbox':b,'native_pixels_ref':{'matrix_ref':r['native_matrix_ref'],'slice_native_xyxy':b},'source_mean_RGB':v[:,:,:3].mean((0,1)).tolist(),'source_std_RGB':v[:,:,:3].std((0,1)).tolist(),'source_min_RGB':v[:,:,:3].min((0,1)).tolist(),'source_max_RGB':v[:,:,:3].max((0,1)).tolist(),'source_peak_xy':[x0+int(x),y0+int(y)],'source_peak_RGBA':v[y,x].tolist(),'sourceA_extrema':[255,255]})
 profiles=[]
 for axis,coord,z0,z1 in [('column',72,218,254),('column',128,164,254),('row',135,49,195),('row',58,95,124),('row',103,95,124),('row',80,38,118)]:
  v=lum[coord] if axis=='row' else lum[:,coord]; xs=[z for z in range(z0,z1) if v[z]>v[z-1] and v[z]>=v[z+1]]
  profiles.append({'axis':axis,'native_fixed_coordinate':coord,'native_axis_interval':[z0,z1],'literal_paintshade_maximum_axis_coordinates':xs,'literal_count':len(xs),'native_successive_pitch':[b-a for a,b in zip(xs,xs[1:])],'qualification':'Literal native pixel luminance phase, not inferred physical mechanisms/fasteners/count thresholds. Complete originalRGBA authoritative; overlapping boxes diagnostic only, not UV crop/registration.'})
 desc='ENTIRE native256square softly filtered matte charcoal-gray/rusty-red diffuse COLOR painting. Retain ONE original muted rusty-red angular polygon at upper-left-middle x38..117,y24..112, TWO original adjacent tiny gray painted patches on its right (upper aroundx109..122,y52..71 and lower aroundx95..113,y95..112), the ONE original broad upper darkgray softly folded/wash field, ONE old horizontal brown-gray marked band x49..194,y124..159, ONE lower-left arched darkgray painted field with its ONE inner semicircular softly bright patch, THREE existing thin tapering horizontal gray strip-paint shapes below it in x39..115,y219..255, ONE lower-middle rectangular softly gray field with the original TWO horizontal lightbands, original lower-right narrow vertical gray stripfield and black painted field, ONE upper-right curved gray wash field with its existing weak tiny strokes, original left-upper gray strip and middle dimgray paintpatch. These are literal existing flat painted color regions, not a request to reconstruct physical plates, clasps, screws, belt machinery, ribs or bolts. Keep ALL original tiny old marks indistinct in the SAME exact positions/counts/phase and all old narrow lines unchanged; do not regularize or invent unknown hardware. The reference includes deliberate soft filtered dark folds and old brown/gray lines: retain their native breadth, position, relative dimness and sourceblur, never turn softwash into photocloth/weave/fibers, castmetal grain, etching, raised gray rims, chrome shine or embossed relief. Keep original red matte and muted, same original irregular border, no bright white edge or new scratches, rust granules, labels or logo. Black RGB with sourceA255 is authored black paint, not empty UV area to repaint. ALL complete native canvas/sourceblur/sourcepaintscale authoritative, no material substitution or added contours.'
 c={'id':i,'before_prompt':True,'native_matrix_ref':r['native_matrix_ref'],'native_size':list(o.size),'actual_RGBA_extrema':M[str(i)]['actual_source_RGBA_extrema'],'native_source_max_mean_RGB_xy':M[str(i)]['native_peak_mean_RGB_xy'],'native_source_max_mean_RGBA':M[str(i)]['native_peak_mean_RGBA'],'source_domains':domains,'source_feature_counts':{'muted_red_angular_paintfield':1,'adjacent_tiny_gray_paintpatches':2,'lower_left_inner_semicircular_paintpatch':1,'lower_left_tapering_horizontal_gray_strips':3,'lower_middle_horizontal_lightbands':2},'native_repeat_count_phase_evidence':profiles,'native_zero_RGB_pixel_count':int((rgb.max(2)==0).sum()),'native_sourceA0_pixel_count':0,'source_description':desc,'qualification':'Full original and nativeNN privately inspected BEFORE. Literal paintregion counts and pixelshade profiles, no guessed physicalpart semantics. Boxes overlap and are diagnostic only; no cropping/UVregistration. No source pattern simplified or intensified.'}
 constraints.append(c);r['source_only_reason']='Eligible FIRST honest re-audit of prior ZEROcall Body5683: matte charcoalgray/rustyred complete256painting, Ordinary straightRGB/A255, opaque Clamp actualstaticconsumer. Literal ONEredpolygon/TWOgraypatches/ONEinnersemicircle/THREEthinlowerstripshapes/TWOlowerhorizontalbands source-first proven. Physical meaning of other weak marks not guessed; retain exactfull painting/nativeblur/material/weakphase.'
save(f'natural-RGB-roundtrip-{ST}.json',{'sources':rounds,'before_call':True})
for c in constraints:c['natural_RGB_roundtrip_ref']={'path':rel(B/f'natural-RGB-roundtrip-{ST}.json'),'file_SHA256':sha(B/f'natural-RGB-roundtrip-{ST}.json'),'source_key':str(c['id'])}
save(f'pattern-constraints-{ST}.json',constraints);save(f'original-only-proof-{ST}.json',[])
save(f'scope-{ST}.json',{'selected_ids':[r['id']for r in P],'unique_native_RGBA_groups':list(groups.values()),'unique_native_RGBA_count':len(groups),'sole_call_ids':CALL,'previous_scope_sourceonly_reaudit_ids':[r['id']for r in P],'fresh_ID_scope_ids':[],'maximum_call_count':3,'not_forced_calls':True,'genuine_pending_uncalled_ids':[r['id']for r in P if r['id']not in CALL],'recommended_original_only_ids':[],'qualification':'All12 honest previous clothing source-only ZEROcall reaudits; global eligible80 contains no fresh ID outside Cl1–51. Source-only views are not calls. No accepted/generated/held/raw/exactRGBA donor repeated.'})
code=[]
for name in ['DBFormat/DataFormat.cpp','Main/LSHead.cpp','assets/terrain-hd/prepare_sources.py','assets/terrain-hd/match_brightness.py']:
 p=ROOT/name; lines=p.read_text(encoding='utf-8').splitlines(); code.append({'path':name,'complete_file_SHA256':sha(p),'relevant_line_references':[{'line':k+1,'text':s}for k,s in enumerate(lines)if any(t in s for t in ['ImportField( "TextureID"','ImportField( "TemplateID"','ImportField( "Material0"','pMaterials[','pad_rgb_under_source_mask','def match_cell'])],'qualification':'Exact current source code registration/material slots and numerical downstream helper; actual consumers remain independent DBrefs, no dynamicFace/meshUV/runtime claim.'})
save(f'consumer-code-proof-{ST}.json',code)
save(f'source-check-{ST}.json',P); assert not (B/f'source-check-{ST}-before-call.json').exists();shutil.copyfile(B/f'source-check-{ST}.json',B/f'source-check-{ST}-before-call.json')
for c in constraints:
 i=c['id'];arg='\r\n\r\n'.join(['Use case: precise-object-edit. Full UV diffuse COLOR texture editing: subtle HD reconstruction of the SAME softly filtered original painted material, sourceblur/nativepatternscale and weaklocalshade. Preserve all original image content.', 'Edit Image1 ENTIRE exactnative256square storedRGB opaque reference. It is original native RGB, not enlarged blocks. Ordinary straightRGB/noPremul, complete originalA255 restored separately. Whole reference only, no new objects/parts, no photographic render.',c['source_description'],f'Actual nativeRGBA extrema {c["actual_RGBA_extrema"]}; native strongest meanRGB pixel is {c["native_source_max_mean_RGBA"]} at {c["native_source_max_mean_RGB_xy"]}. Preserve source dim peak hierarchy, do not turn pale marks into white255, glare, sharp rims or new grain. Source softwash intentionally painted and filtered, no sharpened physical mechanisms.', 'Output ENTIRE SAME SQUARE opaqueRGB canvas with all original paint fields and tiny marks in their exact normalized UV positions. No crop/padding/border/whitespace/rotate/recenter/BBox/island move/zoom/fitting. No invented screws/bolts/buckles/rivets/labels/letters/symbols/grids/weave/fibers/new seams/rust/raised edges/glints. No extra microtexture/regular mark columns. Keep old soft contours and dark painted areas, native pattern scale and original subdued palette.'])
 p=B/f'generated/{i}-prompt.txt';assert not p.exists();p.write_bytes((arg+'\n').encode('utf-8'));(B/f'generated/{i}-{ST}-exact-call-argument.txt').write_bytes(arg.encode('utf-8'))
print('BEFORE12 reaudits/soleFIRST5683',[(c['id'],c['native_source_max_mean_RGB_xy'],c['native_source_max_mean_RGBA'],c['native_repeat_count_phase_evidence'])for c in constraints])
