from pathlib import Path
from datetime import datetime,timezone
import sys,json,hashlib,shutil
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='effects-thirty-ninth';i=int(sys.argv[1]);output=Path(sys.argv[2]);raw=B/f'generated/{i}-raw.png';assert not raw.exists();shutil.copyfile(output,raw)
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
proof=next(r for r in read(B/f'source-check-{ST}-before-call.json')if r['id']==i);prompt=B/f'generated/{i}-prompt.txt';refs=[proof['helper_recipe']['output']];arg=prompt.read_bytes().decode('utf-8');constraints=B/f'pattern-constraints-{ST}.json'
record={'id':i,'tool':'built-in image_gen.imagegen','tool_output':output.name,'tool_output_session':output.parent.name,'saved_utc':datetime.now(timezone.utc).isoformat(),'generated':rel(raw),'raw_sha256':sha(raw),'prompt_file':rel(prompt),'prompt_sha256':sha(prompt),'exact_prompt':arg,'transparent_background':False,'reference_pngs':refs,'reference_sha256':{r:sha(ROOT/r)for r in refs},'source_rgba_sha256':proof['source_rgba_sha256'],'source_transform_recipe':proof['helper_recipe'],'pattern_constraints_ref':{'path':rel(constraints),'file_SHA256':sha(constraints),'id':i},'native_matrix_ref':proof['native_matrix_ref'],'common_actual_records':proof['common_actual_records'],'source_before_call_ref':{'path':rel(B/f'source-check-{ST}-before-call.json'),'file_SHA256':sha(B/f'source-check-{ST}-before-call.json'),'id':i},'reproducible_tool_arguments':{'prompt':arg,'referenced_image_paths':[str((ROOT/r).resolve()).replace('\\','/')for r in refs],'transparent_background':False},'runtime_before_call_ref':{'path':rel(B/f'runtime-consumer-{ST}-before-call.json'),'file_SHA256':sha(B/f'runtime-consumer-{ST}-before-call.json')},'extended_actual_consumer_before_call_ref':{'path':rel(B/f'extended-consumer-{ST}-before-call.json'),'file_SHA256':sha(B/f'extended-consumer-{ST}-before-call.json')},'single_builtin_calls':1,'retries':0,'prompt_serialization':'Exact actual UTF8 LFargument with ONE finalLF; relative references resolved against root. No fullnative raster/DB matrices duplicated inside callmetadata; immutable common refs+SHA.'}
(B/f'generated/{i}-{ST}-call.json').write_text(json.dumps(record,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print('Immediately saved raw+exactargs+compact refs',i)
