from pathlib import Path
from datetime import datetime,timezone
import sys,json,hashlib,shutil
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='weapons-sixteenth';i=int(sys.argv[1]);output=Path(sys.argv[2]);raw=B/f'generated/{i}-raw.png'
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
assert not raw.exists();assert output.exists();shutil.copyfile(output,raw)
proof=next(r for r in read(B/f'source-check-{ST}-before-call.json')if r['id']==i);prompt=B/f'generated/{i}-prompt.txt';argbytes=prompt.read_bytes();arg=argbytes.decode('utf-8');assert not arg.endswith('\n')
refs=[proof['helper_recipe']['output']];constraints=B/f'pattern-constraints-{ST}.json';canonical=argbytes+b'\n';prompt.write_bytes(canonical)
record={'id':i,'tool':'built-in image_gen.imagegen','tool_output':output.name,'tool_output_session':output.parent.name,'saved_utc':datetime.now(timezone.utc).isoformat(),'generated':rel(raw),'raw_sha256':sha(raw),'prompt_file':rel(prompt),'prompt_sha256':sha(prompt),'exact_prompt':arg,'exact_actual_argument_SHA256':hashlib.sha256(argbytes).hexdigest(),'canonical_prompt_recipe':'EXACT actual tool prompt UTF8 argument + ONE additional service LF; original actual argument has NO terminal LF, canonical file has exactly one. Immediate save, no later worker rewrite.','canonical_prompt_SHA256':hashlib.sha256(canonical).hexdigest(),'transparent_background':False,'reference_pngs':refs,'reference_sha256':{r:sha(ROOT/r)for r in refs},'source_rgba_sha256':proof['source_rgba_sha256'],'source_transform_recipe':proof['helper_recipe'],'pattern_constraints_ref':{'path':rel(constraints),'file_SHA256':sha(constraints),'id':i},'native_matrix_ref':proof['native_matrix_ref'],'common_actual_records':proof['common_actual_records'],'source_before_call_ref':{'path':rel(B/f'source-check-{ST}-before-call.json'),'file_SHA256':sha(B/f'source-check-{ST}-before-call.json'),'id':i},'reproducible_tool_arguments':{'prompt':arg,'referenced_image_paths':refs,'transparent_background':False},'literal_actual_tool_arguments':{'prompt':arg,'referenced_image_paths':[(ROOT/r).as_posix()for r in refs],'transparent_background':False},'prompt_serialization':'Literal actual LF prompt has no terminalLF. Saved canonical prompt is exactly argument+ONE LF. Full reference recipe/SHA included, native/common records referenced once.'}
(B/f'generated/{i}-{ST}-call.json').write_text(json.dumps(record,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print('Immediately saved raw+exact actualargs+canonical ONE LF+refs',i)
