from pathlib import Path
from datetime import datetime,timezone
import sys,json,hashlib,shutil
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='clothing-forty-eighth';i=int(sys.argv[1]);output=Path(sys.argv[2]);raw=B/f'generated/{i}-raw.png';assert not raw.exists();shutil.copyfile(output,raw)
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
proof=next(r for r in read(B/f'source-check-{ST}-before-call.json')if r['id']==i);prompt=B/f'generated/{i}-prompt.txt';refs=[proof['helper_recipe']['output']];canonical=prompt.read_bytes();assert canonical.endswith(b'\n')and not canonical.endswith(b'\r\n');arg=canonical[:-1].decode('utf-8');assert (B/f'generated/{i}-{ST}-exact-call-argument.txt').read_bytes()==arg.encode('utf-8');constraints=B/f'pattern-constraints-{ST}.json'
record={'id':i,'tool':'built-in image_gen.imagegen','tool_output':output.name,'tool_output_session':output.parent.name,'saved_utc':datetime.now(timezone.utc).isoformat(),'generated':rel(raw),'raw_sha256':sha(raw),'prompt_file':rel(prompt),'prompt_sha256':sha(prompt),'prompt_argument_sha256':hashlib.sha256(arg.encode('utf-8')).hexdigest(),'canonical_prompt_equals_exact_actual_argument_plus_ONE_additional_LF':True,'exact_prompt':arg,'transparent_background':False,'reference_pngs':refs,'reference_sha256':{r:sha(ROOT/r)for r in refs},'source_rgba_sha256':proof['source_rgba_sha256'],'source_transform_recipe':proof['helper_recipe'],'pattern_constraints_ref':{'path':rel(constraints),'file_SHA256':sha(constraints),'id':i},'native_matrix_ref':proof['native_matrix_ref'],'common_actual_records':proof['common_actual_records'],'source_before_call_ref':{'path':rel(B/f'source-check-{ST}-before-call.json'),'file_SHA256':sha(B/f'source-check-{ST}-before-call.json'),'id':i},'reproducible_tool_arguments':{'prompt':arg,'referenced_image_paths':refs,'transparent_background':False},'prompt_serialization':'Exact actual UTF8 CRLFargument without finalLF; relative references resolved against root. No fullnative raster/DB matrices duplicated inside callmetadata; immutable common refs+SHA.'}
record['literal_actual_tool_arguments']={'prompt':arg,'referenced_image_paths':[(ROOT/r).as_posix()for r in refs],'transparent_background':False}
record['prompt_serialization']='Canonical prompt-file UTF8 bytes == exact actual CRLF argument + ONE additional LF, per coordinator Heads23 explicit instruction. Literal actual argument (without serviceLF) and absolute actualtool references retained separately. No fullnative raster/DB matrices duplicated; immutable common refs+SHA.'
(B/f'generated/{i}-{ST}-call.json').write_text(json.dumps(record,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print('Immediately saved raw+exactargs+compact refs',i)
