from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,sys,shutil
import numpy as np
from PIL import Image,ImageChops,ImageDraw
B=Path(__file__).resolve().parent;ROOT=B.parents[2];ST='clothing-garments-complete-20261008';AUDIT_ST='clothing-complete-20261008';sys.path.insert(0,str(B.parent))
from match_brightness import match_cell,stored_luma,pad_rgb_under_source_mask
from prepare_sources import ReleaseResources,decode_mmp

def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
def save(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def record(i):
 assert i in ALLOWED
 return next(r for r in read(B/f'source-check-{AUDIT_ST}.json')if r['id']==i)
def guard(i):
 tp=B/'delegated-garments-coordinator-tail20-20261008.json'
 assert not tp.exists() or i not in read(tp)['IDs'],('coordinator-owned',i)
 S=read(B.parent/'sources.json')['textures'];Q=read(B/'queue.json');assert i not in {r['id']for r in S},('accepted',i)
 qr=next((r for r in Q if r['id']==i),None);assert qr is None or not any(t in str(qr.get('status')).lower()for t in ['unavailable','refus','validated','generated']),('shared processed',i,qr)
 rr=record(i);rid=rr['resource_when_gfx_texture_usedxt_0'];alias=next(a for a in rr['aliases']if a['resource_id']==rid);h=Path(f'G:/SS/Silent-Storm/Complete/Textures/{rid}').read_bytes();relres=ReleaseResources('G:/SS/lab/baseline/res').read(rid);assert h==relres;im=decode_mmp(h).convert('RGBA');assert hashlib.sha256(im.tobytes()).hexdigest()==alias['native_RGBA_SHA256'];assert Image.open(ROOT/alias['fullRGBA_PNG']).convert('RGBA').tobytes()==im.tobytes();group=next(g for g in ALLOC['groups']if i in g['ids']);assert group['selected_RGBA_SHA256']==hashlib.sha256(im.tobytes()).hexdigest()
 return {'utc':datetime.now(timezone.utc).isoformat(),'sources_count':len(S),'queue_count':len(Q),'sources_SHA256':sha(B.parent/'sources.json'),'queue_SHA256':sha(B/'queue.json'),'own_ID_source_present':False,'own_queue':qr,'selected_resource_id':rid,'fresh_historical_release_native_SHA':hashlib.sha256(h).hexdigest(),'fresh_selected_RGBA_SHA':hashlib.sha256(im.tobytes()).hexdigest(),'current_state_not_published_claim':True}
def norm(i,raw,tag):
 r=record(i);bp=B/f'generated/{i}-{tag}-before-call.json';br=read(bp)if bp.exists()else{};srcpath=ROOT/br['selected_source_RGBA_path']if br.get('selected_source_RGBA_path')else B/f'original/{i}.png';o=Image.open(srcpath).convert('RGBA');im=Image.open(raw).convert('RGBA');sz=(o.width*4,o.height*4);a=o.getchannel('A').resize(sz,Image.Resampling.LANCZOS);inp=im.convert('RGB').resize(sz,Image.Resampling.LANCZOS).convert('RGBA');prem=r['actual_native_Type']=='Transparent';padded,pc,cc=pad_rgb_under_source_mask(inp,a);corr,gain,lum,rounding=match_cell(padded,stored_luma(o),prem,a);corr.putalpha(a)
 out=B/f'private-{ST}/native4x';out.mkdir(exist_ok=True);p=out/f'{i}-{tag}-pure-native4x.png';corr.save(p);rgb=corr.convert('RGB');rgb.save(out/f'{i}-{tag}-pureRGB4x.png');inv=rgb.resize(o.size,Image.Resampling.LANCZOS);inv.save(out/f'{i}-{tag}-RGBinverse-native.png');src=np.array(o.convert('RGB')).astype(float);v=np.array(inv).astype(float);d=(v-src).mean(2);yy,xx=np.unravel_index(np.abs(d).argmax(),d.shape)
 metric={'id':i,'tag':tag,'raw':rel(raw),'raw_SHA256':sha(raw),'raw_size':list(im.size),'target_size':list(sz),'gain':gain,'premultiply_native':prem,'source_alpha_restored_exact':corr.getchannel('A').tobytes()==a.tobytes(),'padding_count':pc,'hidden_clear_count':cc,'rounding':rounding,'stored_luma_target':stored_luma(o),'actual_luma':lum,'native_RGB_correlation':float(np.corrcoef(src.ravel(),v.ravel())[0,1])if src.std()>0 and v.std()>0 else None,'max_absolute_mean_tone_delta':float(d[yy,xx]),'delta_xy':[int(xx),int(yy)],'source_RGB_at_delta':src[yy,xx].astype(int).tolist(),'production_RGB_at_delta':v[yy,xx].astype(int).tolist(),'production_preview':rel(p),'RGB_inverse':rel(out/f'{i}-{tag}-RGBinverse-native.png'),'recipe':'ENTIRE raw RGB FIRST LANCZOS4x; default source-mask padding/global match_cell scalar/fulloriginalA LANCZOS; Transparent nativepremul downstream once. No crop/UV fitting/artistRGB/localcorrection.'};save(out/f'{i}-{tag}-metrics.json',metric);return metric
ALLOC=read(B/'delegated-garments-clothing-complete-20261008.json');ALLOWED={i for g in ALLOC['groups'] for i in g['ids']};assert len(ALLOWED)==88
for key in ['source_audit','actual_records']:assert sha(ROOT/ALLOC[key])==ALLOC[f'{key}_SHA256']
(B/f'private-{ST}/sources').mkdir(parents=True,exist_ok=True)
mode=sys.argv[1]
if mode in ['prepare','prepare-guide','prepare-soft','prepare-dual','prepare-triple']:
 i=int(sys.argv[2]);version=sys.argv[3];desc=sys.argv[4];r=record(i);g=guard(i);assert r['initial_status']=='pending-art-review';tag=f'{ST}-{version}';base=B/f'generated/{i}-{tag}';assert not Path(str(base)+'-raw.png').exists();selectedalias=next(a for a in r['aliases']if a['resource_id']==r['resource_when_gfx_texture_usedxt_0']);ref=ROOT/selectedalias['nativeRGB_PNG'];w,h=r['logical_size'];o=Image.open(ROOT/selectedalias['fullRGBA_PNG']).convert('RGBA');natural=o.convert('RGB').resize((w*4,h*4),Image.Resampling.LANCZOS).resize((w,h),Image.Resampling.LANCZOS);naturalpath=B/f'private-{ST}/sources/{i}-natural-RGB-roundtrip.png';natural.save(naturalpath)
 native_ref=ref;sampling='LANCZOS' if mode=='prepare-soft' else 'NEAREST';ref=B/f'references/{i}-{tag}-whole-selected-{sampling}4x.png';assert not ref.exists();o.convert('RGB').resize((w*4,h*4),Image.Resampling.LANCZOS if mode=='prepare-soft' else Image.Resampling.NEAREST).save(ref)
 arg='\r\n\r\n'.join(['Use case: precise-object-edit. HD game color diffuse texture, edit existing painted UV image, preserve its exact artwork.',f'Image1 is the ENTIRE original opaque native storedRGB {w}x{h} enlarged4x with {sampling} sampling solely to show exact existing UV paint. It is the same full source canvas without any artwork changes. Output entire same aspect {w}:{h} canvas and normalized UV. Original fullalpha restored separately; keep all storedRGB including black authoredpaint. No margin/padding/crop/zoom/island registration/rotation, no layouts shifted.',desc,'Keep original muted filtered hand-painted appearance, source brush softness, palette, relative local lightstrength and native scale. Gently resolve only existing low-resolution paint; keep all weak washes and small marks vague. Remove sampling steps without drawing new surfaces. Do not invent photographic weave, fibers, stipple, pores, metalgrain, raised rims, etching, shiny chrome, brighter white edges, new seams/buttons/straps/hardware, emblems or lettering. Preserve every existing dark gap, small mark, fold, count and phase. Do not brighten or sharpen weak diffuse washes into new structures. Increase resolution to four-times native dimensions while preserving source material and softness. No background texture added, no extraneous objects.'])
 references=[native_ref,ref] if mode in ['prepare-dual','prepare-triple'] else [ref]
 if mode in ['prepare-dual','prepare-triple']:
  arg='\r\n\r\n'.join(['Use case: precise-object-edit. Faithful HD PAINTED GAME diffuse UV texture.',f'Image1 is the exact ENTIRE native stored RGB edit target {w}x{h}. Image2 is ONLY that identical whole source enlarged4x with nearest pixels, to expose the existing tiny paint pattern. Both are the same single canvas. Output ENTIRE same aspect {w}:{h} canvas and UV, same orientation, no margin/crop/padding/repacking/rotation/zoom. Original full selected alpha restored numerically after this edit.',desc,'Only improve painted resolution inside the EXISTING shapes. Preserve original palette, matte or shiny material, low contrast and brush softness, relative local lights, all original black gaps/cutouts, and pattern count and scale. Do not redraw little marks into new symbols, add weave/thread/grain/pores/stitches, new folds, bright bevels or hardware. No photograph, new anatomy, new text or new objects. This must remain a faithful old painted game UV texture, no portrait or assembled garment.'])
 if mode=='prepare-triple':
  smooth=B/f'references/{i}-{tag}-whole-selected-LANCZOS4x-softness.png';assert not smooth.exists();o.convert('RGB').resize((w*4,h*4),Image.Resampling.LANCZOS).save(smooth);references.append(smooth)
  arg+='\r\n\r\nImage3 is the SAME ENTIRE source enlarged4x with Lanczos sampling ONLY to demonstrate the original soft painted color transitions and weak marks. It adds no artwork. Use Image1 for precise source geometry/counts and Image2 for existing small mark phase; keep Image3 soft diffuse paint character. All input images represent ONE identical UV canvas. Do not turn low-resolution pixel steps into raised rims or buttons. Resolve existing brush paint gently, with no new crisp outlines or fine surface texture. The result should remain soft hand-painted game diffuse even at HD resolution.'
 Path(str(base)+'-prompt.txt').write_bytes((arg+'\n').encode('utf-8'));Path(str(base)+'-exact-call-argument.txt').write_bytes(arg.encode('utf-8'));before={'id':i,'generation_variant':tag,'fresh_guard':g,'source_before':r,'literal_source_description_before_prompt':desc,'selected_source_resource_id':selectedalias['resource_id'],'selected_source_RGBA_path':selectedalias['fullRGBA_PNG'],'selected_source_RGBA_SHA256':selectedalias['native_RGBA_SHA256'],'source_selection_reason':('Actual Texture.Format dxt* -> CTexture.Import bIsDXT true, GetRealTextureID gfx_texture_usedxt0 selects highbit UC resource.' if r['CTexture_Import_bIsDXT'] else 'Actual Texture.Format is non-DXT -> CTexture.Import bIsDXT false, GetRealTextureID gfx_texture_usedxt0 selects primary resource.')+' Whole selected historical/release RGBA exact; runtime setting from root proof, no worker measured-runtime claim.','source_reference_privately_viewed_before_tool':True,'both_sourcealiases_nativeRGB_A_inspected':False,'natural_RGB_roundtrip':{'path':rel(naturalpath),'SHA256':sha(naturalpath)},'actual_DB_ref':{'path':rel(B/f'actual-records-{AUDIT_ST}.json'),'SHA256':sha(B/f'actual-records-{AUDIT_ST}.json')},'source_code_ref':{'path':rel(B/f'consumer-code-proof-{AUDIT_ST}.json'),'SHA256':sha(B/f'consumer-code-proof-{AUDIT_ST}.json')},'references':[rel(q) for q in references],'references_SHA256':[sha(q) for q in references],'reference':rel(ref),'reference_SHA256':sha(ref),'reference_recipe':f'WHOLE selected storedRGB {sampling}4x; no crop, pad, registration, color correction or artwork alteration','original_native_RGB_reference':rel(native_ref),'original_native_RGB_reference_SHA256':sha(native_ref),'exact_prompt_argument_SHA256':hashlib.sha256(arg.encode('utf-8')).hexdigest(),'created_utc':datetime.now(timezone.utc).isoformat(),'prior_artistic_repair':bool(r['prior_history']['raws']),'old_history_preserved':True};save(Path(str(base)+'-before-call.json'),before);print(json.dumps({'id':i,'tag':tag,'prompt_argument':arg,'reference':ref.as_posix(),'references':[q.as_posix() for q in references]}))
elif mode=='start':
 i=int(sys.argv[2]);version=sys.argv[3];tag=f'{ST}-{version}';base=B/f'generated/{i}-{tag}';before=read(Path(str(base)+'-before-call.json'));arg=Path(str(base)+'-exact-call-argument.txt').read_bytes();assert hashlib.sha256(arg).hexdigest()==before['exact_prompt_argument_SHA256'];assert Path(str(base)+'-prompt.txt').read_bytes()==arg+b'\n';assert not Path(str(base)+'-raw.png').exists()
 for q,sh in zip(before.get('references',[before['reference']]),before.get('references_SHA256',[before['reference_SHA256']])):assert sha(ROOT/q)==sh
 live=Path(str(base)+'-inflight.lock');live.open('x',encoding='utf-8').write(datetime.now(timezone.utc).isoformat()+'\n');sp=Path(str(base)+'-call-start.json');assert not sp.exists();save(sp,{'id':i,'generation_variant':tag,'fresh_guard':guard(i),'before_call_SHA256':sha(Path(str(base)+'-before-call.json')),'actual_prompt_SHA256':hashlib.sha256(arg).hexdigest(),'status':'tool-call-about-to-start; exclusive local variant lock','utc':datetime.now(timezone.utc).isoformat()});print('fresh start',i)
elif mode=='save':
 i=int(sys.argv[2]);version=sys.argv[3];out=Path(sys.argv[4]);tag=f'{ST}-{version}';base=B/f'generated/{i}-{tag}';raw=Path(str(base)+'-raw.png');assert not raw.exists();shutil.copyfile(out,raw);arg=Path(str(base)+'-exact-call-argument.txt').read_bytes().decode('utf-8');before=read(Path(str(base)+'-before-call.json'));prompt=Path(str(base)+'-prompt.txt');assert prompt.read_bytes()==(arg+'\n').encode('utf-8');call={'id':i,'generation_variant':tag,'tool':'built-in image_gen.imagegen','generated':rel(raw),'raw_SHA256':sha(raw),'output_default_file':out.name,'output_default_session':out.parent.name,'exact_prompt':arg,'prompt_argument_SHA256':hashlib.sha256(arg.encode('utf-8')).hexdigest(),'canonical_prompt_SHA256':sha(prompt),'prompt_file':rel(prompt),'before_call_ref':{'path':rel(Path(str(base)+'-before-call.json')),'SHA256':sha(Path(str(base)+'-before-call.json'))},'literal_actual_tool_arguments':{'prompt':arg,'referenced_image_paths':[(ROOT/q).as_posix() for q in before.get('references',[before['reference']])],'transparent_background':False},'saved_utc':datetime.now(timezone.utc).isoformat()};save(Path(str(base)+'-call.json'),call);m=norm(i,raw,tag);print(json.dumps({'saved':i,'tag':tag,'raw_size':m['raw_size'],'gain':m['gain'],'preview':m['production_preview'],'RGB_inverse':m['RGB_inverse']}))
elif mode=='old':
 done=[]
 for r in read(B/f'source-check-{AUDIT_ST}.json'):
  if r['id'] not in ALLOWED or r['initial_status']!='pending-art-review' or not r['prior_history']['raws']:continue
  generic=B/f'generated/{r["id"]}-raw.png';p=generic if generic.exists()else ROOT/r['prior_history']['raws'][0]['path'];m=norm(r['id'],p,'old-diagnostic');done.append(m)
 save(B/f'old-raw-metrics-{ST}.json',done)
 for start in range(0,len(done),8):
  c=Image.new('RGB',(4*290,2*315),(28,28,28));d=ImageDraw.Draw(c)
  for k,m in enumerate(done[start:start+8]):
   i=m['id'];o=Image.open(B/f'original/{i}.png').convert('RGB');n=Image.open(ROOT/m['RGB_inverse']);x=k%4*290;y=k//4*315;sc=min(1,128/max(o.size));sz=(int(o.width*sc),int(o.height*sc));c.paste(o.resize(sz),(x,y+26));c.paste(n.resize(sz),(x+145,y+26));d.text((x,y),f'{i} source / old pure RGB g{m["gain"]:.3f}',fill='white')
  c.save(B/f'private-{ST}/old-survey-{start:03}.png')
 print('old private normalized',len(done))
elif mode=='mark':
 i=int(sys.argv[2]);version=sys.argv[3];status=sys.argv[4];reason=sys.argv[5];tag=f'{ST}-{version}';base=B/f'generated/{i}-{tag}';c=read(Path(str(base)+'-call.json'));m=read(B/f'private-{ST}/native4x/{i}-{tag}-metrics.json');p=B/f'review-{ST}.json';d=read(p)if p.exists()else{'scope':ST,'status':'in-progress','records':[]};d['records']=[r for r in d['records']if not(r['id']==i and r.get('generation_variant')==tag)];d['records'].append({'id':i,'generation_variant':tag,'status':status,'reason':reason,'call_metadata':rel(Path(str(base)+'-call.json')),'raw_SHA256':c['raw_SHA256'],'private_fullraw_native_reviewed':True,'numeric':m});save(p,d);jobs=[]
 for r in d['records']:
  if r['status']!='ready':continue
  cc=read(ROOT/r['call_metadata']);jobs.append({'id':r['id'],'generation_variant':r['generation_variant'],'generated':cc['generated'],'prompt':cc['exact_prompt'],'reference_pngs':[Path(q).relative_to(ROOT).as_posix()for q in cc['literal_actual_tool_arguments']['referenced_image_paths']],'source_alpha_reference':read(ROOT/cc['before_call_ref']['path']).get('selected_source_RGBA_path',f'assets/terrain-hd/expanded/original/{r["id"]}.png'),'review_concern':r['reason']})
 save(B/f'jobs-{ST}.json',jobs);save(B/f'progress-{ST}.json',{'scope':ST,'status':'in-progress','ready_IDs':[r['id']for r in d['records']if r['status']=='ready'],'held_IDs':[r['id']for r in d['records']if r['status']=='held'],'call_records':len(d['records']),'remaining_category_audit':'87 delegated unique-source groups /88 IDs; coordinator merges whole clothing category','shared_writes':False});print('marked',i,status,'ready',len(jobs))
