# The Windows game renders exclusively through the pinned bgfx backend.
set(S2_BGFX_CMAKE_ROOT "" CACHE PATH "Pinned bgfx.cmake checkout")
set(S2_BGFX_DIR "${S2_BGFX_CMAKE_ROOT}/bgfx" CACHE PATH "Pinned bgfx source")
set(S2_BIMG_DIR "${S2_BGFX_CMAKE_ROOT}/bimg" CACHE PATH "Pinned bimg source")
set(S2_BX_DIR "${S2_BGFX_CMAKE_ROOT}/bx" CACHE PATH "Pinned bx source")
foreach(pair IN ITEMS "${S2_BGFX_CMAKE_ROOT}/CMakeLists.txt" "${S2_BGFX_DIR}/include/bgfx/bgfx.h" "${S2_BIMG_DIR}/include/bimg/bimg.h" "${S2_BX_DIR}/include/bx/bx.h")
  if(NOT EXISTS "${pair}")
    message(FATAL_ERROR "Set S2_BGFX_CMAKE_ROOT, S2_BGFX_DIR, S2_BIMG_DIR, S2_BX_DIR to the pinned trees documented in probes/sdl3-bgfx/README.md")
  endif()
endforeach()
set(BGFX_DIR "${S2_BGFX_DIR}" CACHE PATH "" FORCE)
set(BIMG_DIR "${S2_BIMG_DIR}" CACHE PATH "" FORCE)
set(BX_DIR "${S2_BX_DIR}" CACHE PATH "" FORCE)
set(BGFX_BUILD_TOOLS ON CACHE BOOL "" FORCE)
set(BGFX_BUILD_TOOLS_BIN2C OFF CACHE BOOL "" FORCE)
set(BGFX_BUILD_TOOLS_GEOMETRY OFF CACHE BOOL "" FORCE)
set(BGFX_BUILD_TOOLS_TEXTURE OFF CACHE BOOL "" FORCE)
set(BGFX_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BGFX_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(BGFX_INSTALL OFF CACHE BOOL "" FORCE)
set(BGFX_CONFIG_MAX_FRAME_BUFFERS 1024 CACHE STRING "" FORCE)
set(BGFX_CONFIG_MAX_TEXTURES 4096 CACHE STRING "" FORCE)
set(BGFX_CUSTOM_TARGETS OFF CACHE BOOL "" FORCE)
get_directory_property(_engine_definitions COMPILE_DEFINITIONS)
get_directory_property(_engine_options COMPILE_OPTIONS)
set_directory_properties(PROPERTIES COMPILE_DEFINITIONS "" COMPILE_OPTIONS "")
add_subdirectory("${S2_BGFX_CMAKE_ROOT}" "${CMAKE_BINARY_DIR}/bgfx")
set_directory_properties(PROPERTIES COMPILE_DEFINITIONS "${_engine_definitions}" COMPILE_OPTIONS "${_engine_options}")
target_compile_definitions(bgfx PUBLIC BGFX_CONFIG_MAX_VIEWS=2048)
# Do not let third-party headers inherit the engine's historical /Gr convention.
foreach(bgfxTarget IN ITEMS bgfx bx bimg bimg_decode bimg_encode shaderc fcpp glslang glsl-optimizer spirv-opt spirv-cross)
  if(TARGET ${bgfxTarget})
    target_compile_options(${bgfxTarget} PRIVATE /Gd)
  endif()
endforeach()
find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(S2_BGFX_SHADER_HEADER "${CMAKE_BINARY_DIR}/bgfx-generated/GameShaders.h")
add_custom_command(OUTPUT "${S2_BGFX_SHADER_HEADER}"
  COMMAND "${Python3_EXECUTABLE}" "${root}/diagnostics/CompileBgfxShaders.py"
          --source "${root}/Main/GfxShaders.cpp" --shaderc "$<TARGET_FILE:shaderc>"
          --output "${S2_BGFX_SHADER_HEADER}"
  DEPENDS shaderc "${root}/Main/GfxShaders.cpp" "${root}/diagnostics/CompileBgfxShaders.py"
  VERBATIM)
add_custom_target(S2BgfxShaders DEPENDS "${S2_BGFX_SHADER_HEADER}")
