include(FetchContent)
set(S2_FREETYPE_SOURCE_DIR "" CACHE PATH "Optional local FreeType 2.14.3 source checkout")
set(FT_DISABLE_ZLIB ON CACHE BOOL "" FORCE)
set(FT_DISABLE_BZIP2 ON CACHE BOOL "" FORCE)
set(FT_DISABLE_PNG ON CACHE BOOL "" FORCE)
set(FT_DISABLE_HARFBUZZ ON CACHE BOOL "" FORCE)
set(FT_DISABLE_BROTLI ON CACHE BOOL "" FORCE)
if(S2_FREETYPE_SOURCE_DIR)
  add_subdirectory("${S2_FREETYPE_SOURCE_DIR}" "${CMAKE_BINARY_DIR}/freetype" EXCLUDE_FROM_ALL)
else()
  FetchContent_Declare(freetype
    URL https://download.savannah.gnu.org/releases/freetype/freetype-2.14.3.tar.xz
    URL_HASH SHA256=36bc4f1cc413335368ee656c42afca65c5a3987e8768cc28cf11ba775e785a5f)
  FetchContent_MakeAvailable(freetype)
endif()
add_library(s2_vector_fonts STATIC "${root}/Main/VectorFontRasterizer.cpp")
target_include_directories(s2_vector_fonts PUBLIC "${root}/Main")
target_compile_features(s2_vector_fonts PRIVATE cxx_std_17)
target_link_libraries(s2_vector_fonts PUBLIC freetype)
add_executable(VectorFontTests "${root}/diagnostics/VectorFontTests.cpp")
target_link_libraries(VectorFontTests PRIVATE s2_vector_fonts)
add_test(NAME VectorFontTests COMMAND VectorFontTests "${root}/assets/fonts")
function(s2_copy_fonts target)
  add_custom_command(TARGET ${target} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory "${root}/assets/fonts" "$<TARGET_FILE_DIR:${target}>/fonts")
endfunction()
